### ISSUE TITLE
Worker patch onProperties fails on latest version of Safari

### ISSUE THREAD

**Issue by bvdmitri** [angular/zone.js#1000]
It is related to this [PR](https://github.com/angular/zone.js/pull/915).

Lates version of Safari (11.0.3) has 'Worker' property on window, but it has no prototype property on it.
So TypeError will be raised after getOwnPropertyDescriptor will be called later.

**Comment by JiaLiPassion** [comment]
@bvdmitri , thank you for posting the issue, I will check it.

**Comment by JiaLiPassion** [comment]
@bvdmitri , I just check it, and can't reproduce, I don't know where to download `Safari 11.0.3`, so I use `11.0.2` and `Safari Technical Preview 11.2` to test, and `Worker.prototype` exists, everything work fine.

Could you provide a reproduce sample?

**Comment by bvdmitri** [comment]
@JiaLiPassion Hello!

I just realized that the problem with Worker prototype is not clear enough.
I just check Worker.prototype on two different MacBook Pro - one with 11.0.3 Safari, and the second with 11.0.2 Safari on two sites - YouTube and GitHub.

On YouTube - there is no prototype on Worker.
On GitHub - there is prototype on Worker.

For example:

<img width="323" alt="2018-01-27 12 39 04" src="https://user-images.githubusercontent.com/6557701/35470710-7727a844-035f-11e8-9296-1e8a158e8254.png">

I don't understand is it some kind of bug in safari or may be something else.

<img width="461" alt="2018-01-27 12 48 48" src="https://user-images.githubusercontent.com/6557701/35470755-75979b3c-0360-11e8-8bbf-4211bb19f3b4.png">

I think 11.0.2 behave the same as 11.0.3, I have no access to 11.2 version, so cannot check it.
Can you check Worker on YouTube and GitHub on your side? Is this bug still exist? Or it some kind of magic with my two MacBooks?

**Comment by JiaLiPassion** [comment]
@bvdmitri , I have tried Safari `11.0.2` and `11.2`, both `github.com` and `youtube.com`, and can get `Worker.prototype` correctly.

**Comment by bvdmitri** [comment]
I guess I understand where the problem is. uBlock Origin extension. It is not a zone.js problem.
But this extension is very popular and it can accidentally break any angular application, because it breaks zone.js initialization. 
I don't know should zone.js team add some additional checks on prototype property in patchFilteredProperties function or not.

In case someone will get this error, just disable uBlock Origin.

I think it can be closed now. Thank you for your answers!

**Comment by JiaLiPassion** [comment]
@bvdmitri , thank you for the information, maybe you can find more information here, https://github.com/el1t/uBlock-Safari/issues/89, and I will create a PR to check the prototype is available or not.

**Comment by bvdmitri** [comment]
@JiaLiPassion Nice! Thank you!
