### ISSUE TITLE
IE11 - SecurityError zone.js (192,25)

### ISSUE THREAD

**Issue by kevinkuszyk** [angular/zone.js#1001]
I'm seeing the following error intermittently both before and after applying the fix for the `Can't execute code from a freed script` error (#933).

Here is an example of before:

![image](https://user-images.githubusercontent.com/2734580/35444117-624945b4-02a5-11e8-8b89-672c3083b431.png)

And after:

![image](https://user-images.githubusercontent.com/2734580/35444146-7ff944d8-02a5-11e8-83d2-a1d10f0d4f22.png)

This is a drill down into the sources:

![image](https://user-images.githubusercontent.com/2734580/35444213-aef1cbe8-02a5-11e8-8cb7-611e3c5fcd89.png)

I've pushed a sample repro at [kevinkuszyk/angular-ie-freed-script-error](https://github.com/kevinkuszyk/angular-ie-freed-script-error).  IE may not display the error the first time the app is loaded, but refreshing a few times is usually enough to trigger it.

**Comment by JiaLiPassion** [comment]
@kevinkuszyk , thank you for the sample, I will try to reproduce it.

**Comment by JiaLiPassion** [comment]
@kevinkuszyk , I think I may find the possible reason, when run `ng serve`, there will be `websocket` to connect `angular web app` with `angular dev server`,  and every time refresh IE page, there will be a new `web socket` was created.

and in IE, the maximum `websocket connections` are 6 by default, https://msdn.microsoft.com/ja-jp/library/ee330736%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396.
so error occurs, you can change the number by modify the `registry`.

```
\HKEY_CURRENT_USER\Software\Policies\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_WEBSOCKET_MAXCONNECTIONSPERSERVER
```

and add a `key`, `iexplore.exe（REG_DWORD)` modify the value to `2~128`.

I just modify to `50`, and the error gone.

**Comment by kevinkuszyk** [comment]
Thanks @JiaLiPassion, that seems to have fixed the security error.

**Comment by todthomson** [comment]
```
\HKEY_CURRENT_USER\Software\Policies\Microsoft\Internet Explorer\

**Comment by JiaLiPassion** [comment]
@todthomson , you can search `HKEY_LOCAL_MACHINE` , if not exists either, you need to created those keys yourself.

**Comment by Thomas243** [comment]
@todthomson 
The registry key can be found here:
HKEY_CURRENT_USER (or HKEY_CURRENT_USER)\Software\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_WEBSOCKET_MAXCONNECTIONSPERSERVER

See
https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/general-info/ee330736(v=vs.85)#websocket-maximum-server-connections

**Comment by dudewad** [comment]
Why is this considered a solution?? When running dev servers, people refresh all the time, we're talking about just spinning up web sockets endlessly? Why not fix the actual source of the problem?

**Comment by dudewad** [comment]
Oh I see, you mean that the websocket connection is created inside of IE and not released...? Okay that makes sense then. Sorry, was confused.

**Comment by uberspeck** [comment]
I'm still seeing the "Security Error" even after applying @JiaLiPassion fix. I've also addressed the error in #933 and followed the directions in the [Angular and Internet Explorer](https://blog.angularindepth.com/angular-and-internet-explorer-5e59bb6fb4e9) article. Any subsequent navigation leads to a blank page and no console errors. I've restarted the browser and even restarted my VM and confirmed the registry change is present. Is there any other workaround?

**Comment by JiaLiPassion** [comment]
@uberspeck, yeah, you have to import those `polyfills` to make `es6 APIs` work property in `IE`.

**Comment by varrob112** [comment]
thank you @JiaLiPassion for the registry fix! its working for me. (But i dont know how u figure out this fix. 👍 )

**Comment by chowdam** [comment]
resolved after adding below in polysfills:
import 'core-js/es7/object';
import 'core-js/es7/array';

**Comment by JiaLiPassion** [comment]
will close for now.
