### ISSUE TITLE
Zone.js should register event handlers as passive

### ISSUE THREAD

**Issue by mertdeg2** [angular/zone.js#1002]
Zone.js registers [mousewheel event handlers](https://github.com/angular/zone.js/blob/master/lib/browser/property-descriptor.ts#L70) that run on main thread ([callback](https://github.com/angular/zone.js/blob/master/lib/common/events.ts#L128)). This might cause performance issues.

Quoting my colleague who works on Chrome layout:
The problem is Chrome doesn't know, before running the listener, whether it's going to call preventDefault.  So adding a listener forces the scroll to run on the main thread, even if it doesn't actually preventDefault.  

[More information about passive event handlers](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md)

**Comment by mertdeg2** [comment]
@mhevery

**Comment by mhevery** [comment]
https://github.com/angular/angular/pull/21681#issuecomment-360931320

**Comment by JiaLiPassion** [comment]
close for now, because there are issues in angular repo already.
