### ISSUE TITLE
IN IE11 my Angular 5 application is not loading because of isFrozen method in Zone.js 

### ISSUE THREAD

**Issue by raghu22ram2** [angular/zone.js#1008]
Recently I upgraded my zone.js to latest vertion after that my application is not loading in IE11.

Its throwing error like 
    " Script438: Object doesn't support property or method 'isFrozen'
     File: polyfills.bundles.js, Line: 4277, Column: 5"

**Comment by JiaLiPassion** [comment]
@raghu22ram2 , you are using `angular 5`?  I believe `es6 polyfill` provided `Object.isFrozen` in there.

**Comment by raghu22ram2** [comment]
We are using typescript 2.5.3 version in my application

**Comment by JiaLiPassion** [comment]
@raghu22ram2 , could you provide a reproduce repo?

**Comment by JiaLiPassion** [comment]
in `polyfill.ts`, you should also comment out the following lines.

```javascript
/** IE9, IE10 and IE11 requires all of the following polyfills. **/
// import 'core-js/es6/symbol';
// import 'core-js/es6/object';
// import 'core-js/es6/function';
// import 'core-js/es6/parse-int';
// import 'core-js/es6/parse-float';
// import 'core-js/es6/number';
// import 'core-js/es6/math';
// import 'core-js/es6/string';
// import 'core-js/es6/date';
// import 'core-js/es6/array';
// import 'core-js/es6/regexp';
// import 'core-js/es6/map';
// import 'core-js/es6/weak-map';
// import 'core-js/es6/set';
```

**Comment by raghu22ram2** [comment]
Thanks for quick your response.

My application is  working after uncommenting  // import 'core-js/es6/object'; this line

**Comment by raghu22ram2** [comment]
"import 'core-js/es6/object' in polyfills.js file" is it right solution? or we have any other work around.

Previously everythis is commented except  'zone.js' and' core-js/es7/reflect' in my polyfills.js file 

Now I un-commented "import 'core-js/es6/object" line also.

**Comment by JiaLiPassion** [comment]
yes, it is the right thing to do, newest version of `zone.js` use `Object.isFrozen` to check object can be override or not.
