### ISSUE TITLE
ResizeObserver issue

### ISSUE THREAD

**Issue by scaljeri** [angular/zone.js#1011]
I'm using [ResizeObserver](https://caniuse.com/#feat=resizeobserver) for which I use a [polyfill](https://github.com/que-etc/resize-observer-polyfill) because its browser support is limited. Now, recently, chrome 64 natively supports this API with the result that changes trigged by ResizeObserver don't trigger `changedetection`  in my angular app. 

[stackblitz demo](https://stackblitz.com/edit/resize-observer?file=polyfills.ts)

```typescript
const observer = new window.ResizeObserver(entries => {
          this.observedWidth = entries[0].contentRect.width;  // Outside a zone??!!
});
observer.observe(this.resizable.nativeElement);
```
The expected behaviour can be seen in firefox/safari and chrome 63 of course. 

Now I don't know that much about Zone.js. but I would expect Zone.js to take care of this?

For more details:
[stackoverflow question](https://stackoverflow.com/questions/48579545/angular-async-process-not-triggering-changedetection-only-in-chrome-64)

**Comment by JiaLiPassion** [comment]
@scaljeri, sure, I will make a patch for this.

**Comment by scaljeri** [comment]
For the mean time, is there an easy way to run the code inside the callback within a zone?

**Comment by JiaLiPassion** [comment]
for now, you can do this to run the callback in `ngZone`

```javascript
constructor(private ngZone: NgZone) {}

const observer = new window.ResizeObserver(this.ngZone.run((entries) => {
          this.observedWidth = entries[0].contentRect.width;  // Outside a zone??!!
}));
observer.observe(this.resizable.nativeElement);
```

**Comment by scaljeri** [comment]
thanks a lot!
