### ISSUE TITLE
Jasmine patch

### ISSUE THREAD

**Issue by vicb** [angular/zone.js#102]
@IgorMinar a few questions about the jasmine patch:

The patch is currently internal to zone.js. However as stated in your commit comment, it should **always** be used. Should we make it public and export it to the `dist/` folder ? At least this would be useful for Angular.

If it is made public:
- it should also probably work in the CJS env by removing explicit references to `window`,
- it should auto-detect if the patch need to be applied (`global.it` && `global.zone`)

Thoughts ?

**Comment by IgorMinar** [comment]
sgtm

**Comment by vicb** [comment]
closed via #105
