### ISSUE TITLE
Performance issues in hybrid app

### ISSUE THREAD

**Issue by timruhle** [angular/zone.js#1020]
I have a hybrid app using [angular-hybrid](https://github.com/ui-router/angular-hybrid/) with AngularJS 1.5.11 and Angular 5.2.4 with zone.js 0.8.20.

Zone.js seems to have handlers for every single kind of event and they are making the CPU hit 100% and is producing thousands of DOM nodes. As you can see in this gif, just moving the mouse has some serious performance impacts (sorry about the bad quality) ![zone js performance](https://user-images.githubusercontent.com/28910600/36082238-6126ce58-0ff3-11e8-8d82-94dd8258a883.gif)

If I add

```js
__zone_symbol__BLACK_LISTED_EVENTS = ['scroll', 'mouseenter', 'mouseleave', 'mousemove', 'mouseover', 'mouseout', 'mousewheel', 'pointermove', 'keypress', 'keyup'];
```

before loading zone.js then the whole application works better, however there are still key events on input boxes that lag about a second behind what the user is typing. I cannot seems to blacklist these events and don't know if blacklisting is the best approach for this problem

**Comment by JiaLiPassion** [comment]
@timruhle , thank you for posting the issue, I will check your repo, `zone.js` will patch all `events` so it will have `overhead` especially for events like `scroll, mousemove...`, so I believe you should add those events to `__zone_symbol__BLACK_LISTED_EVENTS`.

About the `keyevents`, I will check your repo and find out whether `angularjs 1.5` fire the `$digest` too often in such kind of `upgrade` application.

**Comment by timruhle** [comment]
@JiaLiPassion I have added `ng-model-options="{'updateOn': 'blur'}"` to the particular fields that are causing the performance issues and it is now working much better.

**Comment by JiaLiPassion** [comment]
@timruhle , thank you for the update.

**Comment by httpete** [comment]
I am using \@angular/hybrid and I am seeing similar things - with angular 1.6.10 and Angular 5.2.10 what does blacklisting the events do to Angular?

**Comment by timruhle** [comment]
@httpete As far as I understand zone.js patches over some in-build javascript functions, and then when they get called zone.js knows to redraw the screen. Blacklisting the events tells zone.js not to redraw the screen on those events, so then it improves performance. Because the screen is not being automatically redrawn, sometimes I have to add in this around my code so that it gets rendered properly.

```javascript
ngZone.run(() => {
    // my code here
})
```

There are also other things you can disable for improved performance - https://github.com/angular/zone.js/blob/master/MODULE.md



I have also found this page which describes downgrading the Angular 5.x app rather than upgrading the AngularJS 1.x app - https://pr18487-aedf0aa.ngbuilds.io/guide/upgrade-performance. If you notice the url isn't the normal angular.io, so it isn't an official thing yet, it is an open pull request (https://github.com/angular/angular/pull/18487). I couldn't quite get it to work properly, but you may have more luck

**Comment by JiaLiPassion** [comment]
`__zone_symbol__BLACK_LISTED_EVENTS` means those events will not be monkey-patched by `zone.js`, so they will be processed by `native` delegate when call `addEventListener` or `onXXX`(for example, onscroll). So this will guarantee the best performance. 

But because those events will not in `ngZone`, so in the callback of those event, if there are some data changes which needed to updated on screen, you need to call `ngZone.run` youself.

**Comment by httpete** [comment]
15 days ago, they changed the way they bootstrapped an uirouter/angular-hybrid app and they do it in a zone.

https://github.com/ui-router/angular-hybrid/blob/master/example/src/main.ts

I can report, it is working MUCH better in my large app. It was insane the way it was before! No blacklist needed.

**Comment by JiaLiPassion** [comment]
@httpete , thank you for the information.

**Comment by timruhle** [comment]
I can also report that I have removed all of the blacklistings and disables (e.g. __Zone_disable_PromiseRejectionEvent) and the performance is not being degraded. I am closing this issue as it seems to be fixed in one of the more recent versions.
