### ISSUE TITLE
Patched removeAllListeners() doesn't seem to return the EventEmitter instance

### ISSUE THREAD

**Issue by jfstgermain** [angular/zone.js#1021]
Hello, I'm using zone.js in an node app and a module chains calls to removeAllListeners().  The patched version of removeAllListeners() doesn't seem to return the EventEmitter.
The following code breaks:

```js
socket.removeAllListeners('error')
  .removeAllListeners('connect')
  .removeAllListeners('secureConnect');
```

Here's my `zone.js` setup code:

```js
const Bluebird = require('bluebird');
require('zone.js/dist/zone-node');
require('zone.js/dist/zone-bluebird');

Zone[Zone.__symbol__('bluebird')](Bluebird);

delete global.Promise;

global.Promise = Bluebird;
```
Am I missing something?

**Comment by JiaLiPassion** [comment]
Thank you for posting the issue, I will check it.
