### ISSUE TITLE
Could not intercept requestAnimationFrame from Google Maps

### ISSUE THREAD

**Issue by wtubog** [angular/zone.js#1024]
**Background:** Google Maps triggers `requestAnimationFrame` when zooming in and out of the map and when panning, I want to intercept these `requestAnimationFrame` via Zone.js to debounce it and may be improve performance on mobile devices...

I created a simple repro code on [StackBlitz](https://stackblitz.com/edit/typescript-ugi7tp?file=index.ts) (please open console to see logs)

The problem here is that I can't seem to intercept the `requestAnimationFrame ` on the `onScheduleTask` method defined on the ZoneSpec of the created Zone called `mapZone` (but I'm seeing intercepted events such as `setTimeout` inside the map when it's being instantiated) ... as you can see on the repro code, I ran the initialization of Google Maps inside the created Zone

I'm newbie on Zone.js, this probably might be a simple problem, but I can't seem to find a solution... what do you think am I missing here? :)

Thanks so much in advance!

**Comment by JiaLiPassion** [comment]
@wtubog , `requestAnimationFrame` is in the zone, https://stackblitz.com/edit/typescript-jxdndx?file=index.ts, I created a demo based on your `stackblitz`.

**Comment by wtubog** [comment]
Hi @JiaLiPassion thanks for the quick reply. 

Please try to zoom in and out on map and notice that `requestAnimationFrame` isn't being intercepted inside the forked Zone... I knew that Google Maps is triggering `requestAnimationFrame` because when you go to the Performance tab of chrome devtools, you'll see the call stack, and it triggers it when you zoom in, out and pan on the map...

**Comment by JiaLiPassion** [comment]
@wtubog , the reason `zoom` not trigger `reqeustAnimationFrame` in `mapZone`, because it is in `root` zone, the `wheel` event listener was added to `google map` when loading `https://maps.googleapis.com/maps/api/js`, so it is not in `mapZone`.

If there are gmaps api that can add customized `wheel` event handler, you can add it into mapZone.

**Comment by wtubog** [comment]
A map instance has a method `addListener` and then you specify the event name, in this case `zoom_changed` and then the callback function (https://stackblitz.com/edit/typescript-ugi7tp?file=index.ts).. I think that the underlying implementation of `addListener` uses that `wheel` event handler that has been registered to the `root` zone...

Is there a way to tap into the `root` zone?

**Comment by JiaLiPassion** [comment]
@wtubog , there is no way to change `root` zone, there maybe some `hack` to intercept the `requestAnimationFrame`, but your first post said you want to improve performance, let `zone` to intercept `requestAnimationFrame` or `wheel` may slow down performance.

**Comment by JiaLiPassion** [comment]
@wtubog , I created a sample to override `root zone`, you can try it for performance test.
https://github.com/JiaLiPassion/customize-root-zone

And sorry I just copied your code from `stackblitz` with the Google map API key, so please change your google map API Keys because it is public in github.

**Comment by JiaLiPassion** [comment]
close for now.
