### ISSUE TITLE
0.8.19+ - Object doesn't support property or method 'isFrozen'

### ISSUE THREAD

**Issue by Mysame** [angular/zone.js#1031]
Browser: IE 11.2068.14393.0 Update Version 11.0.51
zone.js: 0.8.20
Last working zone.js version: 0.8.18

Since updating I've had the following error:
>Object doesn't support property or method 'isFrozen'

```
function rewriteDescriptor(obj, prop, desc) {
    // issue-927, if the desc is frozen, don't try to change the desc
    if (!Object.isFrozen(desc)) { // <<<<<<<<<
        desc.configurable = true;
    }
    // ...
}
```

So the issue is related to the fix of #927 
This is odd, seeing how isFrozen is natively supported in IE11.
Purely informational, I also have the following polyfills:
```
/** IE9, IE10 and IE11 requires all of the following polyfills. **/
import "core-js/es6/symbol";
import "core-js/es6/object";
import "core-js/es6/function";
import "core-js/es6/parse-int";
import "core-js/es6/parse-float";
import "core-js/es6/number";
import "core-js/es6/math";
import "core-js/es6/string";
import "core-js/es6/date";
import "core-js/es6/array";
import "core-js/es6/regexp";
import "core-js/es6/map";
import "core-js/es6/weak-map";
import "core-js/es6/set";

/** IE10 and IE11 requires the following for NgClass support on SVG elements */
import "classlist.js";  // Run `npm install --save classlist.js`.

/** IE10 and IE11 requires the following for the Reflect API. */
import "core-js/es6/reflect";

/**
 * Required to support Web Animations `@angular/platform-browser/animations`.
 * Needed for: All but Chrome, Firefox and Opera. http://caniuse.com/#feat=web-animation
 **/
import "web-animations-js" // Run `npm install --save web-animations-js`.
```

**Comment by JiaLiPassion** [comment]
@Mysame , you need to `import "core-js/es6/object"`.

**Comment by Mysame** [comment]
@JiaLiPassion It's in there. 2nd line in the imports.

**Comment by JiaLiPassion** [comment]
@Mysame, sorry I didn't see it, if you import `object`, `isFrozen` should be there. Could you post a reproduce repo?

**Comment by Mysame** [comment]
I've got a suspicion it's Webpack-related.
It executes that piece of code a couple of times, until suddenly it can't.
The object 'desc' it's trying to execute it on is pretty interesting (see attachment
![2018-02-27_15-22-07](https://user-images.githubusercontent.com/1966231/36733830-19753d3e-1bd2-11e8-872a-2e32b910f09e.png)
.

**Comment by JiaLiPassion** [comment]
@Mysame , I think I still need a reproduce repo, could you just try to print `Object.isFrozen` or other `polyfills` which loaded by `core-js`.

**Comment by Dirtyburger1338** [comment]
I just had this problem in an aspnet core angular build where i import polyfills in bootbrowser.ts. 
For me, it was solved by importing the polyfills **before** zone.js 

import './polyfills';
import 'zone.js';

**Comment by Mysame** [comment]
I can confirm this works.
I wouldn't call it a fix, though.

**Comment by elvirdolic** [comment]
We have the same issue, when we split the polyfills for IE and for other browser like angular.io is doing

**Comment by davcyr** [comment]
Has this issue been resolve? We are having the same issue except it only happens when my coworker compiles the project. The "if (!Object.isFrozen(desc)) ..." appear in his polyfill but when I compile the code it doesn't. We compared the package.json file and they were the same. How does polyfills.bundle.js file gets generated?

**Comment by JiaLiPassion** [comment]
@davcyr , please post reproduce repo, thanks.

**Comment by piyushkashyap14** [comment]
I am using angular 5 and has the same error. i have imported all mentioned by uncommenting. Also I have no bootbrowser.ts file. Kindly help!

**Comment by JiaLiPassion** [comment]
@piyushkashyap14, please provide a reproduce repo.

**Comment by JiaLiPassion** [comment]
will close it for now.
