### ISSUE TITLE
messed up args in setInterval / setTimeout in fakeAsyncZones

### ISSUE THREAD

**Issue by e-hein** [angular/zone.js#1032]
https://github.com/angular/zone.js/blob/e1df4bc636b4de6e89b24349dcbb3a95ce17220c/lib/zone-spec/fake-async-test.ts#L417

The genuine args-Array in a setInterval or setTimeout call contains the function to be called and the delay. The arguments for the function start at the third position. By passing the arguments like this, the function invoked will get an array as argument that contains the function itself and the delay and the expected needed arguments.

Sample:
`setInterval((name) => console.log('my name:', name), 100, 'Emanuel')`
expected call:
`('Emanuel') => console.log('my name:', 'Emanuel')`
actual call:
`([function, 100, 'Emanuel') => console.log('my name:', [function, 100, 'Emanuel'])`

**Comment by JiaLiPassion** [comment]
@e-hein , thank you for posting the issue, this is a known issue, I will fix it.

**Comment by e-hein** [comment]
spec:
`
    it('should pass arguments to times', () => {
      fakeAsyncTestZone.run(() => {
        let value = 'genuine value';
        let id = setTimeout((arg1, arg2) => {
          value = arg1 + arg2;
        }, 0, 'expected', ' value');

        testZoneSpec.tick();
        expect(value).toBe('expected value');
      });
    });

    it('should pass arguments to periodic timers', () => {
      fakeAsyncTestZone.run(() => {
        let value = 'genuine value';
        let id = setInterval((arg1, arg2) => {
          value = arg1 + arg2;
        }, 10, 'expected', ' value');

        testZoneSpec.tick(10);
        expect(value).toBe('expected value');
      })
    });

`
fix:
`
            case 'setTimeout':
              task.data['handleId'] =
                  this._setTimeout(task.invoke, task.data['delay'], Array.prototype.slice.call((task.data as { args: IArguments }).args, 2));
              break;
            case 'setInterval':
              task.data['handleId'] =
                  this._setInterval(task.invoke, task.data['delay'], ...Array.prototype.slice.call((task.data as { args: IArguments }).args, 2));
`
