### ISSUE TITLE
Unhandled Promise rejection: [$injector:modulerr] Failed to instantiate module $$UpgradeModule due to: Error: [$injector:modulerr] Failed to instantiate module {"_invokeQueue":[],"_configBlocks":[["$injector","invoke",{}]],"_runBlocks":[],"requires":["ngAnimate","ngMessages","ngResource","ngCookies","ui.router","base64","smn-ui","core"],"name":"nexus"} due to: Error: [ng:areq] Argument 'module' is not a function, got Object http://errors.angularjs.org/1.6.9/ng/areq?p0=module&p1=not%20a%20function%2C%20got%20Object

### ISSUE THREAD

**Issue by pcbsytem** [angular/zone.js#1037]
When trying to make an application hybrid with angularJs and angular 4 this error, I use this example https://vsavkin.com/migrating-angular-1-applications-to-angular-2-in-5-simple-steps-40621800a25b.

**Comment by pcbsytem** [comment]
Can anybody sugest a valid example for angular ugrade?

**Comment by JiaLiPassion** [comment]
@pcbsytem , please post your question in `stackoverflow`, this is not a `zone.js` issue.

**Comment by sathishkumar94** [comment]
[$injector:modulerr] Failed to instantiate module $$UpgradeModule due to:


Same error throwing myself also. when i try to reload the page with angular and angular 5

**Comment by singhvivek2503** [comment]
@sathishkumar94  Me too facing the same issue. Were you able to fix it?

**Comment by JiaLiPassion** [comment]
will close this for now because of lack of information.
