### ISSUE TITLE
[Question] Does this work with mongoose and the likes?

### ISSUE THREAD

**Issue by natanavra** [angular/zone.js#1043]
Do user libraries need to be monkey patched?
If so, this is quite similar to `continuation-local-storage`, which doesn't work out of the box with external libraries like `mongoose` and `bluebird`.

I've tested it with Mongoose `find` callback / promises and the context is lost, am I missing something?

**Comment by JiaLiPassion** [comment]
@natanavra , yes, you are right, `zone.js` works similar with `continuation-local-storage/async-listener` which monkey patch possible known `async callback`.

In next version, `zone.js` will support `bluebird`, for  `mongoose`, it is not supported now.

**Comment by matthewadams** [comment]
@JiaLiPassion Is this project intended solely for use in browsers, or can it work on Node.js server-side, headless backends as well?

**Comment by JiaLiPassion** [comment]
@matthewadams, yes, this project can work in `nodejs`, `browser`, or mix environment like `electron`.
if you are using `nodejs`, you can `import 'zone.js/dist/zone-node'`.

**Comment by matthewadams** [comment]
@JiaLiPassion At what time should I `require('zone.js/dist/zone-node')`?  At the earliest possible moment in my Node.js app, or simply before the first use of `zone.js`?

**Comment by JiaLiPassion** [comment]
here is an example. https://github.com/JiaLiPassion/zone-node
