### ISSUE TITLE
NullInjectorError: No provider for AddItemPage! -- Ionic 3

### ISSUE THREAD

**Issue by 06MOHD04** [angular/zone.js#1046]
Error:

> Uncaught (in promise): Error: StaticInjectorError[AddItemPage]: StaticInjectorError[AddItemPage]: NullInjectorError: No provider for AddItemPage! Error: StaticInjectorError[AddItemPage]: StaticInjectorError[AddItemPage]: NullInjectorError: No provider for AddItemPage! at _NullInjector.get (http://localhost:8100/build/vendor.js:1276:19) at resolveToken (http://localhost:8100/build/vendor.js:1564:24) at tryResolveToken (http://localhost:8100/build/vendor.js:1506:16) at StaticInjector.get (http://localhost:8100/build/vendor.js:1377:20) at resolveToken (http://localhost:8100/build/vendor.js:1564:24) at tryResolveToken (http://localhost:8100/build/vendor.js:1506:16) at StaticInjector.get (http://localhost:8100/build/vendor.js:1377:20) at resolveNgModuleDep (http://localhost:8100/build/vendor.js:10938:25) at NgModuleRef_.get (http://localhost:8100/build/vendor.js:12159:16) at resolveNgModuleDep (http://localhost:8100/build/vendor.js:10938:25)

When i write in HomePage:
```
import { AddItemPage } from './../add-item/add-item';
...
constructor(... ,private addItemPage: AddItemPage){...}
...
editItems(item){
    this.addItemPage.editItem(item);
}
```
Why is that happening ? I tried a lot (importing Http..)  but its not working..

> Angular 5
> CLI 1.4.5
> Ionic 3

Any Solutions?

**Comment by JiaLiPassion** [comment]
@06MOHD04 , it seems you didn't provide `AddItemPage` in `NgModule` or `Component`.
 this is not a `zone.js` issue, please ask it in `stackoverflow`.
