### ISSUE TITLE
angular 5 after routing to another page and resize window appears Error: this.each is not a function

### ISSUE THREAD

**Issue by VyacheslavSulimov** [angular/zone.js#1060]
Angular 5 after routing to next page  and resize window appers next error. If refresh the page (F5) then resize working as expected. 

used 0.8.14 version zone.js
![image](https://user-images.githubusercontent.com/9913905/38135302-24305392-3420-11e8-9873-fb3b31115906.png)

**Comment by JiaLiPassion** [comment]
@VyacheslavSulimov , please provide a reproduce repo, thank you.

**Comment by JiaLiPassion** [comment]
Will close this for now.
