### ISSUE TITLE
Regression: usage of date pipe in template of component tested using fakeAsync makes test fail in 0.8.21

### ISSUE THREAD

**Issue by jnizet** [angular/zone.js#1064]
Here's a repo reproducing the issue: https://github.com/jnizet/zonejsbug.

The bug is illustrated in https://github.com/jnizet/zonejsbug/blob/master/src/app/app.component.spec.ts.

I'm not exactly sure of what causes the issue. I've had this bug in a real test of mine, and tried to reproduce it here with a relatively simple test. It appears that the bug is caused by the usage of the date pipe in the template of the component. The same test passes if version 0.8.20 is used (which can be tested by changing the version in package.json, re-executing yarn, then re-executing ng test).

**Comment by JiaLiPassion** [comment]
@jnizet , thank you for posting the issue, this has been fixed in https://github.com/angular/zone.js/pull/1051
