### ISSUE TITLE
__zone_symbol__xhrScheduled error in IE/Edge

### ISSUE THREAD

**Issue by DevInstinct** [angular/zone.js#1072]
I'm using an external library (oidc-client) and I am getting this error in IE/Edge, but otherwise it works fine in Chrome/Firefox.

I'd like to understand what could be the cause of this zone.js error. The app is an Angular 5 app.

SCRIPT5007: Unable to get property '__zone_symbol__xhrScheduled' of undefined or null reference
zone.js (2959,1)
ERROR TypeError: Unable to get property 'current' of undefined or null reference
SCRIPT5007: Unable to get property 'stackTraceLimit' of undefined or null referenceeval code (1466) (119,9)
SCRIPT5007: Unable to get property '__zone_symbol__xhrScheduled' of undefined or null referencezone.js (2959,1)
ERROR TypeError: Unable to get property 'current' of undefined or null reference
SCRIPT5007: Unable to get property 'stackTraceLimit' of undefined or null referenceeval code (1466) (119,9)
SCRIPT5007: Unable to get property '__zone_symbol__xhrScheduled' of undefined or null referencezone.js (2959,1)
ERROR TypeError: Unable to get property 'current' of undefined or null reference
SCRIPT5007: Unable to get property 'stackTraceLimit' of undefined or null referenceeval code (1466) (119,9)
SCRIPT5007: Unable to get property '__zone_symbol__xhrScheduled' of undefined or null referencezone.js (2959,1)
ERROR TypeError: Unable to get property 'current' of undefined or null reference
SCRIPT5007: Unable to get property 'stackTraceLimit' of undefined or null referenceeval code (1466) (119,9)
SCRIPT5007: Unable to get property '__zone_symbol__xhrScheduled' of undefined or null referencezone.js (2959,1)
SCRIPT5007: Object expectedzone.js (192,1)

Thanks for any help.

**Comment by JiaLiPassion** [comment]
@DevInstinct , please post a reproduce repo, thanks.

**Comment by DevInstinct** [comment]
Fix #1072 seems to get rid of one error, but I continue to get these errors, which were also in the original trace:

![image](https://user-images.githubusercontent.com/8344000/38570759-923c58d2-3cbc-11e8-9e3d-7ec182f6391a.png)

**Comment by JiaLiPassion** [comment]
@DevInstinct, I still need a reproduce repo, maybe you use some `3rd party` lib to make `XMLHttpRequest` changed.

**Comment by DevInstinct** [comment]
Got the error using oidc-client and the silent renew feature in an Angular 5 app. 

Worked around it by getting rid of Angular for the silent renew callback; stopped getting the errors even without the fix. Thanks.

**Comment by DevInstinct** [comment]
See https://github.com/IdentityModel/oidc-client-js/issues/528
