### ISSUE TITLE
process is not defined

### ISSUE THREAD

**Issue by G-Bazan** [angular/zone.js#1083]
Hi Guys, I installed zone.js via npm in my Angular 5 application.
When the app start I got this error in chrome inspector:

Uncaught ReferenceError: process is not defined
    at zone-node.js:2216

// patch process related methods
Zone.__load_patch('nextTick', function () {
    // patch nextTick as microTask
    patchMicroTask(process, 'nextTick', function (self, args) {
        return {
            name: 'process.nextTick',
            args: args,
            cbIdx: (args.length > 0 && typeof args[0] === 'function') ? 0 : -1,
            target: process
        };
    });
});

How can I solve?

Best regards

**Comment by JiaLiPassion** [comment]
@G-Bazan , could you post a reproduce repo? because `zone-node.js` is only used in `nodejs` project. it should not be loaded in `angular` project. So you must have some wrong `polyfills` settings.

**Comment by JiaLiPassion** [comment]
Will close for now because no reproduce info
