### ISSUE TITLE
zone.onMicrotaskEmpty.emit(null) causing browser(Chrome and Firefox) to freeze 

### ISSUE THREAD

**Issue by CruelEngine** [angular/zone.js#1086]
Occurs during a Subscription in Angular 5 application . When a GET request is subscribed for first time its all good . but if the same GET request is subscribed browser freezes which eventually forces my application to crash . No errors on console .

Zonejs version : "^0.8.19"

Thanks,

**Comment by JiaLiPassion** [comment]
@CruelEngine , please provide a reproduce repo.

**Comment by CruelEngine** [comment]
@JiaLiPassion i tried reproducing it again and again using a dummy Observable , but i'm unable to do so . I'll try to provide you a repro repo .

**Comment by CruelEngine** [comment]
@JiaLiPassion , after 24hrs of debugging i came to a conclusion that it is angular that is creating this havoc in my project . It seems that angular event propagation is failing which is causing Observable.complete() to never fire the callback function. I'll close this issue .
Thanks for the help and sorry for the trouble .

**Comment by JiaLiPassion** [comment]
@CruelEngine , sure , glad to here the issue was resolved.
