### ISSUE TITLE
ngZone with google map lead to heigh CPU and memory leak

### ISSUE THREAD

**Issue by harishmegharaj** [angular/zone.js#1090]
My APP build with google map and Angular, when I use the application for 10-15 mins it crashes. 
So many zoneTask gets accumulated, if we test through chrome dev memory tools.

**Comment by JiaLiPassion** [comment]
@harishmegharaj, please provide a reproduce repo, so I can check it.

**Comment by harishmegharaj** [comment]
Ok, I will create and update you.

**Comment by harishmegharaj** [comment]
On upgrading to latest zone.js (0.8.17) version it got resolved.
