### ISSUE TITLE
RxJs 6 Support

### ISSUE THREAD

**Issue by MrBlaise** [angular/zone.js#1091]
The `zone-patch-rxjs.js` fails to build with rxjs 6.x that Angular 6 uses now. Any plan on fixing this?

**Comment by JiaLiPassion** [comment]
@MrBlaise , I will check it and try to handle `rxjs 6`, could you provide a reproduce repo to describe the error you mentioned?

**Comment by MrBlaise** [comment]
@JiaLiPassion Unfortunately the repo I am working on is private, you should be able to reproduce the issue by creating a fresh Angular 6 application with the angular-cli (`ng new zonejs`) and import the patch in pollyfils.ts:
`import 'zone.js/dist/zone-patch-rxjs';`

After that building it for production should cause errors (`ng build --prod --aot --build-optimizer`) like this:

`Module not found: Error: Can't resolve 'rxjs/add/observable/defer' in '/REDACTED/node_modules/zone.js/dist'`

**Comment by JiaLiPassion** [comment]
@MrBlaise , ok, got it, you can use `rxjs-compat` for now to resolve this issue until a `rxjs6` version of `zone.js patch` is released.

**Comment by MrBlaise** [comment]
Any news on this @JiaLiPassion?

**Comment by JiaLiPassion** [comment]
@MrBlaise , I have finished `zone-testing-rxjs-fake-async` part, the `rxjs` part need some additional work, I am still working on it, please wait for a little longer, does `rxjs-compat` work for you now?

**Comment by MrBlaise** [comment]
Yes it is working fine. I was just wondering, because this is the last thing that needs the compat library in my setup. I am in no rush, the app working fine with compat until this is finished. Thanks.

**Comment by slavafomin** [comment]
Hello! The `zone.js` is the only dependency which prevents us from dropping the `rxjs-compat` package in our Angular projects. I think this is a major issue for many Angular projects, because this prevents them from building more optimal bundles. Could you please tell me if this issue is actually on a roadmap?

**Comment by JiaLiPassion** [comment]
@slavafomin, @MrBlaise, I am not sure about the release plan, you can test it with this branch.
Update the `package.json` to 
```
I am not sure the release schedule, please use the following branch as temp test solution.
update the package.json

"zone.js": "git://github.com/JiaLiPassion/zone.js#ts29-fix-dist"
```

Thanks.
