### ISSUE TITLE
[Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. 

### ISSUE THREAD

**Issue by tegarjgap** [angular/zone.js#1097]
Hi, I want to ask..

How to solve the problem? ([Violation] Added non-passive event listener to a scroll-blocking 'wheel' event.) 

the temporary step which has iam try :
1. i am use module default-passive-events (npm)
2. and, How to add script event listener in angular? Am i save in component.ts?

Or,. another way to solve this problem?

thank

**Comment by JiaLiPassion** [comment]
Currently to add `passive` event handler, you need to use `dom API` directly.

```ts
element.addEventHandler('scroll`, function() {}, {passive: true});
```

**Comment by JiaLiPassion** [comment]
@tegarjgap , you can check the example here, https://stackblitz.com/edit/angular-xftpwj?file=src%2Fapp%2Fapp.component.ts

**Comment by tegarjgap** [comment]
great... thank sir @JiaLiPassion  👍
