### ISSUE TITLE
Zone throws access deny error

### ISSUE THREAD

**Issue by AndyLex** [angular/zone.js#1100]
I have a project based on Angular 2. Everything works very well before, but recently `Access Deny' error is sometimes thrown. I googled a lot, but nothing is found. Any clue is appropriate. BTW, I am using Angular 4.2.4 and zone 0.8.4.

Here are the screenshot of browser's console:

![issue](https://user-images.githubusercontent.com/40136443/41237249-aac614da-6dc5-11e8-878c-c4a0bab79240.png)

**Comment by JiaLiPassion** [comment]
Could you provide a reproduce repo?

**Comment by StuartNg2** [comment]
@AndyLex I have similar issue. The project based on angular 4.2 and zone 0.8 works very well before, but recently it sometimes throws `undefined is not a function`. 

@JiaLiPassion, I try to create a simple online demo, once it is created, I will post link here.

**Comment by BerndLeukert** [comment]
I have some similar error before. I update `zone` to latest version to resolve the problem. Maybe you could have a try.

**Comment by AndyLex** [comment]
@BerndLeukert I updated to latest `zone` and also update other dependencies to latest version, the issue is gone. 

Thanks a lot, everyone. I close the issue, as it is resolved.
