### ISSUE TITLE
Angular not detecting changes in Electron + ExpressJS callbacks

### ISSUE THREAD

**Issue by 255kb** [angular/zone.js#1101]
Hello, 

I have an application built with Electron, Angular 5 and ExpressJS (It's basically running a local server). 

Until Electron v1.8.3 everything was running fine, but since I updated Angular stopped detecting changes in ExpressJS callbacks like `server.listen(8080, () => { /* not executed */ })`. This results in my interface not being updated until a call to the server is made (which strangely "triggers" the callback), or until waiting a random amount of time. 

I spent time reading all the issues regarding Angular, Zone and Electron and I've found some very similar cases with NodeJS `fs` package callbacks.
So I tried various combination of using a ChangeDetectorRef, importing `zone-mix` and/or `zone-patch-electron` in `polyfills.ts`, wrapping all ExpressJS callbacks in `Zone.current.wrap(...)` but nothing worked. 

I saw that there are some specific Zone patches for SocketIo and other libs so I wonder if I should create a patch for ExpressJS maybe? But I would definitely need some guidances here. 

Thank you.

**Comment by JiaLiPassion** [comment]
Could you post a reproduce repo?

**Comment by 255kb** [comment]
Sure I will work on this!

**Comment by 255kb** [comment]
after testing with a more recent electron version (3.0.0) everything seems to be working again, I can close this.
