### ISSUE TITLE
ERROR Error: Uncaught (in promise): Error Error at XMLHttpRequest.onreadystatechange [as 

### ISSUE THREAD

**Issue by ishan123456789** [angular/zone.js#1103]
I'm not able to find the cause of this error is there a solution for that or anything else this error tells.

`ERROR Error: Uncaught (in promise): Error Error at XMLHttpRequest.onreadystatechange [as __zone_symbol__ON_PROPERTYreadystatechange] (VM7676 twilio.js:55) at XMLHttpRequest.H (VM7678 polyfills.js:3) at t.invokeTask (VM7678 polyfills.js:3) at Object.onInvokeTask (VM7679 vendor.js:5425) at t.invokeTask (VM7678 polyfills.js:3) at r.runTask (VM7678 polyfills.js:3) at e.invokeTask [as invoke] (VM7678 polyfills.js:3) at p (VM7678 polyfills.js:2) at XMLHttpRequest.v (VM7678 polyfills.js:2) at XMLHttpRequest.onreadystatechange [as __zone_symbol__ON_PROPERTYreadystatechange] (VM7676 twilio.js:55) at XMLHttpRequest.H (VM7678 polyfills.js:3) at t.invokeTask (VM7678 polyfills.js:3) at Object.onInvokeTask (VM7679 vendor.js:5425) at t.invokeTask (VM7678 polyfills.js:3) at r.runTask (VM7678 polyfills.js:3) at e.invokeTask [as invoke] (VM7678 polyfills.js:3) at p (VM7678 polyfills.js:2) at XMLHttpRequest.v (VM7678 polyfills.js:2) at c (VM7678 polyfills.js:3) at VM7678 polyfills.js:3 at VM7676 twilio.js:55 at XMLHttpRequest.onreadystatechange [as __zone_symbol__ON_PROPERTYreadystatechange] (VM7676 twilio.js:55) at XMLHttpRequest.H (VM7678 polyfills.js:3) at t.invokeTask (VM7678 polyfills.js:3) at Object.onInvokeTask (VM7679 vendor.js:5425) at t.invokeTask (VM7678 polyfills.js:3) at r.runTask (VM7678 polyfills.js:3) at e.invokeTask [as invoke] (VM7678 polyfills.js:3)`

**Comment by JiaLiPassion** [comment]
@ishan123456789 ,  please provide a reproduce repo.

**Comment by ishan123456789** [comment]
Sorry but I can't I'm not authorised to share the code but I can explain that could be a reason a bit.
I'm integrating twilio with streamtext iframe so when I change Streamtext iframe url dynamically on click of button and then, when I stop twilio connection then I get this error and all of sudden the page reloads due to this error and behave strangely.

**Comment by JiaLiPassion** [comment]
@ishan123456789 , in such case, especially involves some 3rd party libs, without reproduce repo, it is hard to debug, most of such kind of error is not `zone.js` error, `zone.js` just catch all errors happened inside `promise` and throw them out.

 So if you can create a very simple repo to reproduce this error, I can help to debug.

**Comment by ishan123456789** [comment]
Thanks for giving your time @JiaLiPassion I've still not figured out what the problem could be but i fixed the error by instead of using property binding on iframe I switched to DOM manipulation.
What I did was
**Replaced**
```
  <p *ngIf="state.state == 1 || state.state == 2">
    <iframe [src]="iframeUrl" id="transcribed-content" frameborder="0" *ngIf="iframeUrl"></iframe>
```
**With**
```

 <p id="iframeContainer" *ngIf="state.state == 1 || state.state == 2">
  
   </p>

```
And instead add iframe using this
```
  appendIframe () {
    console.log('onChange called')
    let elem = document.getElementById('iframeContainer');
    if(elem) {
        let iframe = document.createElement('iframe');
        iframe.src = this.presentIframeUrl; 
        iframe.setAttribute('frameborder' , "0");
        iframe.setAttribute("id", "transcribed-content");
        elem.innerHTML = iframe.outerHTML;
    }
  }
```

So this error was gone with this.
