### ISSUE TITLE
Dynamic form disappears on clicking on a link to add more dynamic form

### ISSUE THREAD

**Issue by TaposhiBaruah** [angular/zone.js#1105]
I am loading a dynamic form from a json and also i have a link on click which I am adding more form controls in the same dynamic formGroup. When first time I am clicking on the link the dynamic form disappears, when I reload my page and click again in that link it is working. Please can anyone tell me why it is happening. While debugging I got that it is breaking when the control is going inside zone.ts
when this line is loading inside scheduleTask() function.
try {
                task.invoke.apply(this, arguments);
            }

**Comment by JiaLiPassion** [comment]
I don't think this is a `zone.js` issue, please ask it in stackoverflow. thank you.
