### ISSUE TITLE
Firefox Add-on TypeError: "fetch" is read-only

### ISSUE THREAD

**Issue by saiumesh-letznav** [angular/zone.js#1115]
I've developed Extension using Angular 4 which works well on Chrome but not on firefox, result in **TypeError: "fetch" is read-only**

The stack of error as follows 

```
var global = module.exports = typeof window != 'undefined' && window.Math == Math
  ? window : typeof self != 'undefined' && self.Math == Math ? self
  // eslint-disable-next-line no-new-func
  : Function('return this')();

function zoneify(fn) {
        return function () {
            var resultPromise = fn.apply(this, arguments);
            if (resultPromise instanceof ZoneAwarePromise) {
                return resultPromise;
            }
            var ctor = resultPromise.constructor;
            if (!ctor[symbolThenPatched]) {
                patchThen(ctor);
            }
            return resultPromise;
        };
    }
    if (NativePromise) {
        patchThen(NativePromise);
        var fetch_1 = global['fetch'];
        if (typeof fetch_1 == 'function') {
            global['fetch'] = zoneify(fetch_1); // **error line**
        }
    }
```

**Comment by JiaLiPassion** [comment]
@saiumesh-letznav, in firefox extension environment, a lot of `window global` object can't be `monkey patched`, so you can disable the errored one, in this case, you can add this line before `import zone.js`.

```
(window as any).__Zone_disable_fetch = true;
```

**Comment by saiumesh-letznav** [comment]
Thanks for response. unfortunately it didn't work. I still get same error **TypeError: "fetch" is read-only polyfills.bundle.js:8719:31 **

**polyfills.browser.ts** as follows

```
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es7/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/set';
import 'core-js/es6/weak-map';
import 'core-js/es6/weak-set';
import 'core-js/es6/typed';
import 'core-js/es6/reflect';
import 'core-js/es7/reflect';
(window as any).__Zone_disable_fetch = true;
// import 'zone.js'; // tried both of these imports
import 'zone.js/dist/zone';
```

**Comment by JiaLiPassion** [comment]
@saiumesh-letznav, yeah, the `fetch` is still not a module in `0.8.26`, currently, you have to wait for the next version of `zone.js` and try this flag until then.

**Comment by saiumesh-letznav** [comment]
@JiaLiPassion I did try with your flag. still I get the same error.

**Comment by saiumesh-letznav** [comment]
@JiaLiPassion With same version of zone.js with Angular 6 works but doesn't work with Angular 4.

**Comment by SerkanSipahi** [comment]
@JiaLiPassion will this issue really fixed in the next version of zone.js?

**Comment by SerkanSipahi** [comment]
@JiaLiPassion why patching on developer console of firefox is working without any error (fetch is read-only)?
```
window.fetch = function() {console.log('xxx')}
fetch(); // logs: xxx
```

**Comment by JiaLiPassion** [comment]
@SerkanSipahi, `console` is different with `Extension`, `extension` is like a `limited environment`, a lot of `behaviors` are not allowed there.

**Comment by SerkanSipahi** [comment]
@JiaLiPassion do you have plan when will this issue (the fetch is still not a module) fill be fixed?

**Comment by SerkanSipahi** [comment]
Update: i found a way to run the extension firefox but that is a really really bad solution. The error "fetch is read-only" appears only in `"strict mode"`. What i have done? Well, i removed from compiled pollyfills.js the `"strict mode"` function headers.

Now i get some different weired error:

```
ERROR TypeError: "'clearInterval' called on an object that does not implement interface Window."
Error: macroTask 'setInterval': can not transition to 'running', expecting state 'scheduled', was 'unknown'.
```

**Comment by SerkanSipahi** [comment]
@saiumesh-letznav @JiaLiPassion  now i have found a way to run the angular app in firefox without any errors. Its hackie but is works :) It has one downside but this ok. You have to trigger the rendering engine `this.appRef.detectChanges()` by your self on any change. 

in main.ts pass `{ngZone: 'noop'}` to bootstrapModule:
```
platformBrowserDynamic()
  .bootstrapModule(AppModule, {ngZone: 'noop'})
```
then remove then from pollyfills:
```
import 'zone.js/dist/zone';  // Included with Angular CLI.
```

and remove this line from angular itself: https://github.com/angular/angular/blob/master/packages/core/src/testability/testability.ts#L74

I did lot of research to running that in Firefox as Extension. Im not an angular or zone.js core developer with deep knowledge. Is there a other way to solve that?

@JiaLiPassion Do you think this is now more a Angular issue because of the Testability class? Maybe there is a way to disable that like `ngZone: 'noop'`! Or should we wait as you described above everything will be solved when zone.js comes with modules. What to do?

P.S. Please read all my thread notes to get an overview, thank you.

**Comment by saiumesh-letznav** [comment]
Hello There, with new version of Angular this issue will be resolved. Thanks!!

**Comment by SerkanSipahi** [comment]
really? :) which new version? v7.x or v8?

**Comment by saiumesh-letznav** [comment]
Yes. with Angular 7.1.0
