### ISSUE TITLE
App keep calling this

### ISSUE THREAD

**Issue by mpadierna** [angular/zone.js#1117]
Starting today, I observed this instruction is repeating every second, while testing Angular apps locally.

ZoneDelegate.prototype.invokeTask = function (targetZone, task, applyThis, applyArgs) {
            return this._invokeTaskZS ?
                this._invokeTaskZS.onInvokeTask(this._invokeTaskDlgt, this._invokeTaskCurrZone, targetZone, task, applyThis, applyArgs) :
                task.callback.apply(applyThis, applyArgs);        **<--**
        };

**Comment by JiaLiPassion** [comment]
This is not an issue, every `async` operations in `angular` will finally call this method, such as you have a `setInterval(..., 1000)`, it will call this function every second.

**Comment by mpadierna** [comment]
Thank you
