### ISSUE TITLE
Compatibility with native Promise.race

### ISSUE THREAD

**Issue by robwalch** [angular/zone.js#1130]
We've run into an issue on a handful of websites where embedding zone.js after jwplayer.js broke setup of our players because of a mix of Promise types used in Promise.race. The issue only surfaced as we rolled out a release that included changes to a promise chain ([addressed here](https://github.com/jwplayer/jwplayer/pull/3044)).

jwplayer.js uses references to `Promise` stored in a module on script embed to prevent interference by third party libraries. zone expects `Promise` to be used globally, so if a site doesn't include zone.js before other libraries like ours, issues like this could arise.

Here's the issue boiled down to it's simplest form. First ZoneAwarePromise a is resolved, then native Promise b. Native Promise.race picks native Promise b instead of ZoneAwarePromise a. It should always pick a which is the case when the Promise type is consistent.

https://codepen.io/anon/pen/NLbPrW?editors=1010

```js
/* in the head
<script>window.NativePromise = Promise</script>
<script src=//unpkg.com/zone.js@0.8.26/dist/zone.js></script>
*/
var NativePromise = window.NativePromise;

console.log('===============================');
console.log('native Promise:', NativePromise);
// console.log('native Promise.all:', NativePromise.all);
// console.log('native Promise.race:', NativePromise.race);
// console.log('native Promise.resolve:', NativePromise.resolve);
console.log('===============================');
console.log('global Promise:', Promise);
// console.log('global Promise.all:', Promise.all);
// console.log('global Promise.race:', Promise.race);
// console.log('global Promise.resolve:', Promise.resolve);
console.log('===============================');

var a = Promise.resolve('a');
var b = NativePromise.resolve('b');

console.log("Promise a:", a);
console.log("Promise b:", b);
console.log('===============================');
var c = NativePromise.race([a, b]);

c.then(function(all) {
  // The result should always be 'a'
  // In this scenario native Promise.race does not recognize that ZoneAwarePromise was resolved first
  console.warn("Final result:", all);
  console.log('===============================');
}).catch(function(error) {
  console.error("Exception:", error);
  console.log('===============================');
});
```
I hesitated to log this issue because in jwplayer.js we can [opt to always use Promise globals](https://github.com/jwplayer/jwplayer/pull/3045), and site developers can embed zone.js first to resolve this issue. In practice these changes can be difficult our outside of our control, so I wanted to bring it up here with simple reproduction steps in case this is something that could be prevented by making ZoneAwarePromise behave as native Promises do in this scenario.

**Comment by JiaLiPassion** [comment]
@robwalch, thank you for posting the issue, the reason the result is `b` because the `thenCallback` of `NativePromise` will be `executed earlier` than `ZoneAwarePromise`. Because `ZoneAwarePromise` use `NativePromise.then` as `scheduler`, so even `promise a` is `resolved`, it will still behind `NativePromise b`.
`zone.js` patch `Promise`, so the intent is letting `app` use `global.Promise(ZoneAwarePromise)` all the time, if there are some libraries still use `NativePromise`, just like you said, we can change the `import order` to let them use it.

**Comment by robwalch** [comment]
Hi @JiaLiPassion,

Thank you for the explanation. Could native promises in `Promise.race` be detected to avoid the additional `NativePromise.then` scheduler? If not feel free to close.

**Comment by JiaLiPassion** [comment]
This is not easy to implement such feature, so I will close this for now.
