### ISSUE TITLE
updating data from back end data using Http but im getting Error

### ISSUE THREAD

**Issue by Mallesh25nayak** [angular/zone.js#1136]
im updating data but using angular 4 in  server backend application Http
![decoratorfacory](https://user-images.githubusercontent.com/42228652/45608739-3307fe00-ba72-11e8-884d-b7312c58367d.PNG)

**Comment by JiaLiPassion** [comment]
Please ask the question to stackoverflow, this is not a `zone.js` issue.

**Comment by Mallesh25nayak** [comment]
thanks
