### ISSUE TITLE
How to ignore on properties with lazy loaded library

### ISSUE THREAD

**Issue by egaoneko** [angular/zone.js#1137]
I lazily load some libraries. I set `__Zone_disable_timer = true` to ignore `setTimeout` and `setInterval` in the lazily loaded libraries and then set `__zone_symbol__BLACK_LISTED_EVENTS`to ignore custom events in the libraries like `pointermove` and `mousemove`. But I think it doesn't work well like under pictures.

* Before settings on window
![image](https://user-images.githubusercontent.com/6583941/45750029-85027c80-bc48-11e8-868f-2766a8080404.png)

* After Settings on window
![image](https://user-images.githubusercontent.com/6583941/45750341-9730ea80-bc49-11e8-8fbf-9e2f05287cca.png)

* Before settings on loaded libraries
![image](https://user-images.githubusercontent.com/6583941/45750241-386b7100-bc49-11e8-9b5e-39b6a7bcf7cf.png)

* After settings on loaded libraries
![image](https://user-images.githubusercontent.com/6583941/45750426-04dd1680-bc4a-11e8-9677-c7faaad769e8.png)

How to set ignore with lazily loaded libraries.

**Comment by JiaLiPassion** [comment]
Please provide a reproduce repo, thanks.

**Comment by egaoneko** [comment]
@JiaLiPassion ,

I made simple repo. I ask for understanding on slow loading.

* repo : https://github.com/egaoneko/zone-test
* page : http://egaoneko.github.io/zone-test/

I want to ignore things like under pictures.

![image](https://user-images.githubusercontent.com/6583941/45790794-7efcb200-bcc1-11e8-85b4-4f82dc593d6a.png)

![2018-09-20 10 41 06](https://user-images.githubusercontent.com/6583941/45790840-cb47f200-bcc1-11e8-9842-5d85ef914bcf.png)

**Comment by egaoneko** [comment]
@JiaLiPassion , Thank you for the solution! It's works! I'll close this issue!
