### ISSUE TITLE
Unable to run unit test in Angular 5 - ng test 

### ISSUE THREAD

**Issue by sivarajthava** [angular/zone.js#1141]
While running ng test, I am getting error

"Uncaught TypeError: Zone.__load_patch is not a function".

I checked the source code in the debugger console in chrome, it is showing error ../zone.js/dist/async-test.js_global. It was worked earlier but now seems some of the dependencies got upgraded.

**Dev Dependencies version:**

@Angular/cli: 1.2.7,
@angular/compiler-cli:~5.2.0,
@types/jasmine:2.5.38,
@types/jasminenewd:~2.0.2,
@types/node:~6.0.60,
karma:~1.4.1,
karma-chrome-launcher:~2.1.1,
Karma-cli: ~1.0.1,
karma-jasmine: ~1.1.0,
ts-node: ^3.3.0,
talent: ~4.5.0

**Dependencies:**
zone. js: ^0.8.4

**Comment by JiaLiPassion** [comment]
It seems your `environment` is not correct, please provide a `reproduce repo`.

**Comment by sivarajthava** [comment]
Thank You. It worked 2 weeks back. I did not change anything in the code base. I created another sample project event that project also worked for me.  After launched chrome browser I checked the developer console I am getting error in "Uncaught TypeError: Zone.__load is not a function at zone-testing.js" and cause is from test.js. Could you please let me know any version compatibility  issue
