### ISSUE TITLE
How to make zone.js not to patch some async tasks like settimeout 

### ISSUE THREAD

**Issue by kksevta** [angular/zone.js#1146]
Hi Folks,
We have a scenario where we are continuously polling data from server in frequent calls of **setTimeout**.
We don't want the change detection to run after each setTimeout.

I know we can run setTimeout **outsideAngularZone**. But we have setTimeout at multiple places in our code. So putting each setTimeout in outsideAngularZone will be time taking process.

So what is the best way to tell Zone.js not to patch some async tasks.
If there is way to set the blacklist required async tasks something like following.

`Zone.setBlacklist('setTimeout','requestAnimationFrame', 'XHR')
`
Please suggest your way to do this kind of stuff

**Reason why we need it** because continuous calls of setTimeout and XHR gives sudden memory spikes in IE10 after a long run. 
But when we remove the **__load_patch** calls for timers, requestAnimationFrame and XHR in Zone.js, there are no memory spikes at all.

**Comment by JiaLiPassion** [comment]
here is the document, https://github.com/angular/zone.js/blob/master/MODULE.md
Just add code before `import 'zone.js/dist/zone'; in polyfills.ts`
```
(window as any).__Zone_disable_timers = true;
(window as any).__Zone_disable_requestAnimationFrame = true;
import 'zone.js/dist/zone';
```

**Comment by kksevta** [comment]
Thanks @JiaLiPassion  for quick response.
I hope for XHR` (window as any).__Zone_disable_XHR = true; ` will work.
and this won't trigger changeDetection at all after XHR completion?

**Comment by JiaLiPassion** [comment]
Yes, it should work, but I only disable this `XHR` may not enough, because I remember `Angular` also use `xhr.onload`, so you may also need to disable `onload`
```
    (window as any).__Zone_ignore_on_properties = [
      {
        target: XMLHttpRequest.prototype,
        ignoreProperties: ['load']
      }
    ];

```

**Comment by kksevta** [comment]
what about onReadyStateChange?

**Comment by JiaLiPassion** [comment]
Yeah, you may need to disable that too.

**Comment by kksevta** [comment]
HI @JiaLiPassion 

Polyfills.ts
```
(window as any).__Zone_disable_timers = true;
import 'zone.js/dist/zone'; 
```
App.Component.ts
```

class AppComponent implements OnInit {
  value = 0;
  ngOnInit() {
    setInterval(() => {
      this.value = +new Date();
    }, 500);
  }
}

```
This is updating the value in template after each interval, that's means Angular Change detection is running after each interval.

But instead of making changes in Polyfills.ts, If I directly comment out code in Zone.js

```
// Zone.__load_patch('timers', function (global) {
//     var set = 'set';
//     var clear = 'clear';
//     patchTimer(global, set, clear, 'Timeout');
//     patchTimer(global, set, clear, 'Interval');
//     patchTimer(global, set, clear, 'Immediate');
// });
```
The value is not updated in template and angular change detection is not running.
Please let me know what am I missing?

**Comment by kksevta** [comment]
```
Zone.__load_patch = function (name, fn) {
                console.log(__Zone_disable_timers);
......
}
```
This was giving undefined, So for the time being I have defined it in index.html

```
 <link rel="icon" type="image/x-icon" href="favicon.ico">
  <script>
    __Zone_disable_timers = true;
    __Zone_disable_requestAnimationFrame = true

  </script>
```

and this works fine
