### ISSUE TITLE
Question:When Can we expect new release of zone.js?

### ISSUE THREAD

**Issue by abdulkareemnalband** [angular/zone.js#1149]
## Question

It has been long time since last release. There are quite few fixes available on trunk for long time (like rxjs6 compability #1122 )

When can we expect next release?

**Comment by peterbakonyi05** [comment]
Any update on this please? :)

Back in July, there was an important memory leak fix when running tests using Jest (https://github.com/angular/zone.js/pull/1106). Would be nice to know when can we expect that fix to be released (maybe at least as a nightly).

**Comment by JiaLiPassion** [comment]
I created a temp release branch for test, I am not sure about the official release date.
update `package.json` as below

```
"zone.js": "git://github.com/JiaLiPassion/zone.js#release-20181029"
```

**Comment by hlovdal** [comment]
And please, please start adding [changelog entries](https://keepachangelog.com/en/1.0.0/) to the releases. Currently https://github.com/angular/zone.js/releases contains **zero** release related information except for the dates.

Or if you want to keep the changelog information in a dedicated file instead that is fine as well ([example](https://github.com/pallets/flask/blob/master/CHANGES.rst)), but DO write change log entries. It is not just something nice to have, it is absolutely essential.

**Comment by JiaLiPassion** [comment]
@hlovdal, there is change log here, https://github.com/angular/zone.js/blob/master/CHANGELOG.md

**Comment by dottodot** [comment]
Considering how much zone.js is used in Angular I'm bit confused as to why none of the bug fixes are getting released. It now been 7 months since the last release.

**Comment by mko** [comment]
@JiaLiPassion I think one of the big concerns from the community is why an official release is being held up. I greatly appreciate the "temp release" on your fork, but we're stuck in a weird holding pattern until that becomes formalized properly.

**Comment by JiaLiPassion** [comment]
Sure, guys, sorry for the delay, I will ask @mhevery about the release schedule.

**Comment by mko** [comment]
@JiaLiPassion @mhevery Any update on a Zone.js release? There's numerous issues fixed by the temp release version but none appear to be usable by the community.

**Comment by ArielBar** [comment]
any updates?

**Comment by JiaLiPassion** [comment]
Sorry, I still confirm the `release date` with `angular core team`, hope will cut a release soon!

**Comment by oocx** [comment]
We are currently getting many support calls from our customer because of issue #1072, which was fixed by #1074. A new release that contains that PR would be great.

**Comment by JiaLiPassion** [comment]
we will have a new release very soon, sorry for the long waiting!

**Comment by JiaLiPassion** [comment]
0.8.27 is live in npm now!
