### ISSUE TITLE
ZoneTask.toString can return a number, which causes problems in Jasmine

### ISSUE THREAD

**Issue by fr0** [angular/zone.js#1153]
If a karma/jasmine test fails due to an unhandled promise rejection, Jasmine's `PrettyPrinter` class throws an exception due to the `ZoneTask.toString` function not returning a string.

See: https://github.com/jasmine/jasmine/issues/1575

**Comment by fr0** [comment]
I have not been able to reproduce it outside of my private repo, but I will keep trying. Thanks!

**Comment by Jonatino** [comment]
Also seeing this issue in jasmine.

**Comment by Jonatino** [comment]
@JiaLiPassion @fr0 looks like the issue is coming from here

```
    public toString() {
      if (this.data && typeof this.data.handleId !== 'undefined') {
        return this.data.handleId;
      } else {
        return Object.prototype.toString.call(this);
      }
    }
```
It will return the `TaskData.handleId` which is a number. Returning a number and not a string doesn't make sense in a `toString()` call.

**Comment by JiaLiPassion** [comment]
@Jonatino, thanks! I will fix this one.
