### ISSUE TITLE
drainMicroTaskQueue infinite loop Angular 6 safari

### ISSUE THREAD

**Issue by nategurian** [angular/zone.js#1154]
I recently upgraded my angular 5 app to angular 6. On my windows machine the app works as expected.  When I cloned the repo on my MAC the app does not ever visually load. I am able to hit breakpoints but the app never loads. 

After debugging, I found that the function drainMicroTaskQueue gets stuck in an infinite loop and that is causing the hang up of the browser.

Angular 6
zone.js: 0.8.24
Mac: High Sierra
Safari

Any insights would be greatly appreciated, I can also post any other information needed upon request.

Thanks!

**Comment by JiaLiPassion** [comment]
@nategurian, yeah, please post some reproduce repo, thanks!

**Comment by nategurian** [comment]
@JiaLiPassion I am trying. I just created a new angular 6 app for repro purposes with all the same versions I am using and its working. So Just a bit confused at the moment

**Comment by nategurian** [comment]
@JiaLiPassion Yea I am not sure I am able to reproduce the error in another small repo. I am more than willing to post my private repo in github for someone to check it out to reproduce.

**Comment by nategurian** [comment]
Found the issue. I had an async call that was being called over and over causing the app to jam up. Still a mystery as to why it would not jam on windows but it would on mac. Either way, ticket closed and not zone.js related
