### ISSUE TITLE
Cannot assign to read only property 'message'

### ISSUE THREAD

**Issue by staeke** [angular/zone.js#1155]
We have unit tests throwing errors with `message` being read-only. This blows up with zone in `mocha-patch.js` since it's writing to the `message` property, thereby hiding our original errors (apart from destroying the test run)

**Comment by staeke** [comment]
The offending line is line 150 in `mocha-patch.js`. I can work on creating a reproducible case, but is it necessary. If you just look at that line, I think you can agree that this would not work if the errors don't allow resetting `message`. Btw...using `0.8.26`

**Comment by staeke** [comment]
@JiaLiPassion - somehow my answer ended up before yours :), so look above

**Comment by JiaLiPassion** [comment]
@staeke, ok, I will add `check` logic there, thanks.

**Comment by JiaLiPassion** [comment]
@staeke, which version are you using, and could you post a reproduce repo? thanks!

**Comment by staeke** [comment]
@JiaLiPassion thanks
