### ISSUE TITLE
Patch decodeAudioData

### ISSUE THREAD

**Issue by maximedupre** [angular/zone.js#1165]
Using the promise version of `decodeAudioData` returns a zone aware promise, but since this method has not been patched, the operation is not included in the list of microtasks.

    context.decodeAudioData(ab).then(this.audioDataDecoded.bind(this))
    this.ngZone.hasPendingMicrotasks // returns false
    Promise.resolve(null).then(() => {});
    this.ngZone.hasPendingMicrotasks // returns true

Using zone `v0.8.26`

**Comment by JiaLiPassion** [comment]
I will try it later, thanks!

**Comment by maximedupre** [comment]
Maybe that the `.then` is added as a micro task once the decoding is done?

**Comment by JiaLiPassion** [comment]
@maximedupre, yes, you are right, when `decodeAudioData` is finished, `hasPendingMicrotasks` will be true.

**Comment by maximedupre** [comment]
Shouldn't there be a microtrask as soon as the `.then` is called?

**Comment by JiaLiPassion** [comment]
No, this is how promise worked, microtask only scheduled when promise is resolved or rejected.
