### ISSUE TITLE
Suspicious code in promise.ts

### ISSUE THREAD

**Issue by shicks** [angular/zone.js#1168]
https://github.com/angular/zone.js/blob/9ed57124d19b116fbdf0869da94804be960a53fe/lib/common/promise.ts#L296
https://github.com/angular/zone.js/blob/9ed57124d19b116fbdf0869da94804be960a53fe/lib/common/promise.ts#L299

I'm rolling out a new lint check and discovered some suspicious code in promise.ts.  In the above snippets, `null` is always falsy, so it is ignored.  It can be simplified to simply `promise = resolve(value)` or `promise = reject(value)`.

**Comment by JiaLiPassion** [comment]
Thanks, I will fix it!
