### ISSUE TITLE
Error: ReferenceError: Zone is not defined

### ISSUE THREAD

**Issue by papushe** [angular/zone.js#1174]
1. I've created a new project

2. trying to run this -
![image](https://user-images.githubusercontent.com/23402732/50144107-0359d380-02b7-11e9-91c6-3f6ee0ce5b34.png)

3. getting this error
"C:\Program Files\nodejs\node.exe" "C:\Users\ashely\Documents\Angular\unit Testing\runProtractor\node_modules\protractor\bin\protractor" "C:\Program Files\JetBrains\IntelliJ IDEA 2018.3.1\plugins\JavaScriptLanguage\helpers\protractor-intellij\lib\protractor-intellij-config.js" "--intellijOriginalConfigFile=C:\Users\ashely\Documents\Angular\unit Testing\runProtractor\protractor.conf.js" --disableChecks --specs "C:\Users\ashely\Documents\Angular\unit Testing\runProtractor\src\app\app.component.spec.ts" "--grep=^AppComponent "
(node:16588) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[11:12:57] I/launcher - Running 1 instances of WebDriver
[11:12:57] I/direct - Using ChromeDriver directly...
[11:13:02] E/launcher - Error: ReferenceError: Zone is not defined
    at C:\Users\ashely\Documents\Angular\unit Testing\runProtractor\node_modules\@angular\core\bundles\core-testing.umd.js:390:29
    at Object.setPrototypeOf.__proto__ (C:\Users\ashely\Documents\Angular\unit Testing\runProtractor\node_modules\tslib\tslib.es6.js:1:1)
    at Object.<anonymous> (C:\Users\ashely\Documents\Angular\unit Testing\runProtractor\node_modules\@angular\core\bundles\core-testing.umd.js:10:2)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
[11:13:02] E/launcher - Process exited with error code 100

Process finished with exit code 4

4. package.json

{
  "name": "run-protractor",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "~1.7.4",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  }
}

any idea?

**Comment by JiaLiPassion** [comment]
You are not importing `zone testing related stuff`.
I see you are using `zone.js 0.8.19`, so you need to add the following code at the beginning your `src/test.ts`.

```
import 'zone.js/dist/long-stack-trace-zone';
import 'zone.js/dist/proxy';
import 'zone.js/dist/sync-test';
import 'zone.js/dist/jasmine-patch';
import 'zone.js/dist/async-test';
import 'zone.js/dist/fake-async-test';
```

**Comment by papushe** [comment]
1. this is my test.ts file after your answer
![image](https://user-images.githubusercontent.com/23402732/50149733-aa913780-02c4-11e9-80b2-90349da24e11.png)

and still get the same error

**Comment by JiaLiPassion** [comment]
Oh, you already import `zone-testing`, then you don't need
```
import 'zone.js/dist/zone';
import 'zone.js/dist/long-stack-trace-zone';
import 'zone.js/dist/proxy';
import 'zone.js/dist/sync-test';
import 'zone.js/dist/jasmine-patch';
import 'zone.js/dist/async-test';
import 'zone.js/dist/fake-async-test';
```

And I think this is your `intellij setting issue`, it seems this `test.ts` are not loaded...

**Comment by papushe** [comment]
leave it like this?
![image](https://user-images.githubusercontent.com/23402732/50149967-491d9880-02c5-11e9-994e-99979c525674.png)

So what should I do?

**Comment by JiaLiPassion** [comment]
I am not sure about `intellij settings`, if you run `ng test`,  any error there?

**Comment by papushe** [comment]
no. working just fine

**Comment by JiaLiPassion** [comment]
Yeah, so this is not a `zone.js` issue, please ask how to integrate with `ng test` with `jetbrain IDE` in stackoverflow. 

I am using `WebStorm`, with the newest version, there is a built in `run config` named `karma test` under `angular project`, it just work out of the box.

**Comment by papushe** [comment]
I'm using IntelliJ IDEA 2018.3.1 (Ultimate Edition).

Where can I find it? the 'Karma test'?

By the way, If I haven't mentioned it before - I've created a new project with angular cli
and just try to run the specific test as I attached

**Comment by JiaLiPassion** [comment]
Like I said, I am using `WebStorm`, so I am not sure about `Intellij`, you can ask at `stackoverflow`.

**Comment by azatsh** [comment]
Hello papushe !
I just upgraded intellij idea to newest version (2019.1) and faced same issue.
I figured out that karma plugin that was installed earlier is not compatible with the new intellij idea and idea uses Protractor plugin to run my karma tests.
So I had to download a new version of karma plugin from https://plugins.jetbrains.com/plugin/7287-karma/versions and then it worked.

**Comment by markhbucknell** [comment]
@papushe I am having the same issue. I'm curious to know if you came across a fix.

**Comment by JiaLiPassion** [comment]
Will close because this is not a zone.js issue.
