### ISSUE TITLE
Upgrading to karma 3.0.0, failure of test cases

### ISSUE THREAD

**Issue by ossdev07** [angular/zone.js#1187]
Hi, 

Updated the karma version to 3.0.0, failure can be seen in the test command karma start karma-build-jasmine-phantomjs.conf.js --single-run 

https://travis-ci.com/ossdev07/zone.js

The browser gets a launch for the phantomjs but, no test cases are getting executed.
I am unable to understand, why the test cases are not getting executed. 
Please help me with the issue.

Thanks,

**Comment by JiaLiPassion** [comment]
Please provide a reproduce repo, thanks!

**Comment by JiaLiPassion** [comment]
Will close for now, because phantomjs is gone.
