### ISSUE TITLE
microTask 'Promise.then': can not transition to 'running', expecting state 'scheduled', was 'scheduling'.

### ISSUE THREAD

**Issue by earshinov** [angular/zone.js#1189]
Looks similar to https://github.com/angular/zone.js/issues/1167 except that this one is in `Promise.then` instead of `setInterval`.

We receive this error though an automated error reporting system ([Sentry](https://sentry.io/)) and have not yet managed to reproduce it manually.

For what we see, problem occurs in IE11 only.

We use zone.js 0.8.26 (so, https://github.com/angular/zone.js/issues/1085 does not apply).

**Comment by JiaLiPassion** [comment]
@earshinov, could you provide a reproduce repo? thanks.

**Comment by benjaminrau** [comment]
Same happens to us (also known only from Sentry). Happens on different routes, components etc. Yet we have NOT been able to reproduce it ourselves.

**Comment by JiaLiPassion** [comment]
Will close for now, if it can be reproduce, we will research again.
