### ISSUE TITLE
Zone long stack traces generates wrong stack trace

### ISSUE THREAD

**Issue by thekip** [angular/zone.js#1195]
I created a small stackblitz repo which shows the problem: 

https://stackblitz.com/edit/typescript-ouevfy?file=index.html

Click on both buttons, and you will see that place of actual definition of event handler is incorrect. Here is a really simple example where both definitions really close to each other, but in real application, the situation is much worse. 

Actually for all EventTasks (not sure about other, haven't tested it) captured stacktrace equals to the latest one defined event handler. 

This caused because here [long-stack-trace.ts](https://github.com/angular/zone.js/blob/master/lib/zone-spec/long-stack-trace.ts#L112)

```ts
onScheduleTask: function(...): any {
 // ...
  if (!task.data) task.data = {};
  (task.data as any)[creationTrace] = trace; // <------
 // ...
}

```

`data` property from ZoneTask is a reference to global object defined [here](https://github.com/angular/zone.js/blob/master/lib/common/events.ts#L444) as `OPTIMIZED_ZONE_EVENT_TASK_DATA` constant.

And all execution of this callback just mutate this object and all tasks inherit the same stack trace.

There are two possible ways to resolve the problem. 
It's either possible to modify `long-stack-trace.ts` file

```diff
-  (task.data as any)[creationTrace] = trace;
+    (task.data as any) = {
+      ...task.data,
+      [creationTrace]: trace,
+    };

```

Or break the reference in [ZoneTask](https://github.com/angular/zone.js/blob/master/lib/zone.ts#L1171) itself

```diff
class ZoneTask<T extends TaskType> implements Task {
   ...
    constructor(...) {
      this.type = type;
      this.source = source;
-     this.data = options;
+     this.data = { ...options };
      this.scheduleFn = scheduleFn;
      this.cancelFn = cancelFn;
      this.callback = callback;
   }
}
```

**Comment by JiaLiPassion** [comment]
@thekip , thanks for posting this issue, I will check it.
