### ISSUE TITLE
Evergreen bundle missing in dist

### ISSUE THREAD

**Issue by benjamincombes** [angular/zone.js#1196]
Hi, thanks for the great idea to add an evergreen bundle! However, it is stated that an "zone-evergreen.js" bundle can be find in the dist directory, but I couldn't find it : is this an error on my side, or is it really not here? Thanks a lot for your help.

**Comment by JiaLiPassion** [comment]
@benjamincombes, this changes have not been released, after next version `0.9.0` released, it will under `dist`.

**Comment by benjamincombes** [comment]
Hi @JiaLiPassion! As it was mentioned on the main page of the project, I thought it was already available, thanks for your answer.
