### ISSUE TITLE
Provide example for using in plain JavaScript Node.js app

### ISSUE THREAD

**Issue by matthewadams** [angular/zone.js#1208]
This could be an RTFM, but it'd be jim-dandy if you could provide a working example of how to properly use `zone.js` in a headless, plain JavaScript Node.js app that I'd run in a terminal with `node index.js`.

https://github.com/angular/zone.js/blob/HEAD/SAMPLE.md contains what appears to be only browser-based examples.

**Comment by JiaLiPassion** [comment]
@matthewadams, sure, I will add it! Thanks!

**Comment by matthewadams** [comment]
@JiaLiPassion I'm dead in the water right now.  If you could throw something together quickly so that I could get going, I'd really appreciate it!  :)

Currently, I'm getting `undefined` for `Zone.current`.

**Comment by JiaLiPassion** [comment]
@matthewadams, here is a very basic sample, https://github.com/JiaLiPassion/zone-node

**Comment by matthewadams** [comment]
Ah, ok.  By doing `require('zone.js/dist/zone-node')`, you get a global variable `Zone`.  That's the difference.

Perhaps it's worth updating the documentation to say that?  Thanks!

I'll try it out, and reopen this issue if I'm having trouble.

**Comment by JiaLiPassion** [comment]
@matthewadams, sure, I will make documentation more clearly, thanks!
