### ISSUE TITLE
correct zone to enter for Promise.then callbacks

### ISSUE THREAD

**Issue by hayes** [angular/zone.js#130]
I have been working to get proper support for Promises in async-listener, and took a very different direction then what zone.js appears to be doing.  I was wondering what the best approach is since these libraries have fairly similar goals.

The question I have is:
For a promise, how should callbacks passed to `then`, `catch` and `chain` (currently looks like `chain`  is not implemented in zones) be bound to.  

zones appears to be binding to the zone that was active when the promise is first created.
the patch I have been working on for async-listener (https://github.com/hayes/async-listener/blob/4cbbec288ed5e034415b1d4fbb480468627e889d/index.js#L260) binds callbacks to the context that was active when it was `accepted` or `rejected`.  

My thinking with this was that the callback to a then would be a continuation from the previous async task, for example parsing a response would be a continuation from the request rather than the event handler that initiated the request.

I do not usually use Promises in my own code, so I am hoping to get some opinions from other people about the best way for this to work.  I also do not know about the internal implementation of zones in different browsers, only the implementations in v8 used in iojs 1.0, 2.0 and node 0.12, all of which seem to be good about always using the promise.constructor property when creating new promises for continuations. Implementing continuations in the way I have done for async-listener is definitely a lot more complex/complicated.

Feel free to close this is not relevant, or the wrong place to talk about this.

thanks for any input!

**Comment by vicb** [comment]
> For a promise, how should callbacks passed to then, catch and chain (currently looks like chain is not implemented in zones) be bound to.

I think `chain` is not in naitve `Promise`

> zones appears to be binding to the zone that was active when the promise is first created.

The callback are actually bound to the active zone when `then` (or `catch`) is called

I am not familiar with async-listsener, coudl you please expand on its goal and what you are trying to achieve ?

**Comment by hayes** [comment]
Sorry, I did not word that correctly, callbacks are bound to when then is called (then returns a promise, which is what I meant when I said promise is created).

V8 exposes a chain method on the promise prototype: https://github.com/v8/v8-git-mirror/blob/master/src/promise.js#L384

Async-listener is an api that was orinially designed for node, but has since been removed in favor of a lower level api.  It now exists as a polyfillfor the original api that monkeypatches all the async methods in node. It basically provides a way to share context between async calls similar to zone.js. 

Async listener is a bit lower level then zones and does not directly create contexts, instead it allows a user to add a listener for any point when an async callback is created which can return an object that is passed to hooks that are run before and after the callback is executed.  This is the api continuation-local-storage is built on (much closer to the api zone.js exposes). 

My goal here was to figure out what the reasoning was behind zone.js binding at the active zone at the time then or catch was called rather than at the time the promise was resolved.  zone.js 

Its likely that the same approach would make sense in both libraries so I just wanted to understand the reasoning behind the decision.

**Comment by vicb** [comment]
> Async-listener is an api that was orinially designed for node, but has since been removed in favor of a lower level api. It now exists as a polyfillfor the original api that monkeypatches all the async methods in node. It basically provides a way to share context between async calls similar to zone.js.

Interesting... we should have "something" working in the node.js env, I'll take a deeper look at your project.

> My goal here was to figure out what the reasoning was behind zone.js binding at the active zone at the time then or catch was called rather than at the time the promise was resolved. zone.js

I think that if you make a parallel with an event listener, it is easier to understand. You want the listener to execute in the zone where is was set up.
_Note that this behavior is also what Dart implement - Dart has native support for Zones_

**Comment by hayes** [comment]
Thanks for the info, I think this makes sense.  For async-listener, event-listeners can be ignored as being synchronous (for the most part).  I can see why promises would follow the same pattern in zone.js.

Currently async-listener is mostly being used for APM products and long stack traces, so for us I think it makes sense to link the continuations to the thing that resolved the promise rather than the thing that created it.

Both approaches have their places, and I think in browsers (especially with some of the newer apis) promises will be resolved from outside the application, so linking to that does not make as much sense, node and browsers have very different concerns. 

Thanks again
