### ISSUE TITLE
global.zone inconsistent name casing causes an error when using long-stack-trace-zone

### ISSUE THREAD

**Issue by gajus** [angular/zone.js#146]
https://github.com/angular/zone.js/blob/master/lib/zone.js#L6

```js
global.zone = new core.Zone();
```

https://github.com/angular/zone.js/blob/master/lib/browser/long-stack-trace-zone.js#L3

```js
if (!global.Zone) {
    throw new Error('zone.js should be installed before loading the long stack trace zone');
}
```

Undefined `global.Zone` variable causes an error.

I am importing the following files using webpack:

* 'zone.js'
* 'zone.js/lib/browser/long-stack-trace-zone.js'

**Comment by gajus** [comment]
Importing:

* 'zone.js/lib/browser/zone.js'
* 'zone.js/lib/browser/long-stack-trace-zone.js'

Does not throw the error. Maybe it is documentation issue.

**Comment by matthewjh** [comment]
What do you mean by 'inconsistent naming'?

Also, can you post a code snippet illustrating how you're importing zone and long-stack-trace-zone?

**Comment by vicb** [comment]
(global.)`Zone` is the class & `zone` the current zone.

Closing as not an issue.

**Comment by gajus** [comment]
> (You probably want to include the files from /dist)

Including files from /dist prompts a warning:

```
WARNING in ../~/zone.js/dist/long-stack-trace-zone.js
Critical dependencies:
1:113-120 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ../~/zone.js/dist/long-stack-trace-zone.js 1:113-120
```

**Comment by gajus** [comment]
Lets start from the beginning. My problem: I want to enable long stack trace.

Here is my webpack config:

```js
var webpack = require('webpack');

module.exports = {
    debug: true,
    devServer: {
        inline: true,
        colors: true,
    },
    context: __dirname + '/src',
    entry: {
        app: [
            // 'es6-shim',
            'traceur-runtime',
            // Does not need be explicitly included since Angular2 will pick it up using import {}.
            // 'zone.js',
            // Adding long-stack-trace-zone.js has no effect.
            // 'zone.js/dist/long-stack-trace-zone.js',
            'reflect-metadata',
            './app/app'
        ]
    },
    output: {
        path: __dirname + '/endpoint/static',
        filename: '[name].js'
    },
    plugins: [
        new webpack.NoErrorsPlugin()
    ],
    module: {
        loaders: [
            {
                test: /\.html$/,
                loader: 'html'
            },
            {
                test: /\.js$/,
                exclude: [
                    /node_modules/
                ],
                loader: 'babel',
                query: {
                    stage: 0
                }
            }
        ]
    }
};
```

The problem is that Angular2 automatically resolves zone.js dependency. Therefore, even if I include "zone.js/dist/long-stack-trace-zone.js" into the build, it will not take effect, because it affects only the browser build (as far as I can tell).

Is there anything I could change in the app itself to affect which zone.js version is used?

```js
import { Component, View, bootstrap } from 'angular2/angular2';

@Component({
    selector: 'app'
})

@View({
    template: ``
})

class App {
    constructor () {
        
    }
}

document.addEventListener('DOMContentLoaded', () => {
    bootstrap(App);
});
```

**Comment by gajus** [comment]
Ok, I have figured it out. I simply need to add alias to webpack config to make use of dev builds:

```js
alias: {
    'angular2': 'angular2/es6/dev'
},
```

Development bundle uses long stack trace by default https://github.com/angular/angular/blob/f25e43fab8e9d935a155f2a528133871c1cc89b3/gulpfile.js#L956-L964.
