### ISSUE TITLE
[Idea] Patching for pollyfills loaded after Zone.js

### ISSUE THREAD

**Issue by matthewjh** [angular/zone.js#148]
Hi,

Is there any reason not to patch polyfills if they're loaded after Zone.js? If a library you're using pulls in a `MutationObserver`polyfill, shouldn't that polyfill have the same behaviour as if it was loaded prior to Zone.js?

I think this could be done by adding a setter on `global[x]` so that whenever that property is set after zone.js applies its patches (such as by a polyfill), it will be patched accordingly (e.g. if x is "MutationObserver").

@btford, @vicb

**Comment by btford** [comment]
A polyfill will need to use an API that's already patched.

For example, a polyfill for `MutationObserver` might use `setTimeout` to preserve the semantics of `MutationObserver`. Because Zone.js has already patched `setTimeout`, the `MutationObserver` polyfill will also be patched.

**Comment by matthewjh** [comment]
Is that really guaranteed? For example, webcomponentsjs's `MutationObserver` polyfill uses `setImmediate` if it's available, which I don't believe zone.js polyfills…? 

Seems to open the door to inconsistent behaviour between code running on platforms requiring polyfills and those not. I suppose some variance is somewhat inevitable, but it can at least be mitigated by patching the polyfill.

**Comment by btford** [comment]
> Is that really guaranteed?

Yes.

Zone.js does patch `setImmediate`: https://github.com/angular/zone.js/blob/master/lib/patch/browser.js#L14-L18

If there was a native browser API Zone.js didn't patch that a polyfill used, the fix should be to patch the native browser API.

Patching both the polyfills and the underlying API would result in an API being patched twice, which is also incorrect behavior.

**Comment by matthewjh** [comment]
Ahh, okay. Thanks Brian.

From:  Brian Ford
Reply-To:  "angular/zone.js"
Date:  Monday, 20 July 2015 16:35
To:  "angular/zone.js"
Cc:  Matt
Subject:  Re: [zone.js] [Idea] Patching for pollyfills loaded after Zone.js (#148)


Is that really guaranteed?

Yes.

Zone.js does patch setImmediate: https://github.com/angular/zone.js/blob/master/lib/patch/browser.js#L14-L18

If there was a native browser API Zone.js didn't patch that a polyfill used, the fix should be to patch the native browser API.

Patching both the polyfills and the underlying API would result in an API being patched twice, which is also incorrect behavior.
