### ISSUE TITLE
Deprecations regarding webkit

### ISSUE THREAD

**Issue by juergenzimmermann** [angular/zone.js#153]
In the Chrome 44 console I get these messages as shown in the attached screenshot:
![deprecations-webkit](https://cloud.githubusercontent.com/assets/734334/9250644/f5c9ab48-41ce-11e5-9fdc-ef19ed152dbc.png)

**Comment by btford** [comment]
Zone.js patches both the prefixed and unprefixed APIs.

There's really nothing I can do about this though; until the deprecated APIs are removed, Zone.js will have to patch them.
