### ISSUE TITLE
Microtask test failure on Android 4.3.0

### ISSUE THREAD

**Issue by vicb** [angular/zone.js#158]
see https://travis-ci.org/angular/zone.js/builds/76538375#L560

PR #157 has added support for Android browsers but a microtask test fails.

@mlaval could you please take a look at this ?

**Comment by btford** [comment]
This was fixed by f25ca2fc0604e171e9436b2fd1bb5f0fe8e5815d, right?

**Comment by vicb** [comment]
right, closing
