### ISSUE TITLE
Zones are un-expectantly reentrant

### ISSUE THREAD

**Issue by justinfagnani** [angular/zone.js#162]
This may be a education/documentation issue, or something to address in the implementation, but I found reentrancy on Zones to be unexpected, and had to work around it.

I expected zones to not be reentrant, that is, beforeTask and the corresponding afterTask would always be called together, without an intervening beforeTask call on the same zone. Another way to say it is that I expected that only one task would be running at a time in a zone

This ends up being not true when synchronously triggering a bound callback. I happened to me with DOM events:
1. A task bound to my zone runs
2. beforeTask is called
3. The task registers an event handler, which is bound to the zone
4. Later the task fires an event
5. The handler runs, but it's bound to the zone, so
6. beforeTask is called again
7. Later endTask is called twice.

The end result is: beforeTask, beforeTask, endTask, endTask all on the same zone.

This was tricky with my zone because it was trying to accumulate time spent in tasks:

```
    let tagZone = clazz._tagZone = zone.fork({
      beforeTask: function () {
        // assumes beforeTask is never called again before endTask
        this._startTime = performance.now();
      },
      afterTask: function () {
        this._totalTime += performance.now() - this._startTime;
      },
    });
```

This had to be rewritten with a stack:

```
    let tagZone = clazz._tagZone = zone.fork({
      beforeTask: function () {
        this._startTimes.push(performance.now());
      },
      afterTask: function () {
        let startTime = this._startTimes.pop();
        this._totalTime += performance.now() - startTime;
      },
    });
    tagZone._startTimes = [];
```

**Comment by vicb** [comment]
@justinfagnani Any chance you are running this code in the root zone ? This might explain why the inner task is in the same zone. It should be in a child zone for any other zone. The rationale of this behavior is that we don't want to create new (somewhat expensive) zones in Angular for the root zone, which is the one that run "non angular" code.

_Are 5 & 6 swapped in your description above ?_

**Comment by justinfagnani** [comment]
The tasks are running in the zone I create in the code snippet, not the root zone.

5 & 6 might be swapped, depending on how you read it. Is the task executing that causes beforeTask to run, or does beforeTask actually run before the task? Given that the task callback is wrapped in another which delegates to the zone, I tend to think that the task actually triggers beforeTask when it runs, but either way, the task being dequeued and it's impending execution triggers beforeTask.

**Comment by vicb** [comment]
Thanks for the clarification.

I think what happens is that the child zone (of `tagZone`) inherits its hooks (via [`Object.create(parentZone)`](https://github.com/angular/zone.js/blob/3d6dc0850b20fd86eef5879f8283de5ee668a668/lib/core.js)). 

The `beforeTask` hook gets called on the child zone but because it has not been overriden, the prototype hook (`tagZone.beforeTask`) gets called.

**Comment by justinfagnani** [comment]
What child zone of `tagZone`? I don't define one.

I think what's happening is that since DOM events are synchronous, and addEventListener binds its callback to the current zone, any code which adds an event listener and then fires that event in the same synchronous task will have the zone be re-entered.

I suppose this will happen with all synchronous "tasks". Since they aren't a microtask or event loop, there's an existing zone in place when the bound callback is invoked. This means that not only is there a stack of zones from forking, but there's another stack of zones from executing synchronous callbacks.

When trying to account for time like my example, this second stack needs to be carefully handled. My workaround isn't complete, since if the second zone is different from the first, I won't push a new start time, and some time will be double-counted between zones. I would need a global stack, not one per zone.

One way to solve this at the zone.js level would be to call endTask on the current zone before executing a synchronous callback, then call beforeTask again when the callback is complete. Essentially beforeTask and endTask would be called any time the zone is becoming or unbecoming the current zone.

**Comment by vicb** [comment]
> What child zone of tagZone? I don't define one.

Event handlers are executed in a child of the zone that set up their listeners (to support async stack traces).
