### ISSUE TITLE
Safari crashing on reloading remote iOS Safari with Zone

### ISSUE THREAD

**Issue by mlynch** [angular/zone.js#167]
I'm noticing that Safari debugger on OS X has a really tough time handling refresh on a remotely-debugged iOS Safari instance running Zone (and Angular 2). Either Safari will take 10x longer to reload the page, or it will crash on iOS with a notice: "A problem occured with this webpage so it was reloaded."

I was able to get one stack trace to show (and I'm not sure if it's related at all), but this problem is incredibly difficult to debug since the console closes when the refresh fails:

![screenshot 2015-09-01 09 40 06](https://cloud.githubusercontent.com/assets/11214/9607537/588636ba-508f-11e5-8c23-6bc42c085dd0.png)

The error corresponds to this code in zone.js 0.5.2:

``` javascript
      obj[setName] = function () {
        return global.zone[setName].apply(this, arguments);
      };

      var clearDelegate = obj[clearName];

      global.zone[clearName] = function (id) {
        if (ids[id]) {
          delete ids[id];
          global.zone.dequeueTask();
        }
        return clearDelegate.apply(this, arguments);
      };

      obj[clearName] = function () {
        return global.zone[clearName].apply(this, arguments); // Line 3985
      };
    }
  });
};
```

I'll try to create a reproducible test case, but any angular 2 demo should suffice (unless there is an issue with Ionic 2 which I find unlikely).

**Comment by Brooooooklyn** [comment]
aha, I'm building ionic web app with zone.js too. And I'm trying to fix those issues in my zone.js file these day.

**Comment by JiaLiPassion** [comment]
close for now.
