### ISSUE TITLE
Firefox Promise implementation seems to be OK already

### ISSUE THREAD

**Issue by erykpiast** [angular/zone.js#169]
In [this line](https://github.com/angular/zone.js/blob/master/lib/microtask.js#L37-L38) you reffer to [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1162013) in native Promise implementation. It's fixed from some time! (v40). So, I guess it's the time to remove this ugly workaround for ugly bug :)

**Comment by vicb** [comment]
From [here](https://www.netmarketshare.com/browser-market-share.aspx?qprid=2&qpcustomd=0)  39 has still a higher market share. I don't think there is a rush to upgrade.

**Comment by erykpiast** [comment]
I just want to remind you :)
