### ISSUE TITLE
JSPM and zone-microtask.js

### ISSUE THREAD

**Issue by cexbrayat** [angular/zone.js#170]
That's more a question than an issue.
I have a bunch of Angular 2 tests, and for one of them I need to use `fakeAsync`. If I understand correctly, I need to include `zone-microtask.js`, right?

First problem: using Karma with JSPM, I can't load `dist/zone-microtask.js` because it then tries to load `core.js` in the `dist` directory...

Second problem: If I use the `lib/microtask.js` file, it then complains about the lack of `global.zone` with:
`Cannot set property 'scheduleMicrotask' of undefined`. So I assume I also need to load `lib/zone.js`?

Final problem: With the following configuration: 

```
module.exports = function(config) {
  config.set({

    frameworks: ['jasmine', 'jspm'],

    browsers: ['Chrome'],

    port: 9876,

    jspm: {
      loadFiles: [
        'jspm_packages/npm/zone.js@0.5.3/lib/zone.js',
        'jspm_packages/npm/zone.js@0.5.3/lib/microtask.js',
        'jspm_packages/npm/zone.js@0.5.3/lib/jasmine/patch.js',
        'jspm_packages/npm/zone.js@0.5.3/lib/zones/long-stack-trace.js',
        'dist/**/*.js'
      ]
    }
  });
};
```
the tests run, but it looks like it never calls `_scheduleMicrotask` in `fakeAsync`, so I guess I'm missing something but I can't see what... Or I misunderstand the whole thing, which is completely possible...

**Comment by cexbrayat** [comment]
If anyone was struggling like me, I made progress by including `lib/browser/zone-microtask.js` : 

```
module.exports = function(config) {
  config.set({

    frameworks: ['jasmine', 'jspm'],

    browsers: ['Chrome'],

    port: 9876,

    jspm: {
      loadFiles: [
        'jspm_packages/npm/zone.js@0.5.3/lib/browser/zone-microtask.js',
        'dist/**/*.js'
      ]
    }
  });
};
```

**Comment by vicb** [comment]
@cexbrayat thanks for reporting your fix
