### ISSUE TITLE
Use symbols if env supports them when attaching properties to foreign objects

### ISSUE THREAD

**Issue by matthewjh** [angular/zone.js#172]
e.g. in https://github.com/angular/zone.js/blob/master/lib/utils.js#L91 properties such as `_fn`, `_addEventListener` are attached to foreign objects which risks interactions with any other libraries that may also be using these properties.

I think we could use `Symbol`s if the environment supports them, with strings as a fallback, to attach/read these properties.

@vicb

**Comment by btford** [comment]
:+1: 

PR welcome
