### ISSUE TITLE
0.5.5 breaks angular tests

### ISSUE THREAD

**Issue by vicb** [angular/zone.js#183]
see https://github.com/angular/angular/pull/4284

Not sure if this is only Travis being flaky or real issues. Needs more investigation - reproducing locally would be a first step.

/cc @matthewjh would be great if you have some time to check this.

**Comment by matthewjh** [comment]
Sure @vicb, I'll take a look.

Don't forget to look at the node patch PR! ;)

**Comment by matthewjh** [comment]
@vicb

So when running angular's whole test suite locally, I found some concrete errors with regards to zone.js in web workers. I can't guarantee that these are what caused the errors in your angular PR (the error messages in the Travis log are pretty unhelpful), but it seems likely.

See fix in #184

**Comment by vicb** [comment]
fixed by #184
