### ISSUE TITLE
requestAnimationFrame callback arguments not passed in

### ISSUE THREAD

**Issue by mhevery** [angular/zone.js#187]
In alpha36, a requestAnimationFrame's callback correctly gets the timestamp argument:
http://plnkr.co/edit/6ZkphwlO7hUKpoLrBDJw?p=preview

In alpha37, the rAF callback does not get the timestamp argument:
http://plnkr.co/edit/H9bYRx7gDivc5qxkdVB1?p=preview

This causes javascript animations to fail.

Also close: https://github.com/angular/angular/issues/4179

**Comment by vicb** [comment]
@justindujardin this is probably caused by https://github.com/angular/zone.js/commit/3d6dc0850b20fd86eef5879f8283de5ee668a668

Do you have time to take a look ?
