### ISSUE TITLE
Function declarations in lib/keys.js broken when Webpack is used

### ISSUE THREAD

**Issue by ivankashtanov** [angular/zone.js#194]
Webpack turns function declarations of `create` in `lib/keys.js` into function expressions. The relevant part looks like this after Webpack processing:
```javascript
if (typeof _Symbol !== 'undefined') {
    var _create = function _create(name) {
        return _Symbol(name);
    };
} else {
    var _create2 = function _create2(name) {
        return '_zone$' + name;
    };
}

var commonKeys = {
    addEventListener: create('addEventListener'),
    removeEventListener: create('removeEventListener')
};
```

As a result, `create` is not defined when used for properties of `commonKeys` and it breaks initialzation as far as I understand.
I'm not sure if it's zone.js bug or Webpack's, but JSHint also gives a warning on these two declarations so I decided to report it here. Here's the warning text:
`Function declarations should not be placed in blocks. Use a function expression or move the statement to the top of the outer function. (W082)`

**Comment by vicb** [comment]
@ivankashtanov thanks for reporting, could you please test with #195 and let us know how this works - I have included the generated js file in the second commit for now if it could help you.

**Comment by ivankashtanov** [comment]
Replaced `keys.js` file with the new one, app is initialzed without errors now.

**Comment by vicb** [comment]
Thanks !
