### ISSUE TITLE
Promise fulfilled after zone cycle (ES5)

### ISSUE THREAD

**Issue by devintyler** [angular/zone.js#196]
Tried using `this.variable.push()` in the way described below, and DOM didn't update in the current cycle
```
function component(){
    var self = this;
    this.thing = [];

    // just an example of a .then statement
    fetch(apiKey.json).then(function(res){
        self.thing.push("anything");
        // do stuff with res, etc.
    }) // finish fetch call (.then().catch())
}
```
_(Didn't finish the code because the rest of it is irrelevant)_

`this.thing` would update, but wouldn't be pushed (also in the annotations changeDetection was set to "ON_PUSH"). The only way it would show up is if I used a work around I figured out which relies on a `document.getElementById('textBoxID').focus();` call follow by this: `(focus)="contentLoaded()"` on the textbox element, which would just call `this.contentLoaded` in my constructor, which then initiates the cycle again, showing my pushed content.

I don't think Zone.js is waiting to update until the `.then` call finishes, it seems as if it finishes its cycle, and doesn't care that something was updated after. If I'm just using something wrong please let me know, this is proving to be a huge issue for my app. Also I'm willing to provide more information to be more specific

**Comment by vicb** [comment]
Hard to say what's going on without a complete example - a Plunker would help here.

**Comment by devintyler** [comment]
Will add momentarily

**Comment by devintyler** [comment]
Here is the plunker:

http://plnkr.co/edit/p3Ipvw4SNut0XLOn76kJ?p=preview

**Comment by vicb** [comment]
There is no issue with zone.js here. The problem is that you use the OnPush strategy, see https://github.com/angular/angular/issues/4746
