### ISSUE TITLE
addEventListener has issues with a null callback

### ISSUE THREAD

**Issue by alxhub** [angular/zone.js#198]
```
Uncaught TypeError: Cannot read property 'toString' of null
obj.addEventListener @ angular2.dev.js:1068
Gestures.add @ polymer.html:752
```

Polymer adds a `null` listener to the 'tap' event on `document` (something about enabling document-wide listeners):

```
// enable document-wide tap recognizer
if (event === 'tap') {
  Polymer.Gestures.add(document, 'tap', null);
}
```

Unfortunately zone.js's addEventListener has issues with a `null` callback, and throws a few exceptions (calling `toString()` on the callback and trying to set properties on it).

**Comment by vicb** [comment]
The last commit in master tries to fix this issue... but in the wrong way as we only do not delegate to the original add/remove function when the handled is null. It should be fixed before next zone release.

@Brooooooklyn any chance you can give this issue a look ?

**Comment by rvraaphorst** [comment]
Running into exact this issue, but can't update as (AFAIK) my jspm only knows v0.5.8. Any idea when the next version is released?
