### ISSUE TITLE
Add Indexed DB browser patch

### ISSUE THREAD

**Issue by gionkunz** [angular/zone.js#202]
Hey there

I'm using Pouch DB within an Angular 2 project, which is using Indexed DB under the hood and I need to do a manual `ChangeDetectorRef.detectChanges()`, because the Indexed DB events are not proxied through the Zone for change detection.

Any change we can add a patch for Indexed DB?

Cheers
Gion

**Comment by gionkunz** [comment]
`IDBDatabase` inherits from `EventTarget`, would it be that simple to add `IDBDatabase` to https://github.com/angular/zone.js/blob/master/lib/patch/event-target.js#L13-L32 ?

**Comment by cherrydev** [comment]
Apparently this was fixed back in 84a251faabb422a86d91bafc58b1a461cfff6664
