### ISSUE TITLE
Public API for custom zone patches

### ISSUE THREAD

**Issue by mlynch** [angular/zone.js#205]
During our Ionic+Angular chat today we talked about needing to add specific Zone patches to make sure Cordova `exec` calls trigger zone. However, seeing that Cordova is a 3rd party library focused on a niche, it doesn't make sense to add this to zone proper.

In that light, Zone.js could use a public API for custom patches for libraries like Cordova. cc @IgorMinar @btford

**Comment by cherrydev** [comment]
Yes please!  There's definitely interest in this.

**Comment by jahtalab** [comment]
+1, willing to contribute.

**Comment by JiaLiPassion** [comment]
we have some basic support, will dig into cordova.exec later, and duplicate issue already in angular repo, will close this for now.
