### ISSUE TITLE
Is there a way to terminate/cancel all pending tasks in a zone?

### ISSUE THREAD

**Issue by yvoronen** [angular/zone.js#211]
Folks,
is there a way to terminate a zone? I don't see it in the API, but perhaps the question should be, whether it is feasible to implement such functionality. Example of what I mean below:
```
function hello() { console.log("Hello world"); }
zone.run( () => setTimeout(hello, 1000));
zone.terminate();
// nothing should be printed
```

**Comment by vicb** [comment]
There is no built-in way to do this.

However you can use the `setTimeout`, `setInterval`, ... hooks to accumulate the timer ids and cancel them.

**Comment by yvoronen** [comment]
thanks, I'm going to try that.
