### ISSUE TITLE
Zone.js is incompatible with FirefoxDriver

### ISSUE THREAD

**Issue by juliemr** [angular/zone.js#234]
FireFox's webdriver implementation uses a firefox add-on which [adds event listeners](https://github.com/SeleniumHQ/selenium/blob/ab1e647d0fc8fc39e6b00ae94321ab228b6728f2/javascript/firefox-driver/extension/content/server.js#L36) to the page. Because the functions in these event listeners come from the add-on content script, they are not accessible by scripts from the webpage (see https://developer.mozilla.org/en-US/Add-ons/SDK/Guides/Content_Scripts/Interacting_with_page_scripts). 

Since zone patches `window.addEventListener` and tries to process the handler, this causes any test to fail with "Permission denied to access property toString".

I have a repo which shows this error at https://github.com/juliemr/zone-firefox-driver

A potential fix would be something like [this](https://github.com/juliemr/zone-firefox-driver/commit/c6563e95a1bddb1399f75572a70396aa200b8682). I could prepare a PR if that looks reasonable.

**Comment by valorkin** [comment]
+1 this is blocking feature for e2e angular2 tests

**Comment by spinfooser** [comment]
I can verify that this is an issue as well. I've been trying to use FluentLenium (which uses the WebDriver Selenium framework) to automate testing of Angular2 websites. This seems to be a Firefox-specific because of the browser design itself like juliemr has said.

Switching to chrome or another browser web driver is the current work-around for the issue. I made a quick pull request to formalize the changes that I would personally make, but I'm not particularly attached to them.

https://github.com/angular/zone.js/pull/264

**Comment by uglow** [comment]
Switching to Chrome is not an option for those projects running Protractor on TravisCI. We really need a fix for Firefox.

**Comment by spinfooser** [comment]
Yes, it needs to be fixed. That's really unfortunate that switching to something else isn't an option. Lets hope these pull requests are investigated soon! (It seems like there is a log jam)

**Comment by uglow** [comment]
@spinfooser - and you can believe me when I tell you I've tried my utmost to get Chrome to work on TravisCI. Something to do with their version of Linux means that the latest version of Chromium that they can install (or is installed) is 2(?) years old. Firefox was the recommended approach, or using SauceLabs for Protractor testing.

**Comment by rinokadijk** [comment]
+1

**Comment by spinfooser** [comment]
Currently I have in a passing pull request after the big 0.6 Zone.js update. I think this will fix the issue and have tested it locally.

https://github.com/angular/zone.js/pull/309

**Comment by pattishin** [comment]
Just bumping this bug ticket up, since my team is encountering this bug as well running our selenium tests. My teammate was able to switch to using a chrome driver, but would definitely appreciate a fix/patch for this!

**Comment by slavasitnikov** [comment]
+1

**Comment by max-polyakov** [comment]
Hi guys,

Any updates for this issue? Its really annoying indeed :-(

**Comment by JiaLiPassion** [comment]
This should be fixed now.

**Comment by uglow** [comment]
Better late than never, I guess. 😅
