### ISSUE TITLE
[pkg]: "postinstall": "tsd install"

### ISSUE THREAD

**Issue by calebboyd** [angular/zone.js#240]
@mhevery, this statement breaks `npm install` for those who do not have `tsd` installed globally.

I'm not too sure how you'd like to alter that installation

**Comment by mastertinner** [comment]
I agree. As a person using the newer [Typings](https://www.npmjs.com/package/typings) instead of TSD, this breaks my installation.

**Comment by cebor** [comment]
same here

**Comment by psi-4ward** [comment]
+1

**Comment by cebor** [comment]
strange thing is, that `tsd` is already added to devDeps

**Comment by calebboyd** [comment]
@cebor, the problem is that dev dependencies are not installed for consumers

**Comment by cebor** [comment]
yes you are right, so i think its better to remove the `postinstall` and document the typings insall as a manual step for developers

**Comment by TheTedAdams** [comment]
+1 that this just broke our build.

`postinstall` tries to run `tsd install` on anyone installing this package from npm, which I don't think is what you were trying to do.

With tsd in devDependencies there is no guarantee tsd has been installed on the consumer. As a consumer I would also much rather postinstall was just removed, rather than adding a dependency on a successful `tsd install`. We have had tsd fail with API rate limiting so much that we have removed it from our build process and just added our typings folders to git...

**Comment by gdi2290** [comment]
+1 `postinstall` breaks angular2 beta.3 unless `tsd` is installed as a dependency

**Comment by Kikketer** [comment]
+1  Beta.3 fixes issues I have with multiple of the same components, but the dependency of installing tsd breaks my build on a build server.  Moving back to beta.2 until this can be fixed.

**Comment by jrisk** [comment]
`npm install tsd -g` fixed the ERR messages for me on the angular2 npm install

**Comment by laco0416** [comment]
in 0.5.13, `tsd install` is still remains.

**Comment by boneskull** [comment]
@mhevery I think you want `prepublish` here.

- `prepublish`: runs when `npm install` is *explicitly executed* in the `zone.js` dir (and before publication, of course)
- `postinstall`: runs whenever `zone.js` is installed in the `zone.js` dir *or* via `npm install zone.js`

**Comment by boneskull** [comment]
(point being: it doesn't need to be an "extra step" developers of this project need to take)

**Comment by armorik83** [comment]
+1

**Comment by laco0416** [comment]
@mhevery Has there been any progress?  Thanks.

**Comment by nwhite89** [comment]
:+1: As a fix in my own project I have had to do 
```
"preinstall": "npm i tsd"
```
This fixes issues I am having on Circle for example just incase that helps anyone else having this issue rather than having to have `tsd` globally until this is fixed.

**Comment by dpsthree** [comment]
TSD is deprecated in favor of Typings (https://github.com/typings/typings) - see https://github.com/DefinitelyTyped/tsd/issues/269 for more information

**Comment by mikekidder** [comment]
Version 5.14 has moved tsd to prepublish.  I put in a PR #253 for the deprecation, if accepted

**Comment by alexeagle** [comment]
Thanks for the PR, @mikekidder .
I'll close this issue since users should be able to `npm install` 0.5.14

**Comment by boneskull** [comment]
okay, sorry for the PR then!
