### ISSUE TITLE
matchMedia events?

### ISSUE THREAD

**Issue by justindujardin** [angular/zone.js#243]
I'm building an angular2 app and I'm trying to do dynamic things when `window.matchMedia` tells me that a media breakpoint has been hit.  

It seems like this is bypassing change detection, and I suspect it might be because zone.js doesn't wrap the matchMedia API.

Does this sound plausible? Would you be open to a PR to work through and resolve the issue?  Right now I have to manually tick the ng2 app when things change, and it feels pretty dirty.

**Comment by JiaLiPassion** [comment]
supported now.
