### ISSUE TITLE
>npm start does not work after errors in npm install

### ISSUE THREAD

**Issue by MalcolmGC** [angular/zone.js#255]
>npm start does not work after errors in npm install on Window 8.1
Browser only shows "Loading ... "
============================================================
c:\1hello>npm start
> angular2-quickstart@1.0.0 start c:\1hello
> npm run lite
> angular2-quickstart@1.0.0 lite c:\1hello
> lite-server
Did not detect a `bs-config.json` or `bs-config.js` override file. Using lite-server defau
lts...
** browser-sync options **
{ injectChanges: false,
  files: [ './**/*.{html,htm,css,js}' ],
  server: { baseDir: './', middleware: [ [Function], [Function] ] } }
[BS] Access URLs:
 -------------------------------------
       Local: http://localhost:3000
    External: http://10.80.44.175:3000
 -------------------------------------
          UI: http://localhost:3001
 UI External: http://10.80.44.175:3001
 -------------------------------------
[BS] Serving files from: ./
[BS] Watching files...
16.02.11 20:47:52 200 GET /index.html
16.02.11 20:47:53 200 GET /app/app.component.js
16.02.11 20:47:53 200 GET /app/main.js
16.02.11 20:47:54 404 GET /favicon.ico
16.02.11 20:49:27 304 GET /index.html
16.02.11 20:49:28 304 GET /app/app.component.js
16.02.11 20:49:28 304 GET /app/main.js
16.02.11 20:49:31 304 GET /index.html
....

=================================================================
c:\1hello>npm install
> zone.js@0.5.11 postinstall c:\1hello\node_modules\zone.js
> tsd install

'tsd' is not recognized as an internal or external command,
operable program or batch file.
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.7
npm WARN angular2-quickstart@1.0.0 No description
npm WARN angular2-quickstart@1.0.0 No repository field.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "node" "C:\\Users\\ ... [removed some] npm\\node_modules\\npm\\bin\
\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v3.7.2
npm ERR! code ELIFECYCLE

npm ERR! zone.js@0.5.11 postinstall: `tsd install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zone.js@0.5.11 postinstall script 'tsd install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zone.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsd install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zone.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zone.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\1hello\npm-debug.log

c:\1hello>npm bugs zone.js

c:\1hello>

**Comment by alexeagle** [comment]
Fixed in 0.5.14
