### ISSUE TITLE
0.5.15 crashing in a non browser DOM environment

### ISSUE THREAD

**Issue by hdeshev** [angular/zone.js#263]
Patchers in 0.5.15 seem to assume `HTMLElement` and `global.document` are always present and crash if that isn't the case. I'm running in a NativeScript mobile app, and I have to use these hacks to make my Angular app work:

```
//prevent a crash in zone patches
global.HTMLElement = function() {}
global.document = {};
```

Version 0.5.14 did not have that problem.

**Comment by mhevery** [comment]
Should be fixed in v0.6.0
