### ISSUE TITLE
setTimeout ignores additional arguments when run inside Angular class constructor

### ISSUE THREAD

**Issue by lppl** [angular/zone.js#265]
Hi,

Short version: setTimeout fails inside angular2 class cosntructor, but works fine outside of its context.

Plunker example: https://plnkr.co/gaBThueKGEfYXsG3g4yp?p=preview It contains function "run" which starts coutdown. Once inside angular2 code, once outside. The expected behavior is for countdown to hit zero both times.

ps. Tested at newest chrome/firefox on ubuntu and windows system.
ps. I've found two issues about setTimeout arguments: https://github.com/angular/angular/pull/344 and https://github.com/angular/angular/issues/6088. But I'm not sure if they are related.
ps. I've been redirected here from: https://github.com/angular/angular/issues/7165

**Comment by mhevery** [comment]
Fixed in v0.6.0
