### ISSUE TITLE
Unnecessary forking!?

### ISSUE THREAD

**Issue by jahtalab** [angular/zone.js#266]
In my application I need to check if a property is on the current zone or it is inherited.
I can achieve this by checking `zone.hasOwnProperty('property')` but this doesn't work in case of setTimeout since zonejs internally forks my zone so the statement is not true anymore:
https://github.com/angular/zone.js/blob/master/lib/patch/functions.ts#L38

btw, this doesn't work if I bind a function as well:
https://github.com/angular/zone.js/blob/master/lib/core.ts#L81

Is there a way to avoid forking zones, since it creates unexpected behaviour?

**Comment by mhevery** [comment]
Fixed in v0.6.0
