### ISSUE TITLE
zone.js 0.6.x changelog

### ISSUE THREAD

**Issue by sod** [angular/zone.js#271]
@mhevery

I like how angular2 documents breaking changes in the changelog.md

Do you plan to commit a changelog.md or does angular2 communicate the changes when they switch to 0.6? It's impossible the extract any changes from https://github.com/angular/zone.js/commit/63d4552bed2850d5610e1a13dfb728c14651184f 

I guess almost all issues and pull request might be out of date because of this?

Did you publish a blogpost/podcast/talk on why you rewrote everything for 0.6? Just curious :)

**Comment by mhevery** [comment]
Yes, we should set up the change log. Yes, I will have to deal with the PRs separately, or ask people to rebase.
