### ISSUE TITLE
zone.js + select2: onchange not called

### ISSUE THREAD

**Issue by gergaczd** [angular/zone.js#273]
I am creating an angular2 app (so I am using zone.js), but outside of the app, there is a bunch of select2, with an onchange attribute event handler.
The problem is, that zone.js somehow mixed up the event handling, so in this case the onchange attribute event is not called.
You can read the full observation in the select2 issue: https://github.com/select2/select2/issues/4231

I created an example for this: https://jsbin.com/quletutemo
I am not sure which party is responsible for this, so I created an issue for select2 too.

Is there any workaround for wire up the onchange event, without modify the html elements?

**Comment by david10sing** [comment]
I think your issue might be similar to mine. I had this issue a long time ago and posted it on here but no one cared about it. I tried to include a third-party text editor, Froala and zone.js would intercept all events such that jQuery events are no longer available. So my solution to get the editor to run was to run the editor outside of Angular as follows:

`	elemRef: ElementRef;
	zone: NgZone;


	constructor(elemRef: ElementRef, zone: NgZone) {
		this.elemRef = elemRef;
		this.zone = zone;
	}

	ngAfterContentInit() {

		this.zone.runOutsideAngular(function() {
			var editor = jQuery('div.article-text-content');
			editor.froalaEditor({
				// toolbarInline: true,
				toolbarSticky: true,
				pastePlain: true
			});
		});
	
	}`

Hope that helps you too. But I don't get why zone.js is intercepting the events and not allowing jQuery events to fire

**Comment by JiaLiPassion** [comment]
Those event handler need to be inside ngZone.
