### ISSUE TITLE
Calling `EventTarget.removeEventListener` twice causes errors

### ISSUE THREAD

**Issue by sjelin** [angular/zone.js#283]
Consider the following code snippet:

```js
var elem = document.body;
var listener = function (event) {};
elem.addEventListener('click', listener, false);
elem.removeEventListener('click', listener, false);
elem.removeEventListener('click', listener, false);
```

According to the [DOM spec](https://dom.spec.whatwg.org/#dom-eventtarget-removeeventlistener), the second `removeEventListener` should do nothing.  However, with `zone.js` loaded it produces the following error message:

```
	Error: Task does not support cancellation, or is already canceled.
	    at ZoneDelegate.cancelTask (/usr/local/google/home/sjelin/zone.js/test/browser_entry_point.ts:382:24)
	    at Zone.cancelTask (/usr/local/google/home/sjelin/zone.js/test/browser_entry_point.ts:292:45)
	    at zoneAwareRemoveEventListener (/usr/local/google/home/sjelin/zone.js/test/browser_entry_point.ts:970:25)
	    at HTMLBodyElement.removeEventListener (eval at createNamedFn (/usr/local/google/home/sjelin/zone.js/test/browser_entry_point.ts:1051:18), <anonymous>:3:46)
	    at Object.<anonymous> (/usr/local/google/home/sjelin/zone.js/test/browser_entry_point.ts:2354:19)
```

Basically, the problem is that [the patched `removeEventListener`](https://github.com/angular/zone.js/blob/74b4b97c1449819d7a96ce6b60ab860c20e7867f/lib/browser/utils.ts#L190) will [cancel the task](https://github.com/angular/zone.js/blob/74b4b97c1449819d7a96ce6b60ab860c20e7867f/lib/browser/utils.ts#L200), but never removes it from the list of registered tasks.  So when the second `removeEventListener` happens it tries to cancel the task again, leading to the problem.  I suggest we start removing it from the list of registered tasks, unless there is a reason it has to stay there.

**Comment by mhevery** [comment]
Sounds good to me.

**Comment by arsenys** [comment]
I have the exactly the same problem. I have an `Angular2` app with [Semantic-UI](http://semantic-ui.com). After upgrading `zone.js` from 0.5.x to 0.6.x almost every Semantic-UI component, such as modal window or dropdown throws the `SafeSubscriber` errors, whether its  `Task does not support cancellation, or is already canceled.` or `undefined is not an object (evaluating 'task.zone')` errors from `SafeSubscriber`.
