### ISSUE TITLE
Exported typings are not a module

### ISSUE THREAD

**Issue by park9140** [angular/zone.js#297]
Exported external package typings file '**/node_modules/zone.js/dist/zone.js.d.ts' is not a module. Please contact the package author to update the package definition.

It appears that the typescript build is not outputting a module in it's definitions output.

**Comment by park9140** [comment]
This appears to be because the core file being built is not built as an external module.  You need to have at least one import or export to create the external module.

**Comment by Nek-** [comment]
I'm having same issue @park9140 did you fixed it ?

If I don't import 'zone.js' my code does not work but if I do I get this error...

**Comment by park9140** [comment]
@Nek- This works for now.
```
declare module 'zone.js/dist/zone' {
    export var Zone; // this doesn't actually do anything just makes the compiler not complain about the empty module
}
declare module 'zone.js/dist/long-stack-trace-zone' {
    export var Zone; // this doesn't actually do anything just makes the compiler not complain about the empty module
}
import 'zone.js/dist/zone';
import 'zone.js/dist/long-stack-trace-zone';
```

**Comment by Nek-** [comment]
@park9140 using your code generate a different error:

```
src-js/app/main.ts(4,16): error TS2664: Invalid module name in augmentation, module 'zone.js/dist/zone' cannot be found.
src-js/app/main.ts(7,16): error TS2664: Invalid module name in augmentation, module 'zone.js/dist/long-stack-trace-zone' cannot be found.
```

But still an error.

**Comment by park9140** [comment]
@Nek- One thing I forgot to mention that may cause a problem.

The first part 
```typescript
declare module 'zone.js/dist/zone' {
    export var Zone; // this doesn't actually do anything just makes the compiler not complain about the empty module
}
declare module 'zone.js/dist/long-stack-trace-zone' {
    export var Zone; // this doesn't actually do anything just makes the compiler not complain about the empty module
}
```
I have a in a separate `.d.ts` ambient definition.  I'm not sure if those declares have to be in a `.d.ts` file.  Also I'm using typescript 1.8.9.

In addition I don't every import 'zone.js' directly anymore.

**Comment by Nek-** [comment]
My bad ! I added a `main.d.ts`. It works like a charm. Thank you so much.

**Comment by Nek-** [comment]
@park9140 well, I still get an error related to `zone.js`. I don't know why. But this is not critical (the app works)

Anyway here is the message:

```
Uncaught TypeError: Cannot read property 'cancelTask' of undefined
```

**Comment by sebilasse** [comment]
@Nek- Getting exactly the same error, also for other modules! 
Is main.ts the file where you import the zone.js stuff? Why do we need a d.ts now if it is already TS ?

**Comment by Nek-** [comment]
@sebilasse idk why TS is asking for a d.ts when it's already in TS :/. But yes I put the fix in my main.ts file.

**Comment by alexeagle** [comment]
@robwormald discussed this with @mhevery this week, the reasoning for this is that zones are considered a polyfill, so you're expected to treat zone.js as an ambient dependency. Include `zone.js.d.ts` as an input to the typescript compilation, or use a `///<reference path=""/>` to bring it into the compiler.

Importing from it is not the suggested pattern, as that produces a value-side expression in the JS emit asking the module loader to load zone, and instead it should be included as a browser polyfill before the module loader starts.

It's also tricky to get the right order - if you load zone.js after the module loader has started up, then the module loader or any previously loaded modules may hold a reference to un-patched async primitives, which will not be zone-aware.

Closing as WAI, but please let me know if there's something we could do better here. Maybe `import * as zone from 'zone.js';` should bring some symbols into scope?

**Comment by sap9433** [comment]
```declare module 'zone.js/dist/zone' {
    export var Zone; // this doesn't actually do anything just makes the compiler not complain about the empty module
}```
doesn't work , getting . `Invalid module name in augmentation, module 'zone.js/dist/zone' cannot be found`, though i vave `zone.js` module inside `node_modeles`

**Comment by rahmanusta** [comment]
Hello, which version fixes this issue ? I removed the typings file in zone.js and installed typings with `typings install dt~zone.js --save --global` and it solves the issue, but there should be a way without workaround.
