### ISSUE TITLE
"More tasks executed then were scheduled" error when using zone.js and jquery.layout

### ISSUE THREAD

**Issue by NikGovorov** [angular/zone.js#302]
As per @mhevery's request(https://github.com/angular/zone.js/issues/290):
http://plnkr.co/edit/XLXdc1EoEzOE7O4VoPQO?p=preview
To reproduce the issue: resize a window or hover on any resize pane.

**Comment by mhevery** [comment]
This is resolved in the latest Zone.js

**Comment by NikGovorov** [comment]
Thanks @mhevery, https://github.com/angular/zone.js/commit/a8ea55dd977898a9cba4d695beb93bf23e0cbc50 fixes the issue.

Just in case, updated http://plnkr.co/edit/WMKGav4T8DDUAbjnUHIP?p=preview

**Comment by NikGovorov** [comment]
@mhevery, when you are going to push it to npmjs.org?

**Comment by mhevery** [comment]
published

**Comment by NikGovorov** [comment]
Thanks @mhevery!
