### ISSUE TITLE
Uncaught UnsubscriptionError thrown after first subscribe call on angular beta 13

### ISSUE THREAD

**Issue by tiagoroldao** [angular/zone.js#310]
This seems to be a zone.js problem, as rolling back to 0.6.6 solves the issue - angular's dependency on `^0.6.6` resolves to the latest. Also, seems to happen in angular beta 13, and also beta 12 and beta 8, after rolling back.

**Comment by justyns** [comment]
Can confirm I get the same error with angular2 beta 13 and zone.js 0.6.9.   I was able to get it working by rolling back to zone.js 0.6.8.

**Comment by user414** [comment]
I was driving myself crazy debugging this after upgrading to beta 13 and zonejs 0.6.9 reverting to 0.6.8 also fixed the problem. Here what I had found when I was debugging. The error UnsubscriptionError is not the real error, the real error comes from

```
 ZoneDelegate.prototype.cancelTask = function (targetZone, task) {
	            var value;
	            if (this._cancelTaskZS) {
	                value = this._cancelTaskZS.onCancelTask(this._cancelTaskDlgt, this.zone, targetZone, task);
	            }
	            else if (!task.cancelFn) {
	                throw new Error('Task does not support cancellation, or is already canceled.');
	            }
	            else {
	                value = task.cancelFn(task);
	            }
	            if (targetZone == this.zone) {
	                // this should not be in the finally block, because exceptions assume not canceled.
	                this._updateTaskCount(task.type, -1);
	            }
	            return value;
	        };
```
Error: Task does not support cancellation, or is already canceled.(…)

when the cancelFn is null for a source: "XMLHttpRequest.send" and type "macroTask". Hopefully that helps someone else debugging for my part will be content to revert to 0.6.8. Not sure why I don't start with reverting first:) Thanks @tiagoroldao @justyns for solution.

**Comment by Megalepozy** [comment]
Reverting to zone.js 0.6.8 fixed the issue for me as well! thx @user414

**Comment by MarkPieszak** [comment]
Nice catch again @Megalepozy !

**Comment by Megalepozy** [comment]
heheheh thx but I just reconfirmed what @user414 said... :)
