### ISSUE TITLE
Cannot use zone.js with SemanticUI Search

### ISSUE THREAD

**Issue by gaiottino** [angular/zone.js#319]
Hi,

I initially posed this bug in here https://github.com/angular/angular/issues/7750 since I'd only narrowed it down to `angular2-polyfills.js` before I left for holiday. Now that I'm back I dug deeper and found that `zone.js` is the culprit and I can see there are others having similar issues with 3rd party libs. More specifically, in my case, it's because `zone.js` is patching the `onkeydown` event which is used by SemanticUIs Search https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/components/search.js#L100

Here's an updated plunker with only `zone.js` included http://plnkr.co/edit/SQBxicLoQ5LiFXJgT4qm?p=preview. Commenting out `utils_1.patchOnProperties(HTMLElement.prototype, eventNames);` the search tool works as intended again or even just removing `onkeydown` from the patched events "solves" the issue.

This is causing headaches for many people trying to use 3rd party libs with Angular2. Is there a fix coming or a workaround available? Any insight in why this is happening?

Regards,
Daniel

**Comment by gaiottino** [comment]
Looking for a response or thoughts to this issue. I'm not the only one having issues with how `zone.js` patches the events and this preventing 3rd party libs to work properly.

**Comment by mattdemps** [comment]
I second this.  I am using Angular in SharePoint and it is hijacking the onsubmit event for the form.  Content editors cannot save edits when zone.js is included.

Is there a way to possibly scope zone.js so, for example, only elements that are wrapped in a parent element that has a specific attribute or class are affected by it?

I noticed in the property-descriptor.ts file (line: 15)  it is modifying the HTMLElement interface's prototypes, but it might be possible to do some checking on the getters and setters to conditionally hijack events.

**Comment by uNki23** [comment]
same problem here with the Semantic UI search component.. 

are there any known side-effects when commenting out `utils_1.patchOnProperties(HTMLElement.prototype, eventNames);` ?

thanks!

**Comment by gaiottino** [comment]
Still looking for a response to this.

**Comment by uNki23** [comment]
Yes. Me, too.

**Comment by lpotapczuk** [comment]
I am also interested in more actions on this.

**Comment by jlukic** [comment]
I just saw this in one of my own projects using Semantic UI.

**Comment by veered** [comment]
I was able to fix the problem by changing this line: 

https://github.com/angular/zone.js/blob/ed697569119c8d535ac8c640e23d1c21b49cde7d/lib/common/utils.ts#L86

to `return this[_prop] || null;`

**Comment by jlukic** [comment]
I've loosened the typechecks to use `==` instead of `===` which should preserve meaning even if props are returning `null`. This should be a simpler solve then waiting for zones to be patched.

**Comment by gaiottino** [comment]
@jlukic, @veered I tried both your methods but can't see that they fix the problem? This http://plnkr.co/edit/OOA6TWvvk58q2TRqSkz8?p=preview should have both of your tweaks but the problem persists. Mind creating a plunkr showing it's working? Thanks for your participation with this issue.

**Comment by veered** [comment]
If you try it with just my change it works for me http://plnkr.co/edit/O475D4x9SXqDu9naIjpk?p=preview

**Comment by gaiottino** [comment]
@veered you are correct. It does feel like this is a change that should be made in SemanticUI though if it's indeed an issue with `undefined` and `null`. How did you find the issue?

**Comment by veered** [comment]
I think this is genuinely a bug in zone.js. On a normal webpage `document.createElement('input').oninput === undefined` but on a webpage with zone.js `document.createElement('input').oninput === null`. 

I found it by noticing that keyups were triggering search and breakpointing in different places until I notice the difference I described above.
