### ISSUE TITLE
Unable to see long stack trace in Chrome on basic.html example.

### ISSUE THREAD

**Issue by sjogren** [angular/zone.js#324]
Hey!

I cloned the angular/zone.js repo and ran npm install. Everything went fine. Opened up basic.html in Chrome (49) and expected to see the same nice long stack trace as in the YouTube video from Brian Ford (https://www.youtube.com/watch?v=3IqtmUscE_U&t=7m40s).

I just see the following:

```
zone.js:260 Uncaught Error: aw shucks
   throwError @ basic.html:42
   ZoneDelegate.invokeTask @ zone.js:356
   Zone.runTask @ zone.js:256
   ZoneTask.invoke @ zone.js:423
```

Is there something wrong with the example or have I missed something?

**Comment by sjogren** [comment]
I looked at the [long-stack-trace-zone.spec.ts](https://github.com/angular/zone.js/blob/master/test/zone-spec/long-stack-trace-zone.spec.ts#L4) and changed [line 49 in basic.html](https://github.com/angular/zone.js/blob/master/example/basic.html#L49) to the following to see the long stack trace:

```javascript
Zone.current.fork(Zone.longStackTraceZoneSpec).fork({
   name: 'long-stack-trace-zone-test',
   onHandleError: function(parentZoneDelegate, currentZone, targetZone, error) {
      parentZoneDelegate.handleError(targetZone, error);
      console.log(error.stack);
      return false;
}}).run(main);

**Comment by danilosterrapid7** [comment]
@sjogren, I tried it in my version, but it is not working. It seems that I do not have it any sort of output (console.log) working under Zone's domain.
