### ISSUE TITLE
polyfill for cancelAnimationFrame is broken

### ISSUE THREAD

**Issue by manolo** [angular/zone.js#326]
The pachTimer for AnimationFrame prevents animation requests to be cancelled.

This code does not write anything in console normally, but when angular2-polyfills.js is loaded, the callback is executed:

      var callback = function() {
        console.log("Done")
      }
      var i = window.requestAnimationFrame(callback);
      window.cancelAnimationFrame(i);

**Comment by jwoyame** [comment]
Looking at this code in `browser.ts`:

```typescript
patchTimer(_global, 'request', 'cancelMacroTask', 'AnimationFrame');
patchTimer(_global, 'mozRequest', 'mozCancel', 'AnimationFrame');
patchTimer(_global, 'webkitRequest', 'webkitCancel', 'AnimationFrame');
```

Shouldn't it be 'cancel' on the first line, instead of 'cancelMacroTask'? That 'MacroTask' string seems out of place.
