### ISSUE TITLE
Accessing XMLHttpRequest#responseBlob breaks older browsers

### ISSUE THREAD

**Issue by tkazec** [angular/zone.js#328]
`patchClass()` is causing Zone.js to break in older browsers like Android 4.1 – see angular/angular#8000.

Hacky fix: https://github.com/Buzzvil/zone.js/commit/1c3f040cba8a1745829c0f8143620564c250b895

**Comment by Brooooooklyn** [comment]
same issue with you

It's a very old webkit bug https://bugs.webkit.org/show_bug.cgi?id=44721

**Comment by tkazec** [comment]
As far as I know, this was part of a spec, then removed. Some older browsers have a buggy implementation that causes DOM Exception 11 to be thrown when touched.

Since Zone.js is used in Angular 2, and Angular 2 advertises Android 4.1 support, this needs a fix ASAP.

**Comment by tkazec** [comment]
All good now, thanks.
