### ISSUE TITLE
Zone.js Memory Leak LongStackTrace

### ISSUE THREAD

**Issue by Guardiannw** [angular/zone.js#332]
I have been having a memory leak with Angular2 and Rxjs when I try to perform many repetitive http requests to the backend.  I believe I have narrowed it down to Angular2's implementation of Zone.js.  I am using Angular2 version 2.0.0-beta.15 and zone.js 0.6.10, and rxjs v5.0.0-beta.6.  

When I look at the memory leak in the chrome profiler, I find that there are many LongStackTrace objects lying around and not getting cleaned up.  This is a big problem for me in a low memory situation like I am currently in.

I have looked through the zone.js code and am not able to find out exactly why this is happening, but it all seems to be revolving around the LongStackTrace objects hanging around.

See this plnkr for an example, 
[http://embed.plnkr.co/e88fKBwXuLUt1G7qcywt/](http://embed.plnkr.co/e88fKBwXuLUt1G7qcywt/)

I would appreciate any help or fix on this.

Thanks,

**Comment by Guardiannw** [comment]
Fixed I guess ?

**Comment by iBasit** [comment]
No, there is still big memory leak :/ on angular2 application, which hardly have any component. Our complete application is not working properly on mobile or on some computers

**Comment by redcameron** [comment]
Any progress on this issue? Does it still exist in the latest stable release?

**Comment by mhevery** [comment]
The issue has been closed. Please create a new issue with a repro.
