### ISSUE TITLE
zone.afterTask and zone.beforeTask hook methods not working

### ISSUE THREAD

**Issue by sap9433** [angular/zone.js#334]
I'm trying to implement simple `zone.afterTask` and `beforeTask` hooks but though *code ain't throwing any error* , those methods are never getting called.

I searched Zone repo in github , and couldn't find any reference to these methods in the source code apart from the ones that's used in the example. `counting example` does use afterTask and beforeTask but I've set a debugger and saw those methods are never getting called in their example as well .

*It looks like these methods have been deprecated* , If not kindly let me know what I'm doing wrong.

Here's my code -

```
import { Component } from 'angular2/core';

@Component({
  template: `
      <div>
        <p>Basic use of Zone</p>
        <button (click)="startTask()">Start Task</button>
        <p> Time taken {{timeTaken}}</p>
      </div>
    `
})
export class HelloZone {
  timeTaken: any;

  task1(){
    for (let i = 0; i < 1e5; i++);
  }

  startTask() {
    let startTime;

    let myZone = Zone.parent.fork({
      beforeTask: function() {
        startTime = new Date();
      },
      afterTask: function() {
        this.timeTaken = new Date() - startTime;
      }
    });
    myZone.run(function(){
      this.task1();
      setTimeout(this.task1, 2000);
      this.task1();
    }.bind(this));
  }
}
```

**Comment by jahtalab** [comment]
Those methods are deprecated after v0.6.0, 
But they should work for v0.5.x
[here](https://github.com/angular/zone.js/blob/master/dist/zone.js.d.ts) is the new api

**Comment by sap9433** [comment]
Shouldn't we remove them from Readme.md . Too confusing for a developer , as they are present in examples as well .
