### ISSUE TITLE
symbol-observable not found when trying to run the server

### ISSUE THREAD

**Issue by aashirwadgupta** [angular/zone.js#346]
Hi Team, 
I am using angular2. 
When I run the server I am getting 404 error for symbol-observable which comes with zone.js

Below is the snapshot of it
![image](https://cloud.githubusercontent.com/assets/12935036/15267505/d2baa4fe-19e1-11e6-97ff-e2e14e678c03.png)

Below is the index.html file

![image](https://cloud.githubusercontent.com/assets/12935036/15267513/2f66cd22-19e2-11e6-8bb9-68ca6d5d72c4.png)

Below is the systemjs.config.js 

(function (global) {
    var map = {
        'rxjs': 'https://npmcdn.com/rxjs',
        '@angular': 'https://npmcdn.com/@angular',
    };
    
    var packages = {
        'app': {main: 'main.js', defaultExtension:'js'},
        'rxjs': {defaultExtension:'js'}
    };
    
    var packageNames = [
        '@angular/common',
        '@angular/compiler',
        '@angular/core',
        '@angular/http',
        '@angular/platform-browser',
        '@angular/platform-browser-dynamic',
        '@angular/router',
        '@angular/router-deprecated',
        '@angular/testing',
        '@angular/upgrade'
    ];
    
    packageNames.forEach(function (pkgName) {
        packages[pkgName] = {main:'index.js', defaultExtension:'js'};
    });
    
    var config = {
        map: map,
        packages: packages
    }
     if (global.filterSystemConfig) { global.filterSystemConfig(config); }

    System.config(config);
}) (this);

**Comment by bokc** [comment]
Same issue with same systemjs.config.js file. But I don't see the rx.js loaded on the chrome debug windows.

**Comment by BuddyWork** [comment]
i have the issue has anyone got a solution to this problem?

**Comment by robwormald** [comment]
this is unrelated to zoneJS. you're using a later version of RxJS (probably 5.0.0-beta.8), which requires the symbol-observable dependency, and that would need to be configured in your system loader. You should use the same version as Angular2 depends on (beta.6 at this time)

**Comment by byliuyang** [comment]
http://stackoverflow.com/questions/37086070/updating-to-angular2-0-0-rc-1-cant-get-past-this-error
