### ISSUE TITLE
async-test and fake-async-test uses Zone without requiring it - Karma load error

### ISSUE THREAD

**Issue by diestrin** [angular/zone.js#347]
I'm trying to include in my karma.conf the files as described in [here](https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes-1)

```
files: [
  'jspm_packages/npm/zone.js@0.6.12/dist/zone.js',
  'jspm_packages/npm/zone.js@0.6.12/dist/fake-async-test.js',
  'jspm_packages/npm/zone.js@0.6.12/dist/async-test.js',
  'src/**/*.spec.js'
],
```

The problem is they load all at the same time, and async-test and fake-async-test uses Zone without requiring it, so there are some times where Zone isn't loaded yet and it crashes.

Is this the right way to load those libs? Any missing conf?
Thanks.

**Comment by JanRudert** [comment]
Hi @diestrin have you found a solution for this problem in the meanwhile?

**Comment by JiaLiPassion** [comment]
@JanRudert , from `zone.js` 0.8.19, you can load 

```javascript
'zone.js@0.8.19/dist/zone-testing-bundle.js'
```

**Comment by JanRudert** [comment]
Ah, I'm using webjars and it looks like v0.8.19 version is not yet in any public repo.

**Comment by JiaLiPassion** [comment]
@JanRudert , I just tried to update `zone.js` in webjars repository, you can wait for a few hours to see it is updated or not.

**Comment by JanRudert** [comment]
@JiaLiPassion Thanks a lot! It's there. So what do you mean by "you can load"? I have a typescript/angular app backed by Play/sbt-web and webjars. (It's my first angular project thatAND I did not build it myself but have to fix/enhance now.)

**Comment by JiaLiPassion** [comment]
@JanRudert , I never used `webjars` before, so I think you can just load `zone.js` as normal javascript. there should be some manual about how to make an angular app with webjars, you can ask at stackoverflow.

**Comment by JanRudert** [comment]
@JiaLiPassion Thanks a lot for you help. I posted my question [here](https://stackoverflow.com/questions/48263466/using-angular-testbed-with-sbt-jasmine).
