### ISSUE TITLE
Solution for "Cannot use setInterval from within an async zone test?"

### ISSUE THREAD

**Issue by jbreeden** [angular/zone.js#355]
I'm sure this is my own fault somehow, but I'm having issues running async tests with zone.js, jasmine, & angular2. I'm getting the "Cannot use setInterval from within an async zone test" error message.

I've wrapped the `setInterval` method and dumped the stack trace when the call happens just to see:

```JavaScript
_interval = global.setInterval;
global.setInterval = function () {
    console.log("\n\n\n\nsetInterval\n\n\n\n")
    console.trace();
    return _interval.apply(global, arguments);
}

require("reflect-metadata");
require('zone.js');
require('zone.js/dist/async-test');
```

But the call seems to be coming from "inside the house!"

```
Trace
    at global.setInterval (/Users/jbreeden/repos/my_project/spec/helpers/babelhook.helper.js:9:13)
    at ZoneTask.scheduleTask [as scheduleFn] (/Users/jbreeden/repos/my_project/node_modules/zone.js/dist/zone-node.js:643:36)
    at ZoneDelegate.scheduleTask (/Users/jbreeden/repos/my_project/node_modules/zone.js/dist/zone-node.js:294:27)
    at Zone.scheduleMacroTask (/Users/jbreeden/repos/my_project/node_modules/zone.js/dist/zone-node.js:231:40)
    at /Users/jbreeden/repos/my_project/node_modules/zone.js/dist/zone-node.js:658:26
    at setInterval (eval at createNamedFn (/Users/jbreeden/repos/my_project/node_modules/zone.js/dist/zone-node.js:961:18), <anonymous>:3:38)
    at FutureAction._schedule (/Users/jbreeden/repos/my_project/node_modules/rxjs/src/scheduler/FutureAction.ts:95:20)
    at FutureAction.schedule (/Users/jbreeden/repos/my_project/node_modules/rxjs/src/scheduler/FutureAction.ts:42:17)
    at AsyncScheduler.scheduleNow (/Users/jbreeden/repos/my_project/node_modules/rxjs/src/scheduler/AsyncScheduler.ts:8:41)
    at AsyncScheduler.QueueScheduler.schedule (/Users/jbreeden/repos/my_project/node_modules/rxjs/src/scheduler/QueueScheduler.ts:35:12)
```

I'm hoping there's just a `require` statement or configuration that I'm missing. Any ideas?

**Comment by jbreeden** [comment]
So, it looks like I have to be doing an `async(inject(...` test for this to happen.

Also I can't repro if I isolate one of the tests, so it must be caused by something elsewhere in my tests (perfect!).

Given that, I'm sure this is a "me" problem, not a zone.js problem. I'll leave this open for now just in case you guys have any useful pointers. Otherwise we can probably close at least until I have more information.

**Comment by jbreeden** [comment]
I was being dense when I wrote this. It is not necessary to use `async(inject(...` to repro, I just happened to be injecting the thing that caused the call to setInterval. The call was ultimately coming from rxjs, not zonejs itself as I thought initially. Makes sense...

I'm guessing angular's `async` function doesn't allow setInterval because it can never know when the test is finished...? Enter Jasmine's `done` callback... which is awkward to use with `inject`

```JavaScript
/* Contrived example... */
it('does something', function (done) {
  inject([Something], (something) => {
    let count = 0;
    let interval = setInterval(() => {
      count += 1;
      if (count == 3) {
        done(); 
        clearInterval(interval); 
      }
    }, 10);
  })(); /* Need to manually invoke the "injected" function */
});
```

Seems like the constraint on setInterval could be relaxed if the function passed to `async` returns a promise (if I understand the problem correctly). Or there could be a more natural way to utilize the `done` function from jasmine through `inject` and friends (or maybe there is and I just haven't found it). 

If I can't find a cleaner solution in the next few minutes, I'll be using the `done` function workaround as shown above. If anybody has pointers for a cleaner solution I'm all ears.

**Comment by jbreeden** [comment]
Wow. You _can_ just return a `Promise`.

```JavaScript
it('does something', inject([Something], (something) => {
  return Promise.new(() => { /* code w/ setInterval or whatever */ });
});
```

I must have been mixing that with `async` calls before.

Nothing like being totally wrong on the internet.

**Comment by Barryrowe** [comment]
Seeing this, what is the purpose of ```async(``` if returning a promise from ```inject``` is reliable now?

**Comment by danday74** [comment]
I am hitting this error with ...

import 'rxjs/add/operator/timeout';

return this.http[method](url, emit, this.options)
        .timeout(Config.http.timeout, new Error('timeout'))

If i remove the HTTP timeout the prob goes away (but I want the HTTP timeout).

I confirm that I am using async to wrap my test. This is surely bad behaviour and NOT ME!

**Comment by danday74** [comment]
confirmed this was fixed by switching to Jasmine's done which seems more intelligent than it used to.
