### ISSUE TITLE
Bug: Google Maps throws error when adding zone.js (requestAnimationFrame)

### ISSUE THREAD

**Issue by SebastianM** [angular/zone.js#359]
When using zone.js in combination with the Google Maps API, zone.js causes an exception when grabbing the map and panning it as described here: https://github.com/SebastianM/angular2-google-maps/issues/355#issue-155267073

I created a demo where this also happens when angular2-google-maps is not used.
Demo here: http://plnkr.co/edit/hbjkks?p=preview

Related angular2-google-maps issue: https://github.com/SebastianM/angular2-google-maps/issues/355

**Comment by IgorMinar** [comment]
Similar reproduction: http://stackoverflow.com/questions/37348649/uncaught-typeerror-cannot-read-property-ca-of-null-when-dragging-google-map

**Comment by WHarris22** [comment]
I did some more Googling a while back and came across [this issue](https://code.google.com/p/gmaps-api-issues/issues/detail?id=7991), 

I know this is from last year and may have been fixed but it might suggest that it is a problem with the Google API and not Angular

**Comment by SebastianM** [comment]
@IgorMinar it's fixed with v0.16.7 :tada: 

http://plnkr.co/edit/lw1VovPBHroQabVyyAyd?p=preview
