### ISSUE TITLE
requestAnimationFrame should return native handleId or cancelAF should accept TimerOption

### ISSUE THREAD

**Issue by laco0416** [angular/zone.js#360]
From https://github.com/angular/angular/issues/8401

Currently, zone-patched `requestAnimationFrame` returns `ZoneTask`. 

It seems breaking native rAF canceling:

```js
let handleId = requestAnimationFrame(fn);
cancelAnimationFrame(handleId); // not canceled
```

To cancel rAF, we have to use `data.handleId`

```js
let timerOption = requestAnimationFrame(fn);
cancelAnimationFrame(timerOption.data.handleId);
```

**Comment by laco0416** [comment]
Repro (with Angular2): http://plnkr.co/edit/MmQmT8YAbOyg8kh3pnQX?p=preview

**Comment by SebastianM** [comment]
Maybe related to #359

**Comment by b-strauss** [comment]
I think zone.js should not change the signature of any native APIs. Is there a list of all patches that do not preserve the original signature?

**Comment by laco0416** [comment]
AFAIK, set/clearInterval and  set/clearTimeout are preserved its native behavior.

**Comment by laco0416** [comment]
@IgorMinar how do you think about this?

**Comment by laco0416** [comment]
Fixed in latest zone.js. http://plnkr.co/edit/JJCleR?p=preview
