### ISSUE TITLE
Zone.js is  not working on apache server. Get Call "%5Bobject%20Object%5D" on startup

### ISSUE THREAD

**Issue by nawalgupta** [angular/zone.js#363]
Zone.js is making a Get call to http://webroot/%5Bobject%20Object%5D on startup.

In Node (express) env this call is returning the index.html page again.But on any other env (apache) this call is returning 404 error and the page stops here.

Request URL:http://localhost/%5Bobject%20Object%5D

Why  this get call ?

I am using webpack to compile the application.

CallStack:
Zone.js:101	        setNative.apply(data.target, data.args);

**Comment by jrgleason** [comment]
Seem to be getting a similar issue in my application...

https://github.com/jrgleason/ng2-webpack-demo/tree/GULP_EXPRESS

Works fine if I run it under the webpack server, however, if I copy to apache (or even the public folder in express) I get the same error.

**Comment by jrgleason** [comment]
In my case I needed to change `styleUrls: [String(require('./navbar.component.styl'))]`

to `styles: [String(require('./navbar.component.styl'))]`

It is interesting the other one worked with webpack

**Comment by IgorMinar** [comment]
this doesn't look like a zone issue. if you are inlining stylesheets in Angular then you should use `styles` property in the component metadata as @jrgleason suggested.
