### ISSUE TITLE
Uncaught TypeError: Cannot read property 'ca' of null using Google Maps

### ISSUE THREAD

**Issue by WHarris22** [angular/zone.js#369]
When dragging the map and throwing it when releasing the click this error gets thrown in the console log.

Further details can be found in this [Stackoverflow post](http://stackoverflow.com/questions/37348649/uncaught-typeerror-cannot-read-property-ca-of-null-when-dragging-google-map) which also includes a Plunker example using the Ionic 2 framework to replicate.

**Comment by SebastianM** [comment]
possibly dup of #359

**Comment by IgorMinar** [comment]
yup. looks like dupe of #359
