### ISSUE TITLE
Synchronous XHR request through zonejs results in:  More tasks executed then were scheduled

### ISSUE THREAD

**Issue by thelgevold** [angular/zone.js#377]
I am logging a bug report:

There seems to be a bug in the bookkeeping of `XMLHttpRequest` in zone.js.

If I  trigger a synchronous `XMLHttpRequest` when zonejs is loaded on the page I get the following error:
`Error: More tasks executed then were scheduled.`

The error does not occur if the request is asynchronous.

Here is a simple plunker with a repro: https://plnkr.co/edit/7Cn3JknfDIIHMIdqcuo0?p=preview

I have not looked into this extensively, but the error occurs here:
`next` is set to -1 which triggers the error condition.

```
ZoneDelegate.prototype._updateTaskCount = function (type, count) {
	            var counts = this._taskCounts;
	            var prev = counts[type];
	            var next = counts[type] = prev + count;
	            if (next < 0) {
	                throw new Error('More tasks executed then were scheduled.');
	            }
	            if (prev == 0 || next == 0) {
	                var isEmpty = {
	                    microTask: counts.microTask > 0,
	                    macroTask: counts.macroTask > 0,
	                    eventTask: counts.eventTask > 0,
	                    change: type
	                };
	                try {
	                    this.hasTask(this.zone, isEmpty);
	                }
	                finally {
	                    if (this._parentDelegate) {
	                        this._parentDelegate._updateTaskCount(type, count);
	                    }
	                }
	            }
	        };
```

**Comment by thelgevold** [comment]
I agree that sync xhr requests are discouraged, but I think a warning is more appropriate than an error in this scenario.

**Comment by garethdn** [comment]
Having the same issue specifically when trying to use a [Marketo lead-tracking plugin](http://developers.marketo.com/documentation/websites/lead-tracking-munchkin-js/). Granted, the requests the plugin perform should really be async but throwing an error and essentially breaking change detection seems a bit much.

https://github.com/NewsWhip/NewsWhip/issues/8022

**Comment by garethdn** [comment]
https://github.com/angular/zone.js/issues/287#issuecomment-235011681

**Comment by dfahlander** [comment]
The awesome [karma-source-map-support](https://www.npmjs.com/package/karma-source-map-support) needs to do synchronous xhr requests to make the property Error.prototype.stack behave nice, because a getter is always synchronous. Zonejs should neither warn or fail about that. Synchronous request is a public and acceptable use of XMLHttpRequest and zonejs should respect that.  It should really be transparent. This is a bug and I suppose it could be easily fixed for those who are already familiar with the zonejs source code.
