### ISSUE TITLE
Why would zone show 404 in console?

### ISSUE THREAD

**Issue by 5amfung** [angular/zone.js#378]
I use Parse in my project. When the Parse login api returns an error of invalid username and password, I guess the REST API respond with 404 and the error message in the response body.  But my browser would also display the 404 error?  Why?

![image](https://cloud.githubusercontent.com/assets/371691/16892545/0b54a20a-4acb-11e6-9ad2-8864d341c52d.png)

**Comment by SalinderSidhu** [comment]
I can confirm I have the same issue. I'm not aware of any option to disable this if possible?
