### ISSUE TITLE
Conditionnally exclude websocket

### ISSUE THREAD

**Issue by lpenet** [angular/zone.js#381]
Hi.

I am having an issue when testing an angular 2 app with protractor which, AFAIK, boils down to how Zone.js is tracking websockets.

My app relies on websockets for push notifications. The socket is kept opened and, so, the zone is never stable, the angular2 app is never stable and protractor waits forever.

It would be great to have an option not to monitor WS and WSS the same way as standard HTTP(S) requests.

**Comment by vicb** [comment]
Do you have a simple repro case ?

**Comment by lpenet** [comment]
As I am using java and tomcat on server side, providing you a plunker might be a bit difficult.

But, well, I think any case where the client connects to a server with a websocket that gets suspended is concerned.

**Comment by AshMcConnell** [comment]
@lpenet we are having trouble getting protractor to test our app with a websocket.  Did you ever get a workaround?

**Comment by lpenet** [comment]
Le 2017-03-03 12:48, Ash McConnell a écrit :
> @lpenet [1] we are having trouble getting protractor to test our app
> with a websocket. Did you ever get a workaround?
Sadly, I added a parameter to disable websockets on tests with 
protractor...

Ludovic

**Comment by AshMcConnell** [comment]
Thanks Ludovic

That's a shame as that's really the big advantage of protractor (it's angular integration).  So it's essentially broke for Angular 2 if you use websockets (which a lot of people will for hot reloading during development).  

Has anyone else got any workarounds?

**Comment by JiaLiPassion** [comment]
@AshMcConnell , can you post a reproduce repo?

**Comment by AshMcConnell** [comment]
I'll try to create one

**Comment by hungerregnuh** [comment]
@JiaLiPassion, a similar issue is being looked at over in the angularfire2 project as well, https://github.com/angular/angularfire2/issues/779

**Comment by JiaLiPassion** [comment]
@hungerregnuh , I will check it later.

**Comment by VladimirMakaev** [comment]
We have the same issue in an app that uses Firebase. We'd have to disable protractor support for Angular to get it working but that's essentially making us use plain Selenium with a lot of custom waits.

**Comment by AshMcConnell** [comment]
We ended up going for Cypress, it feels much more solid and natural for Angular testing.  I know this isn't a proper answer to the question, but we got so much more by moving to Cypress

**Comment by JiaLiPassion** [comment]
@VladimirMakaev , @AshMcConnell , please provide some reproduce repo so I can try to resolve the issue. thanks.

**Comment by VladimirMakaev** [comment]
@JiaLiPassion I've reproduced the issue here https://github.com/VladimirMakaev/todo-angular-firebase
If you run:
```
npm run e2e
```
You'd see the tests failing with 
```
Failed: Timed out waiting for asynchronous Angular tasks to finish after 40 seconds. This may be because the current page is not an Angular application. Please see the FAQ for more details: https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular
```
At the same time if you uncomment the line in `app.e2e-spec.ts` you'd get them pass.
```
// browser.ignoreSynchronization = true;
```

**Comment by VladimirMakaev** [comment]
Essentially it all goes down to Angular Testability constantly returning false for isStable()
if you go to https://ng2-todo-app.firebaseapp.com/tasks and in console enter:
```
window.getAllAngularTestabilities()[0].isStable()
```
![image](https://user-images.githubusercontent.com/2001475/33574616-9769548e-d931-11e7-85e4-df0c3e204d97.png)

**Comment by JiaLiPassion** [comment]
close for now, issue is in angular repo.
