### ISSUE TITLE
The zone.js.d.ts file does not work with webpack

### ISSUE THREAD

**Issue by flyOstrich** [angular/zone.js#384]
I tried using zone.js in webpack , see my codes here:
`import "reflect-metadata";`
`import "zone.js";`
`import { Component } from '@angular/core';`
`import { bootstrap }    from '@angular/platform-browser-dynamic';`

`@Component({`
  `selector: 'my-app',`
  `template: '\<h1\>for test\</h1\>'`
`})`
`class AppComponent { }`

`bootstrap(AppComponent);`

the typescript compiler throw error:

**error TS2656: Exported external package typings file '/Users/pjl/ng2-webpack-seed/node_modules/zone.js/dist/zone.js.
d.ts' is not a module. Please contact the package author to update the package definition.**

**Comment by AepKill** [comment]
i have the problem too.

**Comment by gustavohenke** [comment]
The problem is not with Webpack. I have this problem while using Browserify, too.

I think this problem is the same as #297 and #365, and I still don't understand how it should work!

**Comment by GabrielDelepine** [comment]
Check @IgorMinar's answer at #365.

You have to load zone.js from the first script tag of you index.html file. Do not import it like the way describe above.

**Comment by GiuseppePiscopo** [comment]
It looks like this issue could be closed, by now
