### ISSUE TITLE
Don't throw exceptions because of uncaught rejection

### ISSUE THREAD

**Issue by tflori** [angular/zone.js#385]
This is a feature request - or better: a request to remove a feature.

I'm using zone.js 0.6.12 installed via npm.

By throwing an exception because `queue.length == 0 && state == REJECTED` every test fails where someone is not writing `promise.catch(() => {})` or `promise.then(() => {}, () => {})`. It makes the code more ugly and is not helpful.

At least you should be able to disable this feature (inform about uncaught rejections).

Let's assume this code: 

``` ts
export class Simple {
  private i:number = 0;
  public function setIncrement(i:number):void { this.i = i; }
  public function make():Promise<void> {
    return new Promise((resolve, reject) => {
      if (this.is < 10) { resolve(); }
      else { reject('increment to high'); }
    };
  }
}
```

One from this tests fails but the code works fine:

``` ts
import {fakeAsync, flushMicrotasks} from '@angular/core/testing';
import {Simple} from '../simple';

describe('simple', () => {
  var simple;
  beforeEach(() => {
    simple = new Simple();
  });
  it('resolves', fakeAsync(() => {
    simple.setIncrement(3);

    var promise = simple.make();

    expect(promise['__zone_symbol__state']).toBe(true);
  }));
  it('rejects', fakeAsync(() => {
    simple.setIncrement(11);

    var promise = simple.make();

    expect(promise['__zone_symbol__state']).toBe(false);
  }));
});
```

**Comment by cburgmer** [comment]
To reproduce:

```js
> Promise
< function ZoneAwarePromise()

> Promise.reject().then(() => {}, () => {})
< Object { __zone_symbol__state: null, __zone_symbol__value: Array[0] } 

> Promise.reject().then(() => {})
< Object { __zone_symbol__state: null, __zone_symbol__value: Array[0] }
Object { __zone_symbol__error: Error, fileName: Getter, lineNumber: Getter, columnNumber: Getter, message: Getter, name: Getter, stack: Getter, originalStack: Getter, zoneAwareStack: Getter, toString: [524]/</</createMethodProperty/props[key].value(), 5 more… }
```

This feature provides positive value when tracking unhandled promises. However, there are cases where you want to store a promise regardless of its status and process the outcome later. If this promise is then rejected, a massive stacktrace is printed. This gets very prominent in tests when all kinds of behaviour is tested.

As a work around in our tests we are doing this right now:

```js
spyOn(console, 'error').and.callFake(() => { console.log('Suppressed call to console.error'); });
```

**Comment by JiaLiPassion** [comment]
Now zone.js has provide unhandledpromiserejectionhandler

- Browser
use window.unhandledrejection

- nodejs
use unhandledRejection

Can this meet your requirement?

**Comment by cburgmer** [comment]
Thanks for the pointer. I am digging through the source code but fail to see any quick explanation on how to use this.

**Comment by JiaLiPassion** [comment]
Here is the usage

https://github.com/angular/zone.js/pull/627

**Comment by cburgmer** [comment]
If I understand correctly that would be the following?

```js
Zone[Zone.__symbol__('ignoreConsoleErrorUncaughtError')] = true;
```

That's an internal API likely to change in the future though, right?

**Comment by tflori** [comment]
I like @cburgmer  answer the most. But anyway:

```js
Promise.reject('This is not failing at all');
```

should IMHO not cause an error in the console. The default value for this setting should be true.

**Comment by JiaLiPassion** [comment]
@tflori , now  you can set 

```javascript
Zone[Zone.__symbol__('ignoreConsoleErrorUncaughtError')] = true;
```
to ignore the console output.

**Comment by tflori** [comment]
yes, I understand that. 

for me it is a bug. without zonejs it does not throw an error. with zonejs it throws. but as i understand zones it is just an execution zone and not a "you have to do it correct" zone. 

and therefore the symbol should be true by default.

if you don't think so, you can close this issue. it's solved with this symbol.

**Comment by JiaLiPassion** [comment]
@tflori , by default it is true because it is helpful for debug, and BTW the symbol only control to output the error information to console or not. Without the symbol, the error will just be output to console.

I tried the code in nodejs without zone.js, it will also output warning, and in the future it will not be warning but an error.

```javascript

onst promise = new Promise((resolve, reject) => {
  setTimeout(() => {
   reject('fail');
}, 0);
});

setTimeout(() => {
   console.log('promise', promise);
}, 100);
```

```
(node:30630) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): fail
(node:30630) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled w
ill terminate the Node.js process with a non-zero exit code.
```

**Comment by tflori** [comment]
wow, ok. where to discuss about es6 :smile:? 

it feels wrong for me. because it means I don't have the option to ignore the error. on a bash for example when I don't care about non zero exit codes I write `;` instead of `&&`.

but that's a es6 discussion then. and thanks for the info
