### ISSUE TITLE
xhr upload onprogress event is not run in zone

### ISSUE THREAD

**Issue by Matthias247** [angular/zone.js#390]
I'm trying to display a file upload progress in angular2 and I'm using the xhrs upload.onprogress event to get notified about status updates and display them to the user.
However these updates don't seem to trigger change detection at the moment. It only works if I'm wrapping my update in `zone.run()` as follows:

``` js
xhr.upload.onprogress = ev => {
      this.zone.run(() => {
          this.uploadProgress= Math.round((ev.loaded / ev.total) * 100.0);
      });
};
```

As other xhr events work without zone.run I'm guessing there is some patching to the browser APIs missing for this event?

**Comment by JiaLiPassion** [comment]
it should work now
