### ISSUE TITLE
0.6.14 Uncaught Error: Missing: SyncTestZoneSpec for Angular RC4 tests

### ISSUE THREAD

**Issue by binarious** [angular/zone.js#404]
Since 0.6.14 I'm getting `Uncaught Error: Missing: SyncTestZoneSpec` for my Angular2 RC4 unit tests. They work with 0.6.13.

 Affected [project](https://github.com/Sirimangalo/meditation-plus-angular) and [failing build](https://travis-ci.org/Sirimangalo/meditation-plus-angular/builds/152888816#L2389) as a reference.

I'm using [angular2-webpack-starter](https://github.com/AngularClass/angular2-webpack-starter) for my Angular2 project (like many others) which references zone.js via `~0.6.12` ([package.json](https://github.com/AngularClass/angular2-webpack-starter/blob/4cf9947347663d8a61b7c7138a68e2d125bc39f9/package.json#L92)). This issue is likely affecting a lot of people.

**Comment by chrismagri** [comment]
same issue happening for me.. is there any update?

**Comment by binarious** [comment]
Downgrading to zone.js to `0.6.13` works for me.

**Comment by oocx** [comment]
We get the same error with Angular 2 RC5. We are also using a configuration similar to angular2-webpack-starter, and therefore also automatically got the new zone.js version in our CI builds.

**Comment by raelzhu** [comment]
I did the below changes to the config/karma-test-shim.js (or config/spec-bundle.js) and unit tests worked again.
```javascript
require('zone.js/dist/zone');
require('zone.js/dist/long-stack-trace-zone');
require('zone.js/dist/async-test');
require('zone.js/dist/fake-async-test');
require('zone.js/dist/sync-test');
require('zone.js/dist/proxy-zone'); // since zone.js 0.6.14
require('zone.js/dist/jasmine-patch'); // put here since zone.js 0.6.14
```

**Comment by IgorMinar** [comment]
yup. that's the right fix. you need to load the sync-test zone in your testing harness.

**Comment by cdcooksey** [comment]
We are using Angular2 RC2.  

The above test shim update did not resolve the issue.  

I updated `package.json` to this:

```diff
-    "zone.js": "^0.6.12",
+    "zone.js": "^0.6.14",
```

and updated to include: `require('zone.js/dist/sync-test');`

These steps did not resolve the issue.

Forcing a downgrade to `0.6.13` resolved the issue.

```diff
  "dependencies": {
    "@angular/compiler": "2.0.0-rc.2",
    "@angular/common": "2.0.0-rc.2",
    "@angular/core": "2.0.0-rc.2",
    "@angular/http": "2.0.0-rc.2",
    "@angular/platform-browser": "2.0.0-rc.2",
    "@angular/platform-browser-dynamic": "2.0.0-rc.2",
    "@angular/router": "2.0.0-rc.2",
    "@angular/router-deprecated": "2.0.0-rc.2",
    "@angular/upgrade": "2.0.0-rc.2",
    "@ngrx/core": "^1.0.0",
    "@ngrx/store": "^2.0.1",
    "core-js": "^2.4.0",
    "es6-promise": "^3.2.1",
    "es6-shim": "^0.35.1",
    "reflect-metadata": "^0.1.3",
    "require": "^2.4.20",
    "rxjs": "^5.0.0-beta.9",
-    "zone.js": "^0.6.12",
+    "zone.js": "0.6.13",
    "material-design-lite": "^1.1.3",
    "getmdl-select": "^1.0.4"
  },
```

**Comment by nicksterx** [comment]
@cdcooksey Did you clear out your node modules and rerun npm install?

**Comment by SaltyDH** [comment]
As of 0.6.15, the proxy-zone package has been renamed to proxy. The following imports work for us.

```
require('zone.js/dist/zone');
require('zone.js/dist/long-stack-trace-zone');
require('zone.js/dist/async-test');
require('zone.js/dist/fake-async-test');
require('zone.js/dist/sync-test');
require('zone.js/dist/proxy'); // since zone.js 0.6.15
require('zone.js/dist/jasmine-patch'); // put here since zone.js 0.6.14
```

**Comment by c24w** [comment]
@SaltyDH thanks - we found the order of the dependencies was also important...

**Comment by develand** [comment]
Fixed by updating the 'files' array in karma.config.js with:

      'node_modules/zone.js/dist/zone.js',        
      'node_modules/zone.js/dist/long-stack-trace-zone.js',
      'node_modules/zone.js/dist/async-test.js',
      'node_modules/zone.js/dist/fake-async-test.js',
      'node_modules/zone.js/dist/sync-test.js',
      'node_modules/zone.js/dist/proxy-zone.js',
      'node_modules/zone.js/dist/proxy.js',
      'node_modules/zone.js/dist/jasmine-patch.js',

NOTE: as indicated by others, the order is important

**Comment by rsheptolut** [comment]
Just wasted almost an hour on this! The order of imports is indeed important. I use tslint and I've blindly applied the autofix for the "ordered-imports" rule in VS Code (via the TSLint extension), so it sorted them alphabetically. Btw, it would be nice if zone.js fixed this dependency on the order of imports. Easy to overlook, this; and feels like a magic spell, or even like a bug if you ask me, a humble guest in the strange javascript world.

**Comment by julie-ng** [comment]
The sort order I needed for Angular 4.0.0 generated using the CLI was so:

```
import 'zone.js/dist/long-stack-trace-zone'
import 'zone.js/dist/proxy.js'
import 'zone.js/dist/sync-test'
import 'zone.js/dist/jasmine-patch'
import 'zone.js/dist/async-test'
import 'zone.js/dist/fake-async-test'
```

**Comment by RoestVrijStaal** [comment]
@julie-ng In which file did you throw those imports in?

**Comment by renrawnalon** [comment]
@RoestVrijStaal I just ran into the same problem. The imports are already in src/test.ts but TSLint changes their order if you have "ordered-imports" enabled. Changing the order back to the order listed above (and disabling TSLint for this file) solved the problem for me.

**Comment by JiaLiPassion** [comment]
I have made a PR #982 to add a new `zone-testing` file , hope it can resolve this issue.

**Comment by mitschmidt** [comment]
Same issue for me, after tslint auto fixed many files in my project the client tests did not work anymore.
Thanks for the hint with the import orders, that solved the problem for me.

**Comment by rcollette** [comment]
My testbed imports  got reordered as  well.  The complete import list I see for V4.x right now is
```javascript
import 'zone.js/dist/long-stack-trace-zone';
import 'zone.js/dist/proxy.js';
import 'zone.js/dist/sync-test';
import 'zone.js/dist/jasmine-patch';
import 'zone.js/dist/async-test';
import 'zone.js/dist/fake-async-test';
import { getTestBed } from '@angular/core/testing';
import {
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting
} from '@angular/platform-browser-dynamic/testing';
```
