### ISSUE TITLE
Uncaught Error: Zone already loaded

### ISSUE THREAD

**Issue by CanKer** [angular/zone.js#405]
I don't really know how it happened but I got the "`Uncaught Error: Zone already loaded`" error in my console after doing some POST petitions. The functionality it's ok, but the look of the app it changes. 

<img width="1407" alt="screen shot 22" src="https://cloud.githubusercontent.com/assets/7593319/17758657/7cc13bc0-64f1-11e6-8aa4-ca5da7ddeeba.png">

**Comment by dekonunes** [comment]
+1

**Comment by Chasvortex** [comment]
+1

**Comment by AGoodnight** [comment]
Make sure your not loading the module twice, I had it hiding in my index file:

...
<script src="node_modules/zone.js/dist/zone.js"></script>  // <-- I removed this
...

Incidentally if you load it more than once you screw up the router a bit. You need to click your routing links multiple times when this bug arises after loading it too many times.

**Comment by jgf5013** [comment]
I am having this issue as well.

**Comment by Chasvortex** [comment]
It was the same with me. If this happening, try removing where you include zone.js from your index html

**Comment by Splaktar** [comment]
This looks like a project configuration issue rather than a Zone.js bug. That said, the error message could be more helpful. It should specify the name of the zone that is already loaded or some identifying information. In my case, the stack trace pointed to three different source files in my code, none of which were really helpful.

For me, this ended up being an issue with my Polymer dependencies from Bower. If I am missing a Polymer dependency, then this error occurs saying `Uncaught Error: Zone already loaded`. Fixing my `bower.json` and my imports in `elements.html` resolved the error.

**Comment by gandra** [comment]
Angular has a terrible debug feedback ... zone not loaded ... thank you very much!

**Comment by JiaLiPassion** [comment]
Thank you for all the information , I will try to make the error message more helpful.

**Comment by gandra** [comment]
Kudos to @JiaLiPassion for attitude!

**Comment by JiaLiPassion** [comment]
@gandra , thank you!!

**Comment by dgroh** [comment]
what if I want to load two angular apps in the same page? both are going to have `zone`...the error will always appears as soon as I add another app to my application

**Comment by joshbabb** [comment]
Hmmm

```
vendor.js:124539 Uncaught Error: Zone already loaded.
    at vendor.js:124539
    at vendor.js:125151
    at FUNCTION (vendor.js:124516)
    at Object.<anonymous> (vendor.js:124519)
    at Object.<anonymous> (vendor.js:127569)
    at __webpack_require__ (vendor.js:55)
    at Object.<anonymous> (vendor.js:77767)
    at __webpack_require__ (vendor.js:55)
    at Object.<anonymous> (vendor.js:124034)
    at __webpack_require__ (vendor.js:55)
```

**Comment by herkulano** [comment]
Also getting this error running tests

```
  ● Test suite failed to run

    Zone already loaded.

    > 6 | import { Observable } from 'rxjs'
```

**Comment by leandropx** [comment]
> Error: Zone already loaded.
>     at http://localhost:8100/build/vendor.js:126384:15
>     at http://localhost:8100/build/vendor.js:126996:3
>     at FUNCTION (http://localhost:8100/build/vendor.js:126361:10)
>     at Object.<anonymous> (http://localhost:8100/build/vendor.js:126364:2)
>     at Object.<anonymous> (http://localhost:8100/build/vendor.js:129414:30)
>     at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
>     at Object.__extends (http://localhost:8100/build/vendor.js:76999:66)
>     at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
>     at Object.<anonymous> (http://localhost:8100/build/vendor.js:126083:72)
>     at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)

**Comment by guillop** [comment]
fix:
npm install angularfire2@5.0.0-rc.4

**Comment by rahuljograna** [comment]
This is the problem of new firebase update, here is a solution for this error

** Step: 1** Install the lower version of firebase using this command

npm install angularfire2@5.0.0-rc.4

** Step: 2**

npm install

Try.

**Comment by lavanvickyneshwaran** [comment]
Error: Zone already loaded.
    at http://localhost:8100/build/vendor.js:126054:15
    at http://localhost:8100/build/vendor.js:126668:3
    at FUNCTION (http://localhost:8100/build/vendor.js:126031:10)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:126034:2)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:129050:30)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.defineProperty.value (http://localhost:8100/build/vendor.js:79337:66)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:125549:72)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)

**Comment by lavanvickyneshwaran** [comment]
Stack
Error: Zone already loaded.
    at http://localhost:8100/build/vendor.js:126054:15
    at http://localhost:8100/build/vendor.js:126668:3
    at FUNCTION (http://localhost:8100/build/vendor.js:126031:10)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:126034:2)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:129050:30)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.defineProperty.value (http://localhost:8100/build/vendor.js:79337:66)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:125549:72)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)

**Comment by anoopmv6** [comment]
I was facing this problem for last few days..Now I am get out of this "zone already error" from the following way....!

Step 1: Degrade firebase version to lower by typing npm install angularfire2@5.0.0-rc.4

Step 2: run npm install

**Comment by mehtaparam** [comment]
Ty @rahuljograna  @anoopmv6  @guillop solution is working

**Comment by GonzaloUNAB2018** [comment]
thanks for your answers!! it working!
see ya!

**Comment by anoopmv6** [comment]
welcome Gonzalo

**Comment by arjun526nag** [comment]
Uncaught Error: Zone already loaded.
    at zone.js:32
    at zone.js:644
    at FUNCTION (zone.js:9)
    at Object.<anonymous> (zone.js:12)
    at Object.<anonymous> (zone.js:3060)
    at __webpack_require__ (bootstrap 6613f924a1108f55b2e9:54)
    at Object.defineProperty.value (vendor.js:69159)
    at __webpack_require__ (bootstrap 6613f924a1108f55b2e9:54)
    at Object.<anonymous> (vendor.js:117173)
    at __webpack_require__ (bootstrap 6613f924a1108f55b2e9:54)


please help us..i try it npm install angularfire2@5.0.0-rc.4 and npm install also but not working

**Comment by anoopmv6** [comment]
arjun..
after update angularfire run npm install

**Comment by arjun526nag** [comment]
i am trying this command  it's wrkng for me. npm install firebase@4.8.0

**Comment by JiaLiPassion** [comment]
@davidenke, sure, this has been fixed here https://github.com/angular/zone.js/pull/1093

**Comment by JiaLiPassion** [comment]
@davidenke , I have changed PR title, when the flag is true, the `Zone is already loaded error` will be thrown, by default, this error will not be thrown.

**Comment by amitesh786** [comment]
> Make sure your not loading the module twice, I had it hiding in my index file:
> 
> ```
> ...
> <script src="node_modules/zone.js/dist/zone.js"></script>  // <-- I removed this
> ...
> ```
> Incidentally if you load it more than once you screw up the router a bit. You need to click your routing links multiple times when this bug arises after loading it too many times.

I agree, but I just remove some more link related to zone -

I have seen this problem, so I just remove as well as I create `system.config.js` file that contain info related to link & all script it works perfect.

**Comment by robermorales** [comment]
> @davidenke , I have changed PR title, when the flag is true, the `Zone is already loaded error` will be thrown, by default, this error will not be thrown.

Which is the intended process to get this fix inside a running angular 6 application? It seems that the fix is in the zone.js master branch but the latest npm release is from 8 months ago.

Thanks,

**Comment by JiaLiPassion** [comment]
Please wait for a little more longer, the new version will be released soon.

**Comment by fishbone1** [comment]
This error can also occur if you export symbols at the bottom of polyfills.ts and import them in another ts file of your application.
