### ISSUE TITLE
 Error: Missing: SyncTestZoneSpec

### ISSUE THREAD

**Issue by monkeychops** [angular/zone.js#407]
tests are failing webpack:///~/zone.js/dist/jasmine-patch.js:66:0

**Comment by fbmfbm** [comment]
regression to v.0.6.12 is ok but v.0.6.14 give me this to.

**Comment by elhigu** [comment]
0.6.13 was also ok. I'm getting the same error with 0.6.14. 

We are using angular2-webapack-starter

**Comment by crehn** [comment]
I have the same problem. 0.6.13 is OK, 0.6.14 throws the error when running karma tests. Steps to reproduce:
```sh
git clone https://github.com/angular/quickstart.git
cd quickstart
npm install
npm test
```

The problem seems to have been introduced with PR #402. @jelbourn even comments the corresponding lines in the PR.

**Comment by JurajMlich** [comment]
https://github.com/angular/zone.js/issues/404

**Comment by crehn** [comment]
This appears to be the same problem (i.e. duplicate), you are right. Having to update the imports is a breaking change, though. But I guess as zone.js still major version 0, this is semver compliant. OK.

**Comment by HeavenlyHost** [comment]
Also having problem with Angular 2 RC6, I found this problem when trying to unit test under karma and jasmine ?
Karma: 1.2.0
Karma chrome launcher: 2.0.0
Karma jasmine: 1.0.2
Jasmine-core: 2.5.0

**Comment by JurajMlich** [comment]
@HeavenlyHost have a look at #404

**Comment by crh225** [comment]
Im getting this error in rc6. I cant downgrade zone.

**Comment by crh225** [comment]
had to change my code to:
```
require('ts-helpers');

require('zone.js/dist/zone');
require('zone.js/dist/long-stack-trace-zone');
require('zone.js/dist/proxy'); // since zone.js 0.6.15
require('zone.js/dist/sync-test');
require('zone.js/dist/jasmine-patch'); // put here since zone.js 0.6.14
require('zone.js/dist/async-test');
require('zone.js/dist/fake-async-test');

// RxJS
require('rxjs/Rx');

var testing = require('@angular/core/testing');
var browser = require('@angular/platform-browser-dynamic/testing');

testing.TestBed.initTestEnvironment(
  browser.BrowserDynamicTestingModule,
  browser.platformBrowserDynamicTesting()
);
```

**Comment by HeavenlyHost** [comment]
Adding the following

testing.TestBed.initTestEnvironment(
  browser.BrowserDynamicTestingModule,
  browser.platformBrowserDynamicTesting()
);

helped... I think the confusing part is that I think others are using webpack where as I am still using system :-( 

Also can I just say that for my testing I am using...

Karma: 1.2.0
Karma chrome launcher: 2.0.0
Karma jasmine: 1.0.2
Jasmine-core: 2.5.0

is there somewhere on the web that provides a descent example of how to build a test environment using these tools with Angular 2 rc6 ?

**Comment by monkeychops** [comment]
awesome!

Managed to get mine working with webpack and RC6 by using the following config taken from the angular2-webpack-starter project

https://github.com/AngularClass/angular2-webpack-starter/blob/master/config/spec-bundle.js

**Comment by coldhavok** [comment]
@monkeychops solutions works great for me.

**Comment by AndrewCochrane** [comment]
@monkeychops also worked for me

**Comment by dessalines** [comment]
I got this error again in `zone.js@0.6.26`.
