### ISSUE TITLE
chore(travis): spin up test WebSocket server

### ISSUE THREAD

**Issue by btford** [angular/zone.js#41]
right now, the tests likely fail because of it.

**Comment by IgorMinar** [comment]
As @vicb also found, according http://sauceio.com/index.php/2014/11/sauce-connect-gets-a-speed-boost-websocket-support/ sauce should not have websocket support, but in my manual testing it's not the case. At least with sauce connect v4.3.8.

**Comment by IgorMinar** [comment]
for the record the console error reported by the browser is:

```
WebSocket connection to 'ws://localhost:8001' failed: Unexpected response code: 400
```

**Comment by IgorMinar** [comment]
a solution might be to use browserstack instead.

**Comment by vicb** [comment]
I've contacted SL support for that, seems like it is possible.
Will work with them on getting this running.
