### ISSUE TITLE
What is the correct way of using Zone.js in Node

### ISSUE THREAD

**Issue by saskodh** [angular/zone.js#411]
I want to use [Zone.js](https://github.com/angular/zone.js) on the back-end to create something like [ThreadLocal-storage](https://en.wikipedia.org/wiki/Thread-local_storage) similar to the traditional web-servers. The idea is to run the request handling in a new Zone. This will be part of a new back-end framework on which I recently started working.

At the moment I am using it like this, imported before everything else:

``` javascript
import 'zone.js';
import "zone.js/dist/long-stack-trace-zone.js";
```

So far it works fine but importing it like this fails the TypeScript compilation with the following error:

> Error TS2656: Exported external package typings file '../node_modules/zone.js/dist/zone.js.d.ts' is not a module. Please contact the package author to update the package definition.

This was reported [here ](https://github.com/angular/zone.js/issues/297) but so far was not resolved even though the issue was closed.

For now I did a temporary workaround by replacing the default typings that come with the package with typings from DefinitelyTyped which btw are not complete. I did this with postinstall [script](https://github.com/saskodh/framework/blob/master/scripts/disable_zonejs_typings.ts) in order to make it working.

I am using the latest release: v0.6.15

**Comment by gdi2290** [comment]
if you try again with 0.6.27 and latest version of typescript 2.x.x you should be good

**Comment by johnbendi** [comment]
@gdi2290 I'm still getting this error or similar even with the latest 0.7.4

**Comment by JiaLiPassion** [comment]
https://github.com/JiaLiPassion/zone-node
