### ISSUE TITLE
util.ts references Zone['__symbol__'] which is not present on ZoneType

### ISSUE THREAD

**Issue by alexeagle** [angular/zone.js#417]
This breaks closure compilation of an app using zone.js, at
`node_modules$zone_js$v0_6_17$lib$common$utils$zoneSymbol("eventTasks")`

```
app_bundle.js:49 Uncaught TypeError: node_modules$zone_js$v0_6_17$lib$common$utils$zoneSymbol is not a function(anonymous function) @ app_bundle.js:49
```

**Comment by JiaLiPassion** [comment]
this is fixed in https://github.com/angular/angular/pull/31350
