### ISSUE TITLE
Readme and examples use `beforeTask` and `afterTask`

### ISSUE THREAD

**Issue by rictic** [angular/zone.js#418]
AFAICT these functions no longer exist in the API. e.g.

 * https://github.com/angular/zone.js/search?q=beforeTask
 * https://github.com/angular/zone.js/search?q=afterTask

Related issue: https://github.com/angular/zone.js/issues/334

**Comment by warren-bank** [comment]
I absolutely hate asking the kind of question that rightfully should be answered by: RTFM..

but, I'm looking over the typescript declarations for [ZoneSpec](https://github.com/angular/zone.js/blob/master/dist/zone.js.d.ts#L243).. trying to figure out the new equivalent for these methods.. and I'm just not seeing it.

if anybody happens to be familiar with the new API, would you kindly add a few lines of pseudocode that show the general usage pattern to achieve "pre" and "post" hooks. Big thanks!

**Comment by warren-bank** [comment]
my best guess is:

```javascript
  var was_thrown;
  var my_zone = global.Zone.current.fork({
    onHandleError: function(){
      was_thrown = true;
      var error = arguments[3];
      console.log(error);
    },
    onHasTask: function(){
      var hasTask = arguments[3];
      if (!hasTask.microTask && !hasTask.macroTask && !hasTask.eventTask){
        // do finalize tasks
        if (was_thrown){}
        else {}
      }
    }
  });

  my_zone.run(function(){
    // test code
  });
```

Am I getting warmer? :)

**Comment by mhevery** [comment]
See `onInvokeTask` https://github.com/angular/zone.js/blob/master/dist/zone.js.d.ts#L305

**Comment by rictic** [comment]
That's helpful, but I'd recommend leaving this bug open until the documentation no longer references the removed `beforeTask` and `afterTask` methods. The examples in README.md use these methods almost exclusively.

**Comment by warren-bank** [comment]
dead topic.. got it, but fwiw.. one last comment

i ran a few tests using the above methodology.. trying both `onHasTask` and `onInvokeTask` hooks.
in both cases, if the "test code" is completely synchronous (ex: a `console.log()` statement) then neither hook gets invoked. it's only when the "test code" includes asynchronous code that both/either are engaged.

i suppose a (really bad) way to work with this observation would be to wrap all "test code" in a `setTimeout(function(){ test(); }, 0)`, but that feels wrong on so many levels..

anyway, just putting it out there..
