### ISSUE TITLE
Zone JS problem with Edge

### ISSUE THREAD

**Issue by debanjanbasu** [angular/zone.js#436]
I am using the latest EDGE browser, and this is the error I am getting, while loading Zone js

![capture](https://cloud.githubusercontent.com/assets/10209115/18412633/c9ad86e4-77d6-11e6-9f53-c571779feae1.JPG)

**Comment by NeoAdonis** [comment]
Can confirm. Using latest Edge version (Microsoft EdgeHTML 14.14393). Couldn't reproduce in Chrome latest.

It seems Edge doesn't like calling `global['fetch']()` without and arguement and ends the script abrutly.

**Comment by debanjanbasu** [comment]
Yes, this is a weird error, how come the earlier Zone JS worked perfectly? This is a strange error.

**Comment by danhellem** [comment]
+1 on this issue. Works fine in Chrome. I get the same error as above in Edge. Also odd that it works fine in Edge if I reference the Zone.js file like this.

`<script src="https://unpkg.com/zone.js@0.6.17?main=browser"></script>`

However, anything over 6.17 breaks in Edge

**Comment by wizarrc** [comment]
I can confirm that it breaks in Microsoft EdgeHTML 14.393. I modified my local source code repository to
`global['fetch']('')` and everything now works fine. That seems like a decent workaround/fix to the https://github.com/angular/zone.js/commit/44c46fa5a615cfa3ca6ad9ea431e216ec6795bdf commit that added this breaking change.

https://github.com/angular/zone.js/blob/44c46fa5a615cfa3ca6ad9ea431e216ec6795bdf/dist/zone.js#L550

**Comment by debanjanbasu** [comment]
You are right wizarrc, your fix does indeed solve the issue. It is actually right, as EDGE is following very strict checking of es6 features.
