### ISSUE TITLE
zone.js issue with NativeScript

### ISSUE THREAD

**Issue by warren-bank** [angular/zone.js#437]
<pre>
* file: ExampleProject/node_modules/nativescript-angular/application.js
  line: 2
  code: `import "zone.js/dist/zone-node"`
* file: ExampleProject/node_modules/nativescript-angular/node_modules/zone.js/dist/zone-node.js
  line: 670
  code: `var timers = require('timers')`
* note: in NativeScript, "timers" are re-implemented (ie: setTimeout, setInterval, etc)
  repo: https://github.com/NativeScript/NativeScript/tree/master/tns-core-modules/timer
  code: `var timer = require("timer")`
  note: "timer" NOT "timers"
* question:
    which module was most recently changed, such that they are no-longer compatible?
  answer:
  - zone.js
      https://github.com/angular/zone.js/blob/master/dist/zone-node.js
      https://github.com/angular/zone.js/commits/master/dist/zone-node.js
    note:
      2 commits within the last 5 hours
    commits:
      https://github.com/angular/zone.js/tree/55f815017df6bbda23eb0d1f61795f6f0412f51e/dist/zone-node.js
        date: Aug 22, 2016, 10:29 AM PDT
        line: 54
        code: `var timers = __webpack_require__(4);`
      https://github.com/angular/zone.js/tree/44c46fa5a615cfa3ca6ad9ea431e216ec6795bdf/dist/zone-node.js
        date: Sep 10, 2016, 9:04 AM PDT
        line: 664
        code: `var timers = require('timers');`
      https://github.com/angular/zone.js/tree/15d298b877f9da819055dad9d97cd50195c9d9f5/dist/zone-node.js
        date: Sep 10, 2016, 9:05 AM PDT
        line: 670
        code: `var timers = require('timers');`
* workaround?:
    - write a wrapper module named "timers", which exports "timer"
</pre>

**Comment by warren-bank** [comment]
sorry, I should backtrack a bit and mention that this causes any NativeScript app (written with angular 2) to crash in Android (not sure about iOS, not a fan) when the app is launched with a stack trace that includes the following information:

<pre>
Unhandled Exception:
  Error calling module function

Error:
  Failed to find module: "timers", relative to: /app/tns_modules

StackTrace:
  - Frame: function: "require"
    Frame: file: "/data/data/org.nativescript.ExampleProject/files/app/tns_modules/zone.js/dist/zone-node.js", line: 670, column: 14
  - Frame: function: "require"
    Frame: file: "/data/data/org.nativescript.ExampleProject/files/app/tns_modules/nativescript-angular/application.js", line: 2, column: 1
  - Frame: function: "require"
    Frame: file: "/data/data/org.nativescript.ExampleProject/files/app/main.js", line: 3, column: 21
</pre>

**Comment by ross-bradbury** [comment]
I am having the same problem. [nativescript-angular issue #144](https://github.com/NativeScript/nativescript-angular/issues/444) was initially opened for this crash.

(It does also crash on iOS.)

**Comment by VladimirAmiorkov** [comment]
Having the same issue, reverted back to **0.6.17** while this is sorted out.

**Comment by njl07** [comment]
Same issue on `nativescript iOS` application with latest version of `zone.js`.

All is working with `0.6.17` version.

**Comment by DanielJoyce** [comment]
timers is global object in Node, so no reason to import. Breaking on vertx as well.

**Comment by chrillewoodz** [comment]
When is this going to be resolved?

**Comment by JiaLiPassion** [comment]
I will check it.
