### ISSUE TITLE
Fetch API cannot load about:blank. URL scheme "about" is not supported.

### ISSUE THREAD

**Issue by filipesilva** [angular/zone.js#444]
Cross posted from https://github.com/angular/quickstart/issues/219, introduced with `zone.js@0.6.22`.

===
Not sure if this belongs here instead: https://github.com/angular/zone.js

**Repro:**

1. clone
2. npm install
3. npm start

**Google Chrome:** Version 53.0.2785.113 m on Windows10

WORKS in Edge

![image](https://cloud.githubusercontent.com/assets/196044/18526419/d1d6d8b0-7ac0-11e6-8ea3-57ae685551cc.png)

```
zone.js:556 Fetch API cannot load about:blank. URL scheme "about" is not supported.
```

**Comment by iamjohnlong** [comment]
same.. https://github.com/angular/angular-cli/issues/2117

**Comment by jrgleason** [comment]
Is there a temporary solution until this propagates?

**Comment by filipesilva** [comment]
This is a zone.js fix. you can get it right now by doing `npm install `zone.js@0.6.23`.

**Comment by iamjohnlong** [comment]
@mhevery thank you for the quick fix 👍

**Comment by peterheard01** [comment]
thanks
