### ISSUE TITLE
Error when add external Javascript libary

### ISSUE THREAD

**Issue by HenningKuehl** [angular/zone.js#449]
When I add this Javascript libary "https://chayns-res.tobit.com/API/v3.1/js/chayns.min.js", then i get this error: "Uncaught TypeError: Cannot read property 'nodeType' of undefined" 

In the version ^0.5.15 and older, i dont have this problem. But then dont run angular2.

When i dont implement the javascript libary or zone.js, then i dont get this error message.

**Comment by vicb** [comment]
Please re-open with the issue template completed

**Comment by vicb** [comment]
Could you please add a minimal repro a plunker ?

**Comment by jculverwell** [comment]
I have this issue as well.  I am using the Angular-CLI final and https://github.com/Gbuomprisco/ng2-tag-input/. 

I have created a repo here (https://github.com/jculverwell/NgTagsInputWithAngularCLIFinal) where you can see the issue (Uncaught TypeError: Cannot read property 'name' of undefined) 

Error below:

```
zone.js:129 Uncaught TypeError: Cannot read property 'name' of undefined
exports.functionName    @   function-name.ts?6954:7
(anonymous function)    @   transformer.ts?d0de:89
dependencies    @   transformer.ts?d0de:89
(anonymous function)    @   transformer.ts?d0de:145
load    @   transformer.ts?d0de:53
exports.transform   @   transformer.ts?d0de:61
(anonymous function)    @   transformer.ts?d0de:161
transformChildren   @   transformer.ts?d0de:159
(anonymous function)    @   transformer.ts?d0de:180
load    @   transformer.ts?d0de:53
exports.transform   @   transformer.ts?d0de:61
(anonymous function)    @   transformer.ts?d0de:161
transformChildren   @   transformer.ts?d0de:159
(anonymous function)    @   transformer.ts?d0de:180
load    @   transformer.ts?d0de:53
exports.transform   @   transformer.ts?d0de:61
(anonymous function)    @   transformer.ts?d0de:161
transformChildren   @   transformer.ts?d0de:159
(anonymous function)    @   transformer.ts?d0de:180
load    @   transformer.ts?d0de:53
exports.transform   @   transformer.ts?d0de:61
exports.transformToTree @   mutable-tree-factory.ts?f7a1:12
(anonymous function)    @   mutable-tree-factory.ts?f7a1:40
exports.createTreeFromElements  @   mutable-tree-factory.ts?f7a1:40
updateTree  @   backend.ts:65
update  @   backend.ts:90
(anonymous function)    @   backend.ts:101
SafeSubscriber.__tryOrUnsub @   Subscriber.js?215e:223
SafeSubscriber.next @   Subscriber.js?215e:172
Subscriber._next    @   Subscriber.js?215e:125
Subscriber.next @   Subscriber.js?215e:89
DebounceTimeSubscriber.debouncedNext    @   debounceTime.js?500c:98
dispatchNext    @   debounceTime.js?500c:114
AsyncAction._execute    @   AsyncAction.js?e414:111
AsyncAction.execute @   AsyncAction.js?e414:86
AsyncScheduler.flush    @   AsyncScheduler.js?ae69:36
ZoneDelegate.invokeTask @   zone.js:225
Zone.runTask    @   zone.js:125
ZoneTask.invoke @   zone.js:293
```

**Comment by vicb** [comment]
Please describe how you created the project and what lib have been added

**Comment by HennigKuehl** [comment]
https://plnkr.co/edit/FImZRf?p=preview

Here is the plunker of my project, with the issue

**Comment by jakubmal** [comment]
Would really love to help but:
- when I open the plunkr you posted - application is not loading, and there's no error in console
- when I opened the repository - `./node_modules/.bin/ng serve` resulted in configuration errors

**Comment by jculverwell** [comment]
Hi Guys,

I create my project using the angular-cli

```
ng new NgTagsInputWithAngularCLIFinal
```

Then I added in NgTagsInput by adding it to the package.json

```
  "ng2-tag-input": "0.3.7",
```

This is still not working in angular-cli beta 17.

Welcome your thoughts
