### ISSUE TITLE
Create unique ID for each zone.

### ISSUE THREAD

**Issue by mhevery** [angular/zone.js#45]
One of the reasons why debugging zones is hard is that it is hard to quickly tell if you have the same zone. I think it would be useful to append a unique `id` to each zone. Looking at the `id` would than give you the path.

`123>4324>angular>root`

It would probably mean that we could have a global counter. and the either expect the caller to supply the zone name in the fork or use the global counter to create o new `id`

**Comment by btford** [comment]
:+1:

**Comment by mhevery** [comment]
What about the ability to name zones during `fork`? I think that would be useful. Also I think we should concatenate the names, so that we could see something like this: `123>4324>angular>root`. What do you think?

**Comment by btford** [comment]
Where does `123>4324>angular>root` get used/shown? Should this just be part of debug zones #48 ? Or in long stacktraces? Or this is something you think should always exist on all zones?

**Comment by mhevery** [comment]
I would imagine that it would be in all zones. Every time a child zone is created this would get prefixed with a new ID. So you could easily see how deep the zones are and how you got there.
