### ISSUE TITLE
get stdlib typings with --lib

### ISSUE THREAD

**Issue by alexeagle** [angular/zone.js#450]
Especially the dependency on `es6-promise` from DT, which leaks the `Thenable` type into the .d.ts output. This should be `PromiseLike` instead, for compatibility with other code that uses TS types.

**Comment by mhevery** [comment]
I am confused. This is exactly how it is set up. Is this the right repo? Old Code???

**Comment by alexeagle** [comment]
You are right, we just need to sync it to g3
