### ISSUE TITLE
Zone.js browser bundle pollutes global namespace

### ISSUE THREAD

**Issue by ggoodman** [angular/zone.js#456]
The `browser.ts` file (https://github.com/angular/zone.js/blob/master/lib/browser/browser.ts) is not being bundled inside any closure, resulting in all of its top-level functions and variables becoming globals.

This was discovered because this behaviour was breaking Plunker's preview by overriding `window.name` to `alert`. Down the rabbit hole we go and find ourselves here.

**Comment by juliemr** [comment]
We're also seeing this issue causing problems with Protractor since we rely on window.name there as well.

**Comment by juliemr** [comment]
See also https://github.com/angular/zone.js/issues/452

**Comment by ggoodman** [comment]
@juliemr this is, indeed a duplicate. Sorry about that. Feel free to close one and track it one place or the other.

**Comment by juliemr** [comment]
I think this one is more general, I'll close the other.

**Comment by juliemr** [comment]
I'm pretty sure this was due to the swap from webpack to rollup for bundling. The suggested fix is to go back to having everything execute in a closure, I'm trying to figure out how to do that with rollup.

**Comment by juliemr** [comment]
This is now fixed in the latest release.

**Comment by ocombe** [comment]
Awesome, this also fixed my problem: I had an error message of `ERROR in [default] C:\[...]\node_modules\typescript\lib\lib.d.ts:18448:14 Cannot redeclare block-scoped variable 'name'. `, I updated and the error disappeared :)
