### ISSUE TITLE
Error: Missing: SyncTestZoneSpec

### ISSUE THREAD

**Issue by jorawarsingh** [angular/zone.js#464]
I have this issue when i run test only, running application works fine. I googled bit about it and saw some other posts regarding this. some has suggested that downgrade can resolve this issue but then my app break down and i get other errors. I'm using 0.6.23 with angular2.0.0 final.

**Comment by happyvig** [comment]
Same issue here.

**Comment by vicb** [comment]
We can not help without knowing your setup.
Please re-open with an accurate description of your env and a repro

**Comment by jorawarsingh** [comment]
For work around right now use "zone.js": "~0.6.17"

**Comment by happyvig** [comment]
Thank you.

**Comment by jcamus** [comment]
I have the same problem here...
Error: Missing: SyncTestZoneSpec
at c:/oldGen/TransfolioWeb/client/node_modules/zone.js/dist/jasmine-patch.js:32
No sorry... same problem with "zone.js": "~0.6.17"

**Comment by rukeshj** [comment]
Hi @jorawarsingh , @jcamus  , @happyvig : Any solution for this issue : 

I use the following config 
```
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "zone.js": "0.6.25"
```

Some suggestion will be of great help .

**Comment by jorawarsingh** [comment]
Hi @rukeshj  these dependencies are working fine for my in all cases when i use ` "zone.js": "~0.6.17"`
