### ISSUE TITLE
NPE when calling zone.getLongStackTrace();

### ISSUE THREAD

**Issue by mhevery** [angular/zone.js#47]
When calling `zone.getLongStackTrace()` from console (during debug). The method throws an NPE because exception is not specified. It would be useful to make the exception optional so that it would be easy to query the current location.

The issue is in [long-stack-trace-zone.js#L50](https://github.com/angular/zone.js/blob/214f532097082a0a6659d98741378c7a6110467e/long-stack-trace-zone.js#L50)

A simple check to ignore `null` `exception` should suffice.

**Comment by btford** [comment]
:+1:
