### ISSUE TITLE
HTTPS security is compromised by null in Edge

### ISSUE THREAD

**Issue by RaleS** [angular/zone.js#476]
SEC7111: HTTPS security is compromised by null
The error is logged in Edge console window when running zone.js 0.6.25

https://jsfiddle.net/g0mzz515/

**Comment by vicb** [comment]
What is your setup ? Does this happen only in jsfiddle ?

**Comment by RaleS** [comment]
@vicb Not sure why do you ask about the setup. Here is another example with zone.js 0.6.25

https://nspeubk.blob.core.windows.net/temp/zonejsedge.html

**Comment by vicb** [comment]
I should have been clearer, what's Edge version do you use ?
Thanks

**Comment by RaleS** [comment]
It's EdgeHTML 14.14393, Edge 38.14393.0.0, but it also fails in preview Edge 39.14936.1000.0, EdgeHTML 14.14936. Can you reproduce it?

**Comment by born2net** [comment]
same issue here...

**Comment by patrickmichalina** [comment]
Happening here too in an Angular 2 app..

**Comment by JiaLiPassion** [comment]
I did a little debug, I think it is related to fetch promise patch, maybe PR #622 will fix this one.

**Comment by MichaelBuerge** [comment]
Author of PR #622 here. I have a little demo Angular app live that includes said PR (+lots of dev output): https://orino.ch/test/zone.js-fetch/
I'm not seeing the security error anymore there, so it seems that #622 indeed addresses this too.

**Comment by antonyRoberts** [comment]
@JiaLiPassion Can we get this pull request merged?

**Comment by JiaLiPassion** [comment]
@antonyRoberts , sorry I don't have the permission to merge pull request, I think the PR is under review.

**Comment by MichaelBuerge** [comment]
#622
