### ISSUE TITLE
How to work with angular2 app in the portlets?

### ISSUE THREAD

**Issue by furydam** [angular/zone.js#477]
I am trying to use angular2 app in a Liferay portlet. When I put portlet on the page, app is initialized properly, but when I go to another route and return back I have an error Zone already loaded. Maybe, I should load zone.js at once separately without angular app builded with Angular CLI. 

How can I solve this issue?

**Comment by dsumer** [comment]
Remove zone.js from your bundle and find a way to import it on your site in the header (via theme or hook)
