### ISSUE TITLE
How to bundle Zone with Rollup.js in Angular 2 app

### ISSUE THREAD

**Issue by RoxKilly** [angular/zone.js#480]
I'm writing an `Angular 2` app in `typescript 2` and trying to follow [Angular's recommendation](https://angular.io/docs/ts/latest/cookbook/aot-compiler.html#!#tree-shaking) for bundling with Rollup.js

The guide (linked above) only shows how to include `RxJs`.  How can we include this library in the bundle?

**rollup.config.js**

```
    plugins: [
        nodeResolve({jsnext: true, module: true}),
        commonjs({
            include: [ 'node_modules/rxjs/**',
                           'node_modules/zone.js/dist/**/*' ],
        })
    ]
```

During bundling, Rollup throws 4 errors:

> No name was provided for external module 'events' in options.globals – guessing 'events'
> No name was provided for external module 'fs' in options.globals – guessing 'fs'
> No name was provided for external module 'timers' in options.globals – guessing 'timers'
> No name was provided for external module 'crypto' in options.globals – guessing 'crypto'

In the browser, the App fails to run with error: "_events is not defined_"

**Comment by robianmcd** [comment]
You shouldn't need to include zone.js as a commonjs module. It should work as long as it is installed in node_modules. What do you get if you don't include it as a commonjs module?

**Comment by snaikaw** [comment]
When running the AOT build.js, it gives an error "Uncaught ReferenceError: require is not defined".
Looking at the build.js code file, it is the packed zone.js file. See the line 3 below:

`        var V = "set"
          , L = "object" == typeof window && window || "object" == typeof self && self || global
          , H = require("timers");       <<-----
        f(H, V, "clear", "Timeout"),
        f(H, V, "clear", "Interval"),
        f(H, V, "clear", "Immediate"),
        global.setTimeout !== H.setTimeout && (f(L, V, "clear", "Timeout"),
        f(L, V, "clear", "Interval"),
        f(L, V, "clear", "Immediate")),`

It seems to me that we need to include zone.js to handle the above issue. I also tried setting "preferBuiltins: false" as suggested in the warning message by Rollup, before it fails. But no effect.
