### ISSUE TITLE
IE8 expected identifier error

### ISSUE THREAD

**Issue by loliparra80** [angular/zone.js#482]
When I try to open my website in a internet explorer ie8, doesn't work. While in IE11 I have no problems.

When I debug the error is: "Expected identifier" zone.js, line 540 character 36. It seems like don't recognize the "catch" on "ZoneAwarePromise.prototype.catch = function....".

What can  I do?
Thanks.

**Comment by gdi2290** [comment]
I don't think zone.js supports IE8

**Comment by SergeyMell** [comment]
I had the same issue on IE9. However, Angular states that it supports IE9: https://angular.io/guide/browser-support
