### ISSUE TITLE
Zone.js higher than 0.6.21 breaks angular-universal https calls

### ISSUE THREAD

**Issue by AlexYankee** [angular/zone.js#484]
Calls to https:// end up with error code: ECONNRESET, as described in https://github.com/angular/universal-starter/issues/172

**Comment by JiaLiPassion** [comment]
This is because the EventEmitter.once is not handled properly, I have create a pull request, you can use my repository for test, https://github.com/JiaLiPassion/zone.js.git.

**Comment by John0x** [comment]
Any updates on this?

**Comment by JiaLiPassion** [comment]
This has been fixed, you can use the latest zone.js 0.7.1 to test.
