### ISSUE TITLE
when will zone.js 0.6.26 be released?

### ISSUE THREAD

**Issue by Saviio** [angular/zone.js#488]
ATT

Because I found a critical issue was resolved in https://github.com/angular/zone.js/pull/451, and we met the same issue in safari.

**Comment by bisubus** [comment]
Fortunately, there's no need to hurry the things up, because we can always refer to the package by commit hash until the next release, `"zone.js": "angular/zone.js#16be7f916342dae6b2f5fb6c5dcaa411dffe8fe4"`.

**Comment by Saviio** [comment]
@bisubus it won't work, because the entry of zone.js is `dist/zone.js` (built from ts to js), if I refer to the specific commit I have to change my bundle strategy and build zone.js separately.

**Comment by KrauseStefan** [comment]
zone.js 0.6.26 has been release, but for some reason this is not reflected in the releases here on github.
It is however available on npm: https://www.npmjs.com/package/zone.js
