### ISSUE TITLE
npm error: npm ERR! invalid: zone.js@0.6.26

### ISSUE THREAD

**Issue by russelltrafford** [angular/zone.js#490]
I keep receiving the following `invalid` error when I try to install zone.js:

Command:
`$ npm list --depth=0`

> └── zone.js@0.6.26 invalid
> 
> npm ERR! invalid: zone.js@0.6.26 /Users/my-username/my-repo/node_modules/zone.js

My package.json shows:
`"zone.js": "~0.6.17"` in `dependancies` section

I have tried everything from removing zone.js and doing an `npm install` with my package.json (zone.js version ~0.6.17) and even putting zone.js : "*" which then installs 0.6.26 and still shows invalid.

Because the github repo shows latest version as `.25` but npm shows latest version as `.26`, I also tried setting it manually to `zone.js : "0.6.25"` but this then shows the error as the same, but with the `.25` version:

> `npm ERR! invalid: zone.js@0.6.25 /Users/my-username/my-repo/node_modules/zone.js`

I have also removed my node_modules folder completely and done `npm cache clean`
Nothing seems to get rid of the `invalid` error

System: Macbook Pro 15" running OSX El Capitan v 10.11.6
npm version (using nvm): v6.3.1, but also tried v6.9.0

**Comment by PCASME** [comment]
+1
