### ISSUE TITLE
Error: Can't set headers after they are sent.

### ISSUE THREAD

**Issue by Hongbo-Miao** [angular/zone.js#491]
I put the error log here, since it is a little bit long
http://pastie.org/10945816

The reproduce codes app is here
https://github.com/Hongbo-Miao/zonejs-bug

It uses universal-starter, just added **socket.io**, see in [second commit](https://github.com/Hongbo-Miao/zonejs-bug/commit/216a69e589c31f8d9f9157f3be0c57eae111433f).

To see the error, `npm start` and open page [http://localhost:3000/](http://localhost:3000/).

The app works with zone.js 0.6.21, and it shows the error starts from 0.6.22 and also shows in latest 0.6.26

**Comment by JiaLiPassion** [comment]
I made a pull request to fix this issue, for now you can change your package.json to make zone.js reference to https://github.com/JiaLiPassion/zone.js.git to see the result.

**Comment by MrCroft** [comment]
This still occurs in `0.8.20`.
I can't believe how old this issue is :)

My scenario, I have an SSR Response Service:
```
import { Injectable, Inject } from '@angular/core';

import { Response } from 'express';
import { RESPONSE } from '@nguniversal/express-engine';

@Injectable()
export class SsrResponseService {
  constructor(@Inject(RESPONSE) private response: Response) {}

  redirect(url: string, code?: number) {
    if (!!code) {
      return this.response.redirect(code, url);
    } else {
      return this.response.redirect(url);
    }
  }
}
```

Then, in a component, based on some logic, I might need to redirect the user:
```
this.responseService.redirect('/some-other-url', 301);
```

The redirect works, but the server logs:
```
Unhandled Promise rejection: Can't set headers after they are sent. ; 
Zone: <root> ; Task: Promise.then ; Value: Error: Can't set headers after they are sent.
```

Full stack trace [here](https://gist.github.com/MrCroft/c8a659567a3b248744b62a7cc04f061d)

Any ETA on this fix?

**Comment by mike-suggitt** [comment]
Bump - same here

**Comment by JiaLiPassion** [comment]
@mike-suggitt , @MrCroft , I don't think the `Can't set headers after they are sent` is `zone.js` error, it is just `express http response` error.

**Comment by JiaLiPassion** [comment]
@MrCroft , sorry I am not familiar with `SSR`, you can ask at `stackoverflow`.

**Comment by MrCroft** [comment]
@JiaLiPassion actually, I remember that the headers were in fact being set. And the app worked fine. But I was just seeing that error in the log and it mentioned zone.js. Weird... Haven't been doing SSR recently.

**Comment by JiaLiPassion** [comment]
@MrCroft, yeah, almost all the errors in `angular` will mention `zone.js`, so really very little error is really `zone.js` error.
