### ISSUE TITLE
Cannot read property 'scheduleEventTask' of undefined

### ISSUE THREAD

**Issue by arunakshi** [angular/zone.js#496]
I am new to Angular2. I am developing Angular2 app for Sharepoint. I am getting the following error: "Cannot read property 'scheduleEventTask' of undefined" after I load all my JS files. When I debug in zone.js, I see that at first zone is not undefined and later there an event in aspnetForm with eventType: submit and then I get the Zone.Current as undefined. Does anyone have the same issue?

**Comment by arunakshi** [comment]
I solved this problem. I referenced the zone.js file at the end of my page and removed the cleared the Zone from sharepoint with the following: <script>
	window.Zone=null;
</script>
<script src="../node_modules/zone.js/dist/zone.js"></script>

**Comment by zztimy** [comment]
I have the same problem (only I am trying to integrate ASP.NET Webforms with Angular) and you're solution worked. However, I am wondering if this is a hack or a good way of fixing this issue? I don't know much about angular or zone.js, so if this sounds like a stupid question please excuse me :)
