### ISSUE TITLE
.on() does not return EventEmitter instance.

### ISSUE THREAD

**Issue by tomdegoede** [angular/zone.js#508]
Version: 0.6.26
platform: Node

When using Zone.js in combination with the ws package (that uses zlib) an error is thrown on [ws#L267](https://github.com/websockets/ws/blob/master/lib/PerMessageDeflate.js#L267) and [ws#L319](https://github.com/websockets/ws/blob/master/lib/PerMessageDeflate.js#L319) due to on() returning `undefined` instead of the deflate/inflate instance.

**Comment by JiaLiPassion** [comment]
I think it is fixed in https://github.com/angular/zone.js/commit/c5130a614a796a047912326c2a0ad4b590181537, you can try the newest dev version.

**Comment by tomdegoede** [comment]
Works, thanks
