### ISSUE TITLE
bug: RxJS doesn't cause hooks to fire

### ISSUE THREAD

**Issue by btford** [angular/zone.js#51]
This needs some investigation.

Currently RxJS doesn't cause zone hooks to fire. @vsavkin gave me this example: https://github.com/vsavkin/angular/commit/2d0a849792d2256cf5912932674898390cd69441

I think this is re relevant section of the implementation – https://github.com/Reactive-Extensions/RxJS/blob/47cbafa678c0e4f66c7307c8b8ecaab3407444fb/src/core/concurrency/timeoutscheduler.js

**Comment by bman654** [comment]
Rx is a strange beast.  It is often unclear what zone an RxJs callback should be running on.  The zone that was active at the time the callback was defined?  The zone that was active when the observable is actually subscribed?  Different methods in the chain might want something different.

The "Rx way" of handling this is to use their `Scheduler` abstraction.  Which means implementing a `ZoneScheduler` then using it to explicitly define which zone you want a piece of the chain to run within:

```javascript

// Example 1
// immediate scheduler that schedules work on the provided zone
var immediate = new ZoneScheduler(zone); 

// Who knows what someObservable is, but run our subscription
// on the current zone
someObservable.observeOn(immediate).subscribe(...);
   
// Example 2
// timeoutscheduler that schedules work on the provided zone
var timeout = new ZoneScheduler(zone, Rx.Scheduler.timeout);

Rx.Observable.timer(42, timeout).subscribe(...);

// Example 3
var scheduler1 = new ZoneScheduler(zone1, Rx.Scheduler.currentThread);
var scheduler2 = new ZoneScheduler(zone2, Rx.Scheduler.requestAnimationFrame);

// do some work zoneless
// do some part of the work on zone1
// do remainder of work on zone2 inside animation frames
Rx.Observable
    .timer(42, Rx.Scheduler.timeout) // zoneless
    .flatMap(function () { return ... })
    .observeOn(scheduler1)
    .map(function (value) { ... }) // runs on zone1
    .observeOn(scheduler2)
    .subscribe(...) // runs on zone2
```

**Comment by btford** [comment]
Thanks for the tip, @bman654!

**Comment by mhevery** [comment]
The callbacks should always run in the same zone as when it was registered, regardless of what scheduler is running.

**Comment by jeffbcross** [comment]
This is no longer an issue after updating to `@reactivex/rxjs`.

I think the issue @vsavkin was experiencing was due to RxJS assigning global `setTimeout` to a local variable before the zone had a chance to patch it. At least, this is the cause of issues I had with original RxJS.

Issue angular/angular#4603 is tracking the proposal to implement a zone scheduler.

**Comment by errorx666** [comment]
I implemented a zone scheduler for Angular here: https://www.npmjs.com/package/ngx-zone-scheduler
