### ISSUE TITLE
Configuring Root zone

### ISSUE THREAD

**Issue by jahtalab** [angular/zone.js#513]
Is there a way to configure `onScheduleTask` and `onInvokeTask` on the root zone?
Or other interceptions for that matter?

**Comment by JiaLiPassion** [comment]
I don't know why zone was designed to not have a rootZoneSpec, but in my understanding, if there is a rootZoneSpec just like your PR #521, everybody can modify the rootZoneSpec so the whole system may have unstable behavior. 

for example, 

you app have 2 modules,
moduleA will set rootZoneSpec.onHandleError to output log, moduleB will set rootZoneSpec.onHandleError to do other stuffs. That will cause the system in a unpredictable state.
I think it's the one reason that why we can't access current zoneSpec.

**Comment by jahtalab** [comment]
I think this feature expands zone.js' use cases, like this one #422 , 
In my case I need to be notified about every event for performance analysis, and I can't run the whole page inside a zone.

Also, even without this change there's the possibility of monkey patching root zone, (or even monkey patching browser api directly for that matter).

In regards to going into an unpredictable state, I think different modules can modify browser API however they want. I don't think this feature provides more than what is already possible in browsers.

**Comment by JiaLiPassion** [comment]
yeah, I agree with you, in fact , I need such kind of feature too. I have a suggestion that should we remove rootZoneSpec from global after the rootZone has been created?

In your PR, the code like this, after rootZone created, delete it from global so no other code can access it from outside expect who created it.

```javascript
 const symbolRootZoneSpec = '__rootZoneSpec__'
 var rootZone: Zone = new Zone(null, null);
 if (global[symbolRootZoneSpec]) {
   rootZone = <Zone>rootZone.fork(global[symbolRootZoneSpec]);
   delete global[symbolRootZoneSpec];
 }
 +
```

**Comment by jahtalab** [comment]
@JiaLiPassion , Good call 👍  , Done.

**Comment by mhevery** [comment]
Sorry, but this is by design. RootZone should be indistinguishable for no zone at all. This requirement is here so that if we standardize the Zones in TC39, the browser vendors will not have to pay the cost for all of the applications. All zones must be entered explicitly.

**Comment by cedvdb** [comment]
I've somewhat the same use case as you had @jahtalab Could you clarify your code however ? If I understand correctly it checks if the user has already specified '__rootZoneSpec__' and if so make that spec the new spec for the root zone (thus allowing us to have onInvokeTask.
