### ISSUE TITLE
Incompatabile with nodejs 6.9.1: makeZoneAwareRemoveAllListeners addes 'undefined' arguments to real removeAllListeners calls

### ISSUE THREAD

**Issue by KrauseStefan** [angular/zone.js#518]
zone.js wrappes the removeAllListeners call from node.js but breaks compatibility with the real version.

This happens because zone.js parsed undefined arguments to the real call when none should be.
This causes the line highlighted below to fail since node.js tests on arguments.length

link to the faulting line in utils.ts:
https://github.com/angular/zone.js/blob/master/lib/common/utils.ts#L293

snippet form events.js in node 6.9.1
```javascript
// ...
EventEmitter.prototype.removeAllListeners =
    function removeAllListeners(type) {
      var listeners, events;

      events = this._events;
      if (!events)
        return this;

      // not listening for removeListener, no need to emit
      if (!events.removeListener) {
        if (arguments.length === 0) { // <--- length will always be 2, since undefined is always passed
          this._events = new EventHandlers();
          this._eventsCount = 0;
        } else if (events[type]) {
          if (--this._eventsCount === 0)
            this._events = new EventHandlers();
          else
            delete events[type];
        }
        return this;
      }
// ...
```

The function is used by `xml2j`s to remove all event listeners by calling:
`removeAllListeners()` without arguments

**Comment by JiaLiPassion** [comment]
Thank you for finding the bug, I will make a PR to fix this issue.

**Comment by KrauseStefan** [comment]
No problem, I guess we are quite a few people who needs this to work properly in a node.js env, I'll have a look through your changes

**Comment by JiaLiPassion** [comment]
It has been fixed, you can use the newest version to test.

**Comment by KrauseStefan** [comment]
I finally got around to verify this one, yes this issue is gone, but I have a new one now. Will create a new issue for this.
