### ISSUE TITLE
function consoleError is causing a runtime error

### ISSUE THREAD

**Issue by realtebo** [angular/zone.js#519]
[This function](https://github.com/angular/zone.js/blob/master/dist/zone.js#L389-L395) in [`zone.js` file](https://github.com/angular/zone.js/blob/master/dist/zone.js) is causing a runtime error

```
function consoleError(e) {
        var rejection = e && e.rejection;
        if (rejection) {
            console.error('Unhandled Promise rejection:', rejection instanceof Error ? rejection.message : rejection, '; Zone:', e.zone.name, '; Task:', e.task && e.task.source, '; Value:', rejection, rejection instanceof Error ? rejection.stack : undefined);
        }
        console.error(e);
}
```

The problematic row is

```
var rejection = e && e.rejection;
```

I've no idea of what is causing this but I got this error on Firefox 50

> Error: Permission denied to access property "rejection"

So I don't know the cause because your function is hiding the original error causing a new one.

**Comment by JiaLiPassion** [comment]
can't reproduce, I tried some simple test case in FF50, can you post a test code to describe your case?

**Comment by realtebo** [comment]
The specific case is triggerred from a missing declaration for service in the app.module.ts file as 'provider'.

Ok, this is MY error, as a developer, but I think it's an issue about your .js code because it's not right to generate an error when trying to explain an error to the developer. right?

Thanks for your excellent work.

**Comment by JiaLiPassion** [comment]
Yeah, you are right, if you could post your repository, I would like to look into it and find out why zone.js report such error.

**Comment by realtebo** [comment]
Sorry, I can't, but it's VERY VERY simply to reproduce the error.

- create a new angular 2 project
- create a 'doing nothing' service
- import it into your app component
- inject it into app constructor
- import it into app module
- DO NOT declare as provider in `@NgModule` declarator
- ng serve 

The app will build without any warning (and is is a fault of ng2 compiler, i think), and when you look at webapp at localhost:4200, you'll see in the console the error i'm talking about.

The SOURCE error is not have declared properly the service into 'providers' array of the NgModule.

But what I as developer see is 

    Error: Permission denied to access property "rejection"

**Comment by JiaLiPassion** [comment]
ok, I'll check it later, thank you.

**Comment by JiaLiPassion** [comment]
I tried the step above, I declare a service and do not declare provider, the error will be like following 

> Error: Uncaught (in promise): Error: No provider for TestService!(…)consoleError @ zone.js:390

So could you provide your package.json?

**Comment by TO-mkegler** [comment]
Could this be a browser specific issue? I had the same errors (Error: Permission denied to access property "rejection"). Just now I was starting my app in chrome instead of firefox for the first time and I get a "real" error message ("Cannot read property 'length' of null", in this case). So maybe you could look into that?!

**Comment by JiaLiPassion** [comment]
Still can't reproduce, if you guys can provide a repo or plunker to reproduce it, I can look into it, thank you.

**Comment by realtebo** [comment]
Here it is: https://plnkr.co/PEtwUxCEsVfuVrwCKZBT

When runned in firefox, i got in the console the error "Error: Permission denied to access property "rejection""

When runned on chrome I ggot a lot of more descriptive infos

**Comment by JiaLiPassion** [comment]
@realtebo I use your plunker, the error is "No provider for TestService", my firefox version is 50.

**Comment by realtebo** [comment]
Now I undestand !

I'm using Firebug, as you can see. If I watch directly the console, I can see the 'right' error in the native console. (Ctrl + Shift + k) but not in Google Chrome. 

So I close this issue because is not related to you
