### ISSUE TITLE
`registerElement` should support callbacks coming from deep prototype chains

### ISSUE THREAD

**Issue by rkirov** [angular/zone.js#52]
The following line:

https://github.com/angular/zone.js/blob/26a4dc27f781afb6e6dd1258a15cb8c0840c706d/zone.js#L663

Checks `if (opts.prototype[callback])` and then uses `Object.getOwnPropertyDescriptor(opts.prototype, callback)` to retrieve it. If the callback comes from the prototype chain we cannot use `getOwnPropertyDescriptor`.

**Comment by btford** [comment]
+1

**Comment by tkhemani** [comment]
Hi,
I tried to run the "youtube-app" demo, but it's failing at this line. I see that you've mentioned this: 
## need to be patched
- zone.js
	- https://github.com/angular/zone.js/issues/52 (need to patch locally in node_modules/zone.js)
- angular 2
	- https://github.com/angular/angular/issues/776 (need to patch locally)

Can you please share the patch...

**Comment by kingcody** [comment]
I encountered this issue as well (when dealing with polymer elements).

@tkhemani, its not very elegant or heavily tested but here was my [solution](https://github.com/kingcody/zone.js/commit/49fd5bbc3032b2b1d4428938c09aa0a6c081f8b8).

**Comment by tkhemani** [comment]
@kingcody . Thanks, I got the youtube-app working after @rkirov shared the patches. But i'm still not able to get a simple [polumer button](https://github.com/Polymer/paper-button) working inside an angular 2.0 component directive. Can you possibly try it out.

**Comment by kingcody** [comment]
@tkhemani Working in FF, but not in Chrome.

**Comment by tkhemani** [comment]
@kingcody, are you saying u were able to  get a [polymer button](https://github.com/Polymer/paper-button) working inside an angular 2.0 component directive? Can you share the code.

**Comment by JoshAntBrown** [comment]
I'm having this issue too, again like @kingcody when dealing with polymer elements but this time the Google Web Component ones. I did see a pull request at https://github.com/angular/zone.js/pull/31 which  looks like it might have tried to fix the problem but implementing their code into my project stopped the console error but still didn't render the component. I tried the same solution as @kingcody as well but same result as the pull request.

**Comment by jianliao** [comment]
@JoshAntBrown Yes, there is no such issue in FF, but it seems to me the property binding like this 
```
[hidden]="!active" 
``` 
does not work. The reason that customer element does not work in Chrome is probably due to https://github.com/angular/angular/issues/1442

**Comment by justinfagnani** [comment]
Yes, you need a fix for both the zone.js and Angular issues before custom elements work. I have all this working locally, but don't have time to put together a tested PR.

**Comment by vicb** [comment]
@justinfagnani you can send me "some" code and I'll try to clean and PR if you like
