### ISSUE TITLE
window.addEventListener is undefined in IE right after opening new window

### ISSUE THREAD

**Issue by marcovdb** [angular/zone.js#535]
**I'm submitting a ...**  (check one with "x")
```
[*] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In one part of my application I open up a new window using window.open, but I want to attach some code to the window's beforeclose event (because I need to refresh some data on the page). Window.open returns a reference to the window object, but in IE if I access the reference right after opening the window the addEventListener method is undefined. If I wrap it in a short timeout it's usually OK, but this feels hackish an unreliable to me.

My current guess it's because Zone.js monkey-patches the addEventListener function and it's taking some time in IE.

**Expected behavior**
window.open should return a complete reference to the window object, with all of its methods intact.

**Minimal reproduction of the problem with instructions**

Check the following Plunker in IE and in Chrome (or any other browser, really) and observe the difference.
https://plnkr.co/edit/FbvnWDdaN5aheFZG7PDC?p=preview

**What is the motivation / use case for changing the behavior?**
We should be able to reliably access a newly opened window's object.

**Please tell us about your environment:**
* **Browser:** Internet Explorer 11

**Comment by JiaLiPassion** [comment]
I don't think it is a zone.js issue, the problem only occurs in plunker, in local it is ok, and in plunker, if you setimeout a little more longer, the listener1 will be ok, it seems window.open in plunker will return a not fully loaded window object, after 500ms, the window object is ok.

**Comment by marcovdb** [comment]
I think you're right. I had tested it locally without Zone.js so assumed "Zone.js issue", but locally even with Zone.js the problem doesn't occur. Apparently it just takes IE a while to get the new window (when the content is loaded from a remote server) in a state where events can be added. Weird that no one else would run into this issue, though. I spent tons of time googling it but haven't found any issues like this.

In any case, I came up with this:

```  function openWindow() {
    var newWin = window.open('foo.html');
    var newWinInit = false;
    while (newWinInit === false) {
      if (typeof newWin.addEventListener === 'function') {
        newWinInit = true;
      }
    }
    newWin.addEventListener('beforeunload', function (){
      console.log('window closed');
    });
  }
```
And it fixes my issue. So, case closed.
