### ISSUE TITLE
Notifications API is not covered by Zone.js

### ISSUE THREAD

**Issue by marcovdb** [angular/zone.js#536]
The [Notifications API](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API) is not covered by Zone.js - meaning, if I initiate a notification from a zone and attach an function to the notification's onclick event, this function is not executed in the current zone.

I originally opened this as an Angular issue (https://github.com/angular/angular/issues/12624) but I was asked to reopen it here, so here goes.

**Comment by JiaLiPassion** [comment]
Sure, several other apis are not in zone now, I would like to make a pr to implement it.
