### ISSUE TITLE
Wrong currentZone value inside of onInvoke hook

### ISSUE THREAD

**Issue by davidich** [angular/zone.js#538]
Hi, there.

According to comments I found in zone.ts file, onInvoke hook has to receive currentZone as second parameter:

`/**
   * Allows interception of the callback invocation.
   *
   * @param parentZoneDelegate Delegate which performs the parent [ZoneSpec] operation.
   * @param currentZone The current [Zone] where the current interceptor has beed declared.
   * @param targetZone The [Zone] which originally received the request.
   * @param delegate The argument passed into the `run` method.
   * @param applyThis The argument passed into the `run` method.
   * @param applyArgs The argument passed into the `run` method.
   * @param source The argument passed into the `run` method.
   */
  onInvoke?:
      (parentZoneDelegate: ZoneDelegate, currentZone: Zone, targetZone: Zone, delegate: Function,
       applyThis: any, applyArgs: any[], source: string) => any;`

I created an interceptZone, which I suppose should be passed as current zone to my hook method. But for some reason I receive the same value as targetZone.
I created a demo [HERE](http://plnkr.co/edit/iwdW5x3EURKopuwtiX4s?p=preview), which depicts the described problem.

Am I missing something?

Thanks,
Oleksiy

**Comment by JiaLiPassion** [comment]
It seems a bug when currentZoneSpec has not onInvoke callback or maybe zone.js designed that way, I'll confirm it, thanks for posting the issue.

**Comment by JiaLiPassion** [comment]
close for fixed
