### ISSUE TITLE
It looks like Safari isn't able to patch at all with upstream fixes

### ISSUE THREAD

**Issue by caitp** [angular/zone.js#55]
Been working hard on fixing all of the syntax errors and getting the transpiler to produce valid code, and it looks like it's just about there --- however, there seem to be some issues with (largely) Zone.js at this point. @btford you're probably better at figuring out where these issues are coming from? But to me it looks like Safari isn't able to be patched at all

![screen shot 2015-03-02 at 12 36 02 pm](https://cloud.githubusercontent.com/assets/2294695/6446382/caed11ca-c0d8-11e4-8600-3b35d9e81436.png)

**Comment by caitp** [comment]
hmm, actually I think this is all broken in the angular2 repo, probably not a Zone issue... will keep this open while I investigate though

**Comment by caitp** [comment]
It's definitely not a zone issue, seems to be something broken in the angular compiler with non-chrome browsers =|

**Comment by btford** [comment]
yay/boo
