### ISSUE TITLE
Wrong zone is returned as current inside async.js callback

### ISSUE THREAD

**Issue by krassx** [angular/zone.js#561]
I am trying to use Zone.js in my NodeJS Express app and facing an issue with wrong zone being returned as current when requested inside async.js callback. I mostly use async.series and in some cases async.waterfall and both are affected. THe only thing that helps is wrapping callbacks with `Zone.current.wrap()`, which is definitely neither elegant nor productive way as one could easily miss that wrapper and consequently bad things may happen.

Is there any other way to make Zone.current return correct zone within async.js callbacks?

**Comment by JiaLiPassion** [comment]
Could you provide sample code or plunker to describe the issue?

**Comment by krassx** [comment]
After a more precise look and dozens of checks I found out that context is lost in mongodb callbacks.

**Comment by krassx** [comment]
Will create a code sample to demonstrate this issue

**Comment by JiaLiPassion** [comment]
close for no reproduce.
