### ISSUE TITLE
fake-async-test is broken for setTimeout(f, stringDelay)

### ISSUE THREAD

**Issue by akshaal** [angular/zone.js#563]
core-js uses the following signature for setTimeout:
`function setTimeout(handler: any, timeout?: any, ...args: any[]): number;`

fake-async-test assumes that delay is always numeric:
`scheduleFunction(cb: Function, delay: number, args: any[] = [], id: number = -1): number {`

If, for example, you have a code like:
`setTimeout(() => setTimeout(() => console.log("Hello world"), 0), "2000")`
everything works ok in browsers. You get your "Hello world" in 2000ms. But it doesn't work in tests. This simple test fails:
```
    it(`blah`, fakeAsync(() => {
        let gotIt = false;
        setTimeout(() => setTimeout(() => gotIt = true, 0), "2000");
        tick(3000);
        expect(gotIt).toBe(true);
    }));
```
The reason for it is that (fake-async-test.ts)):
`var endTime = this._currentTime + delay;`
is "02000" (of type 'string') in the call to setTimeout(..., "2000"). endTime is stored then in scheduler's entry. Upon execution of the task, currentTime is assigned from endTime:
`this._currentTime = current_1.endTime;`
and there is a call to setTimeout(..., 0), but this time:
`var endTime = this._currentTime + delay;`
becomes "020000" and not 2000 as one would expect.

The fix is easy:
`var endTime = this._currentTime + delay;`
should be replaced with
`var endTime = this._currentTime + +delay;`

None should really use string for the delay argument, but it happens when you, for example, define your delay in an angular2 template file as a parameter of a component. Everything works fine in dev/prod build but fails with "Error: 1 timer(s) still in the queue." error message in unit tests and it's not that obvious what really happens.

**Comment by sharikovvladislav** [comment]
Why do you pass string as a second parameter? You have to put number there.

**Comment by JiaLiPassion** [comment]
close for not an issue.
