### ISSUE TITLE
cannot assign "onreadystatechange" for XMLHttpRequest in Opera 12 in strict mode

### ISSUE THREAD

**Issue by Yaffle** [angular/zone.js#577]
```
<!DOCTYPE html>
<html>
<head>
  <script src="https://unpkg.com/zone.js/dist/zone.js"></script>
  <script>
  (function () {
    "use strict";
    var url = "data:text/plain,test";
    var xhr = new XMLHttpRequest();
    xhr.open("GET", url, true);
    xhr.onreadystatechange = function () {};
    xhr.send();
    alert("OK");
  })();
  </script>
</head>
<body>
</body>
</html>

```

It seems, `canPatchViaPropertyDescriptor` defines unconfigurable `onreadystatechange` property on XMLHttpRequest.prototype.

**Comment by JiaLiPassion** [comment]
@Yaffle, can you provide a reproduce repo or plunker? I can't reproduce your issue in zone.js 0.7.4

**Comment by Yaffle** [comment]
@JiaLiPassion , I have updated my initialcomment to include the code of full HTML file.

**Comment by JiaLiPassion** [comment]
@Yaffle, thank you, the reason is in Opera 12, XMLHttpRequest.prototype.onreadystatechange is undefined by default, I'll make a PR to let it work.

**Comment by Yaffle** [comment]
@mhevery Thank you!
