### ISSUE TITLE
Overriding onreadystatechange causes Sinon.js errors

### ISSUE THREAD

**Issue by MrFrankel** [angular/zone.js#581]
In property-descriptor.ts, there is a function called "canPatchViaPropertyDescriptor" which overrides the default onreadystatechange and sets it as a getter which always returns true.

Other then seeming very intrusive, it seems to be causing issues with Sinon.js which tries to access it.

Is there a way to avoid this?

Thanks

**Comment by JiaLiPassion** [comment]
@MrFrankel, could you provide a repo to reproduce your issue? which browser are you using? and could you check #577 is the same issue or not?

**Comment by MrFrankel** [comment]
@JiaLiPassion thanks for the quick response.
Ive been trying to reproduce this issue in a plunker but cant.
It is related to #577, but happens on chrome.

Can you tell me if there is a away to avoid having the onreadystatechange set and read only?

**Comment by JiaLiPassion** [comment]
you can try this patched version to see whether it resolves your issue or not.
[zone.js.zip](https://github.com/angular/zone.js/files/682252/zone.js.zip)

**Comment by MrFrankel** [comment]
@JiaLiPassion works!!

when is this version released?

**Comment by JiaLiPassion** [comment]
@MrFrankel , It is under review, please wait until it is merged.

**Comment by MrFrankel** [comment]
@JiaLiPassion You rock!
Thanks!
