### ISSUE TITLE
Unhandled Promise errors aren't inspectable.

### ISSUE THREAD

**Issue by inlined** [angular/zone.js#582]
I'm building a code hosting framework on Zone.js and ran into trouble with unhandled rejections. I force middleware like an error handler and try to catch any unhandled rejections or promises. I wanted to do intelligent things with that error like report the message and provide your beautifully stitched together stack trace to a debugging tool. Unfortunately the great work the longStackTraceZoneSpec has done is lost for me.

The Zone.js code for handling a rejected promise rethrows that promise twice. This causes the entire cleanly formatted object of the original Error to get smashed into the message of the final error. The unit tests that worked flawlessly with an unhandled Error required a lot of string parsing for unhandled Promises and I'm really worried about the stability of any hand-crafted parsing.

**Comment by JiaLiPassion** [comment]
@inlined , do you mean you want to get the original uncaught error?
I think you can get the original error information from error.rejection which was re-throwed by zone

**Comment by JiaLiPassion** [comment]
@inlined , I have made a PR #627 to add unhandledRejection event trigger, is that meet your requirement?

**Comment by inlined** [comment]
Sorry I didn't catch the comment last month. This looks great. Thanks! I'll start testing with this asap.
