### ISSUE TITLE
Property 'current' does not exist on type 'typeof Zone' 

### ISSUE THREAD

**Issue by johnbendi** [angular/zone.js#588]
Universal angular uses the following code snippet
```
export function getRequest() {
    return Zone.current.get('req') || {};
}
export function getResponse() {
    return Zone.current.get('res') || {};
}
```
which reports the above error even when using the latest `zone.js` version

**Comment by JiaLiPassion** [comment]
@johnbendi, could you please provide a repo or plunker that can reproduce this error? Thanks.

**Comment by JiaLiPassion** [comment]
close for not be able to reproduce.
