### ISSUE TITLE
Both "pointerup" and "MSPointerUp"​​​ are triggered in IE10 and IE11 if zone.js is used

### ISSUE THREAD

**Issue by dxvladislavvolkov** [angular/zone.js#589]
Hello, I registered an event handler for the "pointerup" and "MSPointerUp" events. The "MSPointerUp" event is handled for IE10 compatibility and the "pointerup" event for IE11
As a result, both handlers are executed in IE11 (and IE10) if zone.js is registered on the page. 
I expect that only one handler should be executed.
You can see example [here](http://plnkr.co/edit/pXlqiPWjMjD8tussAodO?p=preview).

**Comment by JiaLiPassion** [comment]
Without zone.js, the event also both triggered, you can see this [plunker,](http://plnkr.co/edit/LOpxVAhnEhNPoVCTPaMp?p=preview) but maybe IE do some tricks to see whether the MSPointer handler is the same with pointerup handler, if they the same, the handler will be executed once.

And with zone.js patch, the handler are not equals even they reference the same handler.

I'm not sure whether zone.js should handle this or not.

**Comment by JiaLiPassion** [comment]
close for duplicate
