### ISSUE TITLE
Edge: Object doesn't support property or method 'fetch'

### ISSUE THREAD

**Issue by kemsky** [angular/zone.js#607]
zone.js version: `0.7.6`

After minification using webpack uglify plugin (`minimize: true` only) error is thrown, without minification it works fine.

Minified code:
```
                if (R) {
                    d(R);
                    if ("undefined" != typeof e["fetch"]) {
                        var L = void 0;
                        try {
                            L = e["fetch"]()
                        } catch (e) {
                            L = e["fetch"]("about:blank") //error is here
                        }
                        L.then(function () {
                            return null
                        }, function () {
                            return null
                        });
                        if (L.constructor != R && L.constructor != F) d(L.constructor)
                    }
                }
```
Looks like minification bug, but i guess we could rename `e` to `error` in catch and be safe.

Adding `screw_ie8: true` fixes this problem also.

**Comment by JiaLiPassion** [comment]
yes, it seems it is a uglifyjs issue, https://github.com/mishoo/UglifyJS2/issues/409#issuecomment-229355111, is this the only error when minification zone.js? There are several other places use 

```javascript
  try {
   ...
  } catch (e) {
 }
```

**Comment by kemsky** [comment]
So far i did not notice any other bugs,  may be it makes sense to use unique names for error objects to avoid this situation.

**Comment by JiaLiPassion** [comment]
@kemsky , thank you, I'll make a PR to try to modify the error name.

**Comment by JiaLiPassion** [comment]
@kemsky, could you try to modify node_modules/zone.js/dist/zone.js(or maybe zone-node.js) to 
modify the e -> error to see whether it will be fixed?

I create a sample project, the minified code like this.

```javascript
if(t.Promise=R,C&&(p(C),"undefined"!=typeof t.fetch))
  {
      var N=void 0;
     try{
        N=t.fetch()
     } catch(n){
        N=t.fetch("about:blank")
    }
```

**Comment by kemsky** [comment]
I have tried already replacing e -> error in zone.js and it worked. It seems that uglifier just does not check error object name when generates other names.

Also quite interesting fact that error should override local variable (if i remember it correctly), but not in Edge... In fact it works even with IE 11.

**Comment by JiaLiPassion** [comment]
@kemsky , thank you for the information, change e -> error should be a safe way to avoid such issue.
