### ISSUE TITLE
websocket onmessage event isn't being called

### ISSUE THREAD

**Issue by RoeyMoyal** [angular/zone.js#615]
Hi,

In our app we register the all our opened websockets onmessage event to log an error message in case a message arrives before we bind to the real onmessage event.
Later on we bind the real onmessage handler to the websocket but it is never called only the original events that we bind is called (the error log message).

After investigating the problem we found that zone.js duplicate all the on.. events to originalon.. events and it causes, for unknown reason,  to never call the new handler but only the original one that logs the error message and not allow our application to continue running as it should.

I fixed the problem by changing line 1618 : and setting the supportsWebSocket to false 

any idea what cause's this behavior and is there any other why to fix it ?

Regards,

**Comment by JiaLiPassion** [comment]
could you please post a sample repo or plunker to reproduce your issue?

**Comment by RoeyMoyal** [comment]
Sorry but its not possible, 
if it helps, some more information, : 

1. The first binding to the websockets events occurs before the loading of zone.js to the browser
2. then we load zone.js (as a part of the angular cli created bundle)
3. then we bind the new event to the websocket 
4. a message is received and the old event is called (the one that is saved on the originalonmessage) 

if you don't think that you can help, I would like to know the implications on setting supportsWebSocket  to false, and is there another way for disabling zone.js websocket support until we can figure out why is it happening ?

Regards,

**Comment by JiaLiPassion** [comment]
I created a sample application, but can't reproduce, you can check the attached file to see whether it is the same as your issue.
[test.zip](https://github.com/angular/zone.js/files/726845/test.zip)

**Comment by RoeyMoyal** [comment]
Hi,
I've also tried to reproduce it in a sample app with no success 
as I mentioned before we are working with angular 2, could this effect us in any way ?

also I would like to know is there another way to disable zone for web-sockets at least until we can figure out what causing the issue in our app?

**Comment by JiaLiPassion** [comment]
@RoeyMoyal , I don't know if the issue related with angular 2 or not, but I  think it should have nothing to do with angular 2.

> also I would like to know is there another way to disable zone for web-sockets at least until we can figure out what causing the issue in our app?

- the easy way, just like you post, modify supportsWebSocket to false.
- don't touch zone.js way, 
  
1. first, before load zone.js, keep onmessage property descriptor from WebSocket.prototype.
  by 
  ```javascript
    const originalOnMessage = Object.getOwnPropertyDescriptor(WebSocket.prototype, 'onmessage');
 ```
2   after load zone.js. define the onmessage property with the original one.
   ```javascript
   Object.defineProperty(WebSocket.prototype, 'onmessage', originalOnMessage);
  ```

I didn't try it, you can try to see whether it is ok or not.

**Comment by JiaLiPassion** [comment]
close for not an issue.
