### ISSUE TITLE
Protractor tests on Firefox fail for Angular apps using Zone.JS > 0.7.2

### ISSUE THREAD

**Issue by AlexandrosD** [angular/zone.js#616]
All protractor tests are failing on Firefox 50+, using Angular v2.4.4, zone.js v0.7.6, Geckodriver 0.13.0, protractor 4.0.13.

The error is the following:
`Permission denied to access property "invoke"`

This seems similar to https://github.com/angular/protractor/issues/2784 and can be solved only by downgrading Zone.js to v0.7.2.

**Comment by JiaLiPassion** [comment]
Could you provide a sample repo?

**Comment by rolandjitsu** [comment]
I have the same issues. Check [angular-lab](https://github.com/rolandjitsu/angular-lab) repo.

**Comment by johnstaveley** [comment]
I have the same issue running Selenium tests on zone.js 0.7.7, FF 51.0.1 and Selenium WebDriver 3.0.1. Same error as reported above

**Comment by JiaLiPassion** [comment]
@rolandjitsu @johnstaveley , can you tell me how to reproduce the issue? I use the angular-lab repo, but I don't know how to configure the protractor to run with Firefox 51.

**Comment by rolandjitsu** [comment]
@JiaLiPassion just use `capabilities: {browserName: 'firefox'}` I guess. It should work if you have firefox installed. You can also set the binary path to Firefox.

**Comment by JiaLiPassion** [comment]
@rolandjitsu , I have tried to add a capabilities {browserName: 'firefox'}, it is not working, the protractor complains can't download firefoxdriver, it seems that webdriver doesnot support firefox 50

**Comment by rolandjitsu** [comment]
As far as I know, Firefox is supported, it just seems to be an issue with selenium, see https://github.com/angular/protractor/issues/886#issuecomment-274246993

**Comment by johnstaveley** [comment]
I'm not using protractor, I'm just running web tests using C# on zone.js 0.7.7, FF 51.0.1 and Selenium WebDriver 3.0.1 but it is the same issue. There is a dynamic component built using Angular 2 it fails to find (the first it tries to find). It fails with the error message above on:

_wait.Until(ExpectedConditions.ElementIsVisible(by));

where by is find the element by id

**Comment by mgiambalvo** [comment]
This is still an issue in 0.8.5. It seems the problem was introduced in 0fd8c03ae8de0169976ce39e0e331fea7f1c1852. Geckodriver will throw an error on any page with Zones patched in if setTimeout is called in an async script (which is how Protractor [tests for Angular](https://github.com/angular/protractor/blob/master/lib/clientsidescripts.js#L668)). This is only a problem in Firefox 50+ (Firefox 47 seems ok).

This demonstrates the problem:
```js
let webdriver = require('selenium-webdriver');
let capabilities = webdriver.Capabilities.firefox();
driver = new webdriver.Builder().usingServer('http://localhost:4444/wd/hub').withCapabilities(capabilities).build();
driver.get("http://material.angular.io");
driver.executeAsyncScript((cb) => { window.setTimeout(cb,1000) });
```

I'm guessing the issue is that the patched setTimeout can't call `invoke` in the WebDriver sandbox.

**Comment by JiaLiPassion** [comment]
@mgiambalvo , thank you for the information, I will try to research more, but I am still stuck at the environment, my selenium can't work with firefox 50+.

**Comment by mgiambalvo** [comment]
The easiest way to do that would be to use webdriver-manager. It'll be available in any project with Protractor (or anything created with angular-cli), but you can also just install it directly.

```
npm install webdriver-manager
webdriver-manager update
webdriver-manager start
```

That should start a selenium server listening on port :4444 - you should then be able to run the script I posted. I also put together a repo with everything set up https://github.com/mgiambalvo/firefox-zonejs-issue-demo

**Comment by JiaLiPassion** [comment]
@mgiambalvo , thank you, I will try your repository to reproduce the issue.

**Comment by JiaLiPassion** [comment]
@mgiambalvo , still not working, what firefox version are you using? I tried firefox 50, 51, 52 on mac os 10.12.3, all report org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms.

**Comment by JiaLiPassion** [comment]
@mgiambalvo , I think I know how to fix it, I will make a PR to fix it.

**Comment by pedrotst** [comment]
When can I expect the next release to fetch this fix?

**Comment by AlexandrosD** [comment]
@mhevery please reopen the issue as it is not fixed yet.
Even with the latest version of zone.js (from master branch) the tests continue to fail on firefox.

**Comment by JiaLiPassion** [comment]
@AlexandrosD, could you post your repo, I tested with @mgiambalvo 's sample, so I would like to research with your repo. thank you.

**Comment by AlexandrosD** [comment]
@JiaLiPassion please try with the most widely-used angular seed: https://github.com/mgechev/angular-seed

Run protractor with latest webdriver (v3.3.1), gekcodriver (v0.15.0), and firefox (v51+).

Just reproduced this one:

```
alex@laptop /c/projects/angular-seed (master)
$ protractor --baseUrl=http://localhost:5556/ --seleniumAddress=http://localhost:4444/wd/hub --browser=firefox
[13:19:33] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[13:19:33] I/launcher - Running 1 instances of WebDriver
Started
[13:19:48] E/launcher - Error while running testForAngular: Error: Permission denied to access property "invoke"
Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
System info: host: 'AL471531', ip: '172.17.66.36', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_102'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\alex\AppData\Local\Temp\rust_mozprofile.35X6HsIWf4AJ, rotatable=false, timeouts={implicit=0, pageLoad=300000, script=30000}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=54.0a2, platformVersion=6.1, moz:processID=13440, browserName=firefox, platformName=windows_nt}]
Session ID: a6ba1ede-e0b0-4ac9-8700-2fe91e1fbb53
[13:19:48] E/launcher - Error: Error while running testForAngular: Error: Permission denied to access property "invoke"
Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
System info: host: 'AL471531', ip: '172.17.66.36', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_102'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\alex\AppData\Local\Temp\rust_mozprofile.35X6HsIWf4AJ, rotatable=false, timeouts={implicit=0, pageLoad=300000, script=30000}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=54.0a2, platformVersion=6.1, moz:processID=13440, browserName=firefox, platformName=windows_nt}]
Session ID: a6ba1ede-e0b0-4ac9-8700-2fe91e1fbb53
    at c:\projects\angular-seed\node_modules\protractor\built\browser.js:512:19
    at ManagedPromise.invokeCallback_ (c:\projects\angular-seed\node_modules\selenium-webdriver\lib\promise.js:1379:14)
    at TaskQueue.execute_ (c:\projects\angular-seed\node_modules\selenium-webdriver\lib\promise.js:2913:14)
    at TaskQueue.executeNext_ (c:\projects\angular-seed\node_modules\selenium-webdriver\lib\promise.js:2896:21)
    at asyncRun (c:\projects\angular-seed\node_modules\selenium-webdriver\lib\promise.js:2775:27)
    at c:\projects\angular-seed\node_modules\selenium-webdriver\lib\promise.js:639:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
[13:19:48] E/launcher - Process exited with error code 199
```

**Comment by JiaLiPassion** [comment]
@AlexandrosD , the reason is in master branch of zone.js, `dist` folder is still 0.8.5, not updated, it will only updated when version number change, you can clone the master and run `gulp build`, then copy the dist to your repo/node_modules/zone.js/dist, it should work.

**Comment by AlexandrosD** [comment]
@JiaLiPassion Hm.. indeed - you are right. After building the dist folder locally and copying its contents in the respective directory of our repo the tests run. 
Do you have an estimation regarding when v0.8.6 is going to be released?

**Comment by JiaLiPassion** [comment]
@AlexandrosD , I don't know when it will be released, but I believe it will be soon, because several high priority issues have been merged.

**Comment by MythriManjunath** [comment]
I am facing the same issue. **Failed: Error while running testForAngular: Error: Permission denied to access property "invoke**
```
"zone.js": "0.7.2"
"@angular/core": "2.4.10"
"typescript": "2.2.2"
browserName=firefox
browserVersion=53.0.3
```

**Comment by JiaLiPassion** [comment]
@MythriManjunath , this has been fixed in 0.8.6, so please update to the newest version.

**Comment by MythriManjunath** [comment]
@JiaLiPassion I upgraded to "zone.js": "0.8.6" . I get the same error.

**Comment by JiaLiPassion** [comment]
@MythriManjunath , could you post the full stack trace? It should not throw error in 0.8.6

**Comment by MythriManjunath** [comment]
@JiaLiPassion Okay sure. Here is the stack trace. Let me know if anything else is required thank you .
```
Message:
    Failed: Error while running testForAngular: Error: Permission denied to access property "invoke"
    Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
    System info: host: 'ubuntu', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-78-generic', java.version: '1.8.0_121'
    Driver info: org.openqa.selenium.firefox.FirefoxDriver
    Capabilities [{moz:profile=/tmp/rust_mozprofile.Vaed6CZZUubM, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=53.0.3, platformVersion=4.4.0-78-generic, moz:processID=3625.0, browserName=firefox, javascriptEnabled=true, platformName=linux}]
    Session ID: ed2b609a-e0e3-446b-8812-e33c5f50107b
  Stack:
    Error: Error while running testForAngular: Error: Permission denied to access property "invoke"
    Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
    System info: host: 'ubuntu', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-78-generic', java.version: '1.8.0_121'
    Driver info: org.openqa.selenium.firefox.FirefoxDriver
    Capabilities [{moz:profile=/tmp/rust_mozprofile.Vaed6CZZUubM, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=53.0.3, platformVersion=4.4.0-78-generic, moz:processID=3625.0, browserName=firefox, javascriptEnabled=true, platformName=linux}]
    Session ID: ed2b609a-e0e3-446b-8812-e33c5f50107b
        at executeAsyncScript_.then (/usr/lib/node_modules/protractor/lib/browser.ts:945:27)
        at ManagedPromise.invokeCallback_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1366:14)
        at TaskQueue.execute_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2813:27)
        at /usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:676:7
        at process._tickCallback (internal/process/next_tick.js:103:7)
    From: Task: Run beforeEach in control flow
        at Object.<anonymous> (/usr/lib/node_modules/protractor/node_modules/jasminewd2/index.js:94:19)
    From asynchronous test: 
    Error
        at Suite.<anonymous> (/home/ubuntu/git/idevops/Test/demoDashboardTest/test/menu.js:2:4)
        at Object.<anonymous> (/home/ubuntu/git/idevops/Test/demoDashboardTest/test/menu.js:1:1)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)

```

**Comment by JiaLiPassion** [comment]
@MythriManjunath , the stack trace is protractor side.... could you post your reproduce repository?

**Comment by MythriManjunath** [comment]
@JiaLiPassion Sorry. I do not have permission to share the repository. Thank you!

**Comment by JiaLiPassion** [comment]
@MythriManjunath , sure, maybe you can confirm that you upgrade zone.js to 0.8.6 or higher version correctly by print some information by modifying node_modules/zone.s/dist/zone.js, the `invoke` should not throw error because all `invoke` call have been try/catched from `0.8.6`.

**Comment by MythriManjunath** [comment]
@JiaLiPassion Okay sure. I will do that and Thank you so much for a quick response.
