### ISSUE TITLE
Sharepoint 2013 conflict

### ISSUE THREAD

**Issue by AndriiDidkivsky** [angular/zone.js#618]
Hi, I get an exception "Out of stack space" when I try to use sharepoint [controls](http://prntscr.com/e03bem) 
So, controls aren't available after the exception.

Issue is fully described on [stackoverflow](http://stackoverflow.com/questions/40466012/using-angular2-on-sharepoint-2013-masterpage-leads-to-zone-js-error)

Could you provide workaround for this problem ?
zone.js: 0.7.4 
Thanks.

**Comment by TkachVova** [comment]
Have the same issue. It seems to be some naming conflict with some SharePoint script library.

**Comment by djleonskennedy** [comment]
Same issue

**Comment by JiaLiPassion** [comment]
Could you check this issue, and try the solution posted there?
https://github.com/angular/zone.js/issues/434

**Comment by AndriiDidkivsky** [comment]
@JiaLiPassion I've seen that.  Unfortunately this is not the same issue. :(   
"Out of stack space" appears in **sharepoint 2013** env only when we use standart controls. 
#434 -  **Sharepoint online** issue.

**Comment by djleonskennedy** [comment]
Sorry but I can't restrain myself but it's very clever to name global variable "Zone" : D

**Comment by JiaLiPassion** [comment]
@AndriiDidkivsky , if you can provide a env or steps to reproduce the issue, I may help you to resolve the issue. the core.js source code can be found here, http://www.cpecc.net/www.cpecc.net/_layouts/15/menu.debug.js@rev=rjljph65iwqmjqoxemjt+w_253d=

in your error screenshot, it seems popupmouseoverparent and MenuHtcInternal_Show cause infinite loop, could you try to debug that why the loop occurs?

**Comment by AndriiDidkivsky** [comment]
> in your error screenshot, it seems popupmouseoverparent and MenuHtcInternal_Show cause infinite loop

you're absolutely right. 

> if you can provide a env

Unfortunately I can't. 
Steps is just click on cog

**Comment by JiaLiPassion** [comment]
@AndriiDidkivsky ，you are welcome, I don't know if it is related with zone.js, currently from the error screenshot.
popupmouseoverparent->zonepatch wrapFn-> MenuHtcInternal_Show

from the source code I posted, I think maybe the event order is

1. mouseover of popup trigger it's parent's mouseover event 
2.and somehow parent's mouseover trigger the popup mouseover again. 

I can't debug, so I don't know why menuhtcinternal_show trigger popup mouseover event handler.

**Comment by KoenigLear** [comment]
I can also reproduce Out of stack space.  this is my stack trace:

Uncaught RangeError: Maximum call stack size exceeded
    at ClearTimeOutToHideMenu (core.js?rev=rjZicIy%2BXBea34HbdjHJhw%3D%3D:1)
    at PopupMouseOverParent (core.js?rev=rjZicIy%2BXBea34HbdjHJhw%3D%3D:1)
    at HTMLSpanElement.<anonymous> (core.js?rev=rjZicIy%2BXBea34HbdjHJhw%3D%3D:1)
    at HTMLSpanElement.wrapFn [as _onmouseover] (eval at <anonymous> (vendorbundle.js:5298), <anonymous>:851:29)
    at PopupMouseOverParent (core.js?rev=rjZicIy%2BXBea34HbdjHJhw%3D%3D:1)
    at HTMLSpanElement.<anonymous> (core.js?rev=rjZicIy%2BXBea34HbdjHJhw%3D%3D:1)
    at HTMLSpanElement.wrapFn [as _onmouseover] (eval at <anonymous> (vendorbundle.js:5298), <anonymous>:851:29)
    at PopupMouseOverParent (core.js?rev=rjZicIy%2BXBea34HbdjHJhw%3D%3D:1)
    at HTMLSpanElement.<anonymous> (core.js?rev=rjZicIy%2BXBea34HbdjHJhw%3D%3D:1)
    at HTMLSpanElement.wrapFn [as _onmouseover] (eval at <anonymous> (vendorbundle.js:5298), <anonymous>:851:29)
    at PopupMouseOverParent (core.js?rev=rjZicIy%2BXBea34HbdjHJhw%3D%3D:1)
    at HTMLSpanElement.<anonymous> (core.js?rev=rjZicIy%2BXBea34HbdjHJhw%3D%3D:1)
    at HTMLSpanElement.wrapFn [as _onmouseover] (eval at <anonymous> (vendorbundle.js:5298), <anonymous>:851:29)
    at PopupMouseOverParent (core.js?rev=rjZicIy%2BXBea34HbdjHJhw%3D%3D:1)
    at HTMLSpanElement.<anonymous> (core.js?rev=rjZicIy%2BXBea34HbdjHJhw%3D%3D:1)
Zone.runTask @ zone.js?fad3:155
ZoneTask.invoke @ zone.js?fad3:332

**Comment by JiaLiPassion** [comment]
@KoenigLear , can you help to debug 

```javascript
at HTMLSpanElement. (core.js?rev=rjZicIy%2BXBea34HbdjHJhw%3D%3D:1)
at HTMLSpanElement.wrapFn [as _onmouseover] (eval at (vendorbundle.js:5298), :851:29)
```

what event handler were triggered here?

**Comment by KoenigLear** [comment]
@JiaLiPassion 
ClearTimeOutToHideMenu
-> ClearTimeOut("HideMenuTimeOut");
-> function ClearTimeOut(a) {
    var b = document.body.getAttribute(a);
    b != null && window.clearTimeout(Number(b));
    document.body.removeAttribute(a)
}

not sure why that should lead to a loop.

**Comment by JiaLiPassion** [comment]
@KoenigLear , @AndriiDidkivsky 

maybe the issue because zone.js patch timer and return a Task from setTimeout instead of a number, and in sharepoint, the logic is 

```javascript
String(window.setTimeout(function()
```

and when clearTimeout

```javascript
clearTimeout(Number(timeoutId))
```

so the timer in fact was not cleared, because Number(task) return NaN

I can't test so could you guys try the attached version of zone.js to see whether the issue can be resolved?

**Comment by AndriiDidkivsky** [comment]
@JiaLiPassion , thanks. I'll try.

**Comment by andtii** [comment]
If anyone needs a SharePoint Online environment to help figure this out, contact me and i can give you login information

**Comment by JiaLiPassion** [comment]
@andtii, thank you, if the version I post will not resolve the issue, I will ask for your help!

**Comment by KoenigLear** [comment]
@JiaLiPassion   I see your patchtimer.   I'm afraid the patch doesn't have any effect; still the same error

Anything else you want me to try?

    Uncaught RangeError: Maximum call stack size exceeded
    at HTMLSpanElement.<anonymous> (core.js?rev=rjZicIy%2BXBea34HbdjHJhw%3D%3D:1)
    at HTMLSpanElement.wrapFn [as _onmouseover] (eval at <anonymous> (vendorbundle.js:5298), <anonymous>:1214:29)
    at PopupMouseOverParent (core.js?rev=rjZicIy%2BXBea34HbdjHJhw%3D%3D:1)
    at HTMLSpanElement.<anonymous> (core.js?rev=rjZicIy%2BXBea34HbdjHJhw%3D%3D:1)
    at HTMLSpanElement.wrapFn [as _onmouseover] (eval at <anonymous> (vendorbundle.js:5298), <anonymous>:1214:29)
    at PopupMouseOverParent (core.js?rev=rjZicIy%2BXBea34HbdjHJhw%3D%3D:1)
    at HTMLSpanElement.<anonymous> (core.js?rev=rjZicIy%2BXBea34HbdjHJhw%3D%3D:1)
    at HTMLSpanElement.wrapFn [as _onmouseover] (eval at <anonymous> (vendorbundle.js:5298), <anonymous>:1214:29)
    at PopupMouseOverParent (core.js?rev=rjZicIy%2BXBea34HbdjHJhw%3D%3D:1)
    at HTMLSpanElement.<anonymous> (core.js?rev=rjZicIy%2BXBea34HbdjHJhw%3D%3D:1)
    at HTMLSpanElement.wrapFn [as _onmouseover] (eval at <anonymous> (vendorbundle.js:5298), <anonymous>:1214:29)
    at PopupMouseOverParent (core.js?rev=rjZicIy%2BXBea34HbdjHJhw%3D%3D:1)
    at HTMLSpanElement.<anonymous> (core.js?rev=rjZicIy%2BXBea34HbdjHJhw%3D%3D:1)
    at HTMLSpanElement.wrapFn [as _onmouseover] (eval at <anonymous> (vendorbundle.js:5298), <anonymous>:1214:29)
    at PopupMouseOverParent (core.js?rev=rjZicIy%2BXBea34HbdjHJhw%3D%3D:1)
    at HTMLSpanElement.<anonymous> (core.js?rev=rjZicIy%2BXBea34HbdjHJhw%3D%3D:1)
Zone.runTask @ zone.js?fad3:170
ZoneTask.invoke @ zone.js?fad3:414

**Comment by KoenigLear** [comment]
When the page is loaded there's also this error I forgot to mention.  This is even before you click the ribbon.  It might have an impact on the above events...

addPageComponent: function(a) {
        a: ;!CUI.ScriptUtility.isNullOrUndefined(this.$2o_1[a.getId()]) && Error.create("A PageComponent with id: " + a.getId() + " has already been added to the PageManger.");

Uncaught TypeError: Error.create is not a function
    at SP.Ribbon.PageManager.addPageComponent (/_layouts/15/cui.js?rev=VPkVoHj7Yj40n7Zep%2BVfxg%3D%3D:1)
    at Function.SP.Ribbon.TrackTabPageComponent.registerWithPageManager (sp.ribbon.js:2)
    at sp.ribbon.js:2

**Comment by JiaLiPassion** [comment]
@KoenigLear , thank you for trying, I may need the environment to debug, @andtii , could you please provide the account information to me? thank you very much.

**Comment by KoenigLear** [comment]
A bit of an update  using Zone.js 0.6.26 and adding the following line to 
zoneAwareAddListener right before zone.scheduleEventTask works (no errors)

//SharePoint ribbon issue
        if (data.target.id === 'zz4_Menu_t' || data.target.id === 'zz11_SiteActionsMenu_t')
            	return;

**Comment by andtii** [comment]
@JiaLiPassion I have sent you a mail with the login information

**Comment by JiaLiPassion** [comment]
@andtii, Thank you, I have reproduced the issue, could you tell me how to modify the page such as edit loading javascript files?
If you remove the zone.js , the problem still exists?

**Comment by andtii** [comment]
@JiaLiPassion There error dissapears if you remove the include of zone.js,  If you provide a url to a file hosted somewhere i can include that instead so that you can modify the file as you like.

**Comment by JiaLiPassion** [comment]
@andtii, could you provide another version of the same example without zone.js? thanks.

**Comment by andtii** [comment]
@JiaLiPassion Now i commented out the include of zone.js and everything works

**Comment by JiaLiPassion** [comment]
@andtii, it seems I can't login into it anymore ,could you check it and change the demo to with zone.js version, and could you use the attached version of zone.js ? thank you .

[zone.js.zip](https://github.com/angular/zone.js/files/782604/zone.js.zip)

**Comment by andtii** [comment]
@JiaLiPassion I have updated the zone.js to your version, also sent you new login information

**Comment by JiaLiPassion** [comment]
@andtii, thank you so much for your help, it seems this version's zone.js fixed the problem, I right click the menu, and no error occurs, and I checked the code, that the popupMouseOverParent will not infinite loop again,  could you check it?

**Comment by KoenigLear** [comment]
In my environment the error remains with (zip from -22hours) zone.js?fad3:155 Uncaught RangeError: Maximum call stack size exceeded and also Uncaught TypeError: Error.create is not a function
at SP.Ribbon.PageManager.addPageComponent (/_layouts/15/cui.js?) when loading the page.

**Comment by andtii** [comment]
@JiaLiPassion The error still happens, maybe not the first time you right click but after 2 or 3.

**Comment by andtii** [comment]
Also as @KoenigLear says we have another issue with SP.Ribbon.PageManager.addPageComponent but lets  try fix this one first

**Comment by JiaLiPassion** [comment]
@andtii, I made another test version, please help me to upload it, and if it is possible, please tell me how to update the test version of zone.js, thank you.
[zone.js.zip](https://github.com/angular/zone.js/files/795966/zone.js.zip)

**Comment by andtii** [comment]
@JiaLiPassion You got mail :)

**Comment by JiaLiPassion** [comment]
@andtii , thank you :)

**Comment by andtii** [comment]
@JiaLiPassion  This version seems to fix the issue, also the SP.Ribbon.PageManager.addPageComponent problem is gone. Can you verify this aswell @KoenigLear @AndriiDidkivsky

**Comment by JiaLiPassion** [comment]
@andtii , Thank you for your great help! That's great!

**Comment by KoenigLear** [comment]
@andtii @JiaLiPassion looking great!   The recursive popmenu e.g. maximum call stack error is gone.  however I still see the Uncaught TypeError: Error.create is not a function
    at SP_Ribbon_PageManager.CUI_Page_PageManager$addPageComponent [as addPageComponent]

**Comment by JiaLiPassion** [comment]
@KoenigLear , Thank you for confirming the issue, Error.create should be another problem, could you provide a demo to reproduce? I can guess the reason of this error, but I still need to confirm it.

**Comment by KoenigLear** [comment]
@JiaLiPassion you should still be able to reproduce it in @andtii 's environment.    I just add zone.js to the page and just by loading it and looking at the console you'll see the error.  (It looks like a clash name with the Error global).  At least that's the way I reproduce it on my environment (on premises unfortunately).

if (!CUI.ScriptUtility.isNullOrUndefined(this.$2o_1[component.getId()])) {
            **Error.create('A PageComponent with id: ' + component.getId() + ' has already been added to the PageManger.');**
        }

Uncaught TypeError: Error.create is not a function
at SP.Ribbon.PageManager.addPageComponent (/_layouts/15/cui.js?) when loading the page.

**Comment by JiaLiPassion** [comment]
@KoenigLear , could you send me the url? I can't see the error in @andtii's environment.

**Comment by KoenigLear** [comment]
@JiaLiPassion  

In a new publishing site (via cog wheel, site settings, new subsite, title: angular2, url: angular2, template: Publishing: Publishing site.

I insert a code script via Edit/Insert/Embed code  <script text="javascript/text" src="...zone.js"> </script>

![ribbon_error](https://cloud.githubusercontent.com/assets/19749651/23267592/197badf2-f9e3-11e6-8aae-066ffbeaa09c.png)

**Comment by JiaLiPassion** [comment]
@KoenigLear , thank you , I can reproduce it and I have found the reason, I will post a PR to fix it.

**Comment by AAAnderson7301** [comment]
@JiaLiPassion  I tried ussing your pull request but I am still getting the error "Error.create is not a function" My project is the auto generated project from Angular CLI. I just uploaded the files from the build and added them to a script web part. 

![image](https://cloud.githubusercontent.com/assets/8826208/23374339/db586076-fcf1-11e6-8405-8448653b05db.png)

**Comment by JiaLiPassion** [comment]
@AAAnderson7301 , could you try this attached file again?  thank you.
If the error still exists, just help to debug Error's all properties.
[zone.js.zip](https://github.com/angular/zone.js/files/805368/zone.js.zip)

**Comment by JiaLiPassion** [comment]
@andtii, @KoenigLear , could you help me to upload this attached version to see the infinite loop and Error.create is fixed or not? 
and @andtii, could you upload this zone.js to the test environment, so if it is not fixed, I can continue to debug, thank you!

[zone.js.zip](https://github.com/angular/zone.js/files/805368/zone.js.zip)

**Comment by andtii** [comment]
@JiaLiPassion You already uploaded it?

**Comment by NicolasR** [comment]
Hi,

Your fix seems to work on my side. 
Tested on SharePoint 2013 on premise.

**Comment by JiaLiPassion** [comment]
@andtii, yes, I update zone.js and angular2.bundle.lib.js(I just download this file, and replace my fix of zone.js parts) and re-upload  angular2.bundle.lib.js, no error occur, could help me to double check the two errors? thank you

**Comment by JiaLiPassion** [comment]
@NicolasR , thank you for confirm.

**Comment by KoenigLear** [comment]
@JiaLiPassion yes working great for me me no errors whatsoever!

**Comment by JiaLiPassion** [comment]
@KoenigLear , Thank you for confirm.

**Comment by AAAnderson7301** [comment]
@JiaLiPassion. It turns out the issue was a polyfill was setting the global namespace Error before SharePoint is able to finish loading. I even tried waiting for the file that was calling Error (O365ShellG2Plus.js) but then it never fired the callback. I am using SharePoint online. I ended up just throwing a script in my angular project to handle the issue. Not the best but it works for what I need. 
```
<script>
    Error.create = function(message, errorInfo) {
        return {
            message: message,
            description: errorInfo,
            name: '',
            number: ''
        };
    }
</script>
```

**Comment by JiaLiPassion** [comment]
@AAAnderson7301 , yes, zone.js override the global Error, and sharepoint add some methods to it, so the order of js loading matters, based on the environment @andtii provided, the sharepoint related js will loaded before zone.js and angular polyfill, so please make sure your env is the same order.

**Comment by andybandy89** [comment]
Also with the zone.js version you uploaded here, I still receive this error. I also tried to add the script files I get from angular cli to a script editor webpart. To be sure all SharePoint Scripts loaded, for debugging I add the scripts to body after some seconds. 

![image](https://cloud.githubusercontent.com/assets/15612874/23500158/4ea3367a-ff2f-11e6-8f4e-b863bdbe59ee.png)

If I add the code @AAAnderson7301  added, I receive this error:

![image](https://cloud.githubusercontent.com/assets/15612874/23500035/d02fd4b0-ff2e-11e6-89f6-07bed26e024a.png)

**Comment by JiaLiPassion** [comment]
@andybandy89 , can you provide a test environment? The 2nd screenshot it seems you call err.popStackFrame method, this method should be a function property of Error, so I think it should be called as 

```javascript
Error.popStackFrame
```

**Comment by andybandy89** [comment]
@JiaLiPassion , it's unbelievable. I'm struggling with that for hours now but when I setup a test environment for you everything works. I'll have to investigate the differences of the two environments.

**Comment by JiaLiPassion** [comment]
@andybandy89 , sure, please notify me when you have further information.

**Comment by andybandy89** [comment]
@JiaLiPassion , only one of our SharePoint Farm throws errors. For now I'll develop the solution on another one and investigate more later. The important thing on the other farms also is to ensure the correct loading order of the JavaScripts.

**Comment by JiaLiPassion** [comment]
@andybandy89 , ok, got it.

**Comment by MerlinMartel** [comment]
I confirm, it's working for me too, with my SharePoint Online tenant version : 16.0.6223.1203.
thx a lot for this !!

When can we expect to have this fix in package ?

**Comment by JiaLiPassion** [comment]
@MerlinMartel , thank you for confirm, I think it is under review, please wait for a moment.

**Comment by webtechy** [comment]
Has this fix been packaged into a release now?

**Comment by JiaLiPassion** [comment]
@webtechy , yes, this has been released, you can use the latest version to test.

**Comment by webtechy** [comment]
OK, have updated it, and I was previously seeing:

> Uncaught TypeError: Error.create is not a function
>     at Function.O365SuiteServiceProxy.Util.a (O365ShellG2Plus.js:4)
>     at O365SuiteServiceProxy.f.SessionStorageRequest (O365ShellG2Plus.js:4)
>     at _o365sa.St.S2Ss (O365ShellG2Plus.js:7)
>     at Function._o365sg2p.b.d (O365ShellG2Plus.js:10)
>     at Function._o365sg2p.b.a (O365ShellG2Plus.js:10)
>     at Function._o365sg2p.Loader.$$cctor (O365ShellG2Plus.js:12)
>     at O365ShellG2Plus.js:12
> O365SuiteServiceProxy.Util.a @ O365ShellG2Plus.js:4
> SessionStorageRequest @ O365ShellG2Plus.js:4
> S2Ss @ O365ShellG2Plus.js:7
> _o365sg2p.b.d @ O365ShellG2Plus.js:10
> _o365sg2p.b.a @ O365ShellG2Plus.js:10
> _o365sg2p.Loader.$$cctor @ O365ShellG2Plus.js:12
> (anonymous) @ O365ShellG2Plus.js:12

I then ran:

`npm install zone.js@latest --save`

My webpack is as follows (it did warn about 2 dependencies, webpack and I forget the other):

```
{
  "name": "new-share-point-app",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "dependencies": {
    "@angular/common": "^2.4.9",
    "@angular/compiler": "^2.4.9",
    "@angular/core": "^2.4.9",
    "@angular/forms": "^2.4.9",
    "@angular/http": "^2.4.9",
    "@angular/platform-browser": "^2.4.9",
    "@angular/platform-browser-dynamic": "^2.4.9",
    "@angular/router": "^3.4.9",
    "@microsoft/sp-client-base": "~1.0.0",
    "@microsoft/sp-core-library": "~1.0.0",
    "@microsoft/sp-webpart-base": "~1.0.0",
    "@progress/kendo-angular-buttons": "^0.20.1",
    "@progress/kendo-angular-dialog": "^0.16.0",
    "@progress/kendo-angular-dropdowns": "^0.31.2",
    "@progress/kendo-angular-grid": "^0.19.1",
    "@progress/kendo-angular-inputs": "^0.19.0",
    "@progress/kendo-angular-intl": "^0.10.0",
    "@progress/kendo-angular-l10n": "^0.1.0",
    "@progress/kendo-angular-layout": "^0.21.5",
    "@progress/kendo-angular-popup": "^0.16.2",
    "@progress/kendo-angular-upload": "^0.16.0",
    "@progress/kendo-data-query": "^0.3.6",
    "@progress/kendo-theme-default": "^2.12.29",
    "@types/webpack-env": ">=1.12.1 <1.14.0",
    "angular2-froala-wysiwyg": "^2.5.0-1",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "json-stringify": "^1.0.0",
    "reflect-metadata": "^0.1.10",
    "rxjs": "^5.2.0",
    "sp-pnp-js": "^2.0.1",
    "ts-helper": "0.0.1",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "~1.0.0",
    "@microsoft/sp-module-interfaces": "~1.0.0",
    "@microsoft/sp-module-loader": "^0.5.1",
    "@microsoft/sp-webpart-workbench": "~1.0.0",
    "@types/chai": ">=3.4.34 <3.6.0",
    "@types/jasmine": "^2.5.43",
    "@types/lodash": "^4.14.54",
    "@types/mocha": ">=2.2.33 <2.6.0",
    "@types/node": "^7.0.5",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.26.2",
    "gulp": "~3.9.1",
    "html-loader": "^0.4.5",
    "image-webpack-loader": "^3.2.0",
    "jasmine-core": "^2.5.2",
    "jasmine-spec-reporter": "^3.2.0",
    "karma": "^1.5.0",
    "karma-chrome-launcher": "^2.0.0",
    "node-sass": "^4.5.0",
    "protractor": "^5.1.1",
    "resolve-url-loader": "^2.0.2",
    "sass-loader": "^6.0.2",
    "style-loader": "^0.13.2",
    "ts-node": "^2.1.0",
    "url-loader": "^0.5.8"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  }
}
```

However, I am now seeing:

> Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://portal.office.com') does not match the recipient window's origin ('null').
> O365SuiteServiceProxy.RequestExecutor.sendPostMessage @ O365ShellG2Plus.js:4
> O365SuiteServiceProxy.RequestExecutor.internalProcessIFrameOnload @ O365ShellG2Plus.js:4
> (anonymous) @ O365ShellG2Plus.js:4
> i @ O365ShellG2Plus.js:4
> ZoneDelegate.invokeTask @ zone.js:398
> Zone.runTask @ zone.js:165
> ZoneTask.invoke @ zone.js:460

**Comment by JiaLiPassion** [comment]
@webtechy , the new error seems to be the security problem, the Error.create problem is gone.

**Comment by webtechy** [comment]
True, but still related to Zone.js?

**Comment by JiaLiPassion** [comment]
@webtechy , I don't think it is zone.js problem, it seems like a application issue, you should check the O365SuiteServiceProxy.RequestExecutor.sendPostMessage document for more information.

**Comment by webtechy** [comment]
NB In IE I am still seeing:

> [SPWebPartErrorCode.ScriptLoadError]:: Unable to load web part WebPart.RequirementsFormWebPart.f8e071d2-3f45-4847-842c-558ec9c8d196,Error: Out of stack space script resources due to: {1}. CALLSTACK:: Error at t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-10.003/sp-loader_en-us_58d187e0c698c60c5a3b696238938215.js:88:24458) [<root>] at t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-10.003/sp-webpart-base_en-us_a2923d5eb813f2525c77d8421f93581f.js:146:35649) [<root>] at t.create (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-10.003/sp-webpart-base_en-us_a2923d5eb813f2525c77d8421f93581f.js:146:36091) [<root>] at e.prototype._handleModulePromiseRejection (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-10.003/sp-webpart-base_en-us_a2923d5eb813f2525c77d8421f93581f.js:146:55281) [<root>] at Anonymous function (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-10.003/sp-webpart-base_en-us_a2923d5eb813f2525c77d8421f93581f.js:146:45622) [<root>] at D (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-03-10.003/sp-loader_en-us_58d187e0c698c60c5a3b696238938215.js:88:1887) [<root>]

**Comment by wahin** [comment]
I am using 0.7.2 version of zone.js.
On a sharepoint page in ie11, when I click on Check-in on a publishing page, a dialog box appears to enter version comments. But when i enter any text and click ok, dialog box closes but the page still remains checkedout.

And I can see an exception that says accessing the argument of a function is not allowed in strict mode.
Can you please suggest as it is a roadblock.

**Comment by JiaLiPassion** [comment]
@wahin , please post your error information, and you could try the newest version of zone.js.

**Comment by wahin** [comment]
Error is as stated above, accessing the argument of a function is not allowed in strict mode.
I tried upto 0.7.6 but nothing worked

**Comment by wahin** [comment]
![capture](https://cloud.githubusercontent.com/assets/13927165/24910801/ee254130-1e96-11e7-8ea2-d69812678cce.PNG)
![capture1](https://cloud.githubusercontent.com/assets/13927165/24910802/ee2cafec-1e96-11e7-92dd-28136d33dc6b.PNG)

Attached are the images for this issue. 
Polyfill definition is adding a zone.js of version 0.72.
Polyfills are included in SharePoint master page. 
Now when I try to check-in the publishing page, i get this error.

Also tried with other versions of polyfill - 0.74,0.76, the problem still persists

**Comment by andtii** [comment]
![image](https://cloud.githubusercontent.com/assets/1434571/24910952/b487c9ba-1ec9-11e7-9e7e-ff0ceb4371b6.png)

@wahin @JiaLiPassion We had to remove the 'use strict' in the top of zone.js to get publishing working.

**Comment by JiaLiPassion** [comment]
@wahin , @andtii, is there a reproduce environment or you can click the error stack to check which code call `caller`? thanks.

**Comment by wahin** [comment]
Thanks the issue got resolved with removal of use strict
Also found another alternative to add zone symbol keyword in zone.js.

Thanks for helping out. Really appreciate it

**Comment by wahin** [comment]
I meant replacing this line: var _prop = '_' + prop;
with var _prop = zoneSymbol('_' + prop)

**Comment by howlettt** [comment]
@JiaLiPassion I'm seeing this exception as well, don't have a public environment you can reproduce it in, but here's some info.

Exception:
`Accessing the 'caller' property of a function or arguments object is not allowed in strict mode`

I believe this is the line of code in sp.ui.dialog.debug.js that is triggering the error:
`SP.UI.Dialog.prototype.close.call(this, dialogResult);`

Stack trace:
![image](https://user-images.githubusercontent.com/1786243/28441141-9288dac0-6d66-11e7-94d6-23bf2a2d13bc.png)

Let me know if you need any more information

**Comment by nicholasp** [comment]
hey guys! does angular2 cli working with sharepoint 2013 on premise? i getting errors 'Maximum call stack' at cog mouseover and Uncaught TypeError: Cannot read property 'type' of undefined when trying to access sharepoint webpart properties

**Comment by JiaLiPassion** [comment]
@nicholasp , could you try the latest version of `zone.js`? 0.8.18

**Comment by webtechy** [comment]
@nicholasp Unless there’s been an update, the recommendation is not to use Angular 2 with SPFx as far as I am still aware (Andrew Connell is best contact on this). I could get it to work on Chrome, but not IE.

**Comment by nicholasp** [comment]
@JiaLiPassion i thought i had the latest but you where right i did an npm to latest and worked with chrome. thanks!!! @webtechy thanks for the extra info I'll contact and ask :)

**Comment by angular2fan** [comment]
I am seeing this error on SP 2013. Using ZoneJS 0.8.18. I am using Material Design MatDialogModule and whenever I open the modal window, I am seeing the below error. Unfortunately SP 2013, renders its pages on IE10 mode and therefore I am not able to decide what I can do. Anyhelp is greatly appreciated.

"Accessing the 'arguments' property of a function is not allowed in strict mode"

Accessing the 'callee' property of an arguments object is not allowed in strict mode
Accessing the 'caller' property of a function or arguments object is not allowed in strict mode
