### ISSUE TITLE
`unhandledrejection` even is not fired

### ISSUE THREAD

**Issue by jahtalab** [angular/zone.js#621]
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onunhandledrejection) `unhandledrejection ` event should be fired if the promise rejection is unhandled

**Comment by JiaLiPassion** [comment]
I'll add it when promise has unhandledrejection.

 such spec doesn't exist in Promise A+ spec current version, it seems promise A+ is making the spec of unhandledrejection now, hope it will be compatible with MDN's definition.

**Comment by jahtalab** [comment]
Thanks @JiaLiPassion , FWIW, it is already supported by chrome since version 49

**Comment by JiaLiPassion** [comment]
@jahtalab, you are welcome, I'll make a PR and test it in chrome.
