### ISSUE TITLE
Access wsdl data from Angular2

### ISSUE THREAD

**Issue by bansanguy** [angular/zone.js#623]
Hi All,

I need to access data through a wsdl file. My approach is to convert the wsdl data into json format and later work with the json file. check.wsdl​​ is the associated file with the url and authenticate​ is the method to validate the logged in user credentials of user & password.
Please let me know if it is the right approach to connect to the wsdl from Http. 

​export class WSDLService {

    constructor (private http:Http) { }
    getData:string;
    postData:string;
      let params = new URLSearchParams();
      params.set('user', 'user123');
      params.set ('password', 'pwd@1234');
 
    return this.http
          .get('https://dpls.gf.com:1234/SRDCTM_WebService/Security/WEB-INF/wsdl/check.wsdl'; {method: authenticate}; {search: params})
          .map(request=>request.json())
          .subscribe(
            data => this.getData = JSON.stringify(data),
            error => alert(error),
            () => console.log("Completed!")
          );   
}
Regards, Pradeep

**Comment by JiaLiPassion** [comment]
@bansanguy ， I think your question is not related to zone.js, maybe you should ask it in stackoverflow or post in angular/angular?

**Comment by bansanguy** [comment]
Ok, Will do JiaLiPassion.
