### ISSUE TITLE
Angular 2 not “in the zone” after PhoneGap Build

### ISSUE THREAD

**Issue by rheomatic** [angular/zone.js#636]
Background: My company's mobile app has been in both iOS and Google Play stores since July. It's built using Angular 2, Webpack, and PhoneGap. The working version was built using Angular 2.0.0-beta.17, and we now have a chance to go back and upgrade Angular to the latest released version. We went through the process of rewriting two other internal apps (web only, not ported to mobile) and it went pretty smoothly. They're updated and working. We tackled the mobile app last, using our experience from rewriting the other two apps, and it seemed to be going just as well. The app runs perfectly fine locally in a browser; it also runs perfectly fine using PhoneGap locally, either through the CLI or their desktop app. The problems arise when the app is built at PhoneGap Build (there are no build errors).

What I'm seeing is the simplest change detections not working properly, and it appears that tasks that should be "in the zone" are running outside of the zone and thus, not triggering change detection. Here's the most basic example:

When on the home page of the app, you can choose "register" or "sign in"; either one simply navigates to the respective page. On either page, we're using lifecycle hooks like this:

```javascript
ngAfterViewInit() {
  console.log((<any>window).Zone.current);
  this.isBusy = false;
}
```
`this.isBusy` is just a boolean on the component, which we use like this in the template:

```html
<div class="busyMask" [ngClass]="{busyOff: !isBusy}"></div>
```
I've checked and the lifecycle hooks are working properly and `this.isBusy` gets set... but the view never gets updated. In the browser console I see this:
```javascript
_name:"angular"
_parent:Zone
```
In the PhoneGap debug console, this:
```javascript
_name:"root"
_parent:null
```
I've tried a ton of different ways to get this to work, including removing all Cordova plugins, thinking it must be one of them that's hijacking/changing the Angular's Zone, but even without plugins, the result is the same: no change detection.

I'm pretty sure I _can't_ provide a Plunker that shows the problem since it works everywhere but on an app built with PhoneGap Build (Cordova), so I'm not sure what else I can do but answer questions from someone smarter than me who might be able to help figure this out.

Details for those who care:

Angular: 2.4.7
PhoneGap CLI: 6.5.0

Anyone?

**Comment by JiaLiPassion** [comment]
I use cordova with angular 2,everything work fine,so could you provide a sample reproduce repository so I can try to debug the reason

**Comment by rheomatic** [comment]
Let me know if this is enough: https://github.com/rheomatic/angular-zone-issue636-example

**Comment by JiaLiPassion** [comment]
@rheomatic , could you write a simple build steps?

**Comment by rheomatic** [comment]
1. Install package and dependencies
```sh
npm install
```
2. Build Angular2 app
```sh
npm run build:prod
```
3. Build Cordova app
```sh
cd pgdata/
./pg.pg.sh
```

Alternatively, from inside the pgdata/ directory, you could run cordova/phonegap commands to build or run platform versions of the app.

The Dockerfile.phonegapbuild.* files are used by Jenkins to build and ship the apps to PhoneGap Build, but I removed any sensitive data like app keys and IDs.

**Comment by JiaLiPassion** [comment]
@rheomatic , I can't start the app through phonegap, after pg.pg.sh, should I run

```
 phonegap platform add ios 
```
under pgdata folder?

I did that, but in simulator I just saw a blank page. more detail about build will help.

**Comment by rheomatic** [comment]
@JiaLiPassion, I made a few changes to the repo. I think if you run
```sh
phonegap build ios
```
after what you've already done, you should be able to run the project in Xcode and in the simulator.

**Comment by JiaLiPassion** [comment]
@rheomatic , not working , still blank page. 
When I run phonegap platform add ios, it report error, Error: Source path does not exist: www/res/icons/ios/icon-40.png, so I run 

```
  phonegap platform add ios@4.0.0
```

instead, I can see the page in browser, but in xcode simulator, still blank page, nothing run.

**Comment by rheomatic** [comment]
@JiaLiPassion, there must be something left over from before the latest changes.

Delete /dist, /node_modules, /pgdata/platforms, /pgdata/plugins, /pgdata/config.xml (if it's there), and everything under /pgdata/www **except** for /pgdata/www/res.

Then run:
```sh
npm install
```
```sh
npm run build:prod
```
```sh
cd pgdata/
./pg.pg.sh
phonegap platform add ios
phonegap build ios
```

I just did these same steps and had no errors and the app runs in the simulator. Hopefully this will work for you.

**Comment by JiaLiPassion** [comment]
BTW, I can't find how to install phonegap 6.5.0

**Comment by rheomatic** [comment]
That's the version PhoneGap Build is recommending (specified in config.xml), but it's not a released version we can install, correct. I'm going to roll back the version in config.xml and see if the resulting app works. Maybe that's been the issue all along.

**Comment by rheomatic** [comment]
FYI, I just tried
```xml
<preference name="phonegap-version" value="cli-6.4.0"/>
```
and
```xml
<preference name="phonegap-version" value="cli-6.3.1"/>
```
and neither of those produce a working app, either.

**Comment by JiaLiPassion** [comment]
@rheomatic , I somehow make it output console.log, but I can't reproduce, please see the screenshot.

<img width="792" alt="2017-02-17 10 04 48" src="https://cloud.githubusercontent.com/assets/1442575/23048362/a5575d7a-f4f8-11e6-9703-0e229ea9e584.png">

**Comment by rheomatic** [comment]
@JiaLiPassion, yeah, that's the difficult part of this issue, that building locally shows no sign of the problem. It's only when the app is built at build.phonegap.com that it doesn't work. I'm going to do a complete build locally and submit it to the App Store instead of going the build.phonegap.com route to try and further isolate the problem.

**Comment by pastur** [comment]
http://weblogs.thinktecture.com/thomas/2017/02/cordova-vs-zonejs-or-why-is-angulars-document-event-listener-not-in-a-zone.html

**Comment by JiaLiPassion** [comment]
close for not be able to reproduce.
