### ISSUE TITLE
"Paused in debugger" in Chrome with version "0.7.7"

### ISSUE THREAD

**Issue by fanshuai** [angular/zone.js#638]
<img width="1134" alt="2017-02-15 00 56 43" src="https://cloud.githubusercontent.com/assets/1005487/22939460/b5b37676-f319-11e6-8741-2e0f40dc7d68.png">

When I click a button with `routerLink` for change router url it raise, only with version `0.7.7`.

**Comment by JiaLiPassion** [comment]
@fanshuai , thank you for reporting the issue, I will make a PR to remove it.

**Comment by rsnider19** [comment]
I am seeing the same thing when I run code in `this.zone.runOutsideAngular(() => {...});`. It is happening in 0.7.7, but not in 0.7.6. Even if you remove the `debugger`, it is still going to throw that error. Could there be another issue going on here?

**Comment by JiaLiPassion** [comment]
@rsnider19 , can you post a screenshot of the error or the pause on debugger?

**Comment by rsnider19** [comment]
![image](https://cloud.githubusercontent.com/assets/13546759/23103738/274cab32-f68e-11e6-8d02-d5aef7c0b0c4.png)

**Comment by JiaLiPassion** [comment]
@rsnider19 , thank you for the error screenshot, could you post a repository to reproduce so I can debug into it?

**Comment by rsnider19** [comment]
Sure thing! Here is a plunk. Just hover over the sections of the pie chart a couple times and it will trigger.
https://plnkr.co/edit/gar5B50EwAfrIrdU60m5

**Comment by JiaLiPassion** [comment]
@rsnider19, Thank you, I have made a PR to fix this one.

**Comment by rsnider19** [comment]
Awesome! Thanks!

**Comment by naveedahmed1** [comment]
Should this PR also fix the issues reported here https://github.com/angular/angular/issues/14683#issuecomment-282119653

**Comment by JiaLiPassion** [comment]
@naveedahmed1 , yes, the same issue.

**Comment by naveedahmed1** [comment]
@JiaLiPassion btw when should we expect it to be released?

**Comment by JiaLiPassion** [comment]
@naveedahmed1 , I think it is under review. It will take some time, Thank you.

**Comment by naveedahmed1** [comment]
Is it possible to use the version with your submitted pr while its under review?

**Comment by JiaLiPassion** [comment]
@naveedahmed1 , sure ,you can use the attached file to test.
[zone.js.zip](https://github.com/angular/zone.js/files/802489/zone.js.zip)
