### ISSUE TITLE
Change detection issues in Office add-in after upgrading from 2.0.0 to 2.4.4

### ISSUE THREAD

**Issue by Ibrahim-Islam** [angular/zone.js#646]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Have to manually do `this.cd.detectChanges()` to reflect changes in UI.

**Expected behavior**

Did not have to do `this.cd.detectChanges()` to reflect changes.

**Minimal reproduction of the problem with instructions**

```
this.someService.addItemInList({/..../});
setTimeout(() => {
    this.itemChildComponentsQueryList.last.doSomething();
}, 0);
```
The above code as it was running fine in version `2.0.0` but had to be changed as shown below after upgrading to `2.4.4`.
```
this.someService.addItemInList({/..../});
this.cd.detectChanges();
setTimeout(() => {
	let children = this.itemChildComponentsQueryList.toArray(),
		lastIndex = children.length - 1;
    children[lastIndex].doSomething();
}, 0);
```

**Please tell us about your environment:**

OS: Windows 10 64-bit
Package Manager: yarn/npm
HTTP server: IIS Express

* **Angular version:** 2.0.X

2.4.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

IE 11 (M-integrity level)
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.2.0

* **Node (for AoT issues):** `node --version` =   
Node 6.9.5

https://github.com/angular/angular/issues/14673

**Comment by JiaLiPassion** [comment]
@Ibrahim-Islam , please provide an environment to reproduce, I checked your post in angular/angular#14673, it is a very special environment, so could you provide some sample application and how to install manual for debug?

**Comment by Ibrahim-Islam** [comment]
@JiaLiPassion I can give you a sample application and also instructions on how to debug or step through it. But since this in only reproducible in Outlook Desktop. You have to install it and sideload the sample app yourself. Will that do?

**Comment by JiaLiPassion** [comment]
Yes,sure,a simple manual will help!

**Comment by Ibrahim-Islam** [comment]
@JiaLiPassion I have been able to recreate the issue in a sample app that you can find [here](https://github.com/Ibrahim-Islam/ng2-outlook-imgur). Please follow the directions mentioned in the readme to get it up and running and sideload the app in your Outlook Mail or preferably in Office 365 Mail. Once you get up to that I can take you to Outlook Desktop from there.

**Comment by JiaLiPassion** [comment]
@Ibrahim-Islam , sure ,I have successfully installed the addin, how to reproduce the issue?

**Comment by Ibrahim-Islam** [comment]
@JiaLiPassion That was fast! Next you need to install Outlook Desktop 2016.
1. Link up your account with Outlook Desktop
2. Open a new appointment window
![hffg](https://cloud.githubusercontent.com/assets/6401874/23404738/b1742a66-fde0-11e6-864c-d30b0f1f063c.png)
3. You should see your add-ins in your account in the ribbon or you can access it from "Office add-ins" menu:
![errfg](https://cloud.githubusercontent.com/assets/6401874/23404788/08bf2b18-fde1-11e6-8dcc-f042ac19352d.png)
4. You should see the add-in start up if you don't and instead see the following then just refresh and choose continue to this website:
![ddd](https://cloud.githubusercontent.com/assets/6401874/23404918/aba789f6-fde1-11e6-8933-a969f104f17d.png)
![ddd3](https://cloud.githubusercontent.com/assets/6401874/23404920/af9b3d96-fde1-11e6-8338-27c4f647860a.png)
5. You should be able to get to the login view of the add-in.
6. Now without going any further run this program `C:\Windows\SysWOW64\F12\F12Chooser.exe` and select the app running at `localhost`:
![ddd4](https://cloud.githubusercontent.com/assets/6401874/23404998/2970b560-fde2-11e6-83ea-3a4e19959646.png). This will attach a IE's dev tool scoped to that app only.
7. Now you can continue using the app, attach breakpoints from the Debugger tab, etc.

**Comment by JiaLiPassion** [comment]
@Ibrahim-Islam , sure ,I will try those steps later, and how to reproduce the issue?

**Comment by Ibrahim-Islam** [comment]
@JiaLiPassion The issue is that there is no automatic Change detection by default like I mentioned above. The same app is working fine in Chrome inside Outlook web without any `tick()` or `detectChanges()` but for the change detection to work inside Outlook desktop the following has to be done as shown here: https://github.com/Ibrahim-Islam/ng2-outlook-imgur/blob/master/src/app/%2Balbums/albums.component.ts#L49-L53.

**Comment by JiaLiPassion** [comment]
@Ibrahim-Islam , I will install outlook and try later, I want to know the reproduce steps, how can I run to https://github.com/Ibrahim-Islam/ng2-outlook-imgur/blob/master/src/app/%2Balbums/albums.component.ts#L49-L53, I need to login with imgur? and then click some buttons?

**Comment by Ibrahim-Islam** [comment]
@JiaLiPassion Yes. If you basically login with imgur. It will try to fetch the account's albums and show it in the albums component. I did it this way because it mimics how our actual app works. If you mean running inside outlook office 365 then it should not complain and if it does then just allow and continue. Otherwise, you would have to launch it through VS and IIS Express and that would just be another hassle for you. 

Yes I tested it out in IE 11 and it looks like it behaves the same.

**Comment by JiaLiPassion** [comment]
@Ibrahim-Islam , ok I see. thank you.

> Yes I tested it out in IE 11 and it looks like it behaves the same.

you mean IE 11 outlook web apps also work without detectChange or tick()?

**Comment by Ibrahim-Islam** [comment]
@JiaLiPassion Yes they seem to be working in IE 11 in outlook web. But do not take my work for it. You can try it out as well.

**Comment by JiaLiPassion** [comment]
@Ibrahim-Islam , I can debug the application now, and after I login, I can see the images in the album immediately. that is the behavior you expect, right?

I modified a little code in album.component.ts

```javascript
ngOnInit(){
        let options = new RequestOptions({
            headers: new Headers({
                'Authorization': 'Bearer ' + this.authService.auth.access_token,
            })
        });
        const self = this;
        this.http
            .get('https://api.imgur.com/3/account/'+ this.authService.auth.account_username +'/albums', options)
            .map(v => v.json())
            .flatMap(albumRaw => Observable.from(albumRaw.data))
            .flatMap((album: any) => this.http.get('https://api.imgur.com/3/album/'+ album.id +'/image/' + album.cover, options))
            .map(response => response.json().data)
            .subscribe(album => {
                console.log(album); //if this is visible in console then should be visible in UI also
                self.loaderService.visible = false;
                self.albums.push(album); //should show up on the UI as soon as `albums` have data                
                //this.cd.detectChanges(); //enabling this will cause component changes to be reflected excluding service
                //this.appref.tick(); //enabling with will reflect all changes including components and services
            });
    }
```

**Comment by Ibrahim-Islam** [comment]
@JiaLiPassion Were you able to get the application running as expected in a browser or inside Outlook desktop? Like I mentioned earlier and also in the comments, `AlbumsComponent` is loaded but the changes are not reflected in the view unless I explicitly and manually `detectChanges()` or `tick()`.

**Comment by JiaLiPassion** [comment]
@Ibrahim-Islam , I run the application inside Outlook desktop, and what I do is 

1. login with imageur
2. popup window to login
3. after login,begin to load album
4. two images were loaded and displayed in page.

I did not call detectChanges or tick. 

Is this the correct behavior?

**Comment by Ibrahim-Islam** [comment]
@JiaLiPassion Yes. That is the correct and expected behavior. Makes me wonder why its not working at my end. Can you please give more details on your environment like OS, Outlook version, etc.

**Comment by JiaLiPassion** [comment]
@Ibrahim-Islam , I test it again , and this time, it not working....
And I think I know the reason why it is not refresh.

```javascript
  Office.context.ui.displayDialogAsync(authurl, { height: 65, width: 50, requireHTTPS: true }, (asyncResult) => 
        {
            var dialog = asyncResult.value;
            dialog.addEventHandler(Office.EventType.DialogMessageReceived, (event) => {
                this.authService.auth = JSON.parse(event.message);
                dialog.close();
                this.router.navigate(['/albums']);
            });
        }));       
```

The dialog.addEventHandler are not patched by zone, so the code run inside callback will 
run in root zone, so nothing will refresh.

the solution will be 

```javascript
 Office.context.ui.displayDialogAsync(authurl, { height: 65, width: 50, requireHTTPS: true },  (asyncResult) => 
        {
            var dialog = asyncResult.value;
            dialog.addEventHandler(Office.EventType.DialogMessageReceived, Zone.current.wrap((event) => {
                this.authService.auth = JSON.parse(event.message);
                dialog.close();
                this.router.navigate(['/albums']);
            }));
        });               
```

use zone.wrap to make callback in zone.

In the future, maybe zone.js can patch Office UI event as well

**Comment by Ibrahim-Islam** [comment]
@JiaLiPassion Thanks. That seem to do the trick.
