### ISSUE TITLE
locale not working after updated

### ISSUE THREAD

**Issue by calidion** [angular/zone.js#653]
version change:

0.6.26  →   0.7.7 
moment.locale('zh-CN');

not working.

**Comment by JiaLiPassion** [comment]
what's the error?

**Comment by calidion** [comment]
@JiaLiPassion 

no error, just results turned to english from chinese.

**Comment by JiaLiPassion** [comment]
could you post a plunker to reproduce? only zone.js was upgraded, is that right?

**Comment by calidion** [comment]
seems not.  upgraded with many dependencies.
I would when i have time.
thanks.

**Comment by calidion** [comment]
seems not.  upgraded with many dependencies.
I would when i have time.
thanks.
