### ISSUE TITLE
'Error: Zone already loaded' Conflict on Squarespace website

### ISSUE THREAD

**Issue by lukeclifton** [angular/zone.js#654]
I have developed a simple Angular app built using Angular CLI. Works fine on a demo site in production mode.
When i try and include within a website running on [Squarespace](https://www.squarespace.com/) i get the following error:

```
Uncaught d {__zone_symbol__error: Error: Zone already loaded.
    at d (https://static1.squarespace.com/static/5804a95d5016e1b3e34d642…}
```

I have ensured that my packaged Angular app script is only being included once.
I can only presume that the Squarespace CMS is already including Zone.js perhaps?

Can anyone please give me a little more info on why i would be experiencing a conflict like this and how to prevent it?

I was under the impression that Zone.js does not pollute the global browser namespace. Is that correct?

I've tried all day to try and work out how to fix this but my lack of experience with Zones is not helping.

Running:
Angular @ 2.4.0
zone.js @ 0.7.7

Thanks!

**Comment by JiaLiPassion** [comment]
@lukeclifton , could you provide a sample page to reproduce?

**Comment by lukeclifton** [comment]
@JiaLiPassion Yes good idea. I've setup a new demo website on Sqaurespace.
Intrestingly i now have a different error (see screenshot).
I think this is happening because the Squarespace theme is already WebPack on the page and its conflicting. 

So perhaps this is not a specific Zone.js issue but more of a WebPack issue?

![screen shot 2017-03-02 at 17 56 50](https://cloud.githubusercontent.com/assets/7794283/23520260/15dbfe74-ff72-11e6-9881-24583b2e7871.png)

**Comment by lukeclifton** [comment]
Intrestingly when previewing the site within the admin the app loads without errors. (Ignore the CORS errors, thats expected)
![screen shot 2017-03-02 at 17 55 36](https://cloud.githubusercontent.com/assets/7794283/23520339/72336c7a-ff72-11e6-93b4-5f838a920015.png)

**Comment by JiaLiPassion** [comment]
@lukeclifton , can you package your angular2 app without uglify(minify)?

**Comment by lukeclifton** [comment]
Identified that this issue is being caused by two scripts running the webpack plugin **CommonsChunkPlugin**. Both are using the global variable `window.webpackJsonp`.

Closing this issue as its not really a Zone.js issue.

**Comment by lukeclifton** [comment]
Just found the following webpack config option:
`**output.jsonpFunction**`

The docs says:
The JSONP function used by webpack for async loading of chunks.
Use a different identifier when having multiple webpack instances on a single page.

Only wish i had seen this earlier!
