### ISSUE TITLE
clearInterval on a destroyed interval raises an exception

### ISSUE THREAD

**Issue by alexi2014** [angular/zone.js#656]
The following piece of code raises "TypeError: Cannot read property 'length' of null" exception in Zone._updateTaskCount:
```
        this._interval1 = setInterval(() => {
            // clear interval for the first time
            clearInterval(this._interval1);
        }, 100);
        setTimeout(() => {
            // a bit later clear the destroyed interval - exception
            clearInterval(this._interval1);
        }, 200);

```

Here's a repro plunker - check console log after you open it:
[https://plnkr.co/edit/S0haHUHmxrZHmRql2EjY?p=preview](https://plnkr.co/edit/S0haHUHmxrZHmRql2EjY?p=preview)

As I understand, duplicate call to clearInterval on the same interval should not raise an exception (and doesn't do it with standard implementation in browsers).

**Comment by JiaLiPassion** [comment]
@alexi2014, this has been fixed by this PR #642, please wait for the next release.

**Comment by alexi2014** [comment]
Nice, thanks!
Could you advise me to what zone.js version I need to downgrade my app to get rid of this exception (it seems to be a recently introduced regression)?

**Comment by JiaLiPassion** [comment]
@alexi2014, you can downgrade to 0.7.6, the error will disappear.

**Comment by alexi2014** [comment]
@JiaLiPassion - indeed, thank you so much!

**Comment by naveedahmed1** [comment]
@mhevery should your recent merge https://github.com/angular/zone.js/commit/eb9250da94b29fc0502b0d7f12069e36adebfeac also fix this issue?

**Comment by JiaLiPassion** [comment]
@naveedahmed1 , yes , it also fix this one.

**Comment by naveedahmed1** [comment]
So this issue can also be marked as closed. Can you please also share when should we expect next release with this fix?

**Comment by JiaLiPassion** [comment]
@naveedahmed1 , yes, this can be closed, sorry I don't know when it will be released, but I think it will be released soon.

**Comment by mhevery** [comment]
I am hoping to cut a release this week.
