### ISSUE TITLE
Overriding native function can lead to unwanted side effect

### ISSUE THREAD

**Issue by ssougnez** [angular/zone.js#666]
I'm currently trying to start a project with "angular4" and "ckeditor5" and I noticed that I'm not able to use "ckeditor5" because of "zone.js". The thing is that "ckeditor5" is using "isNative" method from "lodash" library to determine if "addEventListener" is a native method or not and then, based on that, do its stuff. However, when "zone.js" is included un the page, "isNative" returns "false" for "addEventListener". Indeed:

`document.getElementById('XXX').addEventListener`

returns 

`function addEventListener() { [native code] }`

when "zone.js" is not referenced and:

`function addEventListener(){return f(this, arguments)}`

when it is, making the "isNative" function of "lodash" not really reliable anymore (this could be argued as the function is indeed not native anymore, but at the end of the day, "addEventListener" is supposed to be native). 

The real source of the issue is arguable. Indeed, separately, every library work correctly but it's once we associate them that the problem occurs. I posted an issue on "ckeditor github" (https://github.com/ckeditor/ckeditor5/issues/413) as at first I didn't know where the issue came from and a dev over there said something interesting:

> Anyway, there are two options – either zone.js fixes this or we do. From a puristic POV I'd say that it should be zone.js. It's very unlikely that they'll stop changing the native prototypes, so at least they could fix the toString() properties of functions they assign to native prototypes. This would fix the root of the issue and prevent similar errors in the future (we're using Lodash's isNative() function, so there may be more libraries doing so).

Maybe the solution he proposed could be the correct one if it makes "isNative" function returns the correct value. 

Otherwise, I think it could be interesting to discuss about a solution.

**Comment by JiaLiPassion** [comment]
@ssougnez, thank you for reporting the issue, we will make isNative return true for all methods which were patched by zone.js

**Comment by ssougnez** [comment]
Cool, thanks :-D

**Comment by ssougnez** [comment]
Hi, would you have an estimate of the date for the release of the version with this fix? 

Thanks

**Comment by JiaLiPassion** [comment]
Sorry for the late reply,I will try to fix this one this weekend, I will update the status here.

**Comment by ssougnez** [comment]
Awesome, thanks a lot.

**Comment by JiaLiPassion** [comment]
@ssougnez , can you test the attached zone.js to see the problem is gone or not? thank you.
[zone.js.zip](https://github.com/angular/zone.js/files/852450/zone.js.zip)

**Comment by ssougnez** [comment]
@jribble , works like a charm ;-)

**Comment by JiaLiPassion** [comment]
@ssougnez , ok , thank you for confirm.
