### ISSUE TITLE
Wrapper function doesn't return orignal function's result

### ISSUE THREAD

**Issue by zzx88991** [angular/zone.js#667]
I am using ASP.NET Webform (yeah,  it is legacy code..) with `<asp:UpdatePanel> `and `<AsyncPostBackTrigger>`.
When a button click triggers a async postback, `event.onsubmit` from `<form onsubmit="javascript:return WebForm_OnSubmit();">` will be called and return the validation result. However it is not returned once `zone.js` wraps the event handler, resulting the request not passing validation.

The source code here shows that the wrapper function doesn't return the result of 
https://github.com/angular/zone.js/blob/master/lib/common/utils.ts#L89

```javascript
const wrapFn = function(event) {
        let result;
        result = fn.apply(this, arguments);

        if (result != undefined && !result) event.preventDefault();
};
```

Not sure what it the purpose of this code not returning `result`. Thanks for taking a look.

**Comment by JiaLiPassion** [comment]
@zzx88991 , thank you for posting the issue, I will make a PR to fix it.

**Comment by JiaLiPassion** [comment]
@zzx88991 , I have further question about this one, I am not familiar with ASP.NET, current zone.js implementation just call event.preventDefault when eventHandler return false, so in your code, the form will not submit but you will directly use the eventHandler return value somewhere else, is that right?

**Comment by zzx88991** [comment]
Yes, you are right. The eventHandler is called somewhere else before the the form is submitted. I am just curious why `wrapFun` doesn't `return  result`

**Comment by JiaLiPassion** [comment]
@zzx88991 , yes, it should return , I just want to create test case to prove it.
