### ISSUE TITLE
0.8.1 breaks on phantomJS

### ISSUE THREAD

**Issue by paulsouche** [angular/zone.js#674]
Hi,

I have an issue since this [commit](76fa891b88f85bb975ac69c23e620c915e71bf84) on phantomJS 2.2.1.

```
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  TypeError: Attempted to assign to readonly property.
  at karma-shim.js:133326
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  TypeError: Attempted to assign to readonly property.
  at karma-shim.js:133326
```

Line is [here](https://github.com/angular/zone.js/blob/master/lib/zone.ts#L1792)

I think one of the property stack or zoneAwareStack must be readonly but I can't figure out why ? Everything works fine on chrome or when downgrading on 0.8.0.

Thanks

**Comment by JiaLiPassion** [comment]
@paulsouche , could you provide a reproduce repo? the code https://github.com/angular/zone.js/blob/master/lib/zone.ts#L1792 not newly added in 0.8.1, so maybe some other logic goes wrong. thanks.

**Comment by paulsouche** [comment]
@JiaLiPassion we have several private repositories but you can reproduce with [this starter](https://github.com/paulsouche/ionic2-webpack2-starter). I've just updated it to have same dependencies.

**Comment by JiaLiPassion** [comment]
@paulsouche , thank you for the repo, I think I have found the reason , and I will fix it soon.

**Comment by paulsouche** [comment]
Great ! Glad it helps. Thank you for the great work anyway

**Comment by paulsouche** [comment]
Everything's fine since 0.8.2. Thank you
