### ISSUE TITLE
Publish 0.4.2!

### ISSUE THREAD

**Issue by caitp** [angular/zone.js#68]
Good news! With the fixes introduced since 0.4.1 shipped, the angular 2 demo apps work beautifully on WebKit Nightly. (Unfortunately, failures in shipped versions of Safari, due to broken Map implementation in JSC, and likely other things).

It would be great to be able to run tests against WKNightly so that there's a bit more coverage for iOS support, but first things first, we should publish the latest fixes and use them in the angular tree.

**Comment by btford** [comment]
agree

**Comment by btford** [comment]
landed as 3a3dae4295657fb8e09f6025cabb984fed87a38f.

**Comment by caitp** [comment]
Good stuff, thanks
