### ISSUE TITLE
zone.js prints into the console: Error: STACKTRACE TRACKING

### ISSUE THREAD

**Issue by DzmitryShylovich** [angular/zone.js#684]
Repro: http://plnkr.co/edit/lU32vBJY9KYXZUTW7GQQ?p=preview

Probably related to https://github.com/angular/zone.js/issues/661 (https://github.com/angular/angular/issues/15185#issuecomment-287306883)

**Comment by JiaLiPassion** [comment]
this console output has been removed in 0.8.4

**Comment by Martin-Wegner** [comment]
@JiaLiPassion this is not true: https://github.com/angular/angular/issues/15185#issuecomment-287306883

**Comment by JiaLiPassion** [comment]
sorry guys, my mistake, it has been fixed but not released.

**Comment by shwedberlin** [comment]
v 0.8.12 still not released? 
Why then is this closed?

**Comment by JiaLiPassion** [comment]
@shwedberlin , this one has been fixed in 0.8.4, it should not exist in 0.8.12.

**Comment by shwedberlin** [comment]
@JiaLiPassion , ok, maybe we are talking about different consoles? I mean now especially VisualStudio Debug Output when running in IE11. 
Only if start in IE, in Chrome there are no messages.
