### ISSUE TITLE
HTMLCanvasElement.toBlob callback is run outside current zone

### ISSUE THREAD

**Issue by nicolashenry** [angular/zone.js#696]
[HTMLCanvasElement.toBlob](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob) callback is run outside current zone.
It seems that this method is not wrapped by zone.js.

**Comment by JiaLiPassion** [comment]
thank you for posting the issue, I will wrap it.

**Comment by clarkorz** [comment]
It seems that this patch cause Safari throws an error
```
SecurityError (DOM Exception 18): The operation is insecure.
toBlob
```

**Comment by JiaLiPassion** [comment]
@clarkorz, could you provide the `safari` version and `os` version? thank you.

**Comment by clarkorz** [comment]
Safari 11.0.1 (12604.3.5.1.1)
Mac 10.13.1 (17B1003)

We are trying to use image-compressor in our angular5 project. related issue: https://github.com/xkeshi/image-compressor/issues/17
