### ISSUE TITLE
window.onbeforeunload does not work with v0.8.5 in Chrome

### ISSUE THREAD

**Issue by StevenSongToronto** [angular/zone.js#702]
With v0.8.5, the following code cannot cause Popup to show in Chrome. It is ok with IE11. But v0.7.4 has no this issue in Chrome.
window.onbeforeunload = function(e) {
  return 'onbeforeunload';
};

**Comment by JiaLiPassion** [comment]
I think you should do like this

```javascript
window.onbeforeunload = function(e) {
  e.returnValue = 'onbeforeunload';
return 'onbeforeunload';
};
```

**Comment by StevenSongToronto** [comment]
Yes. Adding e.returnValue can fix the problem with Chrome.
