### ISSUE TITLE
Angular2 app freezes during initial load - zone.js

### ISSUE THREAD

**Issue by mazhisai** [angular/zone.js#703]
Hi,

I have an angular2 app that freezes on Edge during the initial load. Upon investigation, my guess is the freeze is caused when Zone.js is invoked ( i may be wrong). there is a ton of garbage collection happening causing the delay. you can find the screenshot below. 

![image](https://cloud.githubusercontent.com/assets/26371384/24438962/fccae010-13ff-11e7-8d57-aff823d8e754.png)

Any inputs on what might be causing this and how to address it would be greatly appreciated.

thanks!

**Comment by JiaLiPassion** [comment]
can you provide a reproduce repo? thanks

**Comment by mazhisai** [comment]
Sorry for the delay in responding. Please find the attached diagsession file that was exported from Edge perf session. I am just using the angular2-webpack-starter app (https://github.com/AngularClass/angular2-webpack-starter) for my repro and i tried refreshing three times to get enough data. as you can see, in each instance there is atleast a second delay. 

It gets worse as you have more components in your app. In my app, i have 177 components and by adding/removing the components i can see the load time change significantly but even if i gut out most of the components, i still see ~3s loadtime in my app. 

My question is, is there anything i can do to optimize this?

![image](https://cloud.githubusercontent.com/assets/26371384/24691045/109a83ee-1986-11e7-8b83-15d339543e06.png)


[Angular2Webpack.zip](https://github.com/angular/zone.js/files/895235/Angular2Webpack.zip)

**Comment by irowbin** [comment]
Same here ... Except chrome, The IE, Firefox and MSEdge are freezes while booting the app. Using angular version 4xx and webpack v2xx. Can't find the solutions.

**Comment by mazhisai** [comment]
hey guys, any thoughts? could someone explain what happens in the invoke call? that would help me investigate on my end if there is anything i can do differently. thanks!

**Comment by JiaLiPassion** [comment]
@mazhisai , I will check it later, could you try the attached zone.js to check the problem still exists?
[zone.js.zip](https://github.com/angular/zone.js/files/914801/zone.js.zip)

**Comment by mazhisai** [comment]
thanks @JiaLiPassion will give it a try

**Comment by mazhisai** [comment]
Hi @JiaLiPassion  sorry for the delay in response. i tried it out and i still see the same issue. thanks!

**Comment by JiaLiPassion** [comment]
@mazhisai, ok, I will try with the repo you posted above to debug what happened.

**Comment by mazhisai** [comment]
Thank you. please let me know if I can help in anyway.

**Comment by JiaLiPassion** [comment]
@mazhisai , I use Edge to debug the repo, I think the reason maybe related to Edge F12 browser tool.

Edge browser_tools add DOMNodeAdded/Removed listener for maybe debug or some other usages, so when angular load DOM, render page, the callback 
```javascript
	function __BROWSERTOOLS_CONSOLE_SAFEFUNC() { [native code] } 
```

will be called.

I debug the zone.js code, zone.js didn't do anything, just addEventListener and invoke the eventListener callback, so I think it maybe an Edge feature?

**Comment by mazhisai** [comment]
Hi @JiaLiPassion  - I do see the similar delay in Chrome. However chrome doesn't freeze, and Edge does.

**Comment by JiaLiPassion** [comment]
@mazhisai, I tried chrome, it didn't trigger any DOMNodeAdded/Removed listener callback even I open chrome developer tool.
