### ISSUE TITLE
circular reference when JSON.stringify an element with attached event listener

### ISSUE THREAD

**Issue by sod** [angular/zone.js#705]
zone.js might break code where an object has an HTMLElement inside and another code tries to JSON.stringify it.

### Without zone.js
HTMLElement is serialized to `{}` by `JSON.stringify`:
![image](https://cloud.githubusercontent.com/assets/905328/24505799/8b9f3226-155b-11e7-9b4f-a1319134c95f.png)

### With zone.js 0.8.5 and an event attached to the element
![image](https://cloud.githubusercontent.com/assets/905328/24505723/3d4dbcd2-155b-11e7-847e-9ceba6f19a88.png)

**Comment by JiaLiPassion** [comment]
@sod, thank you for posting the issue, I will make a PR to fix this one.
