### ISSUE TITLE
Can't use zones with jsdom

### ISSUE THREAD

**Issue by DaveMBush** [angular/zone.js#708]
I'm trying to run jsdom to run my angular2 test with karma.  JsDom tries to set onreadystatechange to null and fails.  The problem exist because jsdom doesn't define onreadystatechange using defineProperty() but zones sets the property as readonly in property-descriptor.ts (line 73).

Adding a setter seems to fix the problem
```
  Object.defineProperty(XMLHttpRequest.prototype, 'onreadystatechange', {
    enumerable: true,
    configurable: true,
    get: function() {
      return this.orsc;
    },
    set: function(f) {
      this.orsc = f;
    }
  });
  const req = new XMLHttpRequest();
  req.onreadystatechange = function(){}
  const result = !!req.onreadystatechange;
```

**Comment by JiaLiPassion** [comment]
@DaveMBush , which version of zone.js you are using, I think this has been fixed in earlier release.

**Comment by DaveMBush** [comment]
Version 0.8.5

**Comment by JiaLiPassion** [comment]
@DaveMBush , could you provide a reproduce repo?

**Comment by DaveMBush** [comment]
https://github.com/DaveMBush/Ng2-JsDom
