### ISSUE TITLE
Change detection not fired when using fs

### ISSUE THREAD

**Issue by MitchTalmadge** [angular/zone.js#710]
Hi,

I am using `Electron 1.6.2`, `Angular 4.0.0`, and `zone.js 0.8.5`. My application loads some projects from a file within a service using `fs`, as seen here:

```typescript
private projects = new ReplaySubject<ETProject[]>(1);

...

/**
 * Loads the projects from the disk. Additionally, creates the projects file if it does not exist.
 */
public loadProjects(): void {
    fs.exists(ProjectService.PROJECTS_FILE_PATH, exists => {
        if (exists) {
            fs.readFile(ProjectService.PROJECTS_FILE_PATH, 'utf8', (err, data) => {
                if (err) {
                    console.log(err);
                    this.projects.next([]);
                } else {
                    this.projects.next(JSON.parse(data));
                }
            });
        } else {
            this.projects.next([]);
        }
    });
}

/**
 * @returns A ReplaySubject that emits an array of saved projects.
 */
public getProjects(): ReplaySubject<ETProject[]> {
    return this.projects;
}
```

In my component where I list the projects, I subscribe to `projects` like so: 

```typescript
projects: ETProject[] = [];

...

ngOnInit() {
    // Get the array of projects
    this.projectService.getProjects().subscribe(projects => {
        this.projects = projects;
    });
}
```

The problem I'm running into is that when the application starts, the subscription _does_ receive the array of projects and it updates the variable in the component, but the UI does not redraw the list of projects until I click on a button somewhere else on the page.

To solve this I injected the `ChangeDetectorRef` and force detection of changes inside the subscription:

```typescript
ngOnInit() {
    // Get the array of projects
    this.projectService.getProjects().subscribe(projects => {
        this.projects = projects;
        this.changeDetectorRef.detectChanges();
    });
}
```

This works, but I find it annoying that I must remember to detect changes every time I use one of my `ProjectService`'s methods that involves `fs`. I found this file https://github.com/angular/zone.js/blob/master/lib/node/fs.ts which I assume is supposed to solve this problem, but evidently it does not. Am I doing something wrong?

**Comment by JiaLiPassion** [comment]
@MitchTalmadge , if you are using Electron, you should load zone-mix.js to patch both browser and node,  I don't know what the current Electron project structure, but maybe you can replace zone.js with zone-mix.js in electron polyfill.ts, it should resolve your issue.

**Comment by MitchTalmadge** [comment]
@JiaLiPassion That fixed it immediately. Thanks so much!! Is there documentation on this? Maybe I missed it.

For reference, in `polyfills.ts` I changed this:

```require('zone.js/dist/zone');```

to this: 

```require('zone.js/dist/zone-mix');```

**Comment by JiaLiPassion** [comment]
Glad to help, the document is a little difficult to find, here it is, https://github.com/angular/zone.js/blob/master/STANDARD-APIS.md
