### ISSUE TITLE
Promise run to completion?

### ISSUE THREAD

**Issue by elierotenberg** [angular/zone.js#713]
Hello,

I'm currently writing a middleware for Koa, the Node HTTP server, to wrap each incoming request handler in its zone to provide isolation, relevent stack traces and timing information (a typical zone.js use case).

I'd like to write a function which runs a handler function and returns a Promise, which rejects if an uncaught exception is thrown in the Zone, and otherwise resolves when there is no more work to do.

After tinkering for a while, I still don't achieve this behavior.

Here's where I'm currently at:

```js
import 'zone.js';
const { Zone } = global;

const nextTick = () =>  new Promise(resolve => process.nextTick(resolve));

const createPromiseZoneSpec = (
  resolve,
  reject,
  {
    name,
    onFrame,
    ctx,
  },
) => ({
  name,

  onInvoke(
    parentZoneDelegate,
    currentZone,
    targetZone,
    delegate,
    applyThis,
    applysArgs,
    source,
  ) {
    const runFrame = () =>
      parentZoneDelegate.invoke(
        targetZone,
        delegate,
        applyThis,
        applysArgs,
        source,
      );
    onFrame(ctx, runFrame);
  },

  onHandleError(parentZoneDelegate, currentZone, targetZone, err) {
    reject(err);
  },

  onHasTask(delegate, current, target, hasTaskState) {
    if (!hasTaskState.microTask && !hasTaskState.macroTask) {
      resolve();
    }
  },
});

export default function runZoneInPromise(
  start,
  { name, onFrame = (ctx, runFrame) => runFrame(), ctx = null },
) {
  return new Promise((resolve, reject) =>
    Zone.current
      .fork(
        createPromiseZoneSpec(resolve, reject, {
          name,
          onFrame,
          ctx,
        }),
      )
      // Run 'start' in next tick to avoid Zalgo
      .run(() => nextTick().then(start)));
}
```

This seems to work okay when no exception is thrown, however, the rejection on uncaught exceptions doesn't seeem to work and I can't find why:

```js
describe('runZoneInPromise', () => {
  it('runs no-op function', () =>
    runZoneInPromise(() => void 0, {
      name: 'no-op',
    }));

  it('runs throwing function', done =>
    runZoneInPromise(
      () => {
        throw new Error('test');
      },
      {
        name: 'throwing',
      },
    )
      .then(() => done(new Error('should have thrown')))
      .catch(err => done()));
});
```

The first test succeeds, the second test fails (`Error: should have thrown`).

Any idea what is wrong with my implementation? Would it be useful to include a wrapper for this (seemingly) typical use-case in zone.js?

**Comment by elierotenberg** [comment]
For the record, my setup is:
- Windows 10
- Node 7.8.0
- `babel-register` 6.24.0 (from within `mocha` CLI)
- `babel-present-env` with `targets:  { node: 'current' }`

**Comment by elierotenberg** [comment]
For some reason unclear to me, this seems to work okay if I replace
```js
      // Run 'start' in next tick to avoid Zalgo
      .run(() => nextTick().then(start)));
```
with
```js
      // Run 'start' in next tick to avoid Zalgo
      .run(() => process.nextTick(start));
```

It doesn't seem to be related with the return value of the `.run()` callback, since the following doesn't work either:
```js

      // Run 'start' in next tick to avoid Zalgo
      .run(() => {
        nextTick().then(start)):
     });
```

Any idea why? I'd like to understand what happens.

**Comment by JiaLiPassion** [comment]
I am not sure I fully understand your middleware purpose, and the reason the code not work is a little tricky.

```
const nextTick = () =>  new Promise(resolve => process.nextTick(resolve));
```

here a promise was returned, and it use process.nextTick

error occurs in promise will not trigger onHandleError immediately (maybe not at all), in this case, it will be triggered after onHasTask(resolve) code.

But I am not sure your goal, so I don't quite sure how to modify your code better.

**Comment by elierotenberg** [comment]
Wow thanks, that was indeed subtle. Thanks for your help.

To clarify the purpose of my library, the goal is to run each incoming request handler in its own zone, to provide a basic isolation mechanism à la PHP. With each incoming request handler wrapped in its own zone, we can do things like measure self CPU time usage per request, resource cleaning (SQL connections...), etc.

I think I can close this issue now, thanks again for your help.
Btw, kudos for this lib which is simply mind-blowing.
