### ISSUE TITLE
SharePoint issues with zone.js > 0.7.6

### ISSUE THREAD

**Issue by andtii** [angular/zone.js#720]
There seems to be new issues with zone.js and SharePoint from versions higher then 0.7.6 @JiaLiPassion fixed some of them in https://github.com/angular/zone.js/issues/618

but running on the latest zone.js version there is new conflicts 

![image](https://cloud.githubusercontent.com/assets/1434571/24661730/74ed6a56-1953-11e7-8259-d9f94fa6e218.png)

@JiaLiPassion The account you have used before is still available if you want to take a look

**Comment by JiaLiPassion** [comment]
@andtii , sure, I think this related to #717, you can try the dist.zip in https://github.com/angular/zone.js/issues/707, I think it will resolve your issue.

**Comment by andtii** [comment]
@JiaLiPassion Also we need the #691 fix because we have the perf issues aswell

**Comment by JiaLiPassion** [comment]
@andtii ,sure , it is under review, and it should be released soon.

**Comment by andtii** [comment]
@JiaLiPassion Yes it works with the dist in #707

**Comment by JiaLiPassion** [comment]
you can find the newest release here
[dist.zip](https://github.com/angular/zone.js/files/916066/dist.zip)
