### ISSUE TITLE
broken table in standard-apis

### ISSUE THREAD

**Issue by Jinkwon** [angular/zone.js#725]
I found some broken table render in markdown page.

https://github.com/angular/zone.js/blob/master/STANDARD-APIS.md

![2017-04-06 5 50 59](https://cloud.githubusercontent.com/assets/1798916/24745708/9b287518-1af1-11e7-9656-94dbfecb67f8.png)

**Comment by JiaLiPassion** [comment]
Thanks, This has been fixed in  #697
