### ISSUE TITLE
Distribute closure externs for Zone

### ISSUE THREAD

**Issue by alexeagle** [angular/zone.js#727]
Since Zone.js is a "prollyfill" and since multiple angular apps might be on a single page, we don't want to bundle it together with the app.
This means closure compiler needs an externs file to avoid renaming Zone's symbols.
I currently have such an externs here:
https://github.com/alexeagle/closure-compiler-angular-bundling/blob/master/vendor/zone_externs.js
but it should be distributed with Zone.js so that users don't have to fetch it themselves.

**Comment by JiaLiPassion** [comment]
@alexeagle , I would like to make this file, and add test cases to make sure it is ok through optimized: advanced for closurescript compiler. But I am totally new to closurescript, so please help me to review my work after I made the PR.

**Comment by alexeagle** [comment]
Hi!

A bit of context. Ideally this extern file should be generated from the TS sources, by github.com/angular/tsickle - this is what we do internally at Google. But I think this is probably out-of-scope for this issue; we can hand-edit the externs file for now. @mhevery might have some opinion about whether the API is stable enough that we'll rarely have to update the externs.

Testing is the right thing to do. Here's where the material2 project added a test, but it only verifies that compilation succeeds, not that the application can access the library APIs at runtime:
https://github.com/angular/material2/commit/51cfb5f75f6e8efbb3cd52ba0113c7301e057c4a
We also need some test that fails if one of the externs is removed from the file.

(by the way, closurescript isn't a thing - there is clojurescript which is actually a different language, that confusingly produces code that can be consumed by closure compiler. closure != clojure)

**Comment by JiaLiPassion** [comment]
@alexeagle , Thank you so much for all those information, I will try to understand and build the externs file by hand.

> (by the way, closurescript isn't a thing - there is clojurescript which is actually a different language, that confusingly produces code that can be consumed by closure compiler. closure != clojure)

Thank you for pointing that out!

**Comment by alexeagle** [comment]
You don't need to rebuild the externs file, the one I pointed to works fine.

**Comment by JiaLiPassion** [comment]
@alexeagle , got it, I will just build the test cases and let you review later, thank you!

**Comment by mhevery** [comment]
I think hand coded externs file is fine for now.

**Comment by JiaLiPassion** [comment]
@mhevery ,got it,I have made a new one based on @alexeagle 's version, I will make a PR to let you review later.

**Comment by mhevery** [comment]
awesome

**Comment by JiaLiPassion** [comment]
@alexeagle , @mhevery , I have made a PR https://github.com/angular/zone.js/pull/731, pleas review.

1. I add more type definition for all Zone type
2. add test cases for closure build
