### ISSUE TITLE
addEventListener and removeEventListener doesn't work with EventListenerOptions

### ISSUE THREAD

**Issue by vevnin** [angular/zone.js#737]
Please see details about EventListenerOptions specification here:
https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md
https://www.chromestatus.com/feature/5745543795965952

The issue is that third parameter of addEventListener and removeEventListener methods is treated as boolean useCapturing parameter. If EventListenerOptions object is used instead then event listener will not be removed with removeEventListener call. This happens because findExistingRegisteredTask task uses reference equality (===) to determine equality of useCapturing parameter. This way it's possible to remove event handler only by passing exactly same object of EventListenerOptions to removeEventListener call.

This behavior seems very counter-intuitive to me. Please add support of EventListenerOptions parameter.

**Comment by JiaLiPassion** [comment]
@vevnin , thank you for posting the issue, I will check it.
