### ISSUE TITLE
Zone.js breaks default behaviour of Promises

### ISSUE THREAD

**Issue by Nilos** [angular/zone.js#743]
During debugging of Performance issues I found out that Zone.js handles all Promise.then callbacks in one large function call. This can lead to problems if an application has got a lot of async tasks returning at once and to a very long stop of the whole js cycle.

I have attached a screenshot of an example timeline.
![screen shot 2017-04-20 at 18 11 42](https://cloud.githubusercontent.com/assets/1300836/25241020/d695f9a0-25f4-11e7-9d9f-e3f6d37f3494.png)

**Comment by JiaLiPassion** [comment]
@Nilos , zone.js only wrap promise.then into a ZoneAwarePromise, in the wrap logic, there is no long time operation. The logic is the very similar with native promise

**Comment by Nilos** [comment]
Mmh it looks like you are correct and native Promises actually behave like that too.
