### ISSUE TITLE
How to leave nested zones?

### ISSUE THREAD

**Issue by CSchulz** [angular/zone.js#745]
I am forking over multiple levels the current zone and want to achieve to return to the parent zone.

```
Root
| -> Zone A
|   | -> Zone B
```

Zone A gets forked from Root and Zone B gets froked from A.

I am using Observables and have noticed that the execution of the success callback in Zone A is called in Zone B.

Is there a way to leave Zone B?

**Comment by JiaLiPassion** [comment]
@CSchulz , can you post some sample code? thanks.

**Comment by CSchulz** [comment]
Here it is, I was too fast with creating the issue. :laughing: 

http://plnkr.co/edit/mOVNKiBAGTQD6KWFg8dg?p=preview

**Comment by JiaLiPassion** [comment]
@CSchulz , you can use the Zone you want at any time, in this case, you can just do like this.
http://plnkr.co/edit/TzzzUfeuLngcEzziOBFF?p=preview

**Comment by CSchulz** [comment]
Hum, I don't see a real difference just some more logging statements, right?

I want to see in line 56 Zone A instead of Zone B. The inner Zone B should be left and Zone A should handle the success callback of the outer Observable.

http://plnkr.co/edit/Z1oEA3FxAPQoyMw9dqT4?p=preview

**Comment by JiaLiPassion** [comment]
@CSchulz , sorry , I didn't click save....
http://plnkr.co/edit/8bsipFXxgzACdOSN6mlb?p=preview

**Comment by CSchulz** [comment]
Thanks. So it is okay to directly access the parent?

Would it not be nice to have the possiblity to "leave" the current zone per command like Zone.current.leave to force an exit.

**Comment by JiaLiPassion** [comment]
I use Zone.parent to just for convenience, you can keep the zone which forked with name A and use zoneA here.

And in fact, it is not leave, the real result is 

Root
  -> Zone A
     -> Zone B
        -> Zone A
     -> Zone B
  -> ZoneA
-> Root

(we don't put angular zone here to simplify this issue)

 So, I believe there is no way to force to leave current zone until  current invoke/invokeTask finished or error occurs.
