### ISSUE TITLE
Remove CSP incompatible Function evals

### ISSUE THREAD

**Issue by ishitatsuyuki** [angular/zone.js#749]
The offending code is [here](https://github.com/angular/zone.js/blob/7b43b51239d21753f50df04eff3dac6f89e5328c/lib/common/utils.ts#L554-L561).

First, there's no way to turn off this violating implementation, which was what `ngCsp` did in AngularJS 1. Browsers report it, regardless if you're catching the exception or not.

Second, I don't see an clear performance benefit from doing a `Function`. This is basically JS engine details, and unlike the AngularJS 1 this is not a so complicated logic. If it does run faster, I would like some reference for it.

**Comment by JiaLiPassion** [comment]
@ishitatsuyuki , thank you for posting the issue, this is being discussed and will be removed in later release.

**Comment by ishitatsuyuki** [comment]
Resolved by #748
