### ISSUE TITLE
Problem with v0.8.8 under Chrome only.

### ISSUE THREAD

**Issue by JoelParke** [angular/zone.js#750]
Under Chome and v0.8.8 I find:

     zone.js:1265 Uncaught TypeError: Cannot read property 'apply' of undefined(…)

This is seen at:

            else {
            // result will be null when use inline event attribute,
            // such as <button onclick="func();">OK</button>
            // because the onclick function is internal raw uncompiled handler
            // the onclick will be evaluated when first time event was triggered or
            // the property is accessed, https://github.com/angular/zone.js/issues/525
            // so we should use original native get to retrieve the handler
            var value = originalDescGet.apply(this);
         -->   value = desc.set.apply(this, [value]);
            if (typeof target['removeAttribute'] === 'function') {
                target.removeAttribute(prop);
            }
            return value;
        }

I realize that this isn't released, but I though a heads up might be helpful.  (I only see this on Chrome and not Firefox).

**Comment by JiaLiPassion** [comment]
duplicate with #746, and have been fixed with #747, thank for posting the issue.

**Comment by JoelParke** [comment]
I tested the newest release official 0.8.8 -- which I suspect doesn't have the fix???  If it does, the issue still lives.

**Comment by JiaLiPassion** [comment]
@JoelParke , you can try the attached zone.js, the error still there because dist folder not updated.
[dist.zip](https://github.com/angular/zone.js/files/949369/dist.zip)

**Comment by DaveMBush** [comment]
@JiaLiPassion I just ran using dist.zip and this solves the problem (also had an issue with jsdom which this fixes) when can we get the correct dist into npm?

**Comment by JiaLiPassion** [comment]
@DaveMBush , I am not sure the release date, it should be released soon!

**Comment by JiaLiPassion** [comment]
Has been fixed in 0.8.9, thanks.

**Comment by JiaLiPassion** [comment]
Close for fixed.
