### ISSUE TITLE
Incorrect typing of the ZoneType

### ISSUE THREAD

**Issue by Jack-Works** [angular/zone.js#751]
Cannot use 'new' with an expression whose type lacks a call or construct signature.

```const Zone: ZoneType```

I think zone.js should provide a new() assign like
```
interface ZoneType {
    new(parentZone?: Zone, data?: any): Zone
}
```

// From https://github.com/DefinitelyTyped/DefinitelyTyped/issues/15887

**Comment by JiaLiPassion** [comment]
ZoneType is just an interface, if you want to create new Zone, you should use
```
    Zone.fork(zoneSpec)
```

**Comment by Jack-Works** [comment]
From the existing type file
Zone.fork(...) cannot pass type checking either...
I will try it later.

**Comment by Jack-Works** [comment]
Umm that strange
`

> Zone
< function Zone(parent, zoneSpec) {
            this._properties = null;
            this._parent = parent;
            this._name = zoneSpec ? zoneSpec.name || 'unnamed' : '<root>';
            this._propertie…
> Zone.fork
< undefined
`

**Comment by CSchulz** [comment]
You have to use `Zone.current` to get the current Zone instance and there you should have `fork`

**Comment by Jack-Works** [comment]
So... I should do this right?
```typescript
    Zone.current.fork(Zone.current)
```
And I still question about why Zone has a Constructor code but does not have a constructor typing...

**Comment by JiaLiPassion** [comment]
@Jack-Works , 

you should do like 

```
Zone.current.fork({
  name: 'newZone',
  properties: {},
  onScheduleTask: ....
  ...
});
```

you can only create a new Zone in this way!

**Comment by CSchulz** [comment]
Just for reference:

https://github.com/angular/zone.js/blob/master/dist/zone.js.d.ts#L164
