### ISSUE TITLE
Incompatible with SignalR2.2.1

### ISSUE THREAD

**Issue by saridakis** [angular/zone.js#754]
This block of code in 0.8.7 

desc.get = function () {
        // in some of windows's onproperty callback, this is undefined
        // so we need to check it
        var target = this;
        if (!target && obj === _global$1) {
            target = _global$1;
        }
        if (!target) {
            return null;
        }
        var r = target[_prop] || null;
        // result will be null when use inline event attribute,
        // such as <button onclick="func();">OK</button>
        // because the onclick function is internal raw uncompiled handler
        // the onclick will be evaluated when first time event was triggered or
        // the property is accessed, https://github.com/angular/zone.js/issues/525
        // so we should use original native get to retrieve the handler
        if (r === null) {
            if (originalDesc && originalDesc.get) {
                r = originalDesc.get.apply(this, arguments);
                if (r) {
                    desc.set.apply(this, [r]);
                    if (typeof target['removeAttribute'] === 'function') {
                        target.removeAttribute(prop);
                    }
                }
            }
        }
        var value = target[_prop] || null;
        return value && value.hasOwnProperty(VALUE) ? value[value] : value;
    };
has been changed in version 0.8.8.

You have remove the if ( r === null ) block with something new. For some reason the SignalR2.2.1 version, when it comes to call that function it raises an error, something like 'Cannot read apply of undefined...'. I suppose that this is because, you have remove the if (originalDesc && originalDesc.get) line. Please check this out.

**Comment by JiaLiPassion** [comment]
this has been fixed in #747.
