### ISSUE TITLE
Zone.invoke takes too much time on Edge compared to Chrome and Firefox

### ISSUE THREAD

**Issue by m-a-l-p** [angular/zone.js#757]
Hi,

I have a performance problem with my angular2 app that runs very slow on Edge as compared to Chrome and Firefox. I'm wondering if you could have a quick look on why Zone.invoke takes too much time on Edge as compared to chrome:
![zone-exec-diff_betwee_edge-and-chrome](https://cloud.githubusercontent.com/assets/18435069/25373007/84da1f68-29ca-11e7-943a-6277158d7d89.PNG)

Many thanks,
Toni

**Comment by JiaLiPassion** [comment]
I think this may related to #703, edge add some event listeners for debug when you open F12 developer tool. I didn't do further research about why.

**Comment by m-a-l-p** [comment]
Hi @JiaLiPassion,

Would that cause too much delays on xhr requests as well?
![edge_xhr_delays](https://cloud.githubusercontent.com/assets/18435069/25420755/390ec06c-2a8c-11e7-813f-c640a67a0cdf.PNG)

Many thanks,
Toni

**Comment by JiaLiPassion** [comment]
@m-a-l-p , could you post your repo? xhr cost more time in Edge than chrome, is that right?

**Comment by JiaLiPassion** [comment]
Close for now for not be able to reproduce.
