### ISSUE TITLE
Uncaught TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by karthikeyan-murugan** [angular/zone.js#759]
I'm seeing below are after recent update.

zone.js:1265 Uncaught TypeError: Cannot read property 'apply' of undefined at XMLHttpRequest.desc.get [as ontimeout] (zone.js:1265) at XHRLocalObject.AbstractXHRObject._cleanup (abstract-xhr.js:149) at XMLHttpRequest.xhr.onreadystatechange (abstract-xhr.js:125) at XMLHttpRequest.wrapFn (zone.js:1230) at ZoneDelegate.invokeTask (zone.js:398) at Zone.runTask (zone.js:165) at XMLHttpRequest.ZoneTask.invoke (zone.js:460)

**Comment by JiaLiPassion** [comment]
Has been fixed in 0.8.9, thanks.

**Comment by ExxFortyFive** [comment]
Same issue in 0.8.10 on huawei smartphone (v5.1.1)

'Uncaught TypeError: Cannot read property 'apply' of undefined'

**Comment by JiaLiPassion** [comment]
@ExxFortyFive , can you provide a screenshot or full stack trace? The error should not still exist in 0.8.10, thanks.

**Comment by karthikeyan-murugan** [comment]
This seems to be resolved in latest version. I don't see any errors now.
