### ISSUE TITLE
ngZone with google map lead to heigh CPU and memory leak

### ISSUE THREAD

**Issue by liaosong** [angular/zone.js#775]
My APP build with google map and Angular. when I opened the infowindow, a setTime Recursion will be run and can't stop. Then so many zoneTask accumulated. the same question can be find in [stackoverflow](http://stackoverflow.com/questions/43860609/angular-with-google-map-settime-always-run-lead-to-high-cup-and-memery-leak)

**Comment by liaosong** [comment]
Can I run the google map out side the zone?

**Comment by liaosong** [comment]
I forked a demo and hooked the setTimeout in a plunker. [click here](http://plnkr.co/edit/DvijNePo4s8L9aINFGSU?p=preview)


open the console and click a marker to open the infowindow you will find that

**Comment by JiaLiPassion** [comment]
@liaosong , thank you for posting the reproduce demo, I will check it.

**Comment by JiaLiPassion** [comment]
@liaosong, I just test it , It seems setTimeout only run for limited times, not forever, the code seems to be here, https://github.com/SebastianM/angular-google-maps/blob/4a0665b6be9bd1542e776eca5c76825fa7223fe1/src/core/directives/map.ts#L391

 the `resize` event triggered several times, and it will finally finish.

**Comment by otodockal** [comment]
@JiaLiPassion did you open infowindow?
@liaosong basically you can with plain Google Maps API like this:

```typescript
this.map = this._zone.runOutsideAngular(() => {
    return new google.maps.Map(document.getElementById('map'), {
        zoom: 10,
        center: {lat, lng}
    })
})
```
or use ChangeDetectionStrategy.OnPush, but from my quick testing it's not the solution, but should be...I haven't investigated more yet...

there is an issue for this problem
https://github.com/SebastianM/angular-google-maps/issues/520

**Comment by JiaLiPassion** [comment]
@otodockal , thank you for the information, I will look into it. And I didn't open infowindow, I will test it too.

**Comment by liaosong** [comment]
@otodockal Thank you, I tested run the map outside angular. but it's not the solution too.

**Comment by liaosong** [comment]
@JiaLiPassion when you opened the infowindow, you will find that , I debug it and found the minify code from google map.
![image](https://cloud.githubusercontent.com/assets/3927282/25938392/9934aa2a-3661-11e7-9224-1a57559786bf.png)

**Comment by JiaLiPassion** [comment]
@liaosong , thanks , I have tried with zone.js 0.8.10, and disable patch `timer`, `onProperties`, `EventTarget.addEventListener`, so basically everything run into a environment without `Zone`, but the infinite loop of setTimeout still exists, I think maybe this is infowindow's problem??

I will do more debug later!

**Comment by liaosong** [comment]
@JiaLiPassion I have tried with Angular.js (angular1, with out zone), And there are no setTimeout loop found.

**Comment by JiaLiPassion** [comment]
@liaosong , thanks, can you also post the angular1 plunker?

**Comment by liaosong** [comment]
@JiaLiPassion I'm sorry to misguide you. angular1 with google map has setTimeout loop too. see [this](http://plnkr.co/edit/xxue13jQrevmr28LLz7u?p=preview)

**Comment by liaosong** [comment]
@JiaLiPassion Should I post this issue to Angular?

**Comment by JiaLiPassion** [comment]
@liaosong , I don't know it is angular issue or the angular-google-map issue, could you try the pure google-map to see whether the issue exists? I think it maybe some event handlers cause loop in 
 angular-google-map  library.

**Comment by liaosong** [comment]
@JiaLiPassion I tried the pure google-map and result of without setTimeout loop. In my local project , I didn't use the Angular-google-map component.  I just open a simple infoWindow, as follows:
```
const el = this._elementRef.nativeElement.querySelector('.google-map');

        this._MapLoader.load().then(() => {
            this.map = new google.maps.Map(el, {
                center: {lat: 12.68781, lng: 7.19579},
                zoom: 3,
                scaleControl: true,
                mapTypeControlOptions: { position: google.maps.ControlPosition.LEFT_BOTTOM },
                overviewMapControl: false,
                panControlOptions: { position: google.maps.ControlPosition.RIGHT_CENTER },
                zoomControl: true,
                zoomControlOptions: { position: google.maps.ControlPosition.RIGHT_BOTTOM, style: google.maps.ZoomControlStyle.SMALL },
                overviewMapControlOptions: { opened: true },
                mapTypeId: google.maps.MapTypeId.ROADMAP,
                streetViewControlOptions: { position: google.maps.ControlPosition.RIGHT_BOTTOM }
            })
            this._GMapProvider.setGMap(this.map)
            const marker = new google.maps.Marker({
                position: {lat: 12.68781, lng: 7.19579}
            })
            const infoWindow = new google.maps.InfoWindow({
                content: `<h1>test</h1>`
            })
            marker.setMap(this.map)
            infoWindow.open(this.map, marker)
        }, (err) => {
            console.log(err)
        })
```

**Comment by JiaLiPassion** [comment]
@liaosong , so it maybe the angular-google-map issue. I also think it is not angular 1.x issue, you can post it to angular-google-map again to ask further information.

**Comment by liaosong** [comment]
Oh, I'm sorry, you misunderstand my comment.  I tried the pure google-map in [this](https://plnkr.co/edit/EbC1TtJEIaMQ6eoxDnc3?p=preview), there is not has this issue. My local project with Angular shows at previous comment . the issue is exists.

**Comment by JiaLiPassion** [comment]
@liaosong , oh, you are right, that seems to be an angular issue! I will also do more research later.

**Comment by liaosong** [comment]
@JiaLiPassion Is there any progress？ I have no idea, and It's Important for me.

**Comment by JiaLiPassion** [comment]
@liaosong , I am not looking into it now, maybe you can also post into angular.js google map repository for better help. I will also try to debug it when I have time !

**Comment by otodockal** [comment]
@JiaLiPassion @liaosong in the meantime I created working version with plain Google maps API

http://plnkr.co/edit/piaqp7NqgesZgci6xgS4?p=preview

And yeah, it's not the solution, it only works :)

**Comment by JiaLiPassion** [comment]
@otodockal, @liaosong , thanks, and I tried with the working one(@otockal 's demo and google map official demo), the google map util.js src is https://maps.googleapis.com/maps-api-v3/api/js/28/18/util.js, and not working one is https://maps.googleapis.com/maps-api-v3/api/js/27/13/util.js, so maybe the google map version problem?

**Comment by liaosong** [comment]
@JiaLiPassion @otodockal  Thanks. I have tried the @otodockal's demo, and when I changed the map loader to `load-google-maps-api-2` the issue  disappeared.  I think @JiaLiPassion is right, and I will check it.
thanks @otodockal, you leaded me to a right way.

**Comment by liaosong** [comment]
Update the google map api  version to over 3.28 then this issue will be fix.
