### ISSUE TITLE
hasOwnProperty is not defined when passing in the Window object 

### ISSUE THREAD

**Issue by ajanytime** [angular/zone.js#781]
patchMethod function breaks when passing in the Window object since it has no way to implement the hasOwnProperty function, in particular,

`function patchMethod(target, name, patchFn) {
    var proto = target;
     while (proto && **!proto.hasOwnProperty(name)**) {
         proto = Object.getPrototypeOf(proto);
     }
    if (!proto && target[name]) {
        // somehow we did not find it, but we can see it. This happens on IE for Window properties.
        proto = target;
    }
    var delegateName = zoneSymbol(name);
    var delegate;
    if (proto && !(delegate = proto[delegateName])) {
        delegate = proto[delegateName] = proto[name];
        proto[name] = createNamedFn(name, patchFn(delegate, delegateName, name));
    }
    return delegate;
}`

I'm suggesting fixing it using,

Object.prototype.hasOwnProperty.call(proto, name)

**Comment by JiaLiPassion** [comment]
@ajanytime thanks, I will look into it. Which browser you are testing with?

**Comment by ajanytime** [comment]
@JiaLiPassion I am using,
Google Chrome
Version 47.0.2526.106 (64-bit) on Fedora 23

**Comment by JiaLiPassion** [comment]
@ajanytime , can you post the error details? I test in chrome, that 

```javascript
console.log('hasOwnProperty', window.hasOwnProperty('onload'));
```

will be ok.

**Comment by JiaLiPassion** [comment]
Close for now for not be able to reproduce.
