### ISSUE TITLE
WebComponent Polyfill Conflicts with Angular Forms

### ISSUE THREAD

**Issue by StephenFluin** [angular/zone.js#782]
**Repro:**
http://plnkr.co/edit/aa6KVLbxWTuDTK1U3Le8?p=preview

**Observed Behavior:**
Type something in the input, the title rendered on the page does not update

**Expected Behavior:**
Type something in the input, the title should update

**Additional Information**
Reordering the script imports in `index.html` fixes/breaks this.

This example does not use web components at all, so these polyfills are fighting.

**Versions**
This works in the latest stable Chrome, and fails in the latest stable Firefox.

**Comment by StephenFluin** [comment]
CC: Misko we chatted about this

**Comment by JiaLiPassion** [comment]
@StephenFluin , I just run your plunker demo, when I input something in the input, the title will update, should I change something in index.html?

**Comment by StephenFluin** [comment]
@JiaLiPassion Sorry about that, I forgot the most important part. This works in Chrome and fails in Firefox.

**Comment by JiaLiPassion** [comment]
@StephenFluin , got it, I will try to debug it.

**Comment by JiaLiPassion** [comment]
@StephenFluin , I have made a PR to fix this one, the temp walk around one can be found here.
http://plnkr.co/edit/VKDESsxIFHEv9BprNlmV?p=preview

**Comment by rusmaxim** [comment]
Big thanks for walk around. When using Webcomponents + Angular for Android there are not working almost all rerendering without this.

**Comment by JiaLiPassion** [comment]
@rusmaxim , glad to help!

**Comment by rusmaxim** [comment]
@mhevery 0.8.10 with patch works fine, but 0.8.11 doesn't. Webcomponents + Angular doesn't refresh angular components on changes.

**Comment by JiaLiPassion** [comment]
@rusmaxim, I have confirmed 0.8.11 also work.
http://plnkr.co/edit/uGJEM10uUUIJ3QBLm1a3?p=preview

did you load the `webapis-shadydom.js`?

**Comment by rusmaxim** [comment]
@JiaLiPassion webapis-shadydom.js help. Thanks.

**Comment by rdhelms** [comment]
I know this has been awhile, but I thought I would mention that this fix worked for me using Angular 6:

`polyfills.ts`
```
/***************************************************************************************************
 * Zone JS is required by default for Angular itself.
 */
import 'zone.js/dist/zone';  // Included with Angular CLI.
import 'zone.js/dist/webapis-shadydom.js';  // For webcomponents compatibility
```
The first line is present by default. Adding the second line is what fixed change detection in Firefox for me.

Pretty similar to the above, just seemed preferable to do it in `polyfills.ts` now instead of in `index.html`

**Comment by adrianbarbe** [comment]
@rdhelms I tried your solution, but it didn't work for me. I still have troubles with change detection when I run my application (component) as web-component and it's critical for me. When I run this application as usually, change detection works well.

I'll appreciate any tips or advices.

**Comment by rdhelms** [comment]
@adrianbarbe Is change detection working for you in Chrome but broken in Firefox? The solution above was for that specific case, but if change detection is broken in all browsers then it's probably a different issue.

Would be happy to help debug, but would probably need some more specifics or code example. Hope it works out!
