### ISSUE TITLE
Use passive listeners to improve scrolling performance

### ISSUE THREAD

**Issue by xban1x** [angular/zone.js#790]
After running Lighthouse over my Angular app i get the following in the audit.

[Screenshot of Lighthouse](http://prntscr.com/fanlfc)

and at line 11248
[Screenshot of Polyfills bundle](http://prntscr.com/fanm1g)

I believe there should be a check if the event is a scroll event and if it is attach `passive: true` to it.

**Comment by JiaLiPassion** [comment]
thanks for posting the issue, I will check it.

**Comment by xban1x** [comment]
So, that means i am doing this somewhere on my own and should i somehow supply this actions ??

**Comment by JiaLiPassion** [comment]
@xban1x , I am not sure I totally understand your issue, you mean that the passive options not being passed to the eventlistener?

**Comment by xban1x** [comment]
No, i mean that this means i probably should do so myself somewhere, but i dont know where since i always use HostBinding annotations.

**Comment by JiaLiPassion** [comment]
@xban1x , I will try to make some samples about it, I don't know the detail about the `passive` scroll listener either.

**Comment by aciccarello** [comment]
@xban1x It is probably an angular issue. See angular/angular#8866

**Comment by surbhi290391** [comment]
Hi all,
I am also facing this same issue please guide me how can i solve this... Issue is
1. Does not use passive listeners to improve scrolling performance.
   View Details:
1. ../static-files/21ba665f.js                                Line:0
2. ../v1514934548259/recaptcha__en.js           Line:40

Please help me to get rid to this problem.
Thanks.

**Comment by JiaLiPassion** [comment]
Close it for now because there is an issue in angular repo already.
