### ISSUE TITLE
Unknown variable _global in webapis-media-query.js

### ISSUE THREAD

**Issue by sod** [angular/zone.js#791]
dist/webapis-media-query.js & dist/webapis-notification.js. How are those supposed to be embedded? When I just load them, webpack complains that `_global` is unknown. Or is it just an error in the file and it should read `global`?

[webapis-media-query.js](https://github.com/angular/zone.js/blob/b92b6e31abb384ad4ac3f38ee0df78ba21104684/dist/webapis-media-query.js#L25)
![image](https://cloud.githubusercontent.com/assets/905328/26311339/44cc877c-3f04-11e7-87e4-f432cc22cf67.png)

--

[webapis-notification.js](https://github.com/angular/zone.js/blob/b92b6e31abb384ad4ac3f38ee0df78ba21104684/dist/webapis-notification.js#L22)
![image](https://cloud.githubusercontent.com/assets/905328/26311279/05f276b0-3f04-11e7-998b-88f6395c3963.png)

**Comment by JiaLiPassion** [comment]
@sod , it should be a mistake, I will fix it.
