### ISSUE TITLE
Ionic2 copyFile moveFile Error, Zone state notScheduled

### ISSUE THREAD

**Issue by AUSdomgarcia** [angular/zone.js#796]
here's my code either I use copyFile or moveFile it always goes to catch handler outside my promise fuction
```
moveFileToStorage(uri) {
        const _extension = '.' + this.getFileExtension(uri);
        const _name = this.getFileName(uri) + _extension;
        const _newPath = this.myStoragePath;
        const _newName = 'camera_' + this.hashName() + _extension;
        const _uri = uri.substring(0, uri.lastIndexOf('/') + 1);
        return this.file.moveFile(_uri, _name, _newPath, _newName);
    }

moveFileToStorage(uri).then((res) => { } ).catch( (err) =>{ err } ) <-- goes here catch handler

```
heres what zone output, actually I don't get what it mean, just a newbie in ionic 2 development.

{"__zone_symbol_currentTask": {"type":"microTask", "state":"notScheduled", "source":"Promise.then", "zone":"angular","cancelFn":null,"runCount"0}}

thanks.

**Comment by JiaLiPassion** [comment]
Can you post a reproduce repo? thanks

**Comment by AUSdomgarcia** [comment]
hello Jialipassion here's my code scroll down to storeFile function
https://github.com/AUSdomgarcia/crud-ionic2/blob/master/src/pages/user/user.ts

and to see this.cameraSettings.useCamera() 
https://github.com/AUSdomgarcia/crud-ionic2/blob/master/src/shared/camera-settings.service.ts

thanks..

**Comment by JiaLiPassion** [comment]
ok, I will check it.

**Comment by AUSdomgarcia** [comment]
thanks I hope u can help me

**Comment by JiaLiPassion** [comment]
@AUSdomgarcia , I just checked it, it is not a `zone.js` issue, it is just a `ionic native` error, you can ask for more detail in https://github.com/ionic-team/ionic-native

**Comment by AUSdomgarcia** [comment]
hi @JiaLiPassion  thank you for making time. I will close this a soon as i get a good feedback from ionic native.

**Comment by AUSdomgarcia** [comment]
btw @JiaLiPassion what can you about the catched error.

{"__zone_symbol_currentTask": {"type":"microTask", "state":"notScheduled", "source":"Promise.then", "zone":"angular","cancelFn":null,"runCount"0}}

what does it mean?

**Comment by JiaLiPassion** [comment]
@AUSdomgarcia , this is just a property which `zone` add to the object. 

the real error is image save url is invalid.
<img width="834" alt="2017-06-02 12 43 49" src="https://cloud.githubusercontent.com/assets/1442575/26709922/4cefa836-4791-11e7-979e-9a1308d803d3.png">

**Comment by AUSdomgarcia** [comment]
`resolveLocalFilesystemUrl` helps me to resolved the issue, I just had a mistake on how I implemented moveTo or copyTo, I didnt notice that this.camera.getPicture(opts) returns DirectoryEntry and from that `directoryEntry` I will call the moveTo/copyTo method, not from this.file

cheers!
