### ISSUE TITLE
promises rejected with a specific error are not of the original type when they are caught (v0.8.10 reproduction included)

### ISSUE THREAD

**Issue by dbpieter** [angular/zone.js#797]
When a  promise is rejected with a specific error it is not of the same type once it is caught.
REPRO: https://plnkr.co/edit/7fASDCWYk0kRqax5oUWz?p=preview

```
class MyError extends Error {}

Promise.reject(new MyError()).catch((err) => {
  if(err instanceof MyError) {
    console.log('workz')
  } else {
    console.log('wtf!') // zone v0.8.10 :(
  }
})
```

This doesn't work as expected when zone v0.8.10 is loaded.
Loading 'zone-js/dist/zone-error.js' fixes the issue. Is it meant to be lke this.

Seems strange this additional script needs to be loaded in order for Zone to not shadow error types.
Zone should be completely transparant right ?

**Comment by JiaLiPassion** [comment]
@dbpieter , I don't think this behavior related to `zone.js`, you can just try use typescript 2.x to write this sample code.

```
class MyError extends Error {}

const error = new MyError();

console.log('instanceof', error instanceof MyError);

```

the result will be `false`.

The typescript compiled  code will look like.

```
var MyError = (function (_super) {
    __extends(MyError, _super);
    function MyError() {
        return _super.apply(this, arguments) || this;
    }
    return MyError;
}(Error));
``` 

the `new MyError()` will always return an `Error` instance not a `MyError`. 

So this is more like a `typescript` behavior.

When you load `zone-js/dist/zone-error.js`, `new MyError()` will return `MyError` instance.

**Comment by dbpieter** [comment]
@JiaLiPassion. Thx for your explanation. The behaviour changed with zone v0.8.10 so I thought this was zone related.

[It seems it is better not to extend from Error at all. ](https://github.com/Microsoft/TypeScript/issues/10166)
