### ISSUE TITLE
toString patched function throws an exception on iOS 9.3.5

### ISSUE THREAD

**Issue by mdudek** [angular/zone.js#802]
There is a bug in toString patched function.  Exception 'TypeError: type error' is thrown on iOS 9.3.2 (Safari).

The bug could be reproduced on plunker:
https://plnkr.co/edit/h28pjXhOKDxhBygUZgEr?p=preview

**Comment by JiaLiPassion** [comment]
@mdudek, thank you for posting the issue, I will check it.
