### ISSUE TITLE
Why is `Promise.then` considered a microtask

### ISSUE THREAD

**Issue by maximusk** [angular/zone.js#808]
[This comment](https://github.com/angular/zone.js/blob/master/dist/zone.js.d.ts#L85) says that:

>  [MicroTask]s represent work which will be done **in current VM turn** as soon as possible, before VM
>  yielding.

However, while debugging Zones I can see that `Promise.then`, which is executed in the following VM turns is scheduled as a microtask. My understanding is that it should be scheduled as a macrotask.

Can someone please explain the inconsistency?

**Comment by JiaLiPassion** [comment]
@maximusk , `Promise.then` should be a microtask, and it will be executed in the `current loop`. `zone.js` only wrap `Promise` with `Zone` information, and will not change the `lifecycle` of `Promise`.

**Comment by maximusk** [comment]
@JiaLiPassion 

Thanks, but that's still confusing. The callback that is added to `.then` is not executed in the loop.

**Comment by JiaLiPassion** [comment]
@maximusk , `Promise.then` should be executed in the loop, it will not be executed immediately, but will be `scheduled` as a microTask, and when `current loop` finish all running job, it will check any `microtask` is pending or not, if there are, those `microtasks` will be executed in the same loop.

**Comment by maximusk** [comment]
@JiaLiPassion, 
 

> those microtasks will be executed in the same loop.

but AFAIK promise is guaranteed to be executed asynchronously, even the ones that resolve immediately:

`return new Promise({resolve}=>{resolve();})`

**Comment by JiaLiPassion** [comment]
@maximusk , 

```
return new Promise({resolve}=>{resolve();})
```

in my understanding, 
this will not be an async operation, it just create a `new Promise` whose state is `resolved`.

It will only be `async` as `microTask` when `.then` is called.

```
const p = new Promise({resolve}=>{resolve();})
p.then(r => {
 // this callback will be run in the current loop as microTask but after other main operations finish.
});
```

**Comment by maximusk** [comment]
@JiaLiPassion 

> this will not be an async operation, it just create a new Promise whose state is resolved.

it will be, you can see the debugger in a browser

**Comment by JiaLiPassion** [comment]
@maximusk , I have tried

```javascript
<!DOCTYPE html>
<html>
<head>
  <script src="./zone.js"></script>
  <script>
    const promise = new Promise((resolve => {
      console.log('resolver');
      resolve(5);
    }));
    promise.then(r => {
      console.log('resolved ', r);
    })
    console.log('main task');
  </script>
</head>
<body>
</body>
</html>>
```

the output is 

```
resolver
main task
resolve 5
```

**Comment by maximusk** [comment]
@JiaLiPassion 

sorry, don't really understand what your code example proves. It's consistent with what I'm saying.  `console.log('resolved')` is evaluated asynchronously in the next VM turn and that's why it's outputted the last

**Comment by JiaLiPassion** [comment]
@maximusk , 
The sample try to explain.

1. 
```
 const promise = new Promise((resolve => {
      console.log('resolver');
      resolve(5);
    }));
```

is not async

2. `Promise.then` is async.

3. And `console.log(resolved)` occurs after `main task` doesn't mean it is in the next `event loop`.
It just means `microTask` will be executed after `main script`.

**Comment by maximusk** [comment]
@JiaLiPassion 
I seem to understand what you mean. Are you saying that [promise executor](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise#Parameters) is defined as microTask and will be executed in the end for the current VM turn and not the callback passed to `then`?

**Comment by JiaLiPassion** [comment]
@maximusk , `promise executor` is not microTask, here is animation, you can see it more clearly.
https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/

**Comment by maximusk** [comment]
@JiaLiPassion, thanks for the link, I'll read it. In the meantime,

> And console.log(resolved) occurs after main task doesn't mean it is in the next event loop.

It **does mean** it in the current implementation of Promise spec in all browsers without zones.

**Comment by maximusk** [comment]
@JiaLiPassion , thanks a lot for your time and especially the link to the article. I think you should've put it in the first post :). I wasn't aware of microtasks queue. Getting back to [my browser screenshot](http://imgur.com/a/W4NYJ), it seems that Chrome shows microtasks as async operations in the debugger.

Thanks again for the quick response! Good luck)

**Comment by JiaLiPassion** [comment]
@maximusk , sure, glad to help:)
