### ISSUE TITLE
How is Zone.runTask useful if ZoneTask is private

### ISSUE THREAD

**Issue by maximusk** [angular/zone.js#813]
There is `Zone.runTask` API method

```
/**
     * Execute the Task by restoring the [Zone.currentTask] in the Task's zone.
     *
     * @param task to run
     * @param applyThis
     * @param applyArgs
     * @returns {*}
     */
    runTask(task: Task, applyThis?: any, applyArgs?: any): any;
```

which takes the task. However, `ZoneTask` is a private class and there is no way I can create a task myself. So why is `Zone.runTask` exposed as a public API?

`scheduleMicroTask` and `scheduleMacroTask` methods return a task, but when I tried to run it like this:

```
const spec = {
  name: 'A'
};
Zone.current.fork(spec).run(() => {
  const task = Zone.current.scheduleMicroTask('Promise.then', cb);
  Zone.current.runTask(task, null, 'df');
});
```

 I got the error:

> zone.js:645 Error: microTask 'Promise.then': can not transition to 'running', expecting state 'scheduled', was 'notScheduled'.

**Comment by JiaLiPassion** [comment]
your sample will work like this 

```javascript
const spec = {
  name: 'A'
};
Zone.current.fork(spec).run(() => {
  const task = Zone.current.scheduleMicroTask('Promise.then', cb, null, function() {});
  Zone.current.runTask(task, null, 'df');
});
```

your example not work because you didn't provide a `customSchedule` method, so `zone.js` will schedule it as `microTask` later.

`runTask` will be useful when you patch your own `async API`.

**Comment by maximusk** [comment]
yeah, that worked, thank a lot!

> runTask will be useful when you patch your own async API.

Can you please provide a very little example?

**Comment by JiaLiPassion** [comment]
you can check https://github.com/angular/zone.js/blob/master/test/common/task.spec.ts for basic usage.
