### ISSUE TITLE
Why does zone pathes synchronous methods 'alert', 'prompt', 'confirm'

### ISSUE THREAD

**Issue by maximusk** [angular/zone.js#814]
I've looked through the source code and found that `Zone` patches synchronous methods `'alert', 'prompt', 'confirm'`. I thought that zone patches the asynchronous methods only. So why are these sync methods patched?
```
Zone.__load_patch('blocking', function (global, Zone, api) {
    var blockingMethods = ['alert', 'prompt', 'confirm'];
```

**Comment by JiaLiPassion** [comment]
you can find some detail information here https://blog.thoughtram.io/angular/2016/01/22/understanding-zones.html

**Comment by maximusk** [comment]
thanks, I've read this article before, now I've looked at it second time. It seems to have some inaccuracies besides explaining the old API. For example this:

> For example, when we call setTimeout() we actually call Zone.setTimeout(), which in turn creates a new zone using zone.fork() in which the given handler is executed.

But from what I've learnt in the sources, it's actually not true. setTimeout schedules a macrotask in the current zone, it doesn't create a new zone. Is it correct?
