### ISSUE TITLE
onHandleError is not triggered when callback to zone.run throws

### ISSUE THREAD

**Issue by maximusk** [angular/zone.js#815]
I have this simple example:

```
const zA = Zone.current.fork({name: 'A', onHandleError() { console.log('error reported'); }});
zA.run(() => {
  throw new Error('h');
});
```

However, the `onHandleError` callback is not triggered. Why?

**Comment by JiaLiPassion** [comment]
this is the spec,

```
zone.run()
```

will not handle error.

```
zone.runGuarded()
```

will handle error.

**Comment by maximusk** [comment]
Got it, appreciate!

**Comment by JiaLiPassion** [comment]
@maximusk , sure, I am happy to do that!

**Comment by maximusk** [comment]
@JiaLiPassion , great, thanks, I'll let you know :). On twitter maybe? 

Btw, did you have a chance to check my [these clarification questions](https://github.com/angular/zone.js/issues/814#issuecomment-308636941)?

**Comment by JiaLiPassion** [comment]
@maximusk , I will check them later, and you can read some new article here, https://docs.google.com/document/d/1F5Ug0jcrm031vhSMJEOgp1l-Is-Vf0UCNDY-LsQtAIY

**Comment by maximusk** [comment]
@JiaLiPassion, thanks, that's a great read! The info clarified some concepts I couldn't understand by reading the sources
