### ISSUE TITLE
Posible bug?

### ISSUE THREAD

**Issue by sergiomcalzada** [angular/zone.js#818]
I have a problem with zone.sj + angular4.umd

I'm not sure if is related to angular or to zone.js, but the error is 

`zone.js:642 Unhandled Promise rejection: Cannot read property 'call' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'call' of undefined`

I reported a [bug](https://github.com/angular/angular/issues/16857) in angular too

Here is a repo: https://github.com/sergiomcalzada/angular_umd
Updated a branch with the latest versions of both libraries

**Comment by JiaLiPassion** [comment]
@sergiomcalzada , thanks for posting the issue, I will check it.

**Comment by JiaLiPassion** [comment]
Close for now because not be able to reproduce.
