### ISSUE TITLE
API documentation instead "d.ts" file

### ISSUE THREAD

**Issue by djleonskennedy** [angular/zone.js#820]
Hello
is there any place with readable docs or examples?

Thank you

**Comment by JiaLiPassion** [comment]
@djleonskennedy , you can find here
https://docs.google.com/document/d/1F5Ug0jcrm031vhSMJEOgp1l-Is-Vf0UCNDY-LsQtAIY

**Comment by djleonskennedy** [comment]
@JiaLiPassion thank you
