### ISSUE TITLE
Unsupported command on IE10

### ISSUE THREAD

**Issue by tonghuashuo** [angular/zone.js#823]
I'm using zone.js (0.8.12) as an official required polyfill of Angular 4.2.4 (with TypeScript 2.3 if that helps locate the problem). My Application runs just fine under Chrome, Firefox, Safari, Edge and IE 11. Until I test it on IE 10 and it gave me the following error:

(The 1st red line is another exception thrown by 'parchment' of 'Quill', which I assume is caused by the 2nd red line.)
(The 2nd red line says: "unsupported command". just in case you don't read Chinese.)

![222](https://user-images.githubusercontent.com/6594276/27509507-28bcb308-5931-11e7-8562-3a13148f7452.PNG)

Inspect into polyfill.bundle.js (11707, 25) led me to this:

![2223](https://user-images.githubusercontent.com/6594276/27509511-528687f4-5931-11e7-8555-a2c56d3dcc87.PNG)

I have no idea what caused it. Hope anyone here can help me.

**Comment by JiaLiPassion** [comment]
@tonghuashuo , can you show the full stack of `error` or can you post a reproduce repository?

**Comment by JiaLiPassion** [comment]
Close for now for not be able to reproduce.
