### ISSUE TITLE
 TypeError: Cannot assign to read only property 'then' of #<Promise>

### ISSUE THREAD

**Issue by htafolla** [angular/zone.js#827]
patchThen function is failing stating that Ctor.prototype. then is read only.

W20170629-08:28:45.732(-5)? (STDERR) C:\Users\mypc\dev\myapp\.meteor\local\build\programs\server\node_modules\fibers\future.js:280
W20170629-08:28:45.734(-5)? (STDERR)                                            throw(ex);
W20170629-08:28:45.735(-5)? (STDERR)                                            ^
W20170629-08:28:45.736(-5)? (STDERR)
W20170629-08:28:45.737(-5)? (STDERR) TypeError: Cannot assign to read only property 'then' of #<Promise>
W20170629-08:28:45.738(-5)? (STDERR)     at patchThen (C:\Users\mypc\dev\myapp\.meteor\local\build\programs\server\npm\node_modules\zone.js\dist\zone-node.js:928:29)
W20170629-08:28:45.739(-5)? (STDERR)     at C:\Users\mypc\dev\myapp\.meteor\local\build\programs\server\npm\node_modules\zone.js\dist\zone-node.js:951:9
W20170629-08:28:45.740(-5)? (STDERR)     at Function.Zone.__load_patch (C:\Users\mypc\dev\myapp\.meteor\local\build\programs\server\npm\node_modules\zone.js\dist\zone-node.js:85:33)
W20170629-08:28:45.741(-5)? (STDERR)     at C:\Users\mypc\dev\myapp\.meteor\local\build\programs\server\npm\node_modules\zone.js\dist\zone-node.js:634:6
W20170629-08:28:45.743(-5)? (STDERR)     at performance (C:\Users\mypc\dev\myapp\.meteor\local\build\programs\server\npm\node_modules\zone.js\dist\zone-node.js:9:65)
W20170629-08:28:45.745(-5)? (STDERR)     at Object.<anonymous> (C:\Users\mypc\dev\myapp\.meteor\local\build\programs\server\npm\node_modules\zone.js\dist\zone-node.js:12:2)
W20170629-08:28:45.747(-5)? (STDERR)     at Module._compile (module.js:409:26)
W20170629-08:28:45.748(-5)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
W20170629-08:28:45.749(-5)? (STDERR)     at Module.load (module.js:343:32)
W20170629-08:28:45.750(-5)? (STDERR)     at Function.Module._load (module.js:300:12)

**Comment by JiaLiPassion** [comment]
@htafolla , could you provide a reproduce repo?

**Comment by JiaLiPassion** [comment]
close for now for not be able to reproduce
