### ISSUE TITLE
Socket.IO

### ISSUE THREAD

**Issue by Kaffiend** [angular/zone.js#828]
Is there a way we can get Socket.io to run within zone? or will we manually have to run every socket callback through zone?

**Comment by JiaLiPassion** [comment]
@Kaffiend ，currently you have to use `Zone.current.wrap(callback)` yourself, I can implement a `patch` for `socket.io` later.

**Comment by brgaulin** [comment]
Although, its weird. I do see that websockets themselves are wrapped. socket.io uses the Component Emitter for handling its events: https://www.npmjs.com/package/component-emitter

**Comment by Kaffiend** [comment]
I added ngrx to manage state better and discovered that `onPush` change detection and async slices of state updated from my socket services makes this work just fine. Not saying it doesnt need patched for other implementations without a reactive library for angular in use.

**Comment by Kaffiend** [comment]
Will zone be patched any time soon for Socket.IO?

**Comment by JiaLiPassion** [comment]
@Kaffiend , I am working on it, I will create a PR soon.
