### ISSUE TITLE
Angular 4.1.2 + Type Script 2.2.2 + Edge 14  TypeError: Object expected

### ISSUE THREAD

**Issue by eegasudheer** [angular/zone.js#829]
Hi,

Recently we have upgraded our application to angular4 and  we are using tinymce plugin for displaying rich textarea box in the UI.  Application is working as expected in IE, FF & Chrome browsers but we see some issues while loading plugin in edge browser.

Below is the error we are receiving in console.

SCRIPT5007: Object expected

```
Zone.prototype.runTask = function (task, applyThis, applyArgs) {
if (task.zone != this) {
throw new Error('A task can only be run in the zone of creation! (Creation: ' +
(task.zone || NO_ZONE).name + '; Execution: ' + this.name + ')');
}
// https://github.com/angular/zone.js/issues/778, sometimes eventTask
// will run in notScheduled(canceled) state, we should not try to
// run such kind of task but just return
// we have to define an variable here, if not
// typescript compiler will complain below
var isNotScheduled = task.state === notScheduled;
if (isNotScheduled && task.type === eventTask) {
return;
}
var reEntryGuard = task.state != running;
reEntryGuard && task._transitionTo(running, scheduled);
task.runCount++;
var previousTask = _currentTask;
_currentTask = task;
_currentZoneFrame = { parent: _currentZoneFrame, zone: this };
try {
if (task.type == macroTask && task.data && !task.data.isPeriodic) {
task.cancelFn = null;
}
try {
return this._zoneDelegate.invokeTask(this, task, applyThis, applyArgs);
}
catch (error) {
if (this._zoneDelegate.handleError(this, error)) {
throw error;
}
}
}

```
ERROR Error: Uncaught (in promise): Error: TypeError: Object expected
Error: TypeError: Object expected

at callWithDebugContext (http://localhost/vendor.dll.js:19309:9)

referring method in angular/core.es5.js file

Really not able to figure out what causing the issue in edge browser, even it's working correctly in ie browser. Any help is appreciated.

Thanks,
Sudheer

**Comment by JiaLiPassion** [comment]
@eegasudheer , could you post a reproduce repo?

**Comment by eegasudheer** [comment]
@JiaLiPassion , its private code, not possible to share it in public repo.
i tried with latest version of zone.js  0.8.12  getting below error

SCRIPT438: Object doesn't support property or method 'substr'
polyfills.dll.js (4007,25)

When i click on the line number 4007, its pointing me to belwo code block in zone.js

`Zone.prototype.runTask = function (task, applyThis, applyArgs) {
            if (task.zone != this) {
                throw new Error('A task can only be run in the zone of creation! (Creation: ' +
                    (task.zone || NO_ZONE).name + '; Execution: ' + this.name + ')');
            }
            // https://github.com/angular/zone.js/issues/778, sometimes eventTask
            // will run in notScheduled(canceled) state, we should not try to
            // run such kind of task but just return
            // we have to define an variable here, if not
            // typescript compiler will complain below
            var isNotScheduled = task.state === notScheduled;
            if (isNotScheduled && task.type === eventTask) {
                return;
            }
            var reEntryGuard = task.state != running;
            reEntryGuard && task._transitionTo(running, scheduled);
            task.runCount++;
            var previousTask = _currentTask;
            _currentTask = task;
            _currentZoneFrame = { parent: _currentZoneFrame, zone: this };
            try {
                if (task.type == macroTask && task.data && !task.data.isPeriodic) {
                    task.cancelFn = null;
                }
                try {
                    return this._zoneDelegate.invokeTask(this, task, applyThis, applyArgs);
                }
                catch (error) {
                    if (this._zoneDelegate.handleError(this, error)) {
                        throw error;
                    }
                }
            }`

**Comment by JiaLiPassion** [comment]
@eegasudheer , thank you for the information, could you help me to debug which object doesn't support property of method `substr`? only 2 places use `substr` call in `zone.js`, so it will not difficult to find out.

**Comment by eegasudheer** [comment]
@JiaLiPassion , it's coming from below line.
line1233: var eventName = prop.substr(2);

**Comment by JiaLiPassion** [comment]
@eegasudheer, thank you, could you also help me to check what the `prop` and `obj` is ?

**Comment by eegasudheer** [comment]
@JiaLiPassion , I see 2 issues here.

**When loading tinymce editor without text in it**
"TypeError: Object expected\n   at Selection.prototype.getRng (eval code:21389:9)\n   at Selection.prototype.getNode (eval code:21600:26)\n   at getBookmark (eval code:17793:11)\n   at Selection.prototype.getBookmark (eval code:21247:9)\n   at self.add (eval code:25584:11)\n   at Anonymous function (eval code:25408:9)\n   at fire (eval code:30773:13)\n   at fire (eval code:31013:9)\n   at initEditor (eval code:43934:7)\n   at Anonymous function (eval code:44081:11)"
[http://tinypic.com/view.php?pic=345n2c6&s=9#.WWopAOnhWUk](url)

**with text in it**
"TypeError: Object doesn't support property or method 'substr'\n   at self.parse (eval code:14084:11)\n   at self.parse (eval code:14733:9)\n   at Editor.prototype.setContent (eval code:45741:13)\n   at Anonymous function (eval code:459:25)\n   at fire (eval code:30773:13)\n   at fire (eval code:31013:9)\n   at initEditor (eval code:43934:7)\n   at Anonymous function (eval code:44081:11)\n   at Anonymous function (eval code:8559:13)\n   at Anonymous function (eval code:8028:11)\n   at 
ZoneDelegate.prototype.invokeTask (http://localhost/polyfills.dll.js:4234:13)\n   at Zone.prototype.runTask (http://localhost/polyfills.dll.js:4003:21)\n   at invoke (http://localhost/polyfills.dll.js:4298:21)\n   at timer (http://localhost/polyfills.dll.js:5352:17)"
[http://tinypic.com/view.php?pic=iz5hew&s=9#.WWoqZenhWUk](url)

**Comment by JiaLiPassion** [comment]
@eegasudheer , the 2nd link seems not have image inside, http://tinypic.com/view.php?pic=iz5hew&s=9#.WWoqZenhWUk, could you check it?

**Comment by eegasudheer** [comment]
@JiaLiPassion , please use belwo link.

http://tinypic.com/view.php?pic=iz5hew&s=9#.WWpD9YiGNhF

**Comment by JiaLiPassion** [comment]
@eegasudheer , thank you , but I can't find the value of `prop` and `obj`, could you go to the stack of `substr` , and help to check what is `prop` and `obj` .

**Comment by eegasudheer** [comment]
@JiaLiPassion , Initially its loading block that contains substr, but actually error not coming from this block. 
This is something issue with tinymce.js, when i check total 33 places they are using substr.
Just want to know  how can i get exact error causing block?

Please refer below stack.
http://tinypic.com/r/1gfzb6/9

**Comment by JiaLiPassion** [comment]
@eegasudheer , I think you can check the error stack to find the `substr` stack frame, and then go to that file manually. Or you can use `pause on exceptions` (Chrome has this feature, I don't know if edge can do that).

**Comment by Niniania** [comment]
Is there any news on this ? Still getting the error in Edge in latest version of Tinymce, its making the Editor unusable for us in Edge browser as we add and destroy components and the Editor along with them and get this error.

**Comment by JiaLiPassion** [comment]
@Niniania , could you provide a reproduce repo? thanks!

**Comment by exsoflowe** [comment]
It can be related with auto_focus = false.
It works for us if we set auto_focus **true** for Edge.

**Comment by JiaLiPassion** [comment]
Close for now for not be able to reproduce.
