### ISSUE TITLE
zone.js v0.8.13 completely brakes down Angular v4.2.6 with NO errors!!!

### ISSUE THREAD

**Issue by Sky4CE** [angular/zone.js#836]
Environment:
- zone.js 0.8.13
- Node 6.11.1 (also tested 7.10.1)
- npm 5.2.0 (also tested v4)
- Angular 4.2.6
- rxjs 5.4.2
- Typescript 2.4.1
- webpack 3.2.0 (also tested 3.1.0)

What happened:
Restored node_modules (with no updates, but dependencies declared with ^) and app stopped working, completely, no errors...Period..
![image](https://user-images.githubusercontent.com/9821633/28164162-b96a43ee-67d6-11e7-9383-51b190d1c2a0.png)

1) No content;
2) app-root hasn't been fullfilled by angular with app logic, we can see only static spinner;
3) No errors at all in console!

Tested on 3 dev machines with slightly different versions of node/npm. Result always was the same. 
I've spent hours to find what was cause the problem, because we have hundreds of dependencies. Who could imagine that minor update (which updated automatically) in angular system dependency (which zone.js actually is) could lead to such unexpected behavior? With no errors at all!

0.8.12 works fine.

**Comment by JiaLiPassion** [comment]
@Sky4CE , could you post a reproduce repo?  Or could you try the attached zone.js?
[zone.js.zip](https://github.com/angular/zone.js/files/1144943/zone.js.zip)

**Comment by Sky4CE** [comment]
@JiaLiPassion , sorry no time for preparing a repo, but I can try your zip... And seems like no difference, unfortunately. Still no errors.

**Comment by Redlable47** [comment]
+1
Environment:
zone.js 0.8.13
Node 8.1.2
npm 5.2.0
Angular 4.1.3
rxjs 5.0.1
Typescript 2.4.0
webpack 3.2.0 (also tested 2.2)

![2017-07-13 14-46-21](https://user-images.githubusercontent.com/4552426/28164942-5a4c9a34-67da-11e7-9a7f-8f6a99c7b340.png)
![2017-07-13 14-45-31](https://user-images.githubusercontent.com/4552426/28164943-5a60331e-67da-11e7-806c-9d7acfb77085.png)

**Comment by JiaLiPassion** [comment]
@Redlable47, thanks, your screenshot have been resolved with #834, I think @Sky4CE 's issue maybe a little different.

**Comment by JiaLiPassion** [comment]
@Sky4CE , could you please try to make a reproduce repo when you have time? in zone.js 0.8.13, there are some major changes for performance, so I am not sure which change break your case.

**Comment by AlexViderman** [comment]
@JiaLiPassion exact same issue with 0.8.13 as @Sky4CE ... same environment. Adding myself to this thread to get updates.

**Comment by JiaLiPassion** [comment]
@AlexViderman , could you please provide a reproduce repo? thanks.

**Comment by AlexViderman** [comment]
@JiaLiPassion, I have a very large project, I stripped it all the way down, but the issue went away 😄 . I will try to find time to strip it down in stages to see whats causing the issue. Will let you know what I come up with.

**Comment by JiaLiPassion** [comment]
@AlexViderman , sure, thank you!

**Comment by AlexViderman** [comment]
@JiaLiPassion, I figured out what's causing the issue for my project: importing the following file anywhere in my code:

https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/daterangepicker.js (version: 2.1.25)

I tested placing it directly in my vendors.ts. With 0.8.12 the app loads, with 0.8.13 the app does not load and there are no errors.

I do not have a simple version of my code that I can publicly provide. Does this help you?

-Alex

**Comment by JiaLiPassion** [comment]
@AlexViderman , thank you for the information, I will try to reproduce with your steps.

**Comment by JiaLiPassion** [comment]
@AlexViderman , I can reproduce now, thank you very much, I will try to figure out why.

**Comment by meiordac** [comment]
zone.js 0.8.13
Angular 4.2.3
angular/cli 1.2.0
Typescript 2.3.4

Completely breaks my ng test, I am getting this error in many tests:

`
Cannot create property '__creationTrace__' on string '__zone_symbol__optimizedZoneEventTask'`

**Comment by JiaLiPassion** [comment]
@meiordac , this issue have been fixed in #834, please wait for the next release.

**Comment by Sky4CE** [comment]
@JiaLiPassion , I've tried new zip and I can confirm that it works, everything working with this new version.

**Comment by JiaLiPassion** [comment]
@Sky4CE , thank you for confirm, sorry for the breaking error, please wait for the next version.

**Comment by Sky4CE** [comment]
@JiaLiPassion , no problem, thank you.

**Comment by AlexViderman** [comment]
@JiaLiPassion, glad you were able to figure it out! Sorry, I did not get a chance to try your new zip.

**Comment by JiaLiPassion** [comment]
@AlexViderman , thank you very much for providing the reproduce lead to help me to resolve this serious issue!!!
