### ISSUE TITLE
Issues with counting example (count remains high, onFlush never fires)

### ISSUE THREAD

**Issue by TheRossman** [angular/zone.js#838]
We would like to use zonejs to track async operations, very much like the counting example provided in the repo.

We have an angular1.x app and want to know when the app is "ready" (ie. all async operations complete) to assist our automated QA testing.

If I make an extremely simple hello world type angular app, such as the one described on [this page](https://docs.angularjs.org/api/ng/function/angular.bootstrap), and perform the angular.bootstrap() call in the button click from your counting example (so it runs in zone), everything works and there is no issue, the onFlush handler fires without issue.

However if I attempt the same with our actual (and much larger) angular application, the onFlush never fires and if I query the zone counter manually it's always in the 60's (doesn't go back down to zero so that flush can happen).

I was hoping you may be able to provide some insight or suggestion.  Thank you.

**Comment by TheRossman** [comment]
Here's a JSBin I put together that is just a slightly modified version of the counting example but bringing a simple angular app into the mix:

http://jsbin.com/xocomefaxu/edit?html,js,output

Also to correct my initial comment, when I run the simplest angular app in the run zone (app that does nothing but set a $scope var), the onFlush never fires and the counter remains at 1.  Never goes back to zero.

**Comment by JiaLiPassion** [comment]
Your counter `plus` and `minus` logic should check `task.type`, in zone.js there are 
3 kinds of tasks.

1. macroTask, such as setTimeout
2. microTask, such as Promise
3. eventTask, such as button.addEventListener('click', ...)

so in your logic ,the flush not being called because there are several eventTasks are remained. 

http://output.jsbin.com/bujesof/4

here is the working version.

**Comment by TheRossman** [comment]
@JiaLiPassion Thanks very much for your reply.  I will try out your version!

**Comment by JiaLiPassion** [comment]
@TheRossman , glad to help. basically you don't need to use your own counter, use `hasTask` callback will do the same thing.

**Comment by JiaLiPassion** [comment]
Close for now.
