### ISSUE TITLE
ReferenceError: _global is not defined in zone.js 0.8.13

### ISSUE THREAD

**Issue by taxilian** [angular/zone.js#842]
After upgrading to zone.js 0.8.13 in my angular 4.3 app I can no longer load the page; when pouchdb calls addEventListener it winds up on line 209 of `lib/common/events.ts` complaining that `ReferenceError: _global is not defined`.

This issue does not happen if I downgrade to zone.js 0.8.12; it's 100% reproducible in my codebase.

**Comment by JiaLiPassion** [comment]
thank you for posting the issue, duplicate with #835, have been fixed and please wait for the next release.

**Comment by JiaLiPassion** [comment]
close for already been fixed
