### ISSUE TITLE
Failed to execute 'removeEventListener' on 'EventTarget'

### ISSUE THREAD

**Issue by hpyou** [angular/zone.js#847]
this is my code:
```
private _removeAnimation(element: HTMLElement) {
    element.removeEventListener('animationend');
}
```

when I use zone.js@0.8.14 it throw this error
![image](https://user-images.githubusercontent.com/15992591/28451071-d338da9a-6e1d-11e7-82fa-3de8f4cb09de.png)
but when I use zone.js@0.8.5, it works ok.

**Comment by JiaLiPassion** [comment]
@hpyou , what is the behavior of 
```javascript
    element.removeEventListener('animationend');
```
it will remove all `aniamteionend listeners` on element ?

**Comment by hpyou** [comment]
a element popup and distroy quickly and repeatedly， before distroy it,  i use an animation , when the animation is end  i run distroy function , when the element popup once again, i need to remove the animationend listener, if not , the element will not popup. popup and distroy functionare asynchronous.

**Comment by JiaLiPassion** [comment]
@hpyou , so you have to pass the `listener` which you used in `element.addEventListener('animationend`, listener);`

**Comment by hpyou** [comment]
@JiaLiPassion ,  i want remove the listener when i popup so that the distroy function will not run

**Comment by JiaLiPassion** [comment]
@hpyou , I don't know why before the new version of `zone.js`, you code can run, but 
`removeEventListener(eventName);` should not work, so you should hold the `listener` when you `popup` and use it as `removeEventListener(eventName, listener)` when destroy.

**Comment by hpyou** [comment]
@JiaLiPassion , in es6 library, `listener` is not required, i used typescript
![image](https://user-images.githubusercontent.com/15992591/28452622-19e287b8-6e26-11e7-9691-575766cd8b39.png)

**Comment by JiaLiPassion** [comment]
@hpyou , yeah, you may ignore the listener, but without listener, nothing should happen based on the spec. I will test it without `zone.js`.

**Comment by JiaLiPassion** [comment]
@hpyou , I tried with the following sample code, a simple html with javascript.

```javascript
<!DOCTYPE html>
<html>
<head>
  <script>
    window.onload = function() {
      document.getElementById('btn').addEventListener('click', function () {
        console.log('click');
      });
      document.getElementById('btn').removeEventListener('click');

    }
  </script>
</head>
<body>
  <button type="button" id="btn"></button>
</body>
</html>>
```

you can run it in chrome, it will report the same error.

**Comment by hpyou** [comment]
@JiaLiPassion, i see it. it might be something wrong with typescript compile, i will add the listener, thank you very much for your help.

**Comment by hpyou** [comment]
@JiaLiPassion, i try again
when i write `element.removeEventListener('animationend', null);` in zone.js@0.8.14, it will not throw that error, and i  write `element.removeEventListener('animationend');` , it will throw. and in  zone.js@0.8.5, `element.removeEventListener('animationend');` without `null` is not throw. so i think maybe something changed when zone.js update， after all,  es6 agree to ignore  `listener` . i just give some hints.

**Comment by hpyou** [comment]
@JiaLiPassion, in zone.js@0.8.5  `element.removeEventListener('animationend');` will remove all listeners, but in zone.js@0.8.14 throw error, and `element.removeEventListener('animationend', null);` will not remove any listener.

**Comment by JiaLiPassion** [comment]
@hpyou , 

> in zone.js@0.8.5 element.removeEventListener('animationend'); will remove all listeners

I will check it later, but if the behavior is remove all listeners, it is not correct, I think current (0.8.14) behavior `throw error` is correct. It is the same behavior with the `non-patched` version.

**Comment by hpyou** [comment]
@JiaLiPassion， i used typescript, pleace use typescript or es6 to check, thinks

**Comment by wkaskie** [comment]
I came across this post and it lead me to my resolution which was to hardcode my package.json file to use version 0.8.5.

Original: zone.js: ^0.8.4
New: zone.js: 0.8.5
