### ISSUE TITLE
Doesn't work on Node.js/Meteor

### ISSUE THREAD

**Issue by ardatan** [angular/zone.js#850]
Node gives that error...
`TypeError: Cannot assign to read only property 'then' of #<Promise> ` in dist/zone-node.js:941
during the re-assignment of 'Ctor.prototype' in patchThen function.

So I couldn't make it work by Angular platform-server until taking that scope under try-catch.

I think this is a critical issue and same with #827

**Comment by JiaLiPassion** [comment]
@ardatan , could you provide a reproduce repo?

**Comment by ardatan** [comment]
https://github.com/ardatan/zone-meteor

**Comment by ardatan** [comment]
So do you have any solution for this?
I have to make this workaround.
```
Object.defineProperty(Promise.prototype, 'then', {
  writable: true
})
import 'zone.js';
```

**Comment by JiaLiPassion** [comment]
@ardatan , yes, you are right, the `meteor` somehow make the global.Promise `writable` to be false. so your walk around seems to be correct. I can add this logic before `patchThen` in `zone.js`
