### ISSUE TITLE
event task 

### ISSUE THREAD

**Issue by ringgoyao** [angular/zone.js#853]
Hi,

I use code like this
 ```
 <textarea #textarea>

      </textarea>
```

`  this.observable= Observable.fromEvent(this.filter.nativeElement, 'keyup')
        .debounceTime(1000)
        .distinctUntilChanged()
        .subscribe(() => {
             this.content=this.filter.nativeElement.value;
             this.doChangeCheck();
        });`
when I  change the content in other method ,for example:
`this.filter.nativeElement.value="“`

it will show Error: 

> eventTask 'HTMLBodyElement.addEventListener:keyup': can not transition to 'running', expecting state 'scheduled', was 'notScheduled'.
>     at t._transitionTo (http://localhost:8100/build/polyfills.js:3:10579)
>     at r.runTask (http://localhost:8100/build/polyfills.js:3:4191)
>     at Array.invoke (http://localhost:8100/build/polyfills.js:3:10150)
>     at unhook (eval at <anonymous> (:2:398), <anonymous>:130:14)
>     at HTMLBodyElement.unhook_f (eval at <anonymous> (:2:398), <anonymous>:125:12)

zone.js version:0.8.14

**Comment by JiaLiPassion** [comment]
@ringgoyao , could you post a reproduce repo?

**Comment by JiaLiPassion** [comment]
close for now for not be able to reproduce.
