### ISSUE TITLE
While debugging, once a test fails many future tests fail

### ISSUE THREAD

**Issue by dfederm** [angular/zone.js#858]
When running Angular2+ UTs using karma+jasmine, if all tests pass, or if I'm not debugging the tests, everything works as expected. However, if I debug the tests in a browser (karma's debug.html while running with `singleRun: false`), once a test fails many future tests fail as well.

Here is an example of a "normal" run with the failling test, and then a "debug" run (clicking that Debug button):
![image](https://user-images.githubusercontent.com/6445614/28655627-fbed0b90-7251-11e7-92e7-1c84b9cf84fe.png)
![image](https://user-images.githubusercontent.com/6445614/28655650-22647b5a-7252-11e7-8867-5019c8c06125.png)

In this example, the `ClansComponent` test fails due to errors in my code. However the other tests should not be failing at all.

Interestingly and possibly unrelated, the stacks for failed assertions are really, really bad. None of my code is on the stack at all somehow!
![image](https://user-images.githubusercontent.com/6445614/28655718-7c1ba70e-7252-11e7-8a11-0435d657ec2f.png)

When I break on all errors after my assertion failure, I end up seeing all kinda of errors inside of zone.js. Here's a sample:
![image](https://user-images.githubusercontent.com/6445614/28655759-bd3feccc-7252-11e7-8396-a55b7b4f8ab1.png)
(somehow `compnent` is null despite setting up properly in a `beforeEach`)
![image](https://user-images.githubusercontent.com/6445614/28655791-e66aec96-7252-11e7-8ca1-1bc99ce5a376.png)
(at the very least this is a bad error message; the error got converted to a string)
![image](https://user-images.githubusercontent.com/6445614/28655816-08c0f2f4-7253-11e7-9c75-fa2bb8a995e7.png)
![image](https://user-images.githubusercontent.com/6445614/28655828-1c680ee6-7253-11e7-9353-9be1de14e20f.png)
![image](https://user-images.githubusercontent.com/6445614/28655833-2818afd4-7253-11e7-8338-3fbea4653c7c.png)

Again, when I fix the failing test to pass properly, everything works as expected and all the other tests pass just fine.

**Comment by JiaLiPassion** [comment]
Close for now.
