### ISSUE TITLE
can i remove 'use strict'? typeError: Attempted to assign to readonly property

### ISSUE THREAD

**Issue by BillyQin** [angular/zone.js#859]
angular: 4.2+
zone.js: 0.7.7 +

error:
function patchPrototype(prototype, fnNames) {
    var source = prototype.constructor['name'];
    var _loop_1 = function(i) {
        var name_1 = fnNames[i];
        var delegate = prototype[name_1];
        if (delegate) {
            prototype[name_1] = (function (delegate) {
                return function () {
                    return delegate.apply(this, bindArguments(arguments, source + '.' + name_1));
                };
            })(delegate);
        }
    };
    for (var i = 0; i < fnNames.length; i++) {
        _loop_1(i);
    }
}

TypeError: Attempted to assign to readonly property   in prototype[name_1]

when i remove 'use strict',it will work.

can i help me ？ thanks

**Comment by JiaLiPassion** [comment]
Could you post a reproduce repo?

**Comment by BillyQin** [comment]
@JiaLiPassion  I am sorry, I can't post a repo.

**Comment by JiaLiPassion** [comment]
You can try the latest version of zone.js
And if the issue still exists, you can try to debug which property is readonly.

**Comment by BillyQin** [comment]
@JiaLiPassion  i have try the latest version of zone.js,and the issue still exists.

function patchPrototype(prototype, fnNames) {
    var source = prototype.constructor['name'];
    var _loop_1 = function(i) {
        var name_1 = fnNames[i];
        var delegate = prototype[name_1];
        if (delegate) {
            prototype[name_1] = (function (delegate) {
                return function () {
                    return delegate.apply(this, bindArguments(arguments, source + '.' + name_1));
                };
            })(delegate);
        }
    };
    for (var i = 0; i < fnNames.length; i++) {
        _loop_1(i);
    }
}

prototype[getCurrentPosition] is readonly,thanks

**Comment by JiaLiPassion** [comment]
Then what is the prototype is?

**Comment by BillyQin** [comment]
@JiaLiPassion 
prototype = Geolocation {getCurrentPosition: function}, fnNames = (2) 

["getCurrentPosition", "watchPosition"]
source = "Geolocation"
_loop_1 = function (i), i = 1
fnNames = (2) ["getCurrentPosition", "watchPosition"]
prototype = Geolocation {getCurrentPosition: function}
prototype = Geolocation {getCurrentPosition: function}
source = "Geolocation"

this is chrome debug , is right?

**Comment by JiaLiPassion** [comment]
I will check it, thanks.

**Comment by BillyQin** [comment]
@JiaLiPassion  my project NOT work in ios10.3.2 and 'use strict', and it can work in chrome、android.
finally, thank you

**Comment by JiaLiPassion** [comment]
@BillyQin , please try the attached zone.js.zip (unzip and copy to node_modules/zone.js/dist) and check whether the issue resolved or not.

**Comment by BillyQin** [comment]
@JiaLiPassion yes,it can work. When will the release be released? thanks
