### ISSUE TITLE
Incorrect parameters to patchEventTarget

### ISSUE THREAD

**Issue by evmar** [angular/zone.js#862]
websocket.ts has

```ts
patchEventTarget(api, _global, [WS.prototype]);
```

https://github.com/angular/zone.js/blob/b0c5076d70f65f48b743c981cdc56efb9745bd44/lib/browser/websocket.ts#L18

However, `patchEventTarget` looks like:

```ts
export function patchEventTarget(
    _global: any, apis: any[], patchOptions?: PatchEventTargetOptions) {
```

This error was caught by TS 2.4.  I'm not exactly sure what the correct params to `patchEventTarget` are here, but what this code currently has looks wrong.

**Comment by evmar** [comment]
@JiaLiPassion wrote this code I think.

**Comment by JiaLiPassion** [comment]
@evmar , thanks for posting the issue, I will fix it.
