### ISSUE TITLE
RxJS patch is not closure safe

### ISSUE THREAD

**Issue by mhevery** [angular/zone.js#863]
1) Assignment into imported constructor is not allowed: https://github.com/angular/zone.js/blob/master/lib/rxjs/rxjs.ts#L75
2) We can’t use string literals here: https://github.com/angular/zone.js/blob/master/lib/rxjs/rxjs.ts#L230 since they don’t minify in closure

The fix for #1 is https://github.com/trxcllnt/rxjs/blob/53eddb1cca1228fe6d81aa6bec0ee0a57c8f4664/src/add/zone.ts#L60-L74 The trick is to intercept the setter to have side-effects. This way we don’t need to replace the constructor.

**Comment by JiaLiPassion** [comment]
@mhevery , I have modified this one in #848, please review.
