### ISSUE TITLE
Cordova File Plugin should be patched, or there should be a way to unpatch things on runtime.

### ISSUE THREAD

**Issue by n00dl3** [angular/zone.js#868]
I am using angular 4.3 (and zone 0.8.12) and I am experiencing some troubles with the official cordova file plugin. The plugin has a patched version of the `FileReader` class that does not implement the `EventTarget` interface. If I understand well what it is done by zone.js to "onProperties" (`onload`,`onerror`...) is that they are converted to there zone-ready `addEventListener(...)` counterpart, so my `onerror`,`onload` callback never got trigerred...

I understand that it is a plague to implement all singularity of any library, so maybe there should be a more-generic method like `zone.runUnpatched(()=>{})` to get the "original"/unpatched constructor of patched API.

suggestion:

For now, if I run this:
 ```typescript
 zone.run(()=>{
   let reader = new FileReader();
 });
  ```
`new FileReader()` it will call zone's delegated constructor that will transform onProperties to `addEventListener`. `reader` being a zone-patched instance of `FileReader`.

Implementing a method like `zone.runUnpatched(()=>{})` that will call the actual non-patched constructor would solve that kind of problem :
 ```typescript
 zone.runUnpatched(()=>{
   let reader = new FileReader();
 });
 ```

**Comment by JiaLiPassion** [comment]
@n00dl3 , could you provide a reproduce repo?

**Comment by n00dl3** [comment]
I guess I can but it will only work on mobile device (not browser) and sounds like a pain in the a** to create. If I just mock cordova's `FileReader` patch is that okay for you (I just need to create a `FileReader` that does not implement `EventTarget`) ?

**Comment by JiaLiPassion** [comment]
@n00dl3 , a cordova project or a mock `FileReader` both works for me.

**Comment by JiaLiPassion** [comment]
@n00dl3 , could you try the attached zone.js.zip?

[zone.js.zip](https://github.com/angular/zone.js/files/1222910/zone.js.zip)

**Comment by JiaLiPassion** [comment]
I think this will be easy to fix in cordova-file-plugin, I have created a PR there.
https://github.com/apache/cordova-plugin-file/pull/215/files
