### ISSUE TITLE
readonly property should not be patched in patchMethod in v0.8.16

### ISSUE THREAD

**Issue by manugarciac** [angular/zone.js#869]
I'm getting the error while testing my application on Safari. It is fixed if I comment this lines (lines 1226 to 1228):

        proto[name] = function () {
            return patchDelegate_1(this, arguments);
        };

Inside `function patchMethod(target, name, patchFn)`.

Could you please check it out?

Thank you

**Comment by JiaLiPassion** [comment]
@manugarciac , could you post a reproduce repo?

**Comment by BillyQin** [comment]
@manugarciac @JiaLiPassion It works. i am wait for the next release

**Comment by manugarciac** [comment]
@JiaLiPassion That is the same file from this issue, right?

https://github.com/angular/zone.js/issues/859#issuecomment-318909774

I had already tested it with that before opening my issue, and no, it doesn't work.

@BillyQin What do you mean? The zip works for you?

**Comment by JiaLiPassion** [comment]
@manugarciac , yes, it is the same file, so could you provide a reproduce repo?

**Comment by manugarciac** [comment]
@JiaLiPassion Here you go:

https://github.com/manugarciac/safari-error-app

You can do `npm install` and then `ng serve` to test it. The page loads, but the error is there. I start it like this: `ng serve --host 0.0.0.0 --disable-host-check` so that I can test it on another PC with Safari (I don't have Safari on my own PC).

**Comment by JiaLiPassion** [comment]
@manugarciac , thank you, I will fix this one.
