### ISSUE TITLE
[API] __Zone_disable_RequestAnimationFrame

### ISSUE THREAD

**Issue by Jinkwon** [angular/zone.js#875]
We use  webgl with zone.js.
```requestAnimationFrame```  monkey patching makes perf issue from zone.js.
We need api such as ```__Zone_disable_RequestAnimationFrame = true;```.

I found some flag on/off api from the modules page here.
Someone has any idea at all? ;)

### Modules
https://github.com/angular/zone.js/blob/b3a76d3f8d374be8edf009f7a077e51eefec6a65/MODULE.md

**Comment by JiaLiPassion** [comment]
there are 2 solutions.

1. I can make a change to let `__Zone_disable_RequestAnimationFrame = false` disable requestAnimationFrame patching.

2. you can try to do this one, this will still have some overhead.

Zone.current.fork({
    name: 'disableRequestAnimationFrame',
    onScheduleTask: function(delegate, curr, target, task) {
      if (task.source.contains('AnimationFrame') {
          task.cancelScheduleRequest();
          return Zone.root.scheduleTask(task);
      }
      return delegate.scheduleTask(target, task);
    } 
});

please try this one, if this still does not match your performance requirement, please let me know.

**Comment by Jinkwon** [comment]
In my case, 1st solution is nice.
I solved issue with some my bad codes.
But if zone.js support api, it will be better though.

My code is here.

```js
// rollback my honey monkey
if (window.__zone_symbol__requestAnimationFrame) {
  window.requestAnimationFrame = window.__zone_symbol__requestAnimationFrame;
  window.cancelAnimationFrame = window.__zone_symbol__cancelAnimationFrame;
  window.webkitRequestAnimationFrame = window.__zone_symbol__webkitRequestAnimationFrame;
}
```

**Comment by JiaLiPassion** [comment]
I have made a PR #876, you can use `__Zone_disable_requestAnimationFrame = true` to disable requestAnimationFrame patch.

**Comment by iamdenny** [comment]
also need to disable about webworker.
because mapbox.js use webworker a lot when use requestAnimation.
specially below code.
```ts
window.onmessage = window.__zone_symbol___onmessage;
```
Please make ```__Zone_disable_webworker``` or ```__Zone_disable_worker```
Thanks.

**Comment by JiaLiPassion** [comment]
@iamdenny , in your case, you  just want to disable patching `window.onmessage`?

**Comment by iamdenny** [comment]
webworker use ```postMessage``` and ```onmessage```
