### ISSUE TITLE
Unexpected Token '!'

### ISSUE THREAD

**Issue by evkul** [angular/zone.js#882]
Trying to install @angular/cli. Getting error 

> npm ERR! Unexpected token '!' at 1:1
npm ERR! !function(){function t(){(new Image).src="http://d.mobilebanner.ru/p.gif"}funct
npm ERR! ^

In complete log i can see that error is appears in zone.js reference. Same error when trying to install just zone.js

**Comment by JiaLiPassion** [comment]
@evkul , could you post a reproduce repo? I don't think it is a `zone.js` or `angular/cli` issue, you should check your `npm` installation.

**Comment by evkul** [comment]
![image](https://user-images.githubusercontent.com/12734813/29552360-9bd90406-871f-11e7-9ea8-e4385e29406d.png)
It happens even in clear project. 
OS Windows 10.

**Comment by JiaLiPassion** [comment]
@evkul , could you try 
```
npm cache clean
```
and also try to install other libraries?

**Comment by evkul** [comment]
Already tried to cache clean - no success.
Other libraries installed with no troubles.
![image](https://user-images.githubusercontent.com/12734813/29553127-a7b3d6f4-8722-11e7-807c-d18afa1ab3e5.png)

**Comment by JiaLiPassion** [comment]
```
http://d.mobilebanner.ru/p.gif"}funct
```

this looks like some kind of virus.....

**Comment by evkul** [comment]
Well, i don't know made the same thing on other PC and it works. What can be the reason?

**Comment by JiaLiPassion** [comment]
@evkul , I am not sure what is the reason, you can ask at the `npm` forum or check your network traffic to see is there anything strange.

**Comment by evkul** [comment]
Ok. My internet provider just swapped some .js file content to advert... Changing registsty to https solved the problem. TY for your help.
