### ISSUE TITLE
0.8.13 breaks angular+polymer on IE11

### ISSUE THREAD

**Issue by russoturisto** [angular/zone.js#888]
1.  clone the example project and setup:
git clone https://github.com/first87/polymer-chat.git
npm install
bower install

2. upgrade zone.js
npm i --save zone.js@0.8.13

3. build the app (from root dir):
ng build
polymer build

4. start in a server (from build\es5\dist):
ws --spa index.html

5. Go to IE11, open some other app and load dev tools, with console focused, then go to localhost:8000. The app is broken (compared to the default version - 0.8.12)  - lots of errors in the console

**Comment by JiaLiPassion** [comment]
@russoturisto , I can reproduce with your steps, and I install `npm install --save zone.js@0.8.17`, the error gone.

**Comment by russoturisto** [comment]
Thank you, will try again on Monday, in the example project  and on our
project.  If I can still reproduce on our project it might take me a while
to distill exactly what combination of libraries is causing this (have
deadlines).

Thanks, :)

**Comment by russoturisto** [comment]
Unfortunately, I won't have the time to take a look at it till Thursday.  I know that the page was breaking with 0.8.17 but it also had newer versions of core-js and webcomponentsjs.  I'll have to figure out what versions of those libraries break with 0.8.17.  Will let you know.

Thanks, :)

**Comment by JiaLiPassion** [comment]
Close for now because not be able to reproduce.
