### ISSUE TITLE
es6-promise overwrites zone.js

### ISSUE THREAD

**Issue by josephliccini** [angular/zone.js#891]
I am not sure exactly which library is exactly responsible for the issue, but if one looks at this line:

https://github.com/stefanpenner/es6-promise/blob/a5838bd94a76e31ad80ac1685bcd0dbc3d8ce963/dist/es6-promise.js#L1133-L1144

One can see that they are expecting
`Object.prototype.toString.call(window.Promise.resolve())` to be `[object Promise]`, but `zone.js` gives `[object Object]`

So, I am wondering, should `es6-promise` (coming from another widget hosted on our page served over their CDN) look for `[object Object]`, or should zone.js have `[object Promise]` for this `toString()`

**Comment by josephliccini** [comment]
This seems to work, though not clean or reliable:
```ts
var oldToString = Object.prototype.toString;
Object.prototype.toString = function () {
    if (this instanceof Promise) {
        return '[object Promise]';
    }
    return oldToString.call(this);
};
```

Maybe this could be added to zone.js so other polyfills won't overwrite?

**Comment by josephliccini** [comment]
Or perhaps Zone.js could make `window.Promise` a `setter` function, and anytime it is set, Zone.js wraps with ZoneAwarePromise? So then if any library were to set `window.Promise`, it could reject it, wrap it, or at least warn?  Just brainstorming here

**Comment by JiaLiPassion** [comment]
@josephliccini , it seems duplicate with #499, I will check the behavior later.

**Comment by josephliccini** [comment]
This one seems fixed! Thanks!

There is one issue I am seeing, but it's not affecting me but may be good for you to know.

I did a test to see what would happen with `core-js` Promise.

My code has this now: 
```ts
import 'zone.js';
import 'core-js/es6/promise';
```

And before bootstrap I get this error:
```
Uncaught TypeError: NativePromise.resolve is not a function
    at Object.setNativePromise (zone.js:634)
    at desc.set (zone.js:1028)
    at webpackJsonp.../../../../node_modules/core-js/modules/_redefine.js.module.exports (_redefine.js:19)
    at $export (_export.js:27)
    at Object.../../../../node_modules/core-js/modules/es6.promise.js (es6.promise.js:230)
    at __webpack_require__ (?mockauth=2:61)
    at Object.../../../../node_modules/core-js/es6/promise.js (promise.js:4)
    at __webpack_require__ (?mockauth=2:61)
    at Object../vendor.ts (zone.js:3026)
    at __webpack_require__ (?mockauth=2:61)
```

**Comment by JiaLiPassion** [comment]
@josephliccini , thanks for the information, I will check this error.

**Comment by josephliccini** [comment]
@JiaLiPassion  thanks I am excited to try in next release :)

**Comment by kflorian** [comment]
Our app is not working on IE11 due to this issue, using version 0.8.18.
Waiting desperately for a fixed version!

**Comment by goyalvarun601** [comment]
any update on this?

**Comment by JiaLiPassion** [comment]
@goyalvarun601 , this one have been merged, please wait for the next release.

**Comment by goyalvarun601** [comment]
thanks @JiaLiPassion , when is the next release?

**Comment by JiaLiPassion** [comment]
@goyalvarun601 , I am not sure, please wait for a while.

**Comment by mcterrySep** [comment]
I am also interested in when this is resolved.

**Comment by yevhenGuba** [comment]
The same is at my side. What is the approximate date for a new release ?

**Comment by JiaLiPassion** [comment]
for now, please update your `package.json` with 
```javascript
    "zone.js": "https://github.com/angular/zone.js.git"
```

**Comment by jonathanbarton** [comment]
next release? when's that

**Comment by goyalvarun601** [comment]
I am still getting the same error using "https://github.com/angular/zone.js.git". 
```
zone.js:634 Uncaught TypeError: NativePromise.resolve is not a function
    at Object.setNativePromise (zone.js:634)
```
Did it solve anyone else's issue?

**Comment by JiaLiPassion** [comment]
@goyalvarun601 , sorry,  the `zone.js/dist/zone.js` in this repository is not updated, please used the attached version.
[zone.zip](https://github.com/angular/zone.js/files/1459699/zone.zip)

**Comment by goyalvarun601** [comment]
The zip doesn't have the updated dist/zone.js

**Comment by JiaLiPassion** [comment]
@goyalvarun601 , you are right, I used the old version, please use this one.
[zone.zip](https://github.com/angular/zone.js/files/1459851/zone.zip)

**Comment by goyalvarun601** [comment]
thanks @JiaLiPassion

**Comment by JiaLiPassion** [comment]
@goyalvarun601 , sure, you can use my branch, https://github.com/JiaLiPassion/zone.js/tree/some-fix

**Comment by goyalvarun601** [comment]
@JiaLiPassion The branch doesn't have the updated dist/zone.js

**Comment by JiaLiPassion** [comment]
@goyalvarun601 , please use this one, https://github.com/JiaLiPassion/zone.js/tree/issue-891

**Comment by goyalvarun601** [comment]
Thank you. This works.

**Comment by jdespatis** [comment]
thanks @JiaLiPassion it works also for me
=> any idea when it will be merged in zone.js to have an official new version ?

**Comment by JiaLiPassion** [comment]
@jdespatis , it has been merged, but I am not sure when there will be a new version.

**Comment by jdespatis** [comment]
nice news @JiaLiPassion , but strangely, if I use your branch in my package.json:
"zone.js": "https://github.com/JiaLiPassion/zone.js.git#issue-891",
all is running well, 

but when using zone.js master branch, the problem with NativePromise still exists
my package-lock.json indicates the very last commit on zone.js:
    "zone.js": {
      "version": "git+https://github.com/angular/zone.js.git#326a07fb9095e4a87ff7561cb45fe1d4917c2174"
    }

Maybe I'm doing something wrong, or maybe your branch contains more than the fix committed in zone.js ?

**Comment by JiaLiPassion** [comment]
@jdespatis , the content are the same between my branch and `master`, the reason `master` not work because `dist` folder is not updated in `master` branch, it will only be updated when new version released.

**Comment by jdespatis** [comment]
ok thanks for your feedback @JiaLiPassion !
