### ISSUE TITLE
ZoneAwarePromise.all does not work properly with generators

### ISSUE THREAD

**Issue by OsvaldoRosado** [angular/zone.js#892]
We found this bug from a report of our use of Zone.js in the Application Insights Node.js SDK causing generator functions to not get called: https://github.com/Microsoft/ApplicationInsights-node.js/issues/267

Native promises in Node.js support taking the result of a generator function as an argument to `Promise.all`, and wait for all yielded promises to complete. For example:
```
var generator = function*() {
    yield Promise.resolve('1');
    yield Promise.resolve('2');
    yield Promise.resolve('3');
    return;
};

Promise.all(generator()).then(val=>{
    console.log(val);
})
```
will print out `[ '1', '2', '3' ]`. This breaks when including zone into the project.

The code for the `ZoneAwarePromise.all` method correctly uses a for-of loop to iterate its value (see https://github.com/angular/zone.js/blob/a66595af18d4c42584401dd2df387b02cb01d8d9/lib/common/promise.ts#L273)

However, the compiled source, for zone-node at least, converts this into a standard for loop iterating an index against `value.length` (see https://github.com/angular/zone.js/blob/b9c0d9c09776bc253f3156ea511c9a1a5c952c31/dist/zone-node.js#L893). This unfortunately doesn't work for generators, as they are iterable but don't have a defined length in advance.

The end result is executing the code sample above with zone.js included is getting the following printed out: `[]`

**Comment by JiaLiPassion** [comment]
@OsvaldoRosado , thank you for posting the issue. I will check it.

**Comment by OsvaldoRosado** [comment]
Thanks!
