### ISSUE TITLE
XMLHttpRequest Issue using Java8 JavaFX Web View/Webkit v538.19

### ISSUE THREAD

**Issue by JRiggenbach** [angular/zone.js#906]
Does anyone know of an issue where the patching that zone.js performs for the XMLHttpRequest object does not work with webkit v538.18?  It appears that the XMLHttpRequest object, after it is cloned, all the properties are undefined.  Unfortunately we are stuck using an older version of the Java8 library that has this version of webkit for the web view control.  Newer version of the Java library, and subsequent new version of the webkit library, this problem does not exist.  I can post a gist that can recreate the problem if necessary.  Thanks.

**Comment by JiaLiPassion** [comment]
@JRiggenbach , please create a reproduce repo, and I don't know how to use the specified version of Webkit, please also provide some manual to do that.

**Comment by naveedahmed1** [comment]
Is it similar to this https://github.com/angular/angular/issues/19853

**Comment by JiaLiPassion** [comment]
Close for now because not be able to reproduce.
