### ISSUE TITLE
onHasTask is not triggered when second `setTimeout` macro task is scheduled and the first one completes

### ISSUE THREAD

**Issue by maximusk** [angular/zone.js#907]
I have the following setup:

```
let timer;

const zoneBC = Zone.current.fork({
    name: 'BC',
    onHasTask(delegate, current, target, hasTaskState) {
        console.log(Date.now() - timer);
        console.log(hasTaskState.change);
        console.log(hasTaskState.macroTask);
    }
});

function a() {}

function b() {
    timer = Date.now();
    setTimeout(a, 2000);
    setTimeout(a, 4000);
}

zoneBC.run(b);
```

The output to console is:

```
1
macroTask
true

4006
macroTask
false
```

So it seems that it tracks only `empty/not empty` state, not any changes to the queue like a new task is added/executed. Is it correct?

**Comment by JiaLiPassion** [comment]
@maximusk ,
1. yes, `onHasTask` only trigger when task queue become `empty`.
2. if you want to track `new task` was added, you should use `onScheduleTask` callback.

**Comment by maximusk** [comment]
@JiaLiPassion , that's what I thought. Thanks a lot for the confirmation! I've almost finished the article on zones. Will ping you once it's ready and hopefully you'll have time to review it.

**Comment by JiaLiPassion** [comment]
@maximusk , sure, looking forward to it!

**Comment by maximusk** [comment]
@JiaLiPassion , fantastic! 

To clarify, I can track when an individual task is being added with `onScheduleTask`, but how to know it finished executing and is removed from the tasks queue?

**Comment by JiaLiPassion** [comment]
@maximusk , you can use `onInvokeTask` callback.

```javascript
onInvokeTask(...) {
    const result = delegate.invokeTask(targetZone, task);
    // here the task is invoked.
    console.log('task invoked');
    return result;
}
```

**Comment by maximusk** [comment]
@JiaLiPassion , great suggestion, thanks! Maybe that's the reason Angular `NgZone` uses `onInvokeTask` hook

**Comment by maximusk** [comment]
@JiaLiPassion , and with `onScheduleTask` is my understanding correct that instead of the original task I get through the last parameter:

`onScheduleTask?:  (parentZoneDelegate: ZoneDelegate, currentZone: Zone, targetZone: Zone, task: Task) => Task;
`

I can return a new task to be scheduled?

**Comment by JiaLiPassion** [comment]
@maximusk ,

in `onScheduleTask`, you need to call `return parentZoneDelegate.scheduleTask(targetZone, task);`, otherwise `onInvokeTask` will not be triggered, and `async` operation will not be executed.

And return a different task from `onScheduleTask` are not supported, I am not sure I understand what is your use case.

**Comment by maximusk** [comment]
@JiaLiPassion , appreciate your help! It worked!

> And return a different task from onScheduleTask are not supported, I am not sure I understand what is your use case.

No particular use case, just for educational purposes.

**Comment by maximusk** [comment]
@JiaLiPassion , where can I send you an article draft reference? Do you have a twitter account? Gmail account?

**Comment by JiaLiPassion** [comment]
@maximusk , sure, you can send to JiaLi.Passion@gmail.com

**Comment by maximusk** [comment]
@JiaLiPassion , great, sent an email
