### ISSUE TITLE
zone.js loaded by twice, by two separate sources

### ISSUE THREAD

**Issue by umairda** [angular/zone.js#910]
I built a JS widget using angular 2 that is embedded on other websites. One of the sites that the widget is embedded on has another script that loads zone.js. So when my script loads I get the error: 
```
Error: Zone already loaded. at new g...
```
Is there a way to configure angular-cli (1.0.0-rc.0)/webpack to not load zone.js if it has previously been loaded?

**Comment by oztek22** [comment]
Is there any way to determine it or not?

**Comment by aaaa0441** [comment]
I need to subscribe myself to this issue, waiting for a release of the fix.

**Comment by umairda** [comment]
I was able to solve this issue by ejecting the webpack config then namespacing my chunks via the `jsonpFunction` option.

To be honest I don't understand how this resolves the issue of `zone.js` being loaded twice- but it does.

**Comment by mleibman** [comment]
Should the same be done for loading patches?
