### ISSUE TITLE
0.8.17 seems broken on IE

### ISSUE THREAD

**Issue by marcovdb** [angular/zone.js#911]
Using Zone.js 0.8.17, my application fails in IE11 with the following error message:

```
SCRIPT5007: Unable to get property 'type' of undefined or null reference
zone.js (196,25)
```

Reverting to 0.8.16 fixes the issue.

**Comment by JiaLiPassion** [comment]
@marcovdb ,could you provide a reproduce repo? Or could you help me to debug the error detail? thank you!

**Comment by marcovdb** [comment]
Sure, happy to help.

I modified zone.js to log the offending task to the console and this is what it's telling me:

![image](https://user-images.githubusercontent.com/10506742/30684377-4471f566-9eb1-11e7-9c36-27bfdf213b6d.png)

I don't know if that is helpful at all?

**Comment by JiaLiPassion** [comment]
@marcovdb ,could you show me the source location where the error throw? and which object is undefined? thank you.

**Comment by marcovdb** [comment]
```
"TypeError: Unable to get property 'type' of undefined or null reference
   at wrapFn (eval code:1071:5)
   at loadreadystatechange (eval code:48:9)
   at oninterval (eval code:77:33)
   at Anonymous function (eval code:15:23144)
   at d (eval code:15:23122)
   at ZoneDelegate.prototype.invokeTask (eval code:424:13)
   at Zone.prototype.runTask (eval code:192:21)
   at ZoneTask.invokeTask (eval code:500:17)
   at invoke (eval code:489:21)
   at timer (eval code:1897:17)"
```

**Comment by JiaLiPassion** [comment]
@marcovdb , thank you for the information, so about the stacktrace, I still need to know the `target` and `eventName`, for example, if we call `button.onclick = function() {}`, then `button` is target, and `click` is eventName, so could you help me to find those information by checking the `loadreadystatechange`, `oninterval` and other stack frames?

**Comment by marcovdb** [comment]
![image](https://user-images.githubusercontent.com/10506742/30735280-b10ce2c6-9f7e-11e7-9bb6-622d42a728ec.png)

The attached zone.js works fine :) No issues with that one.
