### ISSUE TITLE
Zone.js 0.8.18 errors

### ISSUE THREAD

**Issue by dmitrykurmanov** [angular/zone.js#918]
Hello team! I have an example on plnkr with angular2 in es5 style and zone 0.8.17: https://plnkr.co/edit/fTvjvFgA61a6SWzs69IL?p=preview and it works fine. But with a new version of zone.js I have two errors:

VM1443 zone.js:634 Uncaught TypeError: NativePromise.resolve is not a function and
VM1446 core.umd.js:716 Uncaught TypeError: Reflect.defineMetadata is not a function

here an example with 0.8.18

https://plnkr.co/edit/hQ62L8cXZYbEHPYsohP0?p=preview (please check the console)

Could you please help me with it? Thanks.

**Comment by JiaLiPassion** [comment]
@dmitrykurmanov , this has been fixed in #916, I don't know `Reflect.defineMetadata` this error, I will try your plunker later.

**Comment by dmitrykurmanov** [comment]
@JiaLiPassion, ok thanks for the fast respond

**Comment by JiaLiPassion** [comment]
@dmitrykurmanov , sure, I have check your plunker with #916, it works, both errors disappear. So please wait for next release.

**Comment by dmitrykurmanov** [comment]
@JiaLiPassion, great! Thank you!
