### ISSUE TITLE
[Question] Full list of the supported APIs 

### ISSUE THREAD

**Issue by maximedupre** [angular/zone.js#919]
Where can I get the list of the supported APIs?

I know for example that the AudioContext (Web Audio API) is not supported (#600). I also know that Web Workers `onmessage` isn't supported. Where can I get the full list?

Cheers!

**Comment by JiaLiPassion** [comment]
@maximedupre , AudioContext and WebWorker.onmessage should have been supported in `zone.js` 0.8.18, could you test it, and currently there is a document which described the APIs, but not updated. 

https://github.com/angular/zone.js/blob/master/MODULE.md
https://github.com/angular/zone.js/blob/master/NON-STANDARD-APIS.md

**Comment by maximedupre** [comment]
I installed `v0.8.18` and tested support for the AudioContext and WebWorker APIs and it still isn't working. I'm testing via Angular2, so maybe this is why.

**Comment by JiaLiPassion** [comment]
Could you post a reproduce repo?

**Comment by maximedupre** [comment]
I don't have time to try and reproduce, but all my libs (angular + zone) are at the latest version if that helps. Change detection works as expected everywhere except with `decodeAudioData` and `postMessage`, so I run change detection manually in those cases.

**Comment by JiaLiPassion** [comment]
so please post some sample code to describe which API you used.

**Comment by maximedupre** [comment]
Literally this is what is happening:

In template: 
    
    {{ this.status }}


In component:

    this.drawWorker.onmessage = e => {
        this.status = 'drawn';
        this.changeDetectionRef.detectChanges();    // Without this line of code, template isn't updated
    }

**Comment by maximedupre** [comment]
I think that another lib I'm using (Tone.js) is also patching some functions, which cancels the effect of zone.js

**Comment by JiaLiPassion** [comment]
@maximedupre , if that is the case, you should load `Tone.js` before `zone.js`.

**Comment by JiaLiPassion** [comment]
Close it for now.
