### ISSUE TITLE
RTCPeerConnection broken on iOS 11.01 Safari

### ISSUE THREAD

**Issue by benbro** [angular/zone.js#920]
I have angular WebRTC app that works with zone.js 0.8.12 but breaks with zone.js 0.8.18.
I tried both pc.addEventListener() and pc.onX callbacks.
Issue https://github.com/angular/zone.js/issues/883 and PR https://github.com/angular/zone.js/pull/905 are related.

I'm using [adapter.js](https://github.com/webrtc/adapter) that [polyfills](https://github.com/webrtc/adapter/blob/master/src/js/safari/safari_shim.js) some of the RTC objects.

Change detection is unpredictable in different browsers when using zone.js with adapter.js.
On some browsers RTCPeerConnection callback run inside the zone and on others outside the zone.
For example pc.onicecandidate=callback or pc.addEventListener('icecandidate', callback) run inside the zone on Chrome but outside in Firefox and Safari.
I've been fighting zone.js for days and it changes on each zone.js / adapter.js release.

**Comment by JiaLiPassion** [comment]
@benbro , could you post a reproduce repo? and please tell me which browser not work. thanks!

**Comment by benbro** [comment]
Safari on iOS 11.01 is broken.

I'll try to add zone.js to one of the RTCPeerConnection samples.
https://webrtc.github.io/samples/

I'll close it until I have a repo test.

**Comment by benbro** [comment]
@JiaLiPassion how can I add zone.js to a webrtc sample and test what callbacks run inside the zone and what outside the zone?
For example, how can I add zone.js to the [Basic peer connection example](https://github.com/webrtc/samples/blob/gh-pages/src/content/peerconnection/pc1/js/main.js).

In angular 4 app, do I need to load adapter.js (webrtc polyfill) before zone.js?
I'm currently loading adapter.js in vendor.ts but maybe I should load it in polyfills.ts before zone.js?

vendor.ts
```typescript
// Angular
import '@angular/platform-browser';
import '@angular/platform-browser-dynamic';
import '@angular/core';
import '@angular/common';
import '@angular/http';
import '@angular/router';
// RxJS
import 'rxjs';
// WebRTC
import '../node_modules/webrtc-adapter/out/adapter.js';
```

polyfills.ts
```typescript
import 'core-js/es6';
import 'core-js/es7/reflect';
// Do I need to load adapter.js here?
require('zone.js/dist/zone');

if (process.env.ENV === 'production') {
  // Production
} else {
  // Development and test
  Error['stackTraceLimit'] = Infinity;
  require('zone.js/dist/long-stack-trace-zone');
}
```

**Comment by benbro** [comment]
@JiaLiPassion 
In Firefox 56.0 [RTCPeerConnection.ontrack](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/ontrack) run outside of the zone.
In Chrome 61 ontrack run inside the zone.

I'm not sure how to reproduce without a full angular app.
I forked the WebRTC PeerConnection example and added some console messages.
https://benbro.github.io/samples/src/content/peerconnection/pc1
https://github.com/benbro/samples/blob/gh-pages/src/content/peerconnection/pc1/js/main.js
adapter.js (WebRTC polyfill) is added here:
https://github.com/benbro/samples/blob/gh-pages/src/content/peerconnection/pc1/index.html

Can you please guide me how to show that ontrack is run inside the zone in Chrome and outside the zone in Firefox?

**Comment by JiaLiPassion** [comment]
@benbro , could you tell me how to reproduce the issue with https://benbro.github.io/samples/src/content/peerconnection/pc1/ ?

**Comment by benbro** [comment]
I don't know yet how to reproduce it without a full angular app.
Is there a basic angular 4 template with recent zone.js that I can use and just add the webrtc part?

Is it possible to log what triggered the zone in one of the callbacks (onHasTask, onScheduleTask, onInvokeTask) ?
https://github.com/benbro/samples/blob/gh-pages/src/content/peerconnection/pc1/js/main.js#L14

**Comment by JiaLiPassion** [comment]
@benbro , ok , I will try to create a sample and try to run in the latest version of Firefox and Chrome.

**Comment by benbro** [comment]
I've opened an new issue.
