### ISSUE TITLE
what's wrong? how can I fix it

### ISSUE THREAD

**Issue by yangzhaohui89** [angular/zone.js#923]
![1](https://user-images.githubusercontent.com/21998464/31328525-3e9bacc6-ad08-11e7-86ef-526750715873.png)
loop not stop

![2](https://user-images.githubusercontent.com/21998464/31328550-6a0a3864-ad08-11e7-8d0b-c66f98e8df22.png)

**Comment by JiaLiPassion** [comment]
@yangzhaohui89, I don't think this is `zone.js` issue, it should be your application's error, and `zone.js` just catch it and report it to you.

**Comment by RoestVrijStaal** [comment]
Well, it doesn't say which file and line the ticket starter needs to look at.

**Comment by JiaLiPassion** [comment]
Close it because it is not a zone.js issue.
