### ISSUE TITLE
zone.js 0.8.4 upgrade throwing net:  ERR CONNECTION REFUSED doing some sort of XHR task

### ISSUE THREAD

**Issue by bofcarbon1** [angular/zone.js#932]
I am running an Angular 4 app on Cloud 9 IDE (Ubuntu VM) which uses webpack 3.10..n starts a server with 'ng server host 0.0.0.0 and port 8080. The local host URL is very specific for Cloud 9 IDE and the ports are limited. Never the less the app works but I recently started to get this error

htttp://localhost/8080/sock.js-node/?info?t=some number net::ERR-CONNECTION REFUSED

And the error is picked up in zone.js

The zone.js code and error look from bottom up 3 lines ....

start of code....

function scheduleTask(task) {
    XMLHttpRequest[XHR_SCHEDULED] = false;
    var data = task.data;
    // remove existing event listener
    var listener = data.target[XHR_LISTENER];
    if (listener) {
        data.target.removeEventListener('readystatechange', listener);
    }
    var newListener = data.target[XHR_LISTENER] = function () {
        if (data.target.readyState === data.target.DONE) {
            // sometimes on some browsers XMLHttpRequest will fire onreadystatechange with
            // readyState=4 multiple times, so we need to check task state here
            if (!data.aborted && XMLHttpRequest[XHR_SCHEDULED] && task.state === 'scheduled') {
                task.invoke();
            }
        }
    };
    data.target.addEventListener('readystatechange', newListener);
    var storedTask = data.target[XHR_TASK];
    if (!storedTask) {
        data.target[XHR_TASK] = task;
    }
    sendNative.apply(data.target, data.args);  ///' error message Failed to load resource: net::ERR_CONNECTION_REFUSED  ////
    XMLHttpRequest[XHR_SCHEDULED] = true;
    return task;
}
end of code.............

I don't even know what the scheduled task would be or why zone.js is processing this XHR TASK for data.
My observable calls are in an injected service and they are the only way that I pass Json data back and forth through http request/responses. All this works fine. Can't figure out why this task attempt is made with no data on Google Chrome.

Any ideas?

**Comment by JiaLiPassion** [comment]
@bofcarbon1 , `zone.js` monkey-patch `XHR` to be able to manage async operations, the error seems like you can't access the `URL` you provided. it doesn't look like a `zone.js` issue.

**Comment by schrodi** [comment]
Hi,

I have the same issue with a dev-server on cloud9. It is correct, that the url is not reachable. The reason is, that the dev-server is not running on localhost. The dev-server is running on a distant server in the cloud9 cloud. The url with localhost is not correct.

Is there a way to change the url to the server for the XHR requests.

This are mine consol outputs:

GET http://localhost:8080/sockjs-node/info?t=1510126113321 net::ERR_CONNECTION_REFUSED

**Comment by schrodi** [comment]
Hi there,

I think I have found a workaround.

Actually I start the dev-server manually:

$ webpack-dev-server --inline --hot --host 0.0.0.0

To use the webpack-dev-server command you need a webpack.config.js . In my environment there was no config file. I have generated it with 

$ ng eject

Then I could start the webpack server by  the above command. I get not anymore WDV Disconnects or 404 error.

**Comment by JiaLiPassion** [comment]
Closes it because it is not a zone.js issue.
