### ISSUE TITLE
`.catch` is not patched in Zones when overriding promise set later

### ISSUE THREAD

**Issue by benjamingr** [angular/zone.js#936]
Found in [question here](https://stackoverflow.com/questions/46881209/updating-angular-component-field-from-promise-catch-does-not-update-ui).

`patchThen` is missing a line that patches `.catch` and there is no reason to assume `.catch` actually calls `.then` internally.

The following code should suffice:

```js
    Ctor.prototype.catch= function(onReject: any) {
      const wrapped = new ZoneAwarePromise((resolve, reject) => {
        originalThen.call(this, resolve, reject);
      });
      return wrapped.then(null, onReject);
    };
```

**Comment by domenic** [comment]
> there is no reason to assume .catch actually calls .then internally.

Why not? It's in the standard that it does.

**Comment by benjamingr** [comment]
> Why not? It's in the standard that it does.

I'm sorry, you are absolutely right, I was sure it calls `PerformPromiseThen` but it looks like it literally says `Invoke(promise, "then", « undefined, onRejected »).`

**Comment by benjamingr** [comment]
Q, Bluebird, When as well as Chrome all implement `.catch` with `.then`.

Firefox used to call `Then` https://github.com/ricardoquesada/Spidermonkey/blob/4a75ea2543408bd1b2c515aa95901523eeef7858/dom/promise/Promise.cpp#L627-L631 in the C++ layer but seem to have fixed it more recently. I'll wait for OP to respond.

**Comment by JiaLiPassion** [comment]
Close it because it is not an issue.
