### ISSUE TITLE
Cannot find name 'global'.

### ISSUE THREAD

**Issue by MuhammadTaha** [angular/zone.js#947]
I have version 0.8.18

node_modules\zone.js\lib\common\utils.ts:19:81
    Cannot find name 'global'.

node_modules\zone.js\lib\zone.ts:1339:86
    Cannot find name 'global'.

> Can be resolved by adding `declare var global: any;` in zone.ts

**Comment by JiaLiPassion** [comment]
@MuhammadTaha , could you provide a reproduce repo and describe your environment ?

**Comment by MuhammadTaha** [comment]
this is my package.json

{
    "name": "angular-seed",
    "version": "0.1.1-milestone",
    "description": "Angular4 starter seed",
    "scripts": {
        "build": "npm run build:dev",
        "build:dev": "webpack --config config/webpack.dev.js --progress --profile",
        "build:prod": "webpack --config config/webpack.prod.js  --progress --profile --bail",
        "check-updates": "ncu",
        "ci": "npm run lint && npm test0 && npm run e2e",
        "clean": "npm cache clean && npm run rimraf -- node_modules doc coverage dist",
        "clean:dist": "npm run rimraf -- dist",
        "clean:install": "npm set progress=false && npm install",
        "clean:start": "npm start",
        "docs": "npm run typedoc -- --options typedoc.json --exclude '**/*.spec.ts' ./src/",
        "e2e": "npm run protractor",
        "e2e:live": "npm run e2e -- --elementExplorer",
        "list-missing-specs": "./scripts/list-missing-specs/index.js -d src/app",
        "build-and-launch-backend": "npm run build-backend && npm run launch-backend",
        "lint": "npm run tslint && npm run sass-lint",
        "postinstall": "typings install",
        "pree2e": "npm run webdriver:update -- --standalone",
        "protractor": "protractor",
        "rimraf": "rimraf",
        "sass-lint": "sass-lint \"src/**/*.scss\" -v -c .sass-lint.yml -q",
        "server": "npm run server:dev",
        "server:dev": "webpack-dev-server --config config/webpack.dev.js --progress --profile --watch --content-base src/",
        "server:dev:hmr": "npm run server:dev -- --inline --hot",
        "server:prod": "http-server dist --cors",
        "start": "npm run server:dev",
        "start:hmr": "npm run server:dev:hmr",
        "start:hmr:dashboard": "webpack-dashboard -- npm run server:dev -- --inline --hot",
        "tslint": "tslint \"src/**/*.ts\"",
        "typedoc": "typedoc",
        "watch": "npm run watch:dev",
        "watch:dev": "npm run build:dev -- --watch",
        "watch:dev:hmr": "npm run watch:dev -- --hot",
        "watch:test": "npm run local-test -- --auto-watch --no-single-run",
        "watch:prod": "npm run build:prod -- --watch",
        "webdriver:update": "npm run webdriver-manager update",
        "webdriver:start": "npm run webdriver-manager start",
        "webpack": "webpack",
        "webpack-dev-server": "webpack-dev-server",
        "webdriver-manager": "webdriver-manager",
        "whitesource": "whitesource run"
    },
    "dependencies": {
        "@angular-redux/store": "6.1.0",
        "@angular/animations": "4.0.3",
        "@angular/common": "4.0.3",
        "@angular/compiler": "4.0.3",
        "@angular/core": "4.0.3",
        "@angular/forms": "4.0.3",
        "@angular/http": "4.0.3",
        "@angular/platform-browser": "4.0.3",
        "@angular/platform-browser-dynamic": "4.0.3",
        "@angular/platform-server": "4.0.3",
        "@angular/router": "4.0.3",
        "@angularclass/conventions-loader": "1.0.2",
        "@angularclass/hmr": "1.2.2",
        "@angularclass/hmr-loader": "3.0.2",
        "@angularclass/request-idle-callback": "1.0.6",
        "@angularclass/webpack-toolkit": "1.3.3",
        "@ngx-translate/core": "6.0.1",
        "@ngx-translate/http-loader": "0.0.3",
        "@types/whatwg-fetch": "0.0.30",
        "assets-webpack-plugin": "3.4.0",
        "compute-median": "2.0.0",
        "core-js": "2.4.1",
        "decamelize": "1.2.0",
        "flexboxgrid": "6.3.1",
        "format-json": "1.0.3",
        "gulp-sourcemaps": "^2.6.0",
        "http-server": "0.9.0",
        "ie-shim": "0.1.0",
        "lodash": "4.17.4",
        "lodash.orderby": "4.5.0",
        "lodash.sortby": "^4.7.0",
        "moment": "2.14.1",
        "open-sans-fontface": "1.4.0",
        "redux": "3.5.2",
        "redux-logger": "2.6.1",
        "redux-thunk": "2.1.0",
        "reflect-metadata": "0.1.9",
        "rxjs": "5.4.2",
        "seamless-immutable": "6.1.1",
        "style-loader": "0.13.1",
        "typescript-require": "^0.2.9-1",
        "url-join": "1.1.0",
        "whatwg-fetch": "1.0.0",
        "zone.js": "0.8.14"
    },
    "devDependencies": {
        "@angular/compiler-cli": "4.0.3",
        "@types/core-js": "0.9.32",
        "@types/es6-collections": "^0.5.29",
        "@types/es6-shim": "^0.31.32",
        "@types/hammerjs": "2.0.28",
        "@types/jasmine": "^2.2.34",
        "@types/node": "^6.0.38",
        "@types/selenium-webdriver": "2.53.33",
        "@types/source-map": "0.1.26",
        "@types/uglify-js": "2.0.27",
        "@types/webpack": "2.0.0",
        "angular-router-loader": "0.4.0",
        "angular2-template-loader": "0.6.0",
        "archiver": "0.21.0",
        "awesome-typescript-loader": "3.0.0-beta.17",
        "codelyzer": "2.0.0-beta.4",
        "copy-webpack-plugin": "4.0.0",
        "css-loader": "0.26.0",
        "es6-promise-loader": "1.0.1",
        "exports-loader": "0.6.3",
        "expose-loader": "0.7.1",
        "file-loader": "0.9.0",
        "gh-pages": "0.11.0",
        "html-webpack-plugin": "2.21.0",
        "imports-loader": "0.6.5",
        "istanbul-instrumenter-loader": "0.2.0",
        "jasmine-core": "^2.5.2",
        "json-loader": "0.5.4",
        "karma": "1.2.0",
        "karma-chrome-launcher": "2.0.0",
        "karma-coverage": "1.1.1",
        "karma-growl-reporter": "1.0.0",
        "karma-jasmine": "1.0.2",
        "karma-jasmine-html-reporter": "0.2.2",
        "karma-jasmine-html-reporter-livereload": "1.0.0",
        "karma-junit-reporter": "1.1.0",
        "karma-mocha-reporter": "2.0.0",
        "karma-phantomjs-launcher": "1.0.2",
        "karma-sourcemap-loader": "0.3.7",
        "karma-webpack": "1.8.1",
        "minimist": "1.2.0",
        "mkdirp": "0.5.1",
        "node-sass": "4.2.0",
        "parse5": "1.5.1",
        "protractor": "4.0.10",
        "raw-loader": "0.5.1",
        "remap-istanbul": "0.6.3",
        "rimraf": "^2.5.2",
        "sass-lint": "1.10.2",
        "sass-loader": "4.1.1",
        "source-map-loader": "0.1.5",
        "style-loader": "0.13.1",
        "to-string-loader": "1.1.4",
        "ts-helpers": "1.1.1",
        "ts-node": "^3.3.0",
        "tslint": "4.2.0",
        "tslint-loader": "3.2.1",
        "typedoc": "0.4.5",
        "typescript": "2.2.2",
        "typescript-formatter": "2.3.0",
        "typings": "^1.5.0",
        "url-loader": "0.5.7",
        "webpack": "2.2.0-rc.2",
        "webpack-dashboard": "0.1.8",
        "webpack-dev-middleware": "1.9.0",
        "webpack-dev-server": "2.2.0-rc.0",
        "webpack-md5-hash": "0.0.5",
        "webpack-merge": "0.14.0",
        "webpack-shell-plugin": "0.4.2",
        "whitesource": "^0.3.14"
    }
}

**Comment by JiaLiPassion** [comment]
close for now for not be able to reproduce.
