### ISSUE TITLE
webrtc-adapter.js error

### ISSUE THREAD

**Issue by benbro** [angular/zone.js#949]
Chrome 62 throws an error when using zone.js 0.8.18 with webrtc-adapter.js 5.06

Loading this [example](https://angular-gitter-hckvde.stackblitz.io) which [imports](https://stackblitz.com/edit/angular-gitter-hckvde?file=polyfills.ts) webrtc-adapter in Chrome 62 gives an error:
```
Error: Uncaught (in promise): undefined
```

**Comment by JiaLiPassion** [comment]
@benbro , the underlying error is `No vendor resolution strategy found` which was reported by `EngineBlock` when loading `webrtc-adapter`, I am not sure how it related with `zone.js`

**Comment by benbro** [comment]
Maybe it's something in stackblitz.com.
Is there online Angular 5 template I can use to reproduce bugs (jsbin/jsfilldle/codepen)?

**Comment by JiaLiPassion** [comment]
@benbro , if it is possible , could you create a repo to reproduce the bug? so I can debug it in my local machine.
