### ISSUE TITLE
zones v0.8.18 interference with SharePoint2013/2016 web forms loading in Safari/Firefox

### ISSUE THREAD

**Issue by ninabina921** [angular/zone.js#950]
Currently running angular 4 app on SharePoint 2016. When changes are made in our webforms, these changes are no longer displayed dynamically. We have determined this issue only occurs with zones v0.8.18. You have to refresh the page to see your changes. 

The following error is shown in after a change in the form is made:

TypeError: Function.caller used to retrieve strict caller
<img width="1031" alt="screen shot 2017-11-02 at 10 59 03 am" src="https://user-images.githubusercontent.com/15370123/32332883-e81cf95a-bfbc-11e7-9bc2-d4498e7375ae.png">                        

This issue is only showing in Safari versions 10.1.2+ and Firefox. We do not experience this issue in Chrome

**Comment by JiaLiPassion** [comment]
@ninabina921 ， could you try to add following code before loading `zone.js`?
```
<script>
__Zone_enable_cross_context_check = true;
</script>

```

**Comment by ninabina921** [comment]
@JiaLiPassion I included this line in the master page before zone.js loads from the vendor.js file and I still get the same error in my console along with the error in my forms.

**Comment by JiaLiPassion** [comment]
@ninabina921 , could you provide a reproduce environment? Or try to find out the exact error (`Function.caller used to retrieve strict caller`) information, which `function` and the detailed `stacktrace`.

**Comment by ninabina921** [comment]
@JiaLiPassion I can check if I can provide a reproduce environment. Until then, these are the functions that appear in this error:

for the `runTask` error, it is occurring at this function : 
```
Zone.prototype.runTask = function(t, e, n) {
                                if (t.zone != this)
                                    throw new Error("A task can only be run in the zone of creation! (Creation: " + (t.zone || p).name + "; Execution: " + this.name + ")");
                                if (t.state !== h || t.type !== P) {
                                    var r = t.state != g;
                                    r && t._transitionTo(g, d), t.runCount++;
                                    var o = D;
                                    D = t, T = {
                                        parent: T,
                                        zone: this
                                    };
                                    try {
                                        t.type == k && t.data && !t.data.isPeriodic && (t.cancelFn = null);
                                        try {
                                            return this._zoneDelegate.invokeTask(this, t, e, n)
                                        } catch (t) {
                                            if (this._zoneDelegate.handleError(this, t))
                                                throw t
                                        }
                                    } finally {                           //runTask error
                                        t.state !== h && t.state !== m && (t.type == P || t.data && t.data.isPeriodic ? r && t._transitionTo(d, g) : (t.runCount = 0, this._updateTaskCount(t, -1), r && t._transitionTo(h, g, h))), T = T.parent, D = o
                                    }
                                }
                            }
```
for the `invokeTask` error : 
```
return ZoneTask.invokeTask = function(t, e, n) {
                                    t || (t = this), S++;
                                    try {
                                        return t.runCount++, t.zone.runTask(t, e, n)  // invokeTask error
                                    } finally {
                                        1 == S && drainMicroTaskQueue(), S--
                                    }
                                }
```

for the `timer` error:
```
  function patchTimer(t, e, n, r) {
                    function scheduleTask(e) {
                        function timer() {
                            try {
                                e.invoke.apply(this, arguments)  //timer error
                            } finally {
                                typeof n.handleId === c ? delete a[n.handleId] : n.handleId && (n.handleId[F] = null)
                            }
                        }
```

**Comment by JiaLiPassion** [comment]
@ninabina921 , I think I still need a reproduce environment to do further debug, those codes are from `zone.js`, I need to know the underlying `function` which `zone.js` try to invoke.

**Comment by ninabina921** [comment]
@JiaLiPassion right. I will work on trying to get access. Would a screen recording help? One of our developers was able to trace a possible caller function from one of the built-in sharepoint libraries `MicrosoftAjaxWebForms.js`

Here is the stack trace Firefox gave us
<img width="1337" alt="screen shot 2017-11-05 at 7 26 57 pm" src="https://user-images.githubusercontent.com/15370123/32563122-5a3ed268-c47e-11e7-81e2-eeffa5f58385.png">

**Comment by JiaLiPassion** [comment]
@ninabina921 , still I don't know the exact error from the screenshot you provided. there are several bugs in `zone.js` 0.8.18, and have been fixed, so please wait for the next release and try again.

**Comment by ninabina921** [comment]
@JiaLiPassion so it looks like this issue was resolved by removing use strict from the zone.js file in dist.  Is there a way a module could be added to disable strict? For example: _Zone_disable_strict = true?

**Comment by JiaLiPassion** [comment]
close for now because we will not remove 'use strict'.
