### ISSUE TITLE
zone.js v0.8.18 interferes with d3 drag/zoom

### ISSUE THREAD

**Issue by peinearydevelopment** [angular/zone.js#951]
I have created a [GitHub repo](https://github.com/PdUi/zone.js-bug) with demo projects showing the issue. I have tried to look through the changes on this repository between the versions and step through the code, but don't understand `zone.js` well enough to accurately debug this issue.

**Steps to reproduce**:
In `/17` run `npm install` then run `npm start`.
_Expected behavior_: click and release the mouse while over a node. Subsequently move the mouse around the screen and the circles should stay in place.
_Actual Behavior_: the expected behavior.

In `/18` run `npm install` then run `npm start`.
_Expected behavior_: click and release the mouse while over a node. Subsequently move the mouse around the screen and the circles should stay in place.
_Actual behavior_: The circles move around with the mouse and the only way to get it to stop is to right click on the screen.

The only thing different between the two examples is the version of `zone.js` used.

Thanks!

**Comment by JiaLiPassion** [comment]
@peinearydevelopment , I will check this one.

**Comment by peinearydevelopment** [comment]
@JiaLiPassion Thank you so much!!! That seems to have fixed it.
