### ISSUE TITLE
False numerous "Uncaught in promise" error indications

### ISSUE THREAD

**Issue by stasberkov** [angular/zone.js#954]
Using *zone.js* 0.8.18
Without *zone.js* the following code runs ok
`var t = Promise.reject(5).then((x)=>{console.log("fulfilled");}).then(null, (x)=>{console.log("rejected");});`
No *uncaught in promise* error indication.
While running the same code having *zone.js* loaded makes browser showing *uncaught in promise* error 3 times.

**Comment by JiaLiPassion** [comment]
@stasberkov , thank you for posting the issue, I will check it.

**Comment by JiaLiPassion** [comment]
@stasberkov , can't reproduce in `0.8.20`, could you provide a reproduce repo?

**Comment by JiaLiPassion** [comment]
will close for now for not be able to reproduce.
