### ISSUE TITLE
Unhandled Promise rejection: matchedQueriesDsl.forEach is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: matchedQueriesDsl.forEach is not a function

### ISSUE THREAD

**Issue by vinjog** [angular/zone.js#964]
Hi,
It looks working fine before installing/uninstalling some of the packages from my project.
but now, getting above error after application run. The project get compiled successful, however after seen developer tool found this error.
Following is the environment -
depdencencies
@angular/animations               5.0.3
@angular/common                   5.0.3
@angular/compiler                 5.0.3
@angular/core                     5.0.3
@angular/forms                    5.0.3
@angular/http                     5.0.3
@angular/platform-browser         5.0.3
@angular/platform-browser-dynamic 5.0.3
@angular/router                   5.0.3
angular-mocks                     1.6.6
core-js                           2.5.1
ng2-toastr                        4.1.2
rxjs                              5.5.2
zone.js                           0.8.18

devDependencies
@angular/cli                      1.5.4
@angular/compiler-cli             5.0.3
@angular/language-service         5.0.3
@types/jasmine                    2.8.2
@types/jasminewd2                 2.0.3
@types/node                       8.0.53
codelyzer                         4.0.1
jasmine-core                      2.8.0
jasmine-spec-reporter             4.2.1
karma                             1.7.1
karma-chrome-launcher             2.2.0
karma-cli                         1.0.1
karma-coverage-istanbul-reporter  1.3.0
karma-jasmine                     1.1.0
karma-jasmine-html-reporter       0.2.2
protractor                        5.2.0
ts-node                           3.3.0
tslint                            5.8.0
typescript                        2.6.1

![angularerror](https://user-images.githubusercontent.com/33949084/33198870-a04dbf48-d113-11e7-9aec-53862c988564.JPG)

**Comment by JiaLiPassion** [comment]
@vinjog , this is not a `zone.js` issue, it is an `error` from other lib, `zone.js` just report this error to console.

**Comment by vinjog** [comment]
ok
