### ISSUE TITLE
Need a way to access target for eventTasks

### ISSUE THREAD

**Issue by jahtalab** [angular/zone.js#969]
In newest versions of zone.js task.data.target is removed, is there anyway to access target for eventTasks?

**Comment by JiaLiPassion** [comment]
@jahtalab , you can call `target.eventListeners(eventName)` to get all listeners by `eventName`.

**Comment by jahtalab** [comment]
@JiaLiPassion, Thanks! I specifically need this for XMLHttpRequest, I have the target when the send method is called but eventTasks like `readystatechange` and `load` doesn't have target and I need to keep track of the events that are registered for XHR.

Calling `target.eventListeners(eventName)` when send is being scheduled only gives me the callbacks but I need to keep track of eventTasks and get notified when they're called.

Another problem is that for XHR it's possible to register those events after you call send (not a good practice but still possible) and then calling  `target.eventListeners(eventName)` wouldn't even include those events.

Is there a problem with adding target to task data here: https://github.com/angular/zone.js/blob/master/lib/common/events.ts#L398

**Comment by JiaLiPassion** [comment]
@jahtalab , could you post some sample code to describe what you need?

**Comment by jahtalab** [comment]
@JiaLiPassion ,

Here's some code (it's not exactly the code that I'm using but a simplified version):
Let me know if I need to clarify anything.

```javascript
Zone.current.fork({
  onScheduleTask: function (parentZoneDelegate, currentZone, targetZone, task) {
    var test = task.data.target['__test_symbol__'] || (task.data.target['__test_symbol__'] = {})
    test[task.source] = false
    if (task.source === 'XMLHttpRequest.send') {
      test.startTime = performance.now()
    }
    return parentZoneDelegate.scheduleTask(targetZone, task)
  },
  onInvokeTask: function (parentZoneDelegate, currentZone, targetZone, task, applyThis, applyArgs) {
    var test = task.data.target['__test_symbol__']
    test[task.source] = true

    var result = parentZoneDelegate.invokeTask(targetZone, task, applyThis, applyArgs)
    if (test['XMLHttpRequest.send'] && test['XMLHttpRequest.addEventListener:readystatechange'] && test['XMLHttpRequest.addEventListener:load']) {
      test.endTime = performance.now()
      console.log('XHR timing:', test.endTime - test.startTime)
    }
    return result
  }
}).run(function () {
  function reqListener () {
    console.log('XMLHttpRequest.load')
  }

  var oReq = new window.XMLHttpRequest()
  oReq.addEventListener('readystatechange', function () {})
  oReq.addEventListener('load', reqListener)

  oReq.open('GET', '/', true)
  oReq.send(null)
})

```

**Comment by JiaLiPassion** [comment]
@jahtalab , so you want to get `target` from `task`? you can try `task.target`.

**Comment by jahtalab** [comment]
@JiaLiPassion , I need the `target` in `onScheduleTask` callback. [here](https://github.com/angular/zone.js/blob/master/lib/common/events.ts#L399) `task.target` is set after the `zone.scheduleEventTask` call. Which makes sense since the `onScheduleTask` is supposed to return the new task. But it also means I can't access target in `onScheduleTask`.

**Comment by JiaLiPassion** [comment]
@jahtalab , I see, I will create a `patch` to let `onScheduleTask` access `target`, because `task` will keep a reference to `data`, so I also need to clean up the `target` from `data` after `scheduleEventTask`.
