### ISSUE TITLE
DOM event globalZoneAwareCallback slow on Edge

### ISSUE THREAD

**Issue by clabough** [angular/zone.js#971]
Using Microsoft Edge 40.15063.674.0, Angular 4.4.6 and Zone.js 0.8.18, I'm experiencing very slow performance. The performance session says that all of the time is being spent on DOM events (globalZoneAwareCallback to be specific).  Here's a snapshot of my performance window. I'm unable to share a public copy of the source, but if necessary, I can try to replicate it in a demo repo.

This may or may not be related to #703 and #757 

![image](https://user-images.githubusercontent.com/5217044/33452689-e3141788-d5c7-11e7-9eaf-ecad6766ab4a.png)

![image](https://user-images.githubusercontent.com/5217044/33452997-e995f6c0-d5c8-11e7-9f78-682573572ce1.png)

**Comment by clabough** [comment]
For now, I've gone back to 0.8.14 - which is the same version that the AngularCLI uses - and it's much better. 

It does seem that these function durations do get inflated when the Edge developer tools window is open but I can't find a way to profile within Edge with the developer tools window closed.

**Comment by JiaLiPassion** [comment]
@clabough , please try to add this in `index.html` before load `zone.js`.

```javascript
<head>
  <script>
    __Zone_enable_cross_context_check = true;
 </script>
</head>
```

**Comment by clabough** [comment]
Between that and an update to the Kendo dropdowns I'm using, things are better. Thanks.
