### ISSUE TITLE
Possibility to avoid zone switch (on emit) to the zone that was current during registration of event listener?

### ISSUE THREAD

**Issue by cbastuck** [angular/zone.js#976]
Imagine a logging framework where arbitrary reporters are **registered** during startup (root zone). The logs happen in individual zones (e.g. zone of a HTTP request) and the framework **dispatches**  them to all reporters. When using an event emitter for decoupling reporters from the framework it might look like this:  

```
require('zone.js/dist/zone-node');
const EventEmitter = require('events');

function reporter(data) {
  console.log(`Data: "${data}" was reported in zone: "${Zone.current.name}"`)
}

// register the reporter
const event = new EventEmitter;
event.on('data', reporter);

// emit data from root zone
event.emit('data', `Emitting from Zone: ${Zone.current.name}`);

// emit data from child zone
const childZone = Zone.current.fork({ name: 'ChildZone' });
childZone.run(() => {
  event.emit('data', `Emitting from Zone: ${Zone.current.name}`);
})
```
The output is as followed:
```
Data: "Emitting from Zone: <root>" was reported in zone: "<root>"
Data: "Emitting from Zone: ChildZone" was reported in zone: "<root>"
```

Is it possible to tell Zone.js to run the emit in ChildZone (current during emit) instead of the root zone (current during register)?

**Comment by JiaLiPassion** [comment]
@cbastuck , `zone.js` will run eventEmitter listener in the `zone` when `registered`, so in your code. you run `event.on('data', reporter);` in `root` zone, the reporter will only run in `root` zone even you `emit` the data in `childZone`.

- So if you want to run reporter in `childZone`, you must run `event.on('data', reporter);` in `childZone`.
- if you want to run reporter in `emit` zone, current you have to disable zone.js patch EventEmitter by add __Zone_disable_EventEmitter = true` to the `first` line of you code.

**Comment by cbastuck** [comment]
@JiaLiPassion thanks for your quick response. 

I fully understand _why_ the emits run in the `root` zone given the example above, and it makes sense to me. It's really just the question, if there is an API to "disable" the "monkey patching" zone.js is doing for **just** a single event emitter (`event` in the example). 

If I add `__Zone_disable_EventEmitter = true` I guess this will disable "monkey patching" for ALL event listeners that are registered afterwards, even in other modules. Is that correct?

**Comment by cbastuck** [comment]
Just a small hack to explain the idea: https://github.com/cbastuck/zone.js/commit/5a9f68ca5a7b76bc9b77bcd6f8010ebf77d20643

With this patch I could write `event.on('data', reporter, true);` instead of `event.on('data', reporter);` in the example above. Depending on the third parameter (`true` in this case) it would use `native` function for registration instead of the "monkey patched" version.

Is there already an API for similar functionality somewhere in zone.js?

**Comment by JiaLiPassion** [comment]
@cbastuck , I see, yes, you can do that, I will try to provide a better API later, for now you can call

```javascript
event[Zone.__symbol__('addListener')]('data', reporter);
```

**Comment by cbastuck** [comment]
@JiaLiPassion this is very helpful. Thanks again for the quick reply.
