### ISSUE TITLE
v0.8.18 Broke Bluebird Integration

### ISSUE THREAD

**Issue by jahumes** [angular/zone.js#977]
We have been dealing with issues with trying to get Bluebird to be our global promise library and still use Zone.js in our upgraded app. Basically, when following the instructions in the documentation for adding Bluebird.js to the ZoneAwarePromise, Bluebird gets overridden as the window.Promise library with the default Promise Library. This causes the browser patch to not work since it doesn't have the setScheduler function.

To fix this, you downgrade to 0.8.17 and everything works again. The code that breaks this is here https://github.com/angular/zone.js/compare/v0.8.17...v0.8.18#diff-c87353777ac53dcde41fac9008e56425, but I can see that is needed to allow for 3rd party libraries using the corejs/es6/promise shim. I am not sure the exact way to fix this, but I would be open to working on it if someone can point me to accommodate both options.

To see this in action, see the below jsBins:

**Working:** https://jsbin.com/zovapulofa/1/edit?html,console
**Broken:** https://jsbin.com/zarefecaha/edit?html,console

The only difference is the version of zone.js. You can type **window.Promise** into the console to see the current type of the global promise.

**Comment by JiaLiPassion** [comment]
@jahumes , yes, you need to use the code like this with `zone.js` 0.8.18

```javascript
  Zone[Zone['__symbol__']('bluebird')](window[Zone.__symbol__('Promise')]);
```

**Comment by jahumes** [comment]
Thanks for the update! That does get rid of the error, but it still doesn't make the window.Promise object a Zone Aware Bluebird Promise. It is just a ZoneAwarePromise. Any way for me to make that update as well?

**Comment by JiaLiPassion** [comment]
@jahumes, yes, current version if you load `zone.js`, the `window.Promise` will be `ZoneAwarePromise`. you can still get `Bluebird` Promise, but it will not ZoneAware.

**Comment by JiaLiPassion** [comment]
zone.js now handle bluebird as well, so I will close this for now
