### ISSUE TITLE
Monkey patching a load event is causing an infinite loading in IE11 after using loadCSS

### ISSUE THREAD

**Issue by rokerkony** [angular/zone.js#978]
Hi ...
based on the issue I created in https://github.com/addyosmani/critical/issues/264 I can say that monkey patching a load event is making https://github.com/filamentgroup/loadCSS unusable.

*loadCSS* is used as one of the dependencies of https://github.com/addyosmani/critical

After making a minimal repository (see here: https://github.com/addyosmani/critical/issues/264#issuecomment-352013453) for reproduction and removing load event from ZoneJS it works smooth.

**Comment by JiaLiPassion** [comment]
@rokerkony, I will check it, and could you describe the error detail ?  or I just run your repo I can see the error?

**Comment by rokerkony** [comment]
you should see an error when you run it in IE11 ... it will load `.css` fil all over again and again... it is caused by polyfill from loadCSS

the `serveDist` command needs `npm` and `find` so you will need to run it on mac or linux

**Comment by JiaLiPassion** [comment]
@rokerkony , could you make a package.json to use `ng build` without `aot and optimizer`? So I can check the code more clearly.

**Comment by rokerkony** [comment]
@JiaLiPassion should be enough to pull a new version and run
```
npm run serveDist:notMinified
```

**Comment by JiaLiPassion** [comment]
@rokerkony, I have made a PR to fix this one, thanks for posting the issue, you can update your `package.json` with 
```
    "zone.js": "https://github.com/JiaLiPassion/zone.js#oneventdist"
```

for test now.
