### ISSUE TITLE
datacloneerror on postMessage in worker.

### ISSUE THREAD

**Issue by snovos** [angular/zone.js#979]
Zone modifies Promise by adding extra properties to object, so it cannot be serialized. Is there any workaround for this case?

**Comment by JiaLiPassion** [comment]
@snovos , could you provide more information? or a reproduce repo?

**Comment by snovos** [comment]
@JiaLiPassion ,Thi is  sample code from **PDF.js** by Mozilla.

```
Promise.resolve().then(function () {
          return action[0].call(action[1], data.data);
        }).then((result) => {
          comObj.postMessage({
            sourceName,
            targetName,
            isReply: true,
            callbackId: data.callbackId,
            data: result,
          });
        }, (reason) => {
          comObj.postMessage({
            sourceName,
            targetName,
            isReply: true,
            callbackId: data.callbackId,
            error: makeReasonSerializable(reason),
          });
        });
```

So in **reason** object I can see some  Function type properties, added by zone.

When _postMessage_ is called, _reason_ cannot be serialized  since Functions and Errors cannot be cloned and throws DATA_CLONE_ERR. Any ideas?

**Comment by JiaLiPassion** [comment]
@snovos , the `reason` object is a `promise` or an `error`? could you post a reproduce repo or plunker? thanks.

**Comment by snovos** [comment]
@JiaLiPassion  https://github.com/snovos/pdf-zone. 

Please run "npm start" and observe that if you pass wong url to <pdf-viewer> component, it throws an error I described above. Please  let me know if you were able to reproduce

**Comment by JiaLiPassion** [comment]
@snovos, thanks for the reproduce repo, I have made a PR to fix this one.

**Comment by snovos** [comment]
@JiaLiPassion  Greath! Thanks

**Comment by JiaLiPassion** [comment]
@snovos , I can create a branch and can update your zone.js in `package.json` to point to my branch.

**Comment by snovos** [comment]
@JiaLiPassion  That would be great. I appreciate it, thanks!

**Comment by JiaLiPassion** [comment]
@snovos, you can use this branch ,https://github.com/JiaLiPassion/zone.js/tree/jsondist

**Comment by snovos** [comment]
@JiaLiPassion thanks a lot. That works.
