### ISSUE TITLE
Do not commit dist/zone*.js with each update

### ISSUE THREAD

**Issue by vicb** [angular/zone.js#98]
As of today, we need to `gulp build` the sources whenever a file in `/lib` is updated.

This causes a few problem:
- size,
- easy to get out of sync.

What we should do:
- use the `/lib` files for the tests,
- only update the `/dist` when the package is published

**Comment by btford** [comment]
> only update the /dist when the package is published

:+1:

**Comment by vicb** [comment]
> only update the /dist when the package is published

I have tried to follow this policy for the last PRs. One exception is when files gets added to the folder, it then makes sense to update it, do you think it makes sense ?
