### ISSUE TITLE
globalZoneAwareCaptureCallback not hitting on dynamic component loading.

### ISSUE THREAD

**Issue by JinsPeter** [angular/zone.js#987]
I'm getting an intermittent issue I really dont understand, but I was able to track it down to that, The issue is occuring when globalZoneAwareCaptureCallback() in zone.js is not hit.

I have a dynamic popup component build using @ngbootstrap/ngbootstrap NgbModal  to make dynamic popup where i pass adynamic popup component to the NgbModal and in there, I use Angular's method of dynamic component injection.
The issue is that 
when i call the NgbModal.open(), most of the times it works, The Modal shows. In that case,
globalZoneAwareCaptureCallback() is triggered after the dynamic componentRef is loaded inside the
 dynamicpopupComponent.ts. 

But after I refresh the page, and then do NgbModal.open(), this globalZoneAwareCaptureCallback() is not triggered  after  dynamic componentRef is loaded in dynamicpopupComponent.ts. and my popup does not load. only a black overlay comes up.
The popup is loaded only after I click somewhere on the screen or do something like press F12, which will trigger globalZoneAwareCaptureCallback().
I would like to know why this is happening, is it zone.js bug. 
When

**Comment by JiaLiPassion** [comment]
@JinsPeter, please provide a reproduce repo , thank you!

**Comment by JinsPeter** [comment]
the Real issue was onNgInit() not being called on a dynamic compoent. solved using zone.run();

**Comment by JinsPeter** [comment]
@JiaLiPassion I'm having to use `NgZone `service to run  NgZone.Run(()=>{})
