### ISSUE TITLE
3.4kb size regressions between 0.8.16 and 0.8.19

### ISSUE THREAD

**Issue by IgorMinar** [angular/zone.js#989]
Size of various polyfills.js build for angular.io with zone.js version changing as the only variable:

v0.8.16 = 37259 bytes
v0.8.17 = 38245 bytes
v0.8.18 = 40274 bytes
v0.8.19 = 40684 bytes

3.4kb is a lot of bytes. Is the increase justified? Can we reduce the size and prevent further regressions?

Justification: zone.js is a prolyfill and as such it needs to be downloaded, parsed and evaluated before anything else gets its turn. This makes the size of zone.js a significant contributor to the overall TTI.

**Comment by JiaLiPassion** [comment]
@IgorMinar , got it, I will check it.

**Comment by IgorMinar** [comment]
thanks @JiaLiPassion!
