### ISSUE TITLE
patchEventTargetMethods is no longer reachable before patches on EventTarget

### ISSUE THREAD

**Issue by marinho** [angular/zone.js#991]
I'm experiencing an issue when trying to upgrade to newer Angular/Zone versions and just found out that https://github.com/angular/zone.js/pull/748 caused it. I will try to describe below with details as possible:

in my job, we have to shit apps wrapped by an internal platform that patches `XMLHttpRequest` before Zone.js is loaded. Such library is patching `addEventListener` and other methods and preventing delegation. So, that makes Zone break, as it relies on delegate to let `XMLHttpRequest` be patched via `EventTarget`.

That's not under my team's feasability to change, so, we solved that with this:

```
require('zone.js/lib/zone');
const patchEventTargetMethods = require('zone.js/lib/common/utils').patchEventTargetMethods;
patchEventTargetMethods(XMLHttpRequest.prototype);
require('zone.js/lib/browser/browser');
```

that means we patch `XMLHttpRequest` directly before `browser` is loaded, so when `patchEventTargetMethods` runs on `EventTarget`, it works as expected.

That used to work until 0.8.9.

Between 0.8.10 and 0.8.12, that's no longer possible, as `zone.js/lib/zone.ts` will complain that `Promise` is already patched:

```
Error: Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.
```

Since 0.8.13, `patchEventTargetMethods` was moved into `lib/common/events.ts`, so I face importing errors, when executing `require('zone.js/lib/zone’)` - before my call on `patchEventTargetMethods`:

```
node_modules/zone.js/lib/common/events.ts:53:26
    Cannot find name '_global'.
```

So, as I understand the main purpose of #748 was about making Zone more modular, I guess there might be another way to reach `patchEventTargetMethods` and call it directly for `XMLHttpRequest` before I run into that issue. Or maybe importing a couple of modules instead of just relying on `dist/zone.js`.

Is there any light that could help me solve this issue? Hopefully I’d like to stick to latest Zone versions, so I’m able to upgrade to Angular 5+.

Thanks.

**Comment by JiaLiPassion** [comment]
@marinho , could you describe more about your issue with some code?
```javascript
require('zone.js/lib/zone');
const patchEventTargetMethods = require('zone.js/lib/common/utils').patchEventTargetMethods;
patchEventTargetMethods(XMLHttpRequest.prototype);
require('zone.js/lib/browser/browser');
```

I am not sure why you did this  before `zone.js 0.8.9`, you didn't add your own patch logic. so could you describe when you did `your own internal platform patch`?

**Comment by JiaLiPassion** [comment]
@marinho , and if you just want to access `patchEventTargetMethod`, you can do like this.

```javascript
// load full zone.js without XHR
__Zone_disable_XHR = true;
require('zone.js');
// patch something you want.
Zone.__load_patch('my_xhr', (global, Zone, api) => {
  api.patchEventTargetMethod(XMLHttpRequest.prototype);
}); 
```

**Comment by marinho** [comment]
@JiaLiPassion thank you for the answer, the `__Zone_disable_*` thing solved my issue pretty well. I took longer to answer so I could try it a bit in further, but yep, that's the answer I was looking for :P

I'm going to close this now as there's no issue to be reported.

**Comment by marinho** [comment]
I just want to write an additional comment, as it's related to the issue and could help on making Zone more modular in the future:

I just realised that **on_property** patch [also affects XHR](https://github.com/angular/zone.js/blob/fd91152/lib/browser/property-descriptor.ts#L306), which means that `__Zone_disable_XHR` doesn't prevent Zone to touch XHR and `XMLHttpRequestEventTarget`.

Additionally, it is also hard to be reused as modular, as [it calls 3 functions](https://github.com/angular/zone.js/blob/fd91152/lib/browser/browser.ts#L74) that are not reachable from external calls (`propertyDescriptorPatch`, `propertyPatch` and `registerElementPatch`) as far as I could find.

So, I think although `__Zone_disable_*` toggles work well for `XHR` and `EventTarget`, once `on_property` is disabled, there's no way to apply it later. I guess that same happens for other toggles

Is there any chance Zone would be turned modular in the sense that its functions are accessible for external imports?

**Comment by JiaLiPassion** [comment]
@marinho, thank you for the comment, but I would like to know more about your use case, so you mean you want to 

1. disable some module of zone.js, for example `on_property`.
2. load `zone.js`.
3. load some of your own module.
4. you want to reload `on_property` patch of `zone.js`

is that correct?

**Comment by marinho** [comment]
@JiaLiPassion, yes, that's correct.

**Comment by JiaLiPassion** [comment]
@marinho , ok, and could you post some `pseudocode` to describe 
- why you need to do `step3` before `step4`
- why can't do `step3` before `step1`.

**Comment by marinho** [comment]
@JiaLiPassion, the thing is: when Zone is loaded, another library already patched `XMLHttpRequest.prototype` (not `XMLHttpRequestEventTarget`) on `addEventListener` and `removeEventListener` not respecting **delegate** pattern. So, Zone's patch doesn't reach them.

But that was clearly stated until version 0.8.9, so, as things changed since then, I'm not sure that's the case anymore.

So, I was wondering to apply the same `on_property`, `XHR` and `EventTarget` patches on `XMLHttpRequest` either between `step3` and `step4` or after `step4`. 

But I must investigate more, as I'm not sure about the causes and effects in there.

**Comment by JiaLiPassion** [comment]
@marinho , ok , I will try to figure out how to make `zone.js` more modular which can be not only being `disabled` but also `enabled` on demand.
