### ISSUE TITLE
set custom global zone

### ISSUE THREAD

**Issue by matthewjh** [angular/zone.js#995]
Hello,

In my use case, I need to have a custom global zone. I want my own zone's hooks to be run, even when not using zone.run. Basically I need to replace the default Zone.current with my own zone, and use that as the "default" zone.

Is there any way to do this?

Thanks,
Matt

**Comment by mleibman** [comment]
You can always just monkey patch it.
Something like this for `runTask`, and similar wrappers for the rest as needed:

```javascript
const runTask = Zone.prototype.runTask;
Zone.prototype.runTask = function(task, applyThis, applyArgs) {
  // Run your own handlers.
  return runTask.call(this, task, applyThis, applyArgs);
};
```

**Comment by JiaLiPassion** [comment]
Will close this for now.
