### ISSUE TITLE
Expose ZoneAwareError and UncaughtPromiseError

### ISSUE THREAD

**Issue by trshafer** [angular/zone.js#996]
UncaughtPromiseError provides the original error which is thrown on the `rejection` property: https://github.com/angular/zone.js/blob/fd91152e615e3e8fbe69102f370fd32df8e3e174/lib/common/promise.ts#L192

It would be helpful to be able to check in angular's error handler what the original error is. In order to safely check what the original error is, it would be helpful to have compiler checking on UncaughtPromiseError. Something like:

```TypeScript
import {UncaughtPromiseError} from '@angular/zone';
import {ErrorHandler} from '@angular/core';

export class MyErrorHandler implements ErrorHandler {
  handleError(error: Error|UncaughtPromiseError) {
    if(error.rejection) {
      // do something with the original error
    }
  }
}
```

Zone is not exposed as an angular npm module, so that might also be a requirement.

Right now the only way to accomplish this is to duplicate the UncaughtPromiseError interface, which is error prone.

Thanks.

**Comment by JiaLiPassion** [comment]
@trshafer, thank you for the proposal, I will check it.
